### ISSUE TITLE
[Question] Update from 3.2.0 to 3.5.2 fails

### ISSUE THREAD

**Issue by HassanMullah** [phpservermon/phpservermon#1001]
Hello, it would be cool if you would update the start page. It still says that 3.2.0 is the current version.

I get the following error message after updating from 3.2.0 to 3.5.2

Fatal error: Your database is for an older version and requires an upgrade, please click here to update your database to the latest version. in /var/www/vhosts/web503.sydney.webhoster.ag/monitor.mydomain.de/src/bootstrap.php on line 106

When I click on "please click here" I get back to the install.php page etc.

**Comment by wienfuchs** [comment]
The issue with the webpage is discussed in #954 - @TimZ99 (maintainer of this github repository) unfortunately has no accesss to the webpage. Relating to the upgrade issue - do you have any entries in your apache server log?
