### ISSUE TITLE
Problem with telegram notification

### ISSUE THREAD

**Issue by HassanMullah** [phpservermon/phpservermon#1002]
Hi,

i use version 3.5.2 and want me to notify with telegram. In the settings of my user i write the telegram chat it (8 numbers) and in the settings of server monitor in "telegram" i write the telegram API Token an save all. if i press the TEST button, i get following failure message:  An error has occurred while sending the Telegram notification: Bad Request: chat not found

what do i wrong?

**Comment by techs2resolve** [comment]
Yes same error is coming to me as well while saving telegram token

**Comment by TimZ99** [comment]
Did you start the bot? Go to your chat with the bot and press start or type /start.

**Comment by techs2resolve** [comment]
> Did you start the bot? Go to your chat with the bot and press start or type /start.

Yes Bot is started and working. I am getting notification. I want to set the cron to 5 min. I am using cpanel and i have crontab access for my user.

**Comment by TimZ99** [comment]
So only the test message failed?

**Comment by dagababaev** [comment]
I have problem with notification to Telegram too. Test message is coming, but when any service is down, notification not sent to Telegram and I can't see them in log.
Notification to Telegram in service is "On", and selected send notification by status change

UPD I am use 3.5.2

**Comment by TimZ99** [comment]
Chat not found is probably related to a non-existing (on telegrams side) of wrong chat_id.

**Comment by dagababaev** [comment]
No, test notification is recieved success
 _The configuration has been updated.
 Telegram notification sent_
Message is delivered to my bot chat

Problem when one of hosts is down, system not send notification to telegram. I can't see in log and don't recieve them, but in host settings "Send Telegram notification" is "Yes"

**Comment by cmachadox** [comment]
Finding out the problem is not really a mistake, for it to work it is necessary to select the user, editing the client goes on

Permissions
Server will be visible for the following users

![image](https://user-images.githubusercontent.com/30154971/116107133-223bb200-a689-11eb-9127-292a6111a324.png)
