### ISSUE TITLE
[BUG] Update from 3.4.5 to 3.5.0 

### ISSUE THREAD

**Issue by sercio** [phpservermon/phpservermon#1003]
**Describe the bug**
I have insalled 3.2.0. Then i I have done the update to all the releases. In sequence: 3.2.1, 3.2.2, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5. All with the same actions: ftp toreplace files and run intall.php. All ok.
when i try to update to 3.5.0, when i run install.php i receive a blank page, and nothing else. The same if I call index.php.
Same result i I try to do a clear installation for the 3.5.2 version.

**To Reproduce**
1. ftp the files of the 3.5.0 release
2. call install.php
3. blank page

**Screenshots**

**Version (please complete the following information):**
 - Version  3.5.0
 - PHP  7.0.3

**Comment by teamayu** [comment]
Did you check your server error log?

**Comment by sercio** [comment]
The only error i see:


  | [error] [client 95.235.15.204] - www.famsd.net - AH01215: PHP Fatal  error:  Redirect failed. in  /web/htdocs/www.famsd.net/home/servmon1/src/psm/Module/User/Controller/LoginController.php  on line 59: /web/htdocs/www.famsd.net/home/servmon1/index.php, referer  http://www.famsd.net/servmon1/
-- | --


but this is not my access (the ip 95.235.15.204 s not mine) to install.php

My access have no error and blank page

![immagine](https://user-images.githubusercontent.com/9134430/92405068-24babd00-f135-11ea-95ed-c2701a2b25ed.png)

**Comment by wienfuchs** [comment]
99.9% duplicate issue as of #908 solved by #913 - roughly discussed in #908

**Comment by sercio** [comment]
Hi,
i have updated th PHP version to 7.3.2 and all work fine.
Thanks

**Comment by wienfuchs** [comment]
Pleased to read that.

**Comment by 4Syno** [comment]
I was facing exact the same problem. PHP Server Monitor update from v3.4.5 to v3.5.2. 
After updating all files from the latest tarball -> blank page; nothing inside webserver or php logs.

Don’t know why, but you’re not shipping the latest composer.json file in this package. I missed one requirement: jaxl/jaxl(v3.1.0), adding this, run composer update, it works immediately.

Version (please complete the following information):
    • Version 3.5.2 
    • PHP 7.2

**Comment by TimZ99** [comment]
It's in the current dev, so it will for sure be in the next release 😉
