### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by zuugakz** [phpservermon/phpservermon#1018]
I can't ping to my server. It's show message like this,
**Last error:
Access denied. Option -c requires administrative privileges.**

How should I do?

Version 3.5.2
PHP 7.4.9
[image](https://user-images.githubusercontent.com/71125125/92898653-5e970680-f448-11ea-87b5-68ac4e5b974a.png)

**Comment by wienfuchs** [comment]
This is not a question of phpservermon (nor PHP) but one of operating system permissions. What operation system do you use? Your webserver user does need the permission to issue a "ping -c" system call.

**Comment by zuugakz** [comment]
> This is not a question of phpservermon (nor PHP) but one of operating system permissions. What operation system do you use? Your webserver user does need the permission to issue a "ping -c" system call.
Oops. sorry.
I am using Windows 10 operating system.

**Comment by wienfuchs** [comment]
> I am using Windows 10 operating system.

Could you please post the value of PHP_OS? (single PHP file containing ``<?php echo PHP_OS; ?>`` should do this)

Version 3.5.2 should not use ping command but use socket connections, based on value of the PHP constant PHP_OS ...

**Comment by zuugakz** [comment]
> > I am using Windows 10 operating system.
> 
> Could you please post the value of PHP_OS? (single PHP file containing `<?php echo PHP_OS; ?>` should do this)
> 
> Version 3.5.2 should not use ping command but use socket connections, based on value of the PHP constant PHP_OS ...

It shows WINNT.

![image](https://user-images.githubusercontent.com/71125125/93032631-d63d7f00-f65c-11ea-9aa1-70cf7682f570.png)

**Comment by wienfuchs** [comment]
Could you pls recheck, if https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Util/Server/Updater/StatusUpdater.php solves your problem? is is the latest updated version, that should use socket instead of ping on Windows.
