### ISSUE TITLE
[BUG] Cannot add new user upon new install

### ISSUE THREAD

**Issue by pellett655** [phpservermon/phpservermon#1020]
**Describe the bug**
When creating a new user from a new install, you will get the following error message when the 1st user is created:
Warning: SQL error: SQLSTATE[HY000]: General error: 1364 Field 'discord' doesn't have a default value in /var/www/html/phpservermon/src/psm/Service/Database.php on line 578

**Version:**
 - Version [PHP Server Monitor v3.6.0.beta2]
 - PHP [7.4]

**Comment by pellett655** [comment]
Modified line 219 of src/psm/Util/Install.php
from `discord` varchar(255) NOT NULL, to `discord` varchar(255), and was able to get around the error.

**Comment by whalehub** [comment]
I can confirm this bug after reproducing it using the same version of PHP Server Monitor and PHP.

**Comment by viharm** [comment]
I have been able to reproduce this issue too.

## Preliminary diagnosis
Installation process creates a new user and adds blank values (not null) for user information fields, like mobile, telegram, etc. All these fields have been specified in the database as `NOT NULL`.

Here it is...
https://github.com/phpservermon/phpservermon/blob/b59f62c13925631dc762a53ab347c27c8613e06e/src/psm/Module/Install/Controller/InstallController.php#L296

The new user creation function does not add the field for `discord`. This causes a database error.

## Possible solution

I have applied a fix in my fork #507 , by adding this variable (as an array element,  `'discord' => ''`).

@pellett655, @sadortun, @TimZ99, are you ok to leave this fix in my fork, or would you prefer a separate PR to fix this issue separately?
