### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JeromeX** [phpservermon/phpservermon#1021]
Ping is not working. All devices are online, as normal. Firewall etc.. is for testing off. Using a Debian Buster on Rasp. Pi with Php 7.3
I can ping from any device to each other. Devices with service on port 80/443 are working.

**Comment by wienfuchs** [comment]
You forgot to mention the essential info, which phpservermon version you are using. Thast is essential, as this probably is duplicate to  #917 solve by #880 / #919

**Comment by JeromeX** [comment]
Sorry, it’s the latest 3.52
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Mon, Sep 21, 2020 at 6:59 AM +0200, "wienfuchs" <notifications@github.com> wrote:















You forgot to mention the essential info, which phpservermon version you are using. Thast is essential, as this probably is duplicate to  #917 solve by #880 / #919

**Comment by wienfuchs** [comment]
Sorry, referenced wrong solving issue. #963 should have solved that issue. Pls download https://raw.githubusercontent.com/wienfuchs/phpservermon/d5005505acf2ff3b151024be6ef1568f70673784/src/psm/Util/Server/Updater/StatusUpdater.php and replace your local src/psm/Util/Server/Updater/StatusUpdater.php - that should solve your problem. (Still duplicate issue, solved)

**Comment by JeromeX** [comment]
Thanks wienfuchs, will test this this evening, btw. Is there anyway to put in a smaller font. The hole view from phpservermon is quite big? Regards, JX
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Mon, Sep 21, 2020 at 8:19 AM +0200, "wienfuchs" <notifications@github.com> wrote:















Sorry, referenced wrong solving issue. #963 should have solved that issue. Pls download https://raw.githubusercontent.com/wienfuchs/phpservermon/d5005505acf2ff3b151024be6ef1568f70673784/src/psm/Util/Server/Updater/StatusUpdater.php and replace your local src/psm/Util/Server/Updater/StatusUpdater.php - that should solve your problem. (Still duplicate issue, solved)

**Comment by JeromeX** [comment]
Thanks for you awesome help. It works without any issues. Will this implement in further updates? Many thanks. Regards JX
    	
    	

    	 Holen Sie sich Outlook für iOS
    
  




On Mon, Sep 21, 2020 at 8:19 AM +0200, "wienfuchs" <notifications@github.com> wrote:















Sorry, referenced wrong solving issue. #963 should have solved that issue. Pls download https://raw.githubusercontent.com/wienfuchs/phpservermon/d5005505acf2ff3b151024be6ef1568f70673784/src/psm/Util/Server/Updater/StatusUpdater.php and replace your local src/psm/Util/Server/Updater/StatusUpdater.php - that should solve your problem. (Still duplicate issue, solved)

**Comment by wienfuchs** [comment]
> Will this implement in further updates?

Sure, it is already merged into development and 3.6.0 beta

**Comment by JeromeX** [comment]
Sounds good too me, might it possible to display status page smaller? It looks a little bit to big on every screen. Shall I open a new issue or could you help ASAP?
    	
    	

    
  
Von: wienfuchs <notifications@github.com>
Gesendet: Montag, September 21, 2020 8:27 PM
An: phpservermon/phpservermon
Cc: JeromeX; State change
Betreff: Re: [phpservermon/phpservermon] [BUG]  (#1021) 




Sure, it is already merged into development and 3.6.0 beta

**Comment by wienfuchs** [comment]
Pls open an new feature issue; I had a short look into but did not find a quick solution to it.
