### ISSUE TITLE
[Question] Date format in notifications

### ISSUE THREAD

**Issue by riotweb** [phpservermon/phpservermon#1035]
- [X] Looked at the documentation first

**Describe the question**
How can I set the date / time format ? 
Its displayed like:  2020-10-18 05:01:02
My timezone (checked in phpinfo() ) is Europe / Berlin

**Version:**
 - Version v3.5.2
 - PHP 7.1

**Additional context**
In the logs its displayed correct  18.10.2020 05:01:02

**Comment by powerhandlar** [comment]
At the moment this seems to be hardcoded in line 372 of ``src/include/functions.inc.php`` as  ``$vars['date'] = date('Y-m-d H:i:s');``

To get the php.ini defined timezone format into you notifications you can try changing this to ``$vars['date'] = strftime('%x %X');``.

As for me, I prefer "usual" international date/time format in notifications as this was coded in original program, as this could be easier reused by any receiving software and usually all admins do easy understand it too. So usual format IMHO is "displayed correct" too ;)

**Comment by wienfuchs** [comment]
At the moment this seems to be hardcoded in line 372 of ``src/include/functions.inc.php`` as ``$vars['date'] = date('Y-m-d H:i:s');``

To get the php.ini defined timezone format beeing used in your notifications you can try changing this to ``$vars['date'] = strftime('%x %X');``

As for me, I prefer "usual" international date/time format in notifications as it was used in original program, as this could be easier reused by any receiving software and usually all admins do easy understand it too. So usual format IMHO is "displayed correct" too ;)

**Comment by riotweb** [comment]
Thank you.
