### ISSUE TITLE
[BUG] Default form submit button on profile screen is Telegram activation button

### ISSUE THREAD

**Issue by viharm** [phpservermon/phpservermon#1036]
**Describe the bug**
The default submit button on the profile form is the "Activate Telegram notifications" button. This results in submission of this button instead of "Save" when update user details and pressing "enger".

**To Reproduce**
1. Go to 'Profile'
2. Change any user details
3. Press enter
4. This shows a modal 'popup' `
Activate Telegram notifications
Allow Telegram notifications to be sent to the specified chat id. Without this permission, Telegram doesn't allow us to send notifications to you. `

**Expected behavior**
Pressing enter should submit the "Save" button

**Version (please complete the following information):**
 - Version v3.6.0.beta2. 
 - PHP 7.4

**Comment by TimZ99** [comment]
Can't reproduce. When I use the save button or save by pressing enter, it works.
Any ideas?
