### ISSUE TITLE
[Question] Monitoring Type Ping not working, how do I debug?

### ISSUE THREAD

**Issue by HermanRas** [phpservermon/phpservermon#1047]
- [ DONE ] Looked at the documentation first
 checked all dependancies
 ckecked install guide

**Describe the question**
when setting the monitor type to Ping, it is not working return latency 0.0000s and always show server as online even if its not.
-all other monitor types work as excepted (Service, Website). 
**How do I go about troubleshooting the problem?**

**Version (please complete the following information):**
 - Version [PHP Server Monitor v3.5.2. Official release]
 - PHP [7.4]
 - Ubuntu20.04
 - MySQL Server version: 8.0.22-0

**Additional context**
- php error reporting is enabled, output from log after Apache2 restart + servermon/?&mod=server_update completed
[Thu Nov 05 14:13:22.984214 2020] [mpm_prefork:notice] [pid 144685] AH00173: SIGHUP received.  Attempting to restart
[Thu Nov 05 14:13:23.021254 2020] [mpm_prefork:notice] [pid 144685] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Thu Nov 05 14:13:23.021297 2020] [core:notice] [pid 144685] AH00094: Command line: '/usr/sbin/apache2'

-phpservermon debug is enabled
define('PSM_DEBUG',true);

-servermon/?&mod=server_log 
no logs

**Comment by powerhandlar** [comment]
Can you ping from commandline as www-data user?
i.e. sudo -u www-data ping 8.8.8.8

**Comment by wienfuchs** [comment]
Can you ping from commandline as www-data user?
i.e. sudo -u www-data ping 8.8.8.8

**Comment by HermanRas** [comment]
boxadmin@CDM-SER-MON-01:$  sudo -u www-data ping 10.110.113.1
PING 10.110.113.1 (10.110.113.1) 56(84) bytes of data.
64 bytes from 10.110.113.1: icmp_seq=1 ttl=255 time=0.330 ms
64 bytes from 10.110.113.1: icmp_seq=2 ttl=255 time=9.72 ms
64 bytes from 10.110.113.1: icmp_seq=3 ttl=255 time=7.48 ms
64 bytes from 10.110.113.1: icmp_seq=4 ttl=255 time=0.262 ms
^C
--- 10.110.113.1 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3031ms
rtt min/avg/max/mdev = 0.262/4.445/9.715/4.224 ms
boxadmin@CDM-SER-MON-01:~$

**Comment by wienfuchs** [comment]
Could you please check if this file from develop solves you problem?
https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Util/Server/Updater/StatusUpdater.php
Not sure, if this made it into 3.5.2 release or was accepted only later.

**Comment by HermanRas** [comment]
100%, checking

**Comment by HermanRas** [comment]
The updated file works 100% thank you !
