### ISSUE TITLE
[BUG]  Only user '__public__' can have the level anonymous.

### ISSUE THREAD

**Issue by HermanRas** [phpservermon/phpservermon#1048]
**Describe the bug**
username: __public__ with Level: Anonymous gives error Only user '__public__' can have the level anonymous.

**To Reproduce**
Quoted from Documentation:
 - https://github.com/phpservermon/phpservermon/pull/986/commits/56b122471b82607f6d4cb290fa688c66ca6a127e
 - 1) Go to users -> create new user.
 - 2) Set the username to '__PUBLIC__', level to 'anonymous' and the rest is up to you. 

**Expected behavior**
Create a PUBLIC /  'anonymous' account

**Screenshots**
![image](https://user-images.githubusercontent.com/38083493/98272554-e5c0b080-1f99-11eb-85e6-ea7ebf5fe9f4.png)

**Version (please complete the following information):**
 - Version v3.6.0.beta2.
 - PHP [7.4]

**Additional context**

mysql> select user_id,user_name,level,name,email from tbl_users;
+---------+------------+-------+--------+---------------------------------+
| user_id | user_name  | level | name   | email                           |
+---------+------------+-------+--------+---------------------------------+
|       1 | admin      |    10 | admin  | anthony.elson@petradiamonds.com |
|       7 | __public__ |    20 | Viewer | no@mail.local                   |
+---------+------------+-------+--------+---------------------------------+

when manulay updating to level 30 it works fine, so must be a problem with input validation on create user page ?
update tbl_users set level=30 where name='Viewer';

**Comment by wienfuchs** [comment]
This is _not_ a bug as the problem is not related to the code but to the reader ;)

Only the user ``__public__`` can have level anonymous - which differs to user ``public`` because of missing __ before and after. Also read https://github.com/phpservermon/phpservermon/pull/986#issuecomment-682340074 to this issue, where same is stated. Easy "trap" to tap into - but also that easy to solve.

**Comment by HermanRas** [comment]
the user is `__public__` sorry github changed `__` to Bold

`  select user_id,user_name,level,name,email from tbl_users;
+---------+------------+-------+--------+---------------------------------+
| user_id | user_name  | level | name   | email                           |
+---------+------------+-------+--------+---------------------------------+
|       1 | admin      |    10 | admin  | anthony.elson@petradiamonds.com |
|       7 | __public__ |    20 | Viewer | no@mail.local                   |
+---------+------------+-------+--------+---------------------------------+
`

**Comment by red-erik** [comment]
Hello,
I solved it using exactly `__PUBLIC__` (capital letters) as username and the user is successfully created with random password and level anonymous.
To avoid too many email notifications, I removed the email from the Database table (it would be nice not be forced to put an email address during anonymous user creation).
Regards,

Red.

**Comment by HermanRas** [comment]
O Sorry never reported back, it was fixed in current dev build..
