### ISSUE TITLE
[Question] How can I edit notification emails?

### ISSUE THREAD

**Issue by mkaand** [phpservermon/phpservermon#1053]
- [ ] Looked at the documentation first

**Describe the question**

I have to modify notification emails like:

IMPORTANT: Server 'WRT1900AC' is DOWN
Failed to connect to the following server: Server: WRT1900AC IP: xxxx.xxxxx.xxxxx Port: 0 Error: Couldn't create socket [11]: Resource temporarily unavailable Date: 2020-11-24 01:40:22

I use email to telegram IFTTT service. I need to custimize PSM email notification files for my needs. I don't know which file is handling. Could you help me?

**Version (please complete the following information):**
 - PHP Server Monitor v3.5.2.
 - PHP [7.3]

Thanks

**Comment by PopcornPanda** [comment]
You need to edit language file in src/lang. Search for notifications array.

**Comment by TimZ99** [comment]
You can also use Telegram notifications out of the box 📦.

**Comment by webbymaster** [comment]
the language is Russian, and the letters come in English. edit en_US.lang.php it didn't help. Edit functions.inc.php it didn't help either
it seems that the script does not pick up ru_RU.lang.php. (((

**Comment by webbymaster** [comment]
is there really no solution with displaying the language in incoming messages?
