### ISSUE TITLE
[Question] Certificate Expiration check

### ISSUE THREAD

**Issue by red-erik** [phpservermon/phpservermon#1054]
Hello,
I read BUG #896 and all discussion.
I update CURL and OPENSSL to latest version but still using a threshold value of 900 days (larger than certificate's expiration date)
I still have no warning.
Am I missing something ?

[XX]# openssl version
OpenSSL 1.1.1  11 Sep 2018
[XX]# curl -V
curl 7.73.0 (x86_64-redhat-linux-gnu) libcurl/7.73.0 NSS/3.44 zlib/1.2.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.9.0 nghttp2/1.33.0
Release-Date: 2020-10-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz Metalink NTLM NTLM_WB PSL SPNEGO SSL UnixSockets

Regards,

Red.

**Comment by wienfuchs** [comment]
Pls supply info on your phpservermon, OS and PHP versions used

**Comment by red-erik** [comment]
Hello,
sorry but I made a mistake. I don't know how, but as address I typed http://... instead of HTTPS://...
Now it work fine with a regular warning.
Sorry for my mistake.
Regards,

Red.

**Comment by arielesp** [comment]
Hi
I have the similar problem ...
I added a domain to check ssl expiring, inserted a lot of days (larger than certificate's expiration date)
I still have no warning.

Using PHP Server Monitor v3.5.2
CentOS 7.9
php 7.4
OpenSSL 1.0.2k-fips  26 Jan 2017
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets


Thanks in advance

**Comment by wienfuchs** [comment]
> I have the similar problem ...
> CentOS 7.9
> curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.53.1 zlib/1.2.7 libidn/1.28 libssh2/1.8.0

Seems to be this CentOS bug issue https://bugzilla.redhat.com/show_bug.cgi?id=1684797 - although here is fix info for you: https://github.com/phpservermon/phpservermon/issues/896#issuecomment-632292409 - curl 7.29.0 is buggy

**Comment by arielesp** [comment]
I updated ... but a question ...
Now all https checks are warning, but ssl "time" doesnt close to expire

SSL certificate expiring: Never

HTTP/2 200
date: Thu, 17 Dec 2020 18:19:02 GMT
content-type: text/html
last-modified: Mon, 08 Jun 2020 01:06:08 GMT
vary: Accept-Encoding
etag: W/&quot;5edd8f00-1445c&quot;
protected: by cWAF 2020090301
strict-transport-security: max-age=31536000
content-security-policy: upgrade-insecure-requests
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
content-encoding: gzip

**Comment by wienfuchs** [comment]
"SSL certificate expiring: Never" - I massively doubt this is correct. Not knowing your site info I doubt there to be a chance to get the problem source.

**Comment by arielesp** [comment]
I tested with some domains ... like
https://server856.servidor101.xyz/

https://www.sslshopper.com/ssl-checker.html#hostname=https://server856.servidor101.xyz/

**Comment by wienfuchs** [comment]
As I cannot reproduce any problems with recent server software, maybe you add the info of a) your server software and b) your test configuration?
![grafik](https://user-images.githubusercontent.com/44177781/102528067-53cebc00-409e-11eb-963e-32200b735b0f.png)
![grafik](https://user-images.githubusercontent.com/44177781/102528125-634e0500-409e-11eb-8abe-f544a36a9a94.png)
