### ISSUE TITLE
[Question] Is there a cli to finish the setup or something similar, to create unattended installations?

### ISSUE THREAD

**Issue by msbt** [phpservermon/phpservermon#1056]
- [x] Looked at the documentation first

**Describe the question**
As the title suggests: I'm trying to create a package which installs PSM automatically (adding SMTP and LDAP information), but right now I'm stuck because I can't write those values into the db since the installation hasn't created the required tables yet. Is there a way to finish the installation via commandline with a default admin user:pass so the tables are being set up immediately?

**Version (please complete the following information):**
 - Version https://github.com/viharm/phpservermon/tree/feature-ldapauth
 - PHP 7.3

**Comment by msbt** [comment]
Follow up: Some settings are only written into the database once you go into the config screen and save (even without changing anything, like the site title, it only appears after saving). Can I somehow trigger that save button from a parameter, like calling `index.php?mod=config&action=save` or `index.php?mod=config&action=enableldap` from the shell? 

This would also come in handy for the ldap module by @viharm which only adds the fields after activating the module.

**Comment by gramakri** [comment]
I managed to automate this with some curl and sed magic. https://git.cloudron.io/cloudron/phpservermonitor-app/-/blob/master/start.sh#L48 . Essentially, you have to pass in the csrf token as well grab the cookies from the initial installer page.

**Comment by msbt** [comment]
awesome, works like a charm!
