### ISSUE TITLE
[Question] How can I set/update the SMTP password from ssh?

### ISSUE THREAD

**Issue by msbt** [phpservermon/phpservermon#1057]
- [x] Looked at the documentation first

**Describe the question**
I'm trying to set/update the SMTP password from an environment variable via shell like so:
`UPDATE monitor_config SET value = '${MAIL_SMTP_PASSWORD}' WHERE monitor_config.key = 'email_smtp_password';` but this obviously doesn't work, because the password is supposed to be saved encrypted in the db. Any idea how I could encrypt that on the fly?

**Version (please complete the following information):**
 - PHP 7.3

**Comment by PopcornPanda** [comment]
SMTP password is encrypted with sha256 using salt from password_encrypt_key which is sha1 hash.
Maybe this will work:
`echo -n "saltpassword" | openssl dgst -sha256 -binary | openssl base64`

Encryption function: [link](https://github.com/phpservermon/phpservermon/blob/b59f62c13925631dc762a53ab347c27c8613e06e/src/includes/functions.inc.php#L934)

**Comment by msbt** [comment]
thanks @NixNotCastey, I tried back then but couldn't get it to work, but it got solved together with https://github.com/phpservermon/phpservermon/issues/1056
