### ISSUE TITLE
Email not triggering even though option is set to yes

### ISSUE THREAD

**Issue by ssx** [phpservermon/phpservermon#106]
Hi,

I've got a fresh installation that has email sending turned on. I've add a few checks and set them to email enabled, however no email is triggered. I can verify this by looking at the maillog and nothing is sent out.

I'm not getting any errors and the service checking is working fine, however the email alert is a pretty important feature for me.

Server is Cent OS 6.4, normal mail operation is fine. I've also tried using an external SMTP service (mandrill) and still no mail.

Any ideas?

**Comment by ghost** [comment]
> After you add a server/monitor you then have to go to "users" and add the server/monitor to the user account!

Aah, thanks for the hint. :laughing: 

I thought that the web pages would be automatically associated with the currently logged in user. :thinking:
