### ISSUE TITLE
little improvement- around 20 minutes - Browser Alert Sound 

### ISSUE THREAD

**Issue by dmd2222** [phpservermon/phpservermon#1069]
**Is your feature request related to a problem? Please describe.**
We need immediately response, if a server crashes.

**Describe the solution you'd like**
A Button for a test sound in the status page and the possibility to enable an alert sound. Server changes status--> sound over browser...

**Describe alternatives you've considered**
None

**Comment by TimZ99** [comment]
Duplicate of #1024
