### ISSUE TITLE
[Question] Report Website Down when 503?

### ISSUE THREAD

**Issue by techteamroi** [phpservermon/phpservermon#1076]
I am running PHP Server Monitor v3.6.0.beta2.

Can there be a configuration that reports the site being down when there is a 503 error?

For example, when a Wordpress website is maintenance mode, it is reported as down?

**Comment by wienfuchs** [comment]
I'm not sure, if I understand your request right. Actual "default" website configuration _does_ show a website as down and therefore triggers a notification if a page turns to 503 response code, I just that moment retestet this to confirm that. What do you want to get as result if a page turns to 503? If you want _no_ error on 503, just enter 503 into "Allow HTTP status code" section - if you _do_ want an error, enter nothing there, That's all that is needed to configure.

**Comment by gcwebsites** [comment]
> I'm not sure, if I understand your request right. Actual "default" website configuration _does_ show a website as down and therefore triggers a notification if a page turns to 503 response code, I just that moment retestet this to confirm that. What do you want to get as result if a page turns to 503? If you want _no_ error on 503, just enter 503 into "Allow HTTP status code" section - if you _do_ want an error, enter nothing there, That's all that is needed to configure.

Well, if that is the case, then it doesn't work. Using WPMUDEV for monitoring, the website was reported as down yet phpservermon still says it is online when it was in maintenance mode.

**Comment by wienfuchs** [comment]
As I just mentioned, I produced a page that returns 503 status. And that indeed is reportet by the version you mentioned. If the page you mentioned does only show a page that reads "maintenance 503" or something but does not set the http header's, that's not the monitor's fault. If a page set's http status 503, it _is_ reported with default page config.

**Comment by gcwebsites** [comment]
This is the headers in the file https://imgur.com/a/jaOFRKg

It reports a 503. As I said, one monitor on wpmudev.org says it is offline with a 503, phpservermon doesn't report it as offline.

Are the headers the wrong config for what phpservermon requires?

**Comment by wienfuchs** [comment]
Headers that I've initially used to test this were:
```
header('HTTP/1.1 503 Service Temporarily Unavailable');
header('Status: 503 Service Temporarily Unavailable');
header('Retry-After: 300');
http_response_code(503);
```

I have changed the test headers to your lines, unkowing what your "{$protocol}" variable contains so I've set it to read:
```
header('http/1.1 503 Service Unavailable', true, 503);
header('Content-Type: text/html; charset=utf-8');
header('Retry-After: 600');
```

Also with this headers I get a "off" state on my phpservermonitor.

Maybe you can post the output of commandline
``curl -I [your tested url]``
and also of the content of your "protocol" variable, that may help track it down.
