### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by canonex** [phpservermon/phpservermon#1077]
- [x] Looked at the documentation first

**Installing issue**

I'm trying to install from github release. As in documentation I'm trying to install / update composer packages.

- During composer update of _./vendor/symfony/config/_ i receive:
 `Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/config 1.0.0+no-version-set conflicts with symfony/dependency-injection v4.4.18.
    - symfony/config 1.0.0+no-version-set conflicts with symfony/dependency-injection v4.4.17.
    ...
    - symfony/config 1.0.0+no-version-set conflicts with symfony/dependency-injection 3.3.x-dev.
    - symfony/config is present at version 1.0.0+no-version-set and cannot be modified by Composer
    - Root composer.json requires symfony/dependency-injection ~3.3|~4.0 -> satisfiable by symfony/dependency-injection[v3.3.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev].`

- Enabling debug I receive this error:
`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "{*CWk^". in /var/www/phpservermon/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:102 Stack trace: #0 /var/www/phpservermon/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('{*CWk^') #1 /var/www/phpservermon/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(234): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('{*CWk^') #2 [internal function]: Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->Symfony\Component\DependencyInjection\ParameterBag\{closure}(Array) #3 /var/www/phpservermon/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(222): preg_replace_callback('/%%|%([^%\\s]+)%...', Object(Closure), 'L....{...') #4 /var/www/phpservermon/vendor/symfony/dependency-injection in /var/www/phpservermon/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php on line 102`

I could not figure out if I'm missing something or if there is some errors...
Than you,
Riccardo

**Version:**
 - Version 3.5.2
 - PHP 7.3.19

**Comment by TimZ99** [comment]
Composer has released v2, which causes some dependencies to be broken. Nothing to do about it from our side, the dependencies need to update somethings.

You can bypass this by using the included composer.phar file. `php ./composer.phar install`. The included composer.phar is v1.8.5 I believe.

**Comment by Dhenshaw96** [comment]
How would I fix this?
