### ISSUE TITLE
[Feature Request] Add Signal notifications

### ISSUE THREAD

**Issue by marc-farre** [phpservermon/phpservermon#1078]
Today, notifications can be sent to Pushover, Telegram and Jabber.

Suggestion: add [Signal](https://signal.org/)

Thanks for this great software!

**Comment by wienfuchs** [comment]
Open to discuss this, especially as it involves "how to integrate Signal somwhere". As far as I searched, I could not yet allocate a simple integration "HowTo" for Signal. There does not seem to exist a framework or php class to do so yet. Server protocoll allthough seems to be well described, so I could find at least [Signal-Server API-Protocol](https://github.com/signalapp/Signal-Server/wiki/API-Protocol) for this. In my eyes it needs someone to be willing to invest "a little more time" into developing a working integration for this API so it could be used. Adopting some existing code seems not the thing, as - at least by me - no souch code can be found.

**Comment by imsoftware** [comment]
I'd really appreciate to use Signal as notification provider but i think it's not easy. As @wienfuchs wrote there's no php lib or framework available yet.
Maybe it would be an option to write a php lib or framework but that's a lot of work.
Another way would be to integrate a "middleware/broker" in another language, like one these named here: https://community.signalusers.org/t/python-signal-bot/3895/2
Or this: https://gitlab.com/digiresilience/link/sigarillo
@funkycram just start building if you want to try. ;)

**Comment by TimZ99** [comment]
I'm open for a PR! In the mean time I will close this feature request as this isn't something that is on the roadmap.

**Comment by imsoftware** [comment]
If anybody wants to work on this topic, here's a multi messenger service written in Python: https://github.com/eknoes/covidbot
