### ISSUE TITLE
[Question]  Why is the publicly downloadable version 3.2 when the latest stable is 3.5? 

### ISSUE THREAD

**Issue by jaylee79** [phpservermon/phpservermon#1083]
Everywhere including google searches (which leads to the 3.2 release blog post) and http://www.phpservermonitor.org/download/ only version 3.2 (from 2017) is shown.  This makes it seems like this project is no longer maintained.  I would think they should be updated to 3.5.

**Comment by wienfuchs** [comment]
Already discussed, unfortunately there is no access to the homepage by the main maintainerm see https://github.com/phpservermon/phpservermon/issues/954
