### ISSUE TITLE
Can i get a Db schema view of the application?

### ISSUE THREAD

**Issue by ArjunDandagi** [phpservermon/phpservermon#1089]
- [ X ] Looked at the documentation first

**Describe the question**
Can i Get a Db schema view of the application , i would like to formulate a query ( sorry not a php Dev) in mysql to directly update a email server notification to add another group to already existing server alert

**Version (please complete the following information):**
not worried of version question is only about DB schema

**Comment by TimZ99** [comment]
Made [this](https://dbdiagram.io/d/60778557b6aeb3052d9029ed) very quick for you, could be that I made a mistake somewhere 🏎️💨. Haven't checkt the values tbh.
