### ISSUE TITLE
[Question] It's multithread available on PHP Server Mon 3.6.0? (server crash)

### ISSUE THREAD

**Issue by dcabezas1** [phpservermon/phpservermon#1090]
- [ ] Looked at the documentation first

**Describe the question**

**Version (please complete the following information):**
 - Version 3.6.0 beta
 - PHP 7.3

**Additional context**

I currently have PHP Server Monitor installed on my server (Nginx and PHP 7.3). In the application there are about 600 sites and at the moment of updating the list the server crashes.

They tell me that this occurs because multi-thread queries are not enabled. Can this be done now with this version? Is there any other solution?

**Comment by dhanrajbsheth** [comment]
@dcabezas1

Yes, code is sync (one check action at a time) , it will take lots of changes and testing to make it async, 
here are few in the similar line, some have tried on personal projects... 

https://github.com/phpservermon/phpservermon/issues/948
https://github.com/phpservermon/phpservermon/issues/914


Hope that helps.

**Comment by TimZ99** [comment]
As @dhanrajbsheth wrote, this wil take a lot of changes. 
Probably also a lot of time, that I currently don't have.

Too much for V3, this is on the roadmap for V4.
