### ISSUE TITLE
[Feature Request] Timezone settings

### ISSUE THREAD

**Issue by BeyondVertical** [phpservermon/phpservermon#1092]
**Is your feature request related to a problem? Please describe.**
The loggings of the "last online" status (and many other entries) on my webspace are always "about an hour ago".
There is clearly something wrong with the timezone settings. But I can not change anything, as my webspace is not administrated by myself. A selection of the timezone would here very much.

**Describe the solution you'd like**
A setting to change or select the desired timezone. Timezone differences are then calculated in the background.
With this way I could tweak the setting, so that the times of the loggings are correct.

**Describe alternatives you've considered**
I can not change anything on the server settings, because the webspace is not administrated by myself. So, there are pretty much no alternatives.

**Additional context**
Thank you for this great tool, it helps me very much. Please consider this small, but for me huge addition. :)

**Comment by TimZ99** [comment]
To change the timezone add `date_default_timezone_set("UTC");` to the config.php file.

**Comment by BeyondVertical** [comment]
@TimZ99
Sorry, I did not see your reply. I did add `date_default_timezone_set("Europe/Berlin");` to the config-file.
It works for me very well. Thanks!
