### ISSUE TITLE
Ping does not work on v3.5.2

### ISSUE THREAD

**Issue by sanhwy** [phpservermon/phpservermon#1093]
i have reinstalled v3.5.2 multiple time
i have tested ip 86.121.247.207 for ping that have request time out
but on ping monitor apear with latency 0 and last offline: never

here is the print screen https://ibb.co/jJM2QDx

**Comment by wienfuchs** [comment]
This is a known issue and already solved in development for next release. (see #1047 and #963 ).
You may download https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Util/Server/Updater/StatusUpdater.php to get it working "now".

**Comment by sanhwy** [comment]
i have updated StatusUpdater.php and now it's working
thanks for fast reply
