### ISSUE TITLE
[Feature Request]ServerChan Or Bark

### ISSUE THREAD

**Issue by erwim** [phpservermon/phpservermon#1094]
Please Add [ServerChan](http://sc.ftqq.com/) Or [Bark](https://github.com/Finb/Bark)

It's simple to get or post just like `https://sc.ftqq.com/[SCKEY].send?text=yourserverisdown`，And you can receive from wechat or bark.

**Comment by TimZ99** [comment]
I believe those are ways to get notifications (can't read Chinese).
Looks like you could use a webhook?
This won't be on the roadmap so I will close this issue.
