### ISSUE TITLE
[BUG] Updated  StatusUpdater.php And Ping does not work on v3.5.2

### ISSUE THREAD

**Issue by erwim** [phpservermon/phpservermon#1095]
Centos 7 , PHP Server Monitor v3.5.2

I have download [StatusUpdater.php](https://github.com/phpservermon/phpservermon/raw/develop/src/psm/Util/Server/Updater/StatusUpdater.php),and replace this file.
I also can't ping 172.16.6.1 by PHP Server Monitor v3.5.2.
I can ping it in centos.

83cb22c86462c7af4341ccc74975344d  StatusUpdater.php

```

[root@localhost ~]# sudo -u www ping 172.16.6.1
PING 172.16.6.1 (172.16.6.1) 56(84) bytes of data.
64 bytes from 172.16.6.1: icmp_seq=1 ttl=254 time=2.53 ms
64 bytes from 172.16.6.1: icmp_seq=2 ttl=254 time=1.72 ms
64 bytes from 172.16.6.1: icmp_seq=3 ttl=254 time=0.699 ms
64 bytes from 172.16.6.1: icmp_seq=4 ttl=254 time=0.530 ms
64 bytes from 172.16.6.1: icmp_seq=5 ttl=254 time=0.478 ms
64 bytes from 172.16.6.1: icmp_seq=6 ttl=254 time=0.465 ms
^C
--- 172.16.6.1 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5004ms
rtt min/avg/max/mdev = 0.465/1.072/2.539/0.788 ms
[root@localhost ~]#

```

**Comment by wienfuchs** [comment]
Duplicate to still open https://github.com/phpservermon/phpservermon/issues/1093 - known issue and already solved in development for next release. (see #1047 and #963 ).
You may download https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Util/Server/Updater/StatusUpdater.php to get it working "now".

**Comment by erwim** [comment]
I have see those，i download the same Url(raw) StatusUpdater.php, and replace it,But i Dont't work yet.
https://github.com/phpservermon/phpservermon/raw/develop/src/psm/Util/Server/Updater/StatusUpdater.php

**Comment by wienfuchs** [comment]
I'm willing to try to reproduce that locally to solve if able to do so - what version of PHP are you using, what version of MySQL or MariaDB?

**Comment by erwim** [comment]
> I'm willing to try to reproduce that locally to solve if able to do so - what version of PHP are you using, what version of MySQL or MariaDB?

> I'm willing to try to reproduce that locally to solve if able to do so - what version of PHP are you using, what version of MySQL or MariaDB?

PHP 7.4.12 (cli) (built: Feb 25 2021 09:02:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies


mysql  Ver 14.14 Distrib 5.5.62, for Linux (x86_64) using readline 5.1

**Comment by 123710** [comment]
i have the same problem. i download the same Url(raw) StatusUpdater.php, and replace it,But it Don't work yet.

**Comment by moranno** [comment]
> i have the same problem. i download the same Url(raw) StatusUpdater.php, and replace it,But it Don't work yet.

me too, any update?

**Comment by adliazaddin** [comment]
bump..

every ping doesnt to work on any host and i have downloaded the StatusUpdater.php.. it shows fatal error on line 444

IIS
PHP 7.4
MariaDB 10.5
PSM 3.5.2

**Comment by wienfuchs** [comment]
> every ping doesnt to work on any host and i have downloaded the StatusUpdater.php.. it shows fatal error on line 444
> IIS

That line tries to create a socket connection on a Windows host. Maybe your IIS/PHP does not have the permission to do so? Your issue anyway is different to the others in this thread, as it relates to Windows that uses different methods.

**Comment by adliazaddin** [comment]
i have reverted back to the original StatusUpdater.php.. so far service and website works.. except ping... any idea how to fix this?

**Comment by adliazaddin** [comment]
> > every ping doesnt to work on any host and i have downloaded the StatusUpdater.php.. it shows fatal error on line 444
> > IIS
> 
> That line tries to create a socket connection on a Windows host. Maybe your IIS/PHP does not have the permission to do so? Your issue anyway is different to the others in this thread, as it relates to Windows that uses different methods.

it works now... my php_sockets was not properly configured
