### ISSUE TITLE
Getting a 504 Gateway Timeout when I click the update button. 

### ISSUE THREAD

**Issue by briantho** [phpservermon/phpservermon#1097]
Not sure what I'm doing wrong but every time I click the update button at the top of phpservermon's web interface, I get a 504 Gateway time out. Eventulally the page come back up and works fine, but if i click update it does the save thing again. I just installed this on a server for monitoring mdns .local addresses, and it does seem to work. However when i click the update button I get a 504 error. Is anyone else experiencing this issue? [Is it possibly related to this issue?](https://github.com/phpservermon/phpservermon/issues/1093) I already tried updating StatusUpdater.php but it doesn't appear to fix the problem. my server is running debian, with nginx, php 7.3 fpm, and mariadb. I am running the latest release 3.5.2. Please help me. Thanks

**Comment by wienfuchs** [comment]
The "ping" issue is definately not related to an 504 error on updates on nginx.  As I do not have a nginx installation I unfortunately cannot really guess where your issue could come from. Maybe your server logs can help you to find the problem source?

**Comment by briantho** [comment]
There isn't much on info on my server logs. I am getting this in my nginx error logs
`2021/03/04 13:11:54 [error] 8877#8877: *31195 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /?&mod=se
rver_update HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock", host: "127.0.0.1:89", referrer: "http://127.0.0.1:89/?&mod=server_status"
`
There isn't anything else really in error.log
I am running php server monitor on port 89 and accessing through localhost
Also, I tried adding 
define('PSM_DEBUG', true);
to the end of my config.php for php server monitor, but where are the logs for this? I can't seem to find them

**Comment by TimZ99** [comment]
The debug mode just shows PHP warnings en errors.
