### ISSUE TITLE
[SMS.RU support]

### ISSUE THREAD

**Issue by Alexell** [phpservermon/phpservermon#1099]
Hello.
Please add support for the sms.ru gateway, since it is easy to use and does not require signing a contract.

For the monitoring administrator, you need to add the "API key" field, and for users only the phone number.

**HTTP request to send SMS:** `https://sms.ru/sms/send?api_id=API_KEY&to=79000000000&msg=hello+world&json=1`

- The phone number is transmitted in 11-digit format.
- The message text is transmitted in UTF-8 encoding
- Spaces in the message are replaced with a "+" sign.

**Response handling:**
```
{
    "status": "OK", // The request was completed successfully (no authorization errors, no problems with the sender, etc ...)
    "status_code": 100, // Successful execution code
    // ... We don't need the rest
}
```
**P.S.** The documentation says that for authorization, you can use the login and password instead of the API key, passed in the request with the **login** and **password** parameters.

**API documentation:** https://sms.ru/api/send

**Comment by TimZ99** [comment]
Please have a look at the files of the current providers. It's fairly easy to add a new provider.
