### ISSUE TITLE
[Question] status_cron.php returns error

### ISSUE THREAD

**Issue by adliazaddin** [phpservermon/phpservermon#1103]
Hi,

upon running php status_cron.php on windows terminal im receiving below error, kindly assist

C:\inetpub\wwwroot\phpservermon\cron>php status.cron.php

Warning: socket_read(): unable to read from socket [10060]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 in C:\inetpub\wwwroot\phpservermon\src\psm\Util\Server\Updater\StatusUpdater.php on line 449

Notice: Undefined variable: errorcode in C:\inetpub\wwwroot\phpservermon\src\psm\Util\Server\Updater\StatusUpdater.php on line 454

**Version (please complete the following information):**
 - Version 3.5.2
 - PHP 7.4
 - IIS

**Additional context**
by clicking update button it works, but not on terminal.

**Comment by wienfuchs** [comment]
10060 is a timeout error. That may have many reasons, some of them relate to Windows firewall settings for the user or process running the status_cron.

**Comment by adliazaddin** [comment]
> 10060 is a timeout error. That may have many reasons, some of them relate to Windows firewall settings for the user or process running the status_cron.

sorry for the late reply.. fixed with the timeout issues tyvm
