### ISSUE TITLE
phpservermon navigation page issue take me back to apache home bage

### ISSUE THREAD

**Issue by muhmar3i** [phpservermon/phpservermon#1104]
phpservermon navigation page issue take me back to apache home bage
i have issue i can't navigation on phpservermon it's always take me back to apache home 
i must enter phpservermon on like every time i need to move 
i use version 3.5.2

![image](https://user-images.githubusercontent.com/46328320/112764986-44e79600-900b-11eb-8af9-a4d93b2cd897.png)

**Comment by wienfuchs** [comment]
That sounds as if you have eihter installed it in a subdirectory but not properly configered PSM_BASE_URL tou point to that "root" url (to be configured in your config.php) or that you have unzipped your data into /var/www/html without removing your existing index.html

**Comment by muhmar3i** [comment]
> That sounds as if you have eihter installed it in a subdirectory but not properly configered PSM_BASE_URL tou point to that "root" url (to be configured in your config.php) or that you have unzipped your data into /var/www/html without removing your existing index.html

this it not the only one i have i have more than one but only this app make that with me 
i can navigator by enter phpservermon before / and after ? on my url

http://localhost/?&mod=config

**Comment by wienfuchs** [comment]
As mentioned, I highly doubt this is a phpservermon issue or bug, I am 99% sure, it ist related to your apache config / files instead. But without any details of that noone will be able to check that nor to help you.

For example,
.) Apache config line of DirectoryIndex shows what?
.) ``ls -alF index*`` of your host root shows what?

**Comment by muhmar3i** [comment]
> ls -alF index*
this file i have in folder "/var/www/html/phpservermon"


and kindly find PSM_BASE_URL
![image](https://user-images.githubusercontent.com/46328320/112767193-939a2d80-9015-11eb-9aff-a2bad4b4dc84.png)

![image](https://user-images.githubusercontent.com/46328320/112767150-52a21900-9015-11eb-830d-247c42e7a5b4.png)

**Comment by muhmar3i** [comment]
> As mentioned, I highly doubt this is a phpservermon issue or bug, I am 99% sure, it ist related to your apache config / files instead. But without any details of that noone will be able to check that nor to help you.
> 
> For example,
> .) Apache config line of DirectoryIndex shows what?
> .) `ls -alF index*` of your host root shows what?

thank you, you make me look at file config and look at PSM_BASE_URL it was empty i don't write my link 
thanks for your help <3
