### ISSUE TITLE
[BUG] Mail and Pushover notifications not working on Offline/Online changes

### ISSUE THREAD

**Issue by BeyondVertical** [phpservermon/phpservermon#1114]
**Describe the bug**
Mail notifications and Pushover notifications do not work when the status changes.
They do however work when I send the test messages. Those are working fine.
I tried every option in the config menu, but no success.
Also nothing, not even the test messages, is logged in the mail or Pushover logs.

**To Reproduce**
Test the notification of mail and Pushover - that works.
Force a change of status - no messages via mail or Pushover. Nothing. The status however is shown correctly.

**Expected behavior**
Mail and Pushover notifications on status changes or as defined in the config.

**Version (please complete the following information):**
 - Version 3.5.2
 - PHP 7.4

**Comment by wienfuchs** [comment]
Did you add the server to a user? That's the main reason, why mails are not sent - when there is no user associated with the server, ther will not be produced any notification. That's not a bug but a feature ;)

**Comment by BeyondVertical** [comment]
Yeah, well… this is embarrassing, you were right. I forgot or did not know about that. Thanks for the quick help!
