### ISSUE TITLE
[Feature Request] Uptime percentage in status dashboard

### ISSUE THREAD

**Issue by BeyondVertical** [phpservermon/phpservermon#1116]
**Is your feature request related to a problem? Please describe.**
I want to see the uptime percentage at first glance on the status dashboard, instead of going into the details of every server.

**Describe the solution you'd like**
Adding another column to the table with the uptime value from the details page.

**Describe alternatives you've considered**
Maybe also adding a customizable option for this table.

**Comment by TimZ99** [comment]
Feel free to create a pr!
