### ISSUE TITLE
[BUG]  Cron doesn't work (synology DSM / task planner Synology / phpservermon 3.5.2)

### ISSUE THREAD

**Issue by cmoicyril** [phpservermon/phpservermon#1117]
Cron doesn't work (task planned in Synology / DSM)
All other things working

**To Reproduce**
  i've quoted in cron/status.cron.php all "if" block after _if(!psm_is_cli()) {_
  script launched in DSM task planification : 
      /volume1/@appstore/PHP7.0/usr/local/bin/php70 /volume1/web/phpservermonitor3_5_2/cron/status.cron.php

            _output : "PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /volume1/web/phpservermonitor3_5_2/src/psm/Module/User/UserEvents.php on line 38
          
          Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /volume1/web/phpservermonitor3_5_2/src/psm/Module/User/UserEvents.php on line 38
          "_

**Expected behavior**
  i've expected that task planned in DSM would activate php server monitor scanning

**Screenshots**

**Version (please complete the following information):**
    php server monitor last version : 3.5.2
    Synology DSM 6.2.4 25556
    PHP 7.0.33-0028,  PHP 7.3.16-0008  installed
    MariaDB 10.3.24-0069
    All packages up to date (webstation, etc)

**Additional context**
   i searched several hours on internet, didn't found solution.. help ..

**Comment by wienfuchs** [comment]
This is probably related to your Synology PHP as of it shows 7.0 above.
Google immediately founds an answer to your error message relating to this:
"The ability to specify the visibility of class constants was only added in PHP 7.1, from the manual page. Note: As of PHP 7.1.0 visibility "
phpservermonitor 3.5.2 lacks support for PHP 7.0; that was discussed and already solved in https://github.com/phpservermon/phpservermon/issues/908

Pls use search functions both in google and also in github before raising a solved bug a second time ;)

**Comment by cmoicyril** [comment]
Ok, my bad, indeed PHP 7.3 was indicated in Webstation (the webserver), but not in the script. 

Nevertheless, i found an error in /src/psm/Service/Database.php, causing planned task to crush. But (i don't undestand why) the webinterface of PSM working.

The fix, founded on SourceForge, founded with Google, is : 

   Code before:

'mysql:host='.$this->db_host.';port='.$this->db_port.';dbname='.$this->db_name.';charset=utf8',
New code:

'mysql:host='.$this->db_host.':'.$this->db_port.';dbname='.$this->db_name.';charset=utf8',

-> perhaps it can be put in current distribution of psm ? 

Best Regards

**Comment by wienfuchs** [comment]
Pls do not mix different subjects into one thread, instead pls oben a different thread for that subject. :) Id you do so, it probably will be looked into and if necessary it will befixed too.
