### ISSUE TITLE
[Question] Possible to use a unix socket to connect to the database?

### ISSUE THREAD

**Issue by RedKage** [phpservermon/phpservermon#1118]
- [ x] Looked at the documentation first

**Describe the question**
Is it possible to connect using unix socket to the database?
During the `install.php` I cannot provide a host/port as it is not listening on any interface.

I tried to set `PSM_DB_HOST` to my unix socket like `:/home/xxxxxx/var/run/mysql.sock` but it fails with 
> Fatal error: Unable to establish database connection... in /xxxxxxxxx/phpservermon/src/bootstrap.php on line 92

Sometimes I noticed this would work setting up the socket path instead of the DB host, like for nextcloud.

**Version (please complete the following information):**
 - Version 3.5.2
 - PHP 7.4.14
 - MariaDB 10.5.8

**Additional context**
MariaDB is configured with 
```
[mysqld]
skip_networking
#bind_address                    = 127.0.0.1
#port                           = 3306
socket                         = /home/xxxxxxxxxx/var/run/mysql.sock
```

**Comment by RedKage** [comment]
Answering myself : it doesn't, there's no support for unix socket.

I made a quick patch to `/src/psm/Service/Database.php`

```
    protected function connect()
    {
        $isHostunixSocket = strpos($this->db_host, ':') === 0;

        // Initizale connection
        try {
            if ($isHostunixSocket) {
                $this->pdo = new \PDO(
                    'mysql:unix_socket=' . ltrim($this->db_host, ':') .
                        ';dbname=' . $this->db_name .
                        ';charset=utf8',
                    $this->db_user,
                    $this->db_pass
                );
            } else {
                $this->pdo = new \PDO(
                    'mysql:host=' . $this->db_host .
                        ';port=' . $this->db_port .
                        ';dbname=' . $this->db_name .
                        ';charset=utf8',
                    $this->db_user,
                    $this->db_pass
                );
            }

            $this->pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
            $this->status = true;
        } catch (\PDOException $e) {
            $this->status = false;
            return $this->onConnectFailure($e);
        }
        return $this->pdo;
    }
```

If the host starts with `:` then we assume it's a socket.
Which means if a host looks like `:/home/xxxxxx/var/run/mysql.sock` it will be handled as a unix socket

**Comment by RedKage** [comment]
I'm not sure how to do a PR
And besides, as I don't really have time to check if there are other areas which needs to patched as well ... I'd rather not make a PR

**Comment by TimZ99** [comment]
Because this is a 1 file change it is very easy. Go to the file on Github, edit the file and save it. It will be saved on a branch on your own account. After saving, press create pull request (destination is develop branch)(there is a message about this when you're going to the fork created on your own account.

**Comment by RedKage** [comment]
> Because this is a 1 file change it is very easy. Go to the file on Github, edit the file and save it. It will be saved on a branch on your own account. After saving, press create pull request (destination is develop branch)(there is a message about this when you're going to the fork created on your own account.

I did something. Seems to have worked!
