### ISSUE TITLE
Twilio for SMS

### ISSUE THREAD

**Issue by bwhatley87** [phpservermon/phpservermon#112]
It would be really beneficial to add twilio as one of the SMS platforms. It's is the cheapest ad easiest in the US.

**Comment by raggoo** [comment]
Seems like a no-brainer!

copy/paste from twilio:
<blockquote>Twilio delivers messages to over 1,200 carriers in 198 countries around the world, and monitors carriers to ensure your messages are delivered.</blockquote>

What is the timeframe on 3.2.0 please?

**Comment by raggoo** [comment]
Why was twilio sms never added please?

phpservermon really needs twilio.

**Comment by TimZ99** [comment]
Idk, will have a look.

**Comment by TimZ99** [comment]
Hmm, it seems like nobody took the time to implement it.

**Comment by TimZ99** [comment]
https://github.com/phpservermon/phpservermon/tree/feature/twilio

**Comment by TimZ99** [comment]
Btw, the current version doesn’t work. The path to the Twilio class is incorrect. Will change this later today.

**Comment by TimZ99** [comment]
It's added to the develop branch.
