### ISSUE TITLE
[Feature Request] Display latency (ping response) in millisecond and format number to be user-friendly

### ISSUE THREAD

**Issue by cmoicyril** [phpservermon/phpservermon#1122]
**Is your feature request related to a problem? Please describe.**
Currently latency in "state" and "server" pages are in seconds : a lot of zeros, not user-friendly 

**Describe the solution you'd like**
Indicate latency in millisecond, format number to be an integer starting from 1 millisecond (not less) 

**Describe alternatives you've considered**
.
**Additional context**

My configuration : 
php server monitor last version : 3.5.2, French language used
Synology DSM 6.2.4 25556
PHP 7.0.33-0028, PHP 7.3.16-0008 installed
MariaDB 10.3.24-0069
All packages up to date (webstation, etc)

**Comment by TimZ99** [comment]
See #918.
