### ISSUE TITLE
[BUG] Telegram Notification not sent

### ISSUE THREAD

**Issue by khoirulmuhajir** [phpservermon/phpservermon#1126]
**Describe the bug**
Telegram Notification Not sent when Status Changed

**To Reproduce**
1. Simulate server Down
2. Status of those server will be Down(Red)
3. Log created, but Nothing in Telegram Tab

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Version v3.5.2.
 - PHP 7.3

FYI : Test message to Telegram was success

**Comment by wienfuchs** [comment]
At probability of 99,9% this is not a bug but only a issue of not adding the server to an user. Pls use search function to find similar issues like https://github.com/phpservermon/phpservermon/issues/1002 and others.
![grafik](https://user-images.githubusercontent.com/44177781/118464101-c51fa300-b700-11eb-9b2d-96546322abb5.png)

**Comment by khoirulmuhajir** [comment]
> At probability of 99,9% this is not a bug but only a issue of not adding the server to an user. Pls use search function to find similar issues like #1002 and others.
> ![grafik](https://user-images.githubusercontent.com/44177781/118464101-c51fa300-b700-11eb-9b2d-96546322abb5.png)

Wow..thanks..it is my bad
