### ISSUE TITLE
Se pueden crear servidores de manera masiva?

### ISSUE THREAD

**Issue by Chris2129** [phpservermon/phpservermon#1131]
Quiero intentar subir 50 servidores, pero quiero saber si lo puedo hacer todo masivamente, pues no se mucho de programación pero me parece interesante para el monitoreo de unos equipos de computo.

**Comment by TimZ99** [comment]
Hi Chris, We sorted this out 👍🏼 . As I don't speak more than 5 words Spanish, please submit an issue in English next time 😄.
