### ISSUE TITLE
[BUG] [INCOMPLETE ISSUE]Telegram notification

### ISSUE THREAD

**Issue by ghost** [phpservermon/phpservermon#1134]
An error has occurred while sending the Telegram notification: Not Found 
last version

**Comment by wienfuchs** [comment]
An error has occoured while trying to understand your request: No details of anything supplied at all.

**Comment by TimZ99** [comment]
@satory33  Use the bug report template if you want help or want something fixed. Without info we can only guess.

**Comment by adigetr** [comment]
class Telegram
    {
       ..............................
        public function sendurl()
        {
              ..............................
                curl_setopt($con, CURLOPT_SSL_VERIFYPEER, false);      // try adding this line

**Comment by wienfuchs** [comment]
WHY should anyone weaken security by adding this here? Regular Telegram notifies work properly also with this option set. As it is security relevent, one definately should NOT inactivate this. Unless one hase a very specific setup and a very very specific reason to do so..
