### ISSUE TITLE
PHP 8 - can you make it work?

### ISSUE THREAD

**Issue by macuros** [phpservermon/phpservermon#1138]
Hi!

Is there any way to make it work with PHP 8 with the latest version?

Thank you.

**Comment by TimZ99** [comment]
Where do you experience problems?

**Comment by stoamandl** [comment]
tested with Server Monitor v3.5.2 and PHP version 8.0.9 in FCGId mode.
No errors detected in the console or website.
I think this is not a issue, just a question.

**Comment by mtwango** [comment]
Checked with https://github.com/PHPCompatibility/PHPCompatibility and it seems ok on 8.0

**Comment by macuros** [comment]
I just get a blank page. Maybe I need to enable certain PHP modules?

**Comment by mtwango** [comment]
Try manually creating config file from config sample. Had the same issue without it (on Windows 11).

**Comment by macuros** [comment]
Yes! Thank you very much. Just manually added the credentials for the database in now it is already installed.
