### ISSUE TITLE
[Feature Request] Monitor files: PHP or scripts for change

### ISSUE THREAD

**Issue by bigalgeorge** [phpservermon/phpservermon#1139]
Several times in the past my websites have been hacked and new php code added, and others modified such that the hacker sends thousands of spam emails via my smtp code and/or they add redirects or links to other sites and so on.

Existing website monitors are not adequate, as the site remains up, its the operation that changes.
REQUEST:
Website monitor that works like yours, but also checks for the following options:
Number of files in a _monitored directory_ with notice if change exceeds xxx.
Monitoring for changes to existing PHP by filesize change.

Anything else.

So far I have not been able to find such a tool.
Thanks and regards.

**Comment by TimZ99** [comment]
Hi @bigalgeorge, sorry to inform you that this is outside the scope of this project.
