### ISSUE TITLE
[BUG] Non-Secure Forms when running behind reverse proxy with https

### ISSUE THREAD

**Issue by brtwrst** [phpservermon/phpservermon#1140]
**Description**
When running phpservermon behind a reverse proxy that does the ssl termination. When I create or edit a user/server I get this error in the developer console of my browser:
![Untitled](https://user-images.githubusercontent.com/6873862/128129755-3b17bc41-7d9c-4b22-bfc3-808afa6e6464.png)

And the Security Tab:
![image](https://user-images.githubusercontent.com/6873862/128128974-85025b04-c6b8-4888-932f-95abe003f505.png)

And this error when submitting the form:
![image](https://user-images.githubusercontent.com/6873862/128129156-0e6eb153-3307-48c5-b1bc-6eabd1b5507f.png)

**The error does not appear on some other pages that include forms (like the Config page)**

**To Reproduce**
1. Run docker-phpservermon behind a reverse proxy (nginx in this case)
2. Log in and click on Servers -> Add new
3. Open the Developer Console

**Expected behavior**
All Forms should be secure.

**Version**
 - docker.phpservermon v3.5.2
 - Brave version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)

**Comment by wienfuchs** [comment]
That's probably no bug but possibly missing or improper setting of "PSM_BASE_URL" in your individual config.php. Pls try setting this according to your "external" URL including the proper protocol to be used.

**Comment by brtwrst** [comment]
Yes adding it to the config php does fix the Problem, but with the current https://github.com/phpservermon/docker-phpservermonitor configuration there is no way of specifying PSM_BASE_URL.

I will look into adding this to the Dockerfile and docker-entrypoint over in the docker repo.

Thank you for clearing this up for me.

**Comment by casperklein** [comment]
> there is no way of specifying PSM_BASE_URL.

I wasn't aware of the PSM_BASE_URL setting and fixed it within my apache configuration:

```
AddOutputFilterByType SUBSTITUTE text/html
ProxyPass "/phpservermonitor/" "http://127.0.0.1:1084/" retry=0
ProxyPassReverse "/phpservermonitor/" "http://127.0.0.1:1084/"
<Location /phpservermonitor/>
         Substitute "s|http://127.0.0.1:1084/|https://example.com/phpservermonitor/|n"
</Location>
```

I'm looking forward to a proper [solution](https://github.com/phpservermon/docker-phpservermonitor/pull/13) 👍
