### ISSUE TITLE
[Feature Request] ? Get webpage with javascript enabled browser

### ISSUE THREAD

**Issue by loginid** [phpservermon/phpservermon#1144]
Hi there,

Firstly, thanks for a great and free app - I really love it :)

Is there any chance we can get a fully javascript enabled browser to get the monitored page?

Or is there anyway I can change the php to implement this?
If you point me in the right direction I can look into doing it.

Thank you!

**Comment by TimZ99** [comment]
I think you want to have the scheduled checks without a from job?

If so, you can press the update button to run it manually or let some JavaScript (or something else) load the update page.
