### ISSUE TITLE
[Feature Request] Add timeout to devices. Change default

### ISSUE THREAD

**Issue by nahventure** [phpservermon/phpservermon#1145]
Looking to change the timeout that is applied to each device. We have over 100 devices in our servermon instance, to which when a few are down can take forever. All we have are local devices with pings of around 5-50 ms, therefore having anything not reply within a second =! is down. I can't seem to find the option for it anywhere, my apologies if it is a feature I overlooked.

Cheers.

**Comment by gcwebsites** [comment]
You can change the timeout within each server setup. There isn't an overall setting that I am aware of, but you can edit it per server on the timeout before it is reported as "Down".

**Comment by nahventure** [comment]
> You can change the timeout within each server setup. There isn't an overall setting that I am aware of, but you can edit it per server on the timeout before it is reported as "Down".

I suppose this has been added lately, I upgraded the install yesterday, just realized this has been added. Seems like it has a default of 10, would be great to be able to change the default though.

**Comment by gcwebsites** [comment]
I thought it might've because I was running a newer version, the default is 10 and I agree - A global setting would be great.

I use my instance for monitoring websites and have a 30 second time out set.

**Comment by TimZ99** [comment]
I believe that the timeout setting was one of the very first settings that was added.
