### ISSUE TITLE
[Question] How to add an additional column on the status page with a button link to a desired URL? 

### ISSUE THREAD

**Issue by jrmoontech** [phpservermon/phpservermon#1151]
- [x] Looked at the documentation first

**Describe the question**
Essentially my question is two parts:

1. How to add a new column to the status page table that populates the same way as the rest of the data fields
2. How to add a button to said column that acts as a direct link to a user supplied URL (in our case, we want to link to our CRM to make entering tickets quicker and more efficient for the corresponding customer sites) 

**Version (please complete the following information):**
 - Version 3.5.2
 - PHP 7.4.23

**Comment by TimZ99** [comment]
This section for the status page table. 
https://github.com/phpservermon/phpservermon/blob/460db614f8f38b1c8edf97b3a12611443267d747/src/templates/default/module/server/status/index.tpl.html#L53-L105

Here the server data is collected to be displayed.
https://github.com/phpservermon/phpservermon/blob/460db614f8f38b1c8edf97b3a12611443267d747/src/psm/Module/Server/Controller/StatusController.php#L84-L108

Hope this will help you to move forward. Let me know if you need anything else.

**Comment by jrmoontech** [comment]
Thank you Tim!

**Comment by jrmoontech** [comment]
One more question,

What about on the Servers page adding the ability to write a string to a
corresponding database entry? Basically so I can populate the status page
with URL links

Thank you! Do you have anywhere I can contribute money to this project?
