### ISSUE TITLE
[BUG] Composer install fails

### ISSUE THREAD

**Issue by codegm** [phpservermon/phpservermon#1158]
**Describe the bug**
WIth composer 2.1.12 not installable. 

**To Reproduce**
1. composer install  --no-dev
2. Output:
```
  Problem 1
    - mnsami/composer-custom-directory-installer is locked to version 1.1.1 and an update of this package was not requested.
    - mnsami/composer-custom-directory-installer 1.1.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
  Problem 2
    - mnsami/composer-custom-directory-installer 1.1.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.1.0] but it does not match the constraint.
    - viharm/php-ldap-auth v2.5.1 requires mnsami/composer-custom-directory-installer 1.1.* -> satisfiable by mnsami/composer-custom-directory-installer[1.1.1].
    - viharm/php-ldap-auth is locked to version v2.5.1 and an update of this package was not requested.
```

**Expected behavior**
Clean install

**Version (please complete the following information):**
 - Version dev-branch
 - PHP 7.4
 - Composer 2.1.12

**Additional context**
composer update --no-dev throws similar errors

**Solution**
I think viharm/php-ldap-auth and viharm/php-db-auth must require mnsami/composer-custom-directory-installer 2.0.0 to get it running with composer 2.

**Comment by TimZ99** [comment]
Hi, this is a known problem for many projects. See https://github.com/phpservermon/phpservermon/issues/1077#issuecomment-819939627 for more info.
