### ISSUE TITLE
Service status problem [BUG] 

### ISSUE THREAD

**Issue by mark-darko** [phpservermon/phpservermon#1161]
Faced a problem when my service is not active, the monitor shows that the service is running, but no further service status update follows, although the monitor checks other services for their activity
![image](https://user-images.githubusercontent.com/66490236/143688950-ed9b2a1c-198d-42b3-a1d6-f2ca9dbc940d.png)

**Comment by TimZ99** [comment]
No clue why, no way to reproduce, too little information. Maybe you have set a warning threshold?
