### ISSUE TITLE
[BUG] Last online: text encoding error

### ISSUE THREAD

**Issue by baur** [phpservermon/phpservermon#1165]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2898361/141714930-4df744a5-d5fd-4069-93d3-6c40a62e03ea.png)

**To Reproduce**

1. Change to Russian langugage 
2. See servers in offline 3-5 days and more

**Expected behavior**

Normal text

**Screenshots**

**Version (please complete the following information):**
 - Version [3.6.0 master]
 - PHP [e.g. 7.4.25]

**Additional context**
![image](https://user-images.githubusercontent.com/2898361/141717848-f958c152-261a-448a-bf20-3a41ad749dac.png)

![image](https://user-images.githubusercontent.com/2898361/141717903-ce7a2c94-04da-4413-9e56-8f1799d1d759.png)

![image](https://user-images.githubusercontent.com/2898361/144960022-83576c10-208a-44b7-a3a3-abcbfbc22337.png)

**Comment by baur** [comment]
![image](https://user-images.githubusercontent.com/2898361/145334414-43ef25d4-5332-4c6f-a01c-50ba84eabaf9.png)

**Comment by TimZ99** [comment]
Can't reproduce on the latest dev branch. Please update to latest dev and let me know if the problem is still there.

**Comment by baur** [comment]
@TimZ99 

>  Please update to latest dev    

yes, this is from last dev bracnh
>  Can't reproduce    

This bug appearas when server is offline 3-5 days and more
