### ISSUE TITLE
How to set auto monitoring

### ISSUE THREAD

**Issue by jawadaq82** [phpservermon/phpservermon#1168]
I have set it up on my Azure and have added 3 websites for monitoring.
Every time I have to log into this application and manually click on Update button to test and see if my websites are online or no.

How can I set it to automatically look all my websites periodically like every 1 minute?

**Comment by wienfuchs** [comment]
http://docs.phpservermonitor.org/en/latest/install.html#setting-up-a-cronjob has the answer.

**Comment by jawadaq82** [comment]
Great! thanks for prompt response.
