### ISSUE TITLE
[BUG] Missing usernames while adding new server

### ISSUE THREAD

**Issue by jawadaq82** [phpservermon/phpservermon#1169]
When adding a new server we are unable to see usernames as seen below.

![image](https://user-images.githubusercontent.com/10131129/146645713-15673ef2-703a-4188-a815-679c8dc864ed.png)

When updating the server, we are able to see the usernames.

**Comment by wienfuchs** [comment]
That is a known issue in 3.5.2 that was solved in 3.6.0 (yet beta, but very stable). You may want to give the "devel" branch a try.
