### ISSUE TITLE
[BUG] Ping doesn't work

### ISSUE THREAD

**Issue by simone80an** [phpservermon/phpservermon#1173]
**Describe the bug**
I have installed latest PHP Server Monitor on a Windows 2012 server machine which has XAMPP. If i ping from that machine an IP from Windows command line the server responds, but using the ping type from PHP Server Monitor it always tells that is offline.

**Expected behavior**
Using the ping type show me the real status of the server.

**Version (please complete the following information):**
 - Version [3.5.2]
 - PHP [7.4.27]

**Comment by burkhanisci** [comment]
Hello, I have the same issue with v3.5.2.

I tried with v3.4.5 it works.

It may be a version-specific issue not caused by XAMPP or in my case WAMP.
