### ISSUE TITLE
[BUG]  TLS1.3 only sites - TIMEOUT ERROR: no response from server

### ISSUE THREAD

**Issue by jeffshead** [phpservermon/phpservermon#1176]
**Describe the bug**
On three seperate websites, on three seperate servers, I only get the `TIMEOUT ERROR: no response from server` error so those monitored sites always show as down even though I can access them from the server on which PSM is installed. PSM is set to monitor each server as a website and to **Search string/pattern**. All  three servers have a Caddy2 reverse-proxy -> Apache. This problem exists if the Caddy server is setup to use TLS1.3, only. If I add TLS1.2 support, PSM is able to connect to each server and work as expected.

**To Reproduce**
1. Set up a server which supports only TLS1.3.
2. Try to monitor it as a website and use **Search string/pattern**
3. PSM will fail to connect 

**Expected behavior**
PSM should support TLS1.3 as it does TLS1.2.

**Screenshots**

**Version (please complete the following information):**
 - Version  3.6.0
 - PHP 7.4 and 8.x

**Additional context**

**Comment by wienfuchs** [comment]
What curl version are you using? As far as I've seen there is no restrition or option set, not to use TLS v1.3 - so this may be not an phpservermon but a local installed curl issue.

**Comment by jeffshead** [comment]
> What curl version are you using? As far as I've seen there is no restrition or option set, not to use TLS v1.3 - so this may be not an phpservermon but a local installed curl issue.

```
[root@connect ~]# curl --version
curl 7.61.1 (x86_64-redhat-linux-gnu) libcurl/7.61.1 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.6 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.2.0) libssh/0.9.4/openssl/zlib nghttp2/1.33.0
Release-Date: 2018-09-05
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
```

**Comment by wienfuchs** [comment]
Maybe it's a cipher problem with that specific curl version curl?
https://github.com/curl/curl/issues/3178 for example relates to exact the same curl version.

**Comment by jeffshead** [comment]
> Maybe it's a cipher problem with that specific curl version curl? [curl/curl#3178](https://github.com/curl/curl/issues/3178) for example relates to exact the same curl version.

I updated to the latest curl:
```
curl 7.80.0 (x86_64-pc-linux-gnu) libcurl/7.80.0 OpenSSL/1.0.2k-fips zlib/1.2.7
Release-Date: 2021-11-10
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
```
Made no difference.

**Comment by jeffshead** [comment]
Confirmed issue is either with cURL or with one of its dependencies. When I updated to cURL 7.80.0, I followed [these](https://geekflare.com/curl-installation/) instructions but that did not solve the issue.

I performed the update a second time but I followed [these different](https://www.mysterydata.com/update-install-latest-curl-version-on-rhel-8-rhel-7-centos-7-8-cwp-vestacp-cpanel-plesk/) instructions and it now works!

**Comment by wienfuchs** [comment]
> Confirmed issue is either with cURL or with one of its dependencies. 
> 
> I performed the update a second time but I followed [these different](https://www.mysterydata.com/update-install-latest-curl-version-on-rhel-8-rhel-7-centos-7-8-cwp-vestacp-cpanel-plesk/) instructions and it now works!

Glad to hear that. Have a great happy new year!
