### ISSUE TITLE
[BUG] Offline Website

### ISSUE THREAD

**Issue by yasintkgoz** [phpservermon/phpservermon#1209]
why some websites seem down
E.g : https://google.com 

Domain: https://google.com
Type: Website

I have version : 3.6.0

Thank You All.

**Comment by gcwebsites** [comment]
Its most likely your user agent or a security block of the IP you are checking from. I had it happen to me in the past for both user agent and the IP of my server. I ended up changing the user agent to chrome and then using a proxy for the IPs.

**Comment by yasintkgoz** [comment]
> Its most likely your user agent or a security block of the IP you are checking from. I had it happen to me in the past for both user agent and the IP of my server. I ended up changing the user agent to chrome and then using a proxy for the IPs.

thanks for your answer. What did you write in this User Agent field? 3.2.0  version does not have this problem.

**Comment by gcwebsites** [comment]
> > Its most likely your user agent or a security block of the IP you are checking from. I had it happen to me in the past for both user agent and the IP of my server. I ended up changing the user agent to chrome and then using a proxy for the IPs.
> 
> thanks for your answer. What did you write in this User Agent field? 3.2.0 version does not have this problem.

https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome#:~:text=Chrome%20User%20Agents-,Chrome%20(Standard),-Mozilla/5.0%20(Windows
