### ISSUE TITLE
[BUG] Broken Menu in Admin Panel

### ISSUE THREAD

**Issue by Gill-Bates** [phpservermon/phpservermon#1219]
`Version: 3.6.0`

Server Menu is not scrollable.

Same behavior in Edge and Firefox
![image](https://user-images.githubusercontent.com/25774289/189608410-491be72b-7e93-49b6-8076-ad28e95dbd36.png)

Steps to Reproduce:

1. Login as Admin
2. Click on "Servers" in the Menu Bar
3. Click on the 3 Dots at the end of the line

**Comment by TimZ99** [comment]
That's not nice. I don't have a solution for this. What device do you use?
