### ISSUE TITLE
[Feature Request] Local SMS Gateway Support

### ISSUE THREAD

**Issue by cwoelkers** [phpservermon/phpservermon#1243]
**Is your feature request related to a problem? Please describe.**
There is no set feature to send an SMS via a gateway on the local network.

**Describe the solution you'd like**
One or more local SMS gateway solutions added to the dropdown. At the minimum free solutions such as Gammu, PlaySMS, and SMS Server Tools should be supported though there are a myriad of commercial options as well. Beyond the three current fields, username, password, and senders number, they should also include the URL field.

**Describe alternatives you've considered**
Copy and reconfigure one of the existing SMS gateway PHP files to support the local gateway of choice, currently Gammu.

**Additional context**
A local SMS gateway is useful in the a security context as it bypasses sending the SMS to an Internet/cloud based service. Many government entities and industries can only use a very small subset of cloud based services and having a local gateway works around the issue.

**Comment by TimZ99** [comment]
Only adding the URL field is not possible as most API's work different. They require values with different names, request types etc. Is you want to add a specific service, feel free to open a PR.
