### ISSUE TITLE
Unable to log in...

### ISSUE THREAD

**Issue by ghost** [phpservermon/phpservermon#129]
Hello,

i just installed your application but when i click on login with the correct credentials and i press on login
it just refreshes the page...

**Comment by adwait123** [comment]
Same issue. Randomly logs in but then need to login after every click.

**Comment by raenk** [comment]
Same here

PHP 5.4.41 (cli) (built: May 14 2015 23:15:28)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
