### ISSUE TITLE
SMS gateway - use our own sms gateway

### ISSUE THREAD

**Issue by raggoo** [phpservermon/phpservermon#141]
Please write it in so we can use our own sms gateway instead of paid services.

**Comment by CasteyDaSilva** [comment]
It's quite simple:
Make gateway class in src/psm/Txtmsg, of course make class compatible with api of your gateway
<?php
namespace psm\Txtmsg;

class YourGW extends Core {
    // =========================================================================
    // [ Fields ]
    // =========================================================================

        public function sendSMS($message) {
// api base url
        $api_url = "https://panel.promosms.pl/remote/http/send.php";
// encoded message
        $message_body = urlencode( $message );
// get login from field in config
        $api_login = urlencode ( $this->username );
// get pass from config
        $api_pass = urlencode ( $this->password );
// Send SMS to users
                foreach( $this->recipients as $phone ){
//build URL
                        $URL = $api_url.'?login='.$api_login.'&pass='.$api_pass.'&msg='.$message_body.'&to='.$phone;
//Send request                        
$result = psm_curl_get($URL);
                }
                return $result;
        }
}

Next
 add line:
<option value="promo" {{ sms_selected_yourgw|raw }}>{{ label_sms_gateway_yourgw }}</option>
in src/templates/default/module/config/config.tpl.html (line ~150)

add line:
'label_sms_gateway_promo' => psm_get_lang('config', 'sms_gateway_yourgw'),
in src/psm/Module/Config/Controller/ConfigController.class.php (~311)

add line:
'sms_gateway_yourgw' => 'Your GateWay',
in src/lang/en_US.lang.php (~190)

and last additional  lines:
case 'yourgw':
                        $sms = new \psm\Txtmsg\YourGW();
                        break;
in switch(strtolower(psm_get_conf('sms_gateway'))) in file src/includes/functions.inc.php (line ~442)

**Comment by raggoo** [comment]
Comment from owner please?

**Comment by raggoo** [comment]
HELLO???

**Comment by raggoo** [comment]
HElloooooooo???

**Comment by sadortun** [comment]
@raggoo  if you are interested in developing a custom SMS provider you can fork the project, and contribute the feature, or write a gist/wiki
