### ISSUE TITLE
Won't send mail when type = 'website'

### ISSUE THREAD

**Issue by Xsandor** [phpservermon/phpservermon#154]
Hi.
Everything is perfect when I use service and specify a port, I receive an email whenever there is a state change. But when I change the type to website and get a state change there is no email sent. I can see in the log->email that it has been sent. What could be wrong?

I'm using version 3.1.1 on:
Ubuntu 14.04
Apache 2.4.7
PHP 5.5.9
MySQL 5.5.40

I've made my own translation to swedish, but it doesn't work even if I change back to english.

**Comment by sadortun** [comment]
Did you solved this issue?
