### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mokry** [phpservermon/phpservermon#166]
What about checking server from behind proxy servers? For Sites (curl) and Services (via fsockopen)?

**Comment by icarius** [comment]
It is a good idea!
For my part I have change the code to allow me to CURL address behind proxy

**Comment by TimZ99** [comment]
Proxy is in the latest version, Services are not supported tho.

**Comment by gmoulard** [comment]
In my case, for internal usage I need to specify a proxy by server. For some user, I use one proxy for some other I use one other. 
Could you thiink is possible to add the setup sont server parameter?
G.
