### ISSUE TITLE
need support for htpassword logins

### ISSUE THREAD

**Issue by ideasoft** [phpservermon/phpservermon#167]
i have htpassword protected sites to monitor. is it possible for you to bring that feature, to send username and passwords from curl headers?

thanks in advance

**Comment by dopeh** [comment]
Have you tried using the format:
http://user:pass@www.example.org

**Comment by ideasoft** [comment]
i tried now as you say, i am trying to monitor a site with both htpassword and from secure connection. (https 443). it fails.

**Comment by sadortun** [comment]
Still having the issue?

**Comment by ideasoft** [comment]
sorry i had quited using phpservermon. thanks for your quick response.
