### ISSUE TITLE
Pushbullet Integration (NotifyMe)

### ISSUE THREAD

**Issue by TimTims** [phpservermon/phpservermon#168]
Hey ya,

Although PushOver is already integrated in the system, PushBullet integration would be amazing as PushBullet is one of the most used notification services.

It would be amazing if that was a feature that could be implemented.

Thanks :D 
Tim

**Comment by craigbett** [comment]
+1

**Comment by ldrrp** [comment]
+1

**Comment by CodeBrauer** [comment]
+1 / also take a look at https://github.com/notifymehq/notifyme

**Comment by bpvarsity** [comment]
Hipchat support would be awesome to.

**Comment by CodeBrauer** [comment]
@bpvarsity - Slack also!

**Comment by gm-ah** [comment]
+1

**Comment by dopessoa** [comment]
+1

**Comment by lupor0x** [comment]
+1

**Comment by levidurfee** [comment]
Why not just have the ability to add a webhook? [slack webhook](https://api.slack.com/incoming-webhooks) and [pushbullet webhook](https://zapier.com/zapbook/pushbullet/webhook/).

**Comment by sadortun** [comment]
NotifyMe integration is a great idea! Anybody would be interested in contributing the feature?

**Comment by kippg** [comment]
I tried to load their page and only got a white empty page :(

 

If that is something like IFTTT.com?

**Comment by nhalstead** [comment]
I have been writing a Package that will interact with Slack and Discord as well as other services using Webhooks. Once I have it up and running, Ill see about adding it to the project. I know interacting with webhooks from many sources can add a lot of code that can become messy fast. So my plan is to include all of the 3rd party webhook APIs you just specify what you want to connect to and give it all of the needed information and done. All of the APIs so far will have a basic text input and if you want any special that the webhook from that source supports, you just import the extras and tell it what you want to include as an attribute.

I think it would be a good addition to the project overall for adding connections to something like this for updates as they happen.

**Comment by TimZ99** [comment]
Webhooks are finally implemented 🎉
