### ISSUE TITLE
Textmarketer SMS is broken

### ISSUE THREAD

**Issue by mpattman** [phpservermon/phpservermon#172]
Hi @dopeh,

Please could you rename "Textmarketer.php" to "Textmarketer.class.php" to fix the issue and also consider my changes that I have made to the code.

https://github.com/mpattman/phpservermon/commit/6db7f2d36245a5d051abd86342fffe849cc4f65e

Thanks,

Matt

**Comment by gppixelworks** [comment]
Thanks mpattman, was trying to track down this very issue on a new install.

**Comment by sadortun** [comment]
please submit a PR with your proposed changes.  Thanks!

**Comment by TimZ99** [comment]
Fixed on 3.3.0.
