### ISSUE TITLE
Add option to specify which HTTP status codes are considered as "online"

### ISSUE THREAD

**Issue by rjayako** [phpservermon/phpservermon#175]
How do I set header 401 as a Online status and not Offline. Since that doesn't necessarily mean the site is offline. It just means the site required access. Any ideas?

**Comment by JBlond** [comment]
The issue is in src/psm/Util/Server/Updater/StatusUpdater.class.php line 200 till 207

**Comment by JBlond** [comment]
I agree that a 401 doesn't mean anything bad.

**Comment by rjayako** [comment]
Yep already fixed it on my code. Let me know if anyone wants assistance with this.

**Comment by JBlond** [comment]
Can you make a pull request or post the changes you made to get it working?

**Comment by dopeh** [comment]
Currently it is hard-coded to treat all 4xx headers as offline, this should at least be configurable by the user.

**Comment by rjayako** [comment]
Hi @JBlond I created a pull request, you can grab it if you want. I can add this as a configurable option if you guys want, I just didn't see the need to implement it for my use since I had no valid use case for it.

**Comment by dopeh** [comment]
Hi @rjayako thanks for providing the pull request, but for merging it in the project I would need it to be user configurable, as I do not feel comfortable changing 4xx status codes to "OK" if the project has always treated them as "NOT OK" in the past. For users upgrading to the a release I would like the behaviour for existing service/websites to remain the same.

**Comment by rjayako** [comment]
@dopeh ah very true! Alright, I'll work on this and create a pull request when I have the time. 

In the mean time here is the quick fix if anyone wants it dcabf77380118874f1d25c426811fce232256447 resolves this issue.

**Comment by sadortun** [comment]
Hi @rjayako Will you submit a PR for this ?
