### ISSUE TITLE
Feature Request: Hardware status

### ISSUE THREAD

**Issue by ThaMunsta** [phpservermon/phpservermon#177]
I'm in love with this script and its flexibility but I need hardware monitoring too, CPU, RAM, Disk and maybe OS uptime. We have a guy who could make a small program that would respond to pull requests for that info, but hes not sure how to make it play nice with this server monitor script. Historical data would be cool but I've been looking at this as an example: http://servers.nikkii.us/ but the source code is crazy old and out dated https://github.com/nikkiii/status

**Comment by bpvarsity** [comment]
try out https://status2k.com/

**Comment by ThaMunsta** [comment]
That's really good (and I actually bought it) but the problem is some of our servers do not have PHP installed and I was looking for more of running the monitor on one PHP server and having windows services running that would reply to one master server. After playing with it it looks like I'd need this php script on all servers being checked.

**Comment by ThaMunsta** [comment]
I've started dissecting the code and here is what I plan on doing. I'll worry about the client side later but I imagine it being a small app that spits out JSON upon request with CPU avg RAM and disk usage. I'm going to try and add the necessary columns in SQL and classes so a 3rd dropdown option is available - Service, Website or Hardware. I'd give the host that is running the app, the port it's listening on and other normal values. Timeout would have to change... Probably a lot really. I'm likely getting in over my head on this but I'll be working with another programmer I know and any help would be appreciated. Hopefully we can make a nice addition to the hard work already here.

**Comment by joubertredrat** [comment]
Hi guys,

@ThaMunsta, https://github.com/phpsysinfo/phpsysinfo 
I use this, is very nice and complete tool to show hardware status

**Comment by dopeh** [comment]
Hi,
While hardware monitoring is a nice feature to have, I think it may be out of the scope of the core of this project right now. I could imagine it being an addon module that you could enable to add more advanced features, but right now there is no good addon system to load third party modules. That would need a bit of work, first.
There are also several existing technologies like SNMP which should be considered when implementing hardware monitoring. 
In the forseeable future, I think the best chances of integration with hardware monitoring is to make sure phpservermon can be integrated with other software (ie API). A 3rd party hardware monitor could then use hooks to trigger notifications inside phpservermon.

**Comment by joubertredrat** [comment]
Hi guys,

@dopeh nice idea, including, I know one project that have API access, LibreNMS, http://www.librenms.org/

**Comment by sadortun** [comment]
#102
