### ISSUE TITLE
Feature Request: FindMyiPhone push alarm

### ISSUE THREAD

**Issue by floreno** [phpservermon/phpservermon#180]
It would be too nice to implement Apple-push-service over the find-my-iphone-webapp.
Why pay for an extra service and an extra hop in the message-delivery-chain?
The massive pro of the FindMyiPhone-Messaging is that it can play an alarm-sound even in silent mode.
https://github.com/albeebe/PHP-FindMyiPhone

**Comment by dopeh** [comment]
Hi,
Please feel free to fiddle around and open a pull request. I do not have iOS devices myself so would not be able to test it, and I have some other things planned.
