### ISSUE TITLE
Installation: Unable to connect to MySQL

### ISSUE THREAD

**Issue by slackero** [phpservermon/phpservermon#187]
The development release is not able to connect to the database, not during install and also not if config and database were setup manually.

Vendor scripts are fresh loaded by composer.

Replacing the development files with the one from 3.1.1 release excluding the built-in vendors (using the fresh files) it's working as expected.

Tested: Local PHP 5.6.2, Remote PHP 5.6.6

**Comment by pmarkoulidakis** [comment]
Yeap i noticed it too. Just change the constructor to:
 function __construct($host = null,$db = null, $user = null, $pass = null) {

**Comment by Grandmasg** [comment]
Not working for me ... tried it at multiple installations (windows + linux)
![error](https://cloud.githubusercontent.com/assets/6714237/7176965/58967b84-e423-11e4-9f45-c495e27f93bf.png)

**Comment by bactisme** [comment]
:+1: Why this is not yet fixed ?

**Comment by bpvarsity** [comment]
+1 I tried multiple installations/servers as well and it doesnt work. Had
to go back to the old version

**Comment by joglomedia** [comment]
The problem is in the src/config/services.xml lines


		<service id="db" class="psm\Service\Database">
			<argument>%db.host%</argument>
			<argument>%db.name%</argument>
			<argument>%db.user%</argument>
			<argument>%db.pass%</argument>
		</service>

it should be like this (depending on the Database service constructor)


		<service id="db" class="psm\Service\Database">
			<argument>%db.host%</argument>
			<argument>%db.user%</argument>
			<argument>%db.pass%</argument>
			<argument>%db.name%</argument>
		</service>

@dopeh Please update the source file

**Comment by FashionCStar** [comment]
I am using php 7.3.5 and mysql  Ver 8.0.16
I have attached my config screenshot

![psm](https://user-images.githubusercontent.com/39269334/57427722-e144fb80-722d-11e9-8c1f-6a8c81eee778.png)

I have checked /src/services.xml and it is fine
I have created database manually in my server
What is the problem?

**Comment by Jammmmm** [comment]
I have the same problem as @FashionCStar.

It took me several hours to figure out that it doesn't like "localhost" for "Database host". Setting it to "127.0.0.1" works fine.

I am on PHP 7.3.6 and Debian 9.9. My server definitely knows how to resolve "localhost" to "127.0.0.1".

I haven't looked at the code but my assumption is it's trying to resolve "localhost" and is failing. I'm guessing trying a valid domain name will work, as well as an IP.
