### ISSUE TITLE
Feature Request: API

### ISSUE THREAD

**Issue by joubertredrat** [phpservermon/phpservermon#197]
Hi,

I think that is good idea do implement API to use with PHP Server Monitor.
This a good way if you have a automatic process to manage sites and this tool automatic manage sites or services on PHP Server Monitor.

if like this, I can develop a alfa test and open demo to test.

**Comment by diginet-md** [comment]
Hi,
Please let us know if there expecting any news regarding implementation API?
We can participate in testing.

**Comment by sadortun** [comment]
Good idea, we are accepting PR.

Related to #255

**Comment by bastians** [comment]
+1

**Comment by Laupe** [comment]
Hi @sadortun Please assign me. I'll take this charge and prepare it.

**Comment by AaronHolbrook** [comment]
Any update on this?

**Comment by BristolITDave** [comment]
I currently read the database using a PHP script to get around the lack of API, however I am still eagerly watching this waiting for an API 👍

**Comment by AaronHolbrook** [comment]
@BristolITDave mind sharing that script? :P

**Comment by BristolITDave** [comment]
http://pastebin.com/aXcf4Fr4 - I dump out the database to a JSON formatted PHP output - and then read that using JS/Ajax
