### ISSUE TITLE
Last online Never

### ISSUE THREAD

**Issue by jarmouz** [phpservermon/phpservermon#198]
Hello,

I add new website to monitor, but on the server page las online always Never and latency 0.
The website is online.
What's the problem?

![capture](https://cloud.githubusercontent.com/assets/5909895/7595213/f82086aa-f8e5-11e4-9748-7baf7072340f.PNG)

**Comment by joglomedia** [comment]
you need to run the Update menu, and also add the cron/status.cron.php to your cronjob
