### ISSUE TITLE
more info from events

### ISSUE THREAD

**Issue by loran750** [phpservermon/phpservermon#199]
Hello

I monitor websites with the pattern function, in order to verify 2 states : web server alive + mysql alive.

But when I get a mail with en error, I don't know if it's a problem with the mail server, with php or with the database.

Would it be possible to have as well in the mail AND in the events manager infos like : 
- http response header (2xx, 3xxx, 4xxx, 5xxx)
- timeout
- HTML from the page if possible

Regards

**Comment by sadortun** [comment]
Good idea, we are accepting PR.

**Comment by sadortun** [comment]
#220
