### ISSUE TITLE
a gb2312 website setup a Search string/pattern but not working,

### ISSUE THREAD

**Issue by holinhot** [phpservermon/phpservermon#200]
hi,i use PHP Server Monitor Monitoring a gb2312 website setup a Search string/pattern but not working, i try monitor a utf8 website good working
http://www.qq.com
thanks

**Comment by joglomedia** [comment]
i think it is related to the preg_match used to check if the pattern was found,
you can edit your file src/psm/Util/Server/Updater/StatusUpdater.php about line 210
