### ISSUE TITLE
Support embed iframe

### ISSUE THREAD

**Issue by valessiobrito** [phpservermon/phpservermon#208]
Plz,

Add support generator code to "iframe" graph;

Thanks,

**Comment by sadortun** [comment]
Hi @valessiobrito, can you give more details of your suggestion?

**Comment by valessiobrito** [comment]
If supported to embed a graph in a public page without authentication, could customize the dashboard creation / monitoring pages.

It is the ability to get a public URL (token) to generate a display monitor.

**Comment by sadortun** [comment]
Ok Thanks, I am closing this issue in favor of #51  The Public page status should also met your needs.
