### ISSUE TITLE
Can't login after fresh install

### ISSUE THREAD

**Issue by raenk** [phpservermon/phpservermon#211]
LEMP stack, PHP 5.4.41

Right after a fresh install, can't login. I've seen others having same issue, but no solution.

Password reset won't work, changing password directly on DB doesn't work (using the one that translates into 'password'). Looks like the encryption used has a bug.

Is this project active? There are no recent replies from maintainer/owner.

**Comment by joglomedia** [comment]
which branch you're used?

I use LEMP stack, PHP 5.5, there is no problem

**Comment by raenk** [comment]
Hi,

I used master I believe. I'm going to try with develop assuming that's what you're using.

Thanks

**Comment by raenk** [comment]
Well, didn't get that far...

First, it seems that the bundle has a corrupted coposer.phar file, hat to get it directly from https://getcomposer.org/composer.phar

Then, after installing the dependencies i get a blank page at install.php

I'm going to try and debug it.

**Comment by dopeh** [comment]
You can try downloading one of the pre-built releases which should all work. The develop branch is rather unstable at the moment and has been inactive for some time. I will pick up development shortly hopefully to get things sorted out. Apologies if the latest develop version is not working out for you, feel free to dump any errors you get.

**Comment by raenk** [comment]
Hi dopeh,

The first two servers I installed it I got them directly from here:
http://www.phpservermonitor.org/download/ (TAR.GZ)

The third one is the one that just tried a few moments ago with the develop branch. Considering your advice, I'll stay then with the pre-build.

Installation goes smooth, but can't login, no errors. I've seen other users going through this, but there is no public solution.

Any clues?

**Comment by dopeh** [comment]
Add the following line to the end of your config.php file and refresh the page to (hopefully) see any errors:

define('PSM_DEBUG', true);

**Comment by raenk** [comment]
Thanks. this is the only one I get as soon as the login page is loaded.

Warning:  SessionHandler::read(): open(/var/lib/php/session/sess_t4bn6f4keun531inmhqj6k1li4, O_RDWR) failed: No such file or directory (2) in /usr/share/nginx/html/mon/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Proxy/SessionHandlerProxy.php on line 69

Nothing else even after trying to login and sent back to the login page

**Comment by dopeh** [comment]
Well the error corresponds with the symptoms (not being able to keep a session) but unfortunately I can't really help you with that. It appears your nginx is not properly configured, and PHP is trying to store session files in a directory that does not exist or is inaccessible (/var/lib/php/session). You should either create that directory and allow nginx access or get in touch with your webhost if this stuff is not making any sense ;-)

**Comment by raenk** [comment]
Perfect, at least it's a pointer/clue. Much better now place than before to find a solution.

Thanks!

**Comment by raenk** [comment]
Problem solved! Created directory for sessions and gave it the right permissions. An alternate solution could be changing the path in php.ini for sessions to any other writable location by the process.

Thanks again dopeh

**Comment by dopeh** [comment]
Glad you got it working!
