### ISSUE TITLE
Feature request: add header support for website checks

### ISSUE THREAD

**Issue by bootswithdefer** [phpservermon/phpservermon#214]
It would be nice to be able to define extra arbitrary headers to pass to curl, particularly the Host header for sites with vhosts.

**Comment by Dasoren** [comment]
I 2nd this request. I need this for the testing of my websites.

**Comment by mat1010** [comment]
Just bringing this one up again - even though it's pretty old. The initial request in this issue was to be able to define headers that are **SEND** during the website check, not to verify a value of the **RETURNED** headers. The mentioned PR does not solve the above mentioned issue @gmoigneu
