### ISSUE TITLE
Custom Pushover sound

### ISSUE THREAD

**Issue by medhi** [phpservermon/phpservermon#217]
Could you please implement a possibility to set custom Pushover sound? It should be just one more parameter in Pushover command.

Thank you

**Comment by sadortun** [comment]
Good idea, we are accepting PR.i

**Comment by Laupe** [comment]
@sadortun duplicite #212

**Comment by sadortun** [comment]
Not exactly a duplicate, Pushover have a specific parameter for `sound` see https://pushover.net/api#sounds

I Guess we could add a select field in the config page.

**Comment by Laupe** [comment]
Yes, and I in this issue will add a new priority sound. Look closely at my screens;)

**Comment by sadortun** [comment]
Ok Great !
