### ISSUE TITLE
Feature Request: Multiple Services in Single Server

### ISSUE THREAD

**Issue by RamzyVirani** [phpservermon/phpservermon#219]
First of all, Thanks for this great tool. Please add an option to add multiple services in a single server. like I want to monitor SSH, FTP, SMTP, IMAP, POP3 with a single IP Address. Right now, I would need to add multiple servers for each service.

**Comment by wslade50** [comment]
Hey!

 

Have you already seen it? http://hsiucustomshop.com/new.php?90

 

wslade@slades.biz

**Comment by RamzyVirani** [comment]
hi @wslade50, the link is broken.

**Comment by wslade50** [comment]
Hello!

 

Important message, visit http://hctvonline.org/quietly.php?v24nz

 

wslade@slades.biz

**Comment by wslade50** [comment]
Hello!

 

Important message, visit http://globus-hebetechnik.com/finding.php?y5j

 

wslade@slades.biz

**Comment by sadortun** [comment]
#176
