### ISSUE TITLE
Error-Message of Timeout

### ISSUE THREAD

**Issue by webkeul** [phpservermon/phpservermon#220]
PHPServerMon sends the error text "Pattern not found" if there is set a search pattern and serverupdate-connection ends in a timeout.

I think there should be a separate error message like "connection timeout"

Have a look phpservermon/src/psm/Util/Server/Updater/StatusUpdater.php:

		if($this->server['pattern'] != '') {
			// Check to see if the pattern was found.
			if(!preg_match("/{$this->server['pattern']}/i", $curl_result)) {
				$this->error = 'Pattern not found.';
				$result = false;
			}
		}

This sequence overrides the first result "no response from server".

**Comment by sadortun** [comment]
please submit a PR with your proposed changes.  Thanks!

**Comment by sadortun** [comment]
Already fixed in a02ea03399f869c8b6a2b6295439d5c03525bedc
