### ISSUE TITLE
Websites offline exact the same time every day

### ISSUE THREAD

**Issue by criwe** [phpservermon/phpservermon#222]
Hi!
First of all thx for this fantastic Software!

I´ve installed it on two different webspaces to monitor different websites.
Something attract my attention: both installations report website offline every night at the same time for different websites:

phpserver mon A -> website 1, website 2 -> offline for one intervall every night at 5:30 
phpserver mon B -> website 3 -> offline for one intervall every night at 5:30

Are there any ideas what could be the reason?!
Thx!
Chris

**Comment by ericwongcm** [comment]
I don't see such problem for my installation. I would guess it is related to your server. Ask your webhost and see if they might be doing something at those hours.

**Comment by robbens** [comment]
I have the same issue. Five servers "went down" the exact same time. Well, they were offset by 1 second each.

So,
Server 1 went down 11:30:32
Server 2 went down 11:30:33
Server 3 went down 11:30:34
...

**Comment by lupor0x** [comment]
I dont have that problem, maybe it's something happening to your server at 5.30..

**Comment by sadortun** [comment]
Please check with your host.
