### ISSUE TITLE
System Update status page

### ISSUE THREAD

**Issue by ryan8382** [phpservermon/phpservermon#225]
This is probably outside of the scope of the project but I figured I would ask anyway. I was wondering if you guys would be willing to add a page that has Server update status. We use a variety of Windows, Linux and Mac servers. It would be nice to have a page that we can go to that shows the current system version, and if updates are available. On that same page have a RDP shortcut download, VNC shortcut download, and SSH shortcut download. I'm not a coder so I don't know what kind of help I would be.

**Comment by sadortun** [comment]
#102
