### ISSUE TITLE
Feature Request:  Automatic monitor refresh in browser

### ISSUE THREAD

**Issue by franko108** [phpservermon/phpservermon#226]
I like your program, quite nice, simple for use.

Although there is latest monitor status through cron job, we don't see any changes on the browser, as it needs to refresh status manually. This is not perfect situation.
It would be much better to make automatic refresh and this is very simple to implement.
Simple javascript can be loaded on main *index.php* when we're logged in.
This js works out for automatic page refresh every 1 minute.
```javascript
function timeRefresh(timeoutPeriod) {
	setTimeout("location.reload(true);",timeoutPeriod);
}
```
Html may have this line:
```javascript
<body onload="javascript:timeRefresh(60000);">
```

One step further, it would be better that user can decide through config page how often page shall be refreshed. Default time could be 1 minute.

**Comment by JackwBull** [comment]
If you go into Config you will see there is an Auto refresh already their, just type in how any seconds you want between each refresh and away you go,

**Comment by franko108** [comment]
Yes, indeed, I didn't see it.
Thanks, you may close this request.

Regards,
