### ISSUE TITLE
psm_servers_uptime data should be compressed

### ISSUE THREAD

**Issue by thijshakkenberg** [phpservermon/phpservermon#227]
We have an phpservermon install monitoring our servers every 10s. This has already (after three weeks) made the psm_servers_uptime table grow to 14MB and the reports cannot be run because the data sets have become to large. 

An extra cronjob, to replace all rows for one day with an average for that day per server for all data older then e.g. a week, would greatly reduce the data points and increase reporting without sacrifising the statistiscs. 

E.g. SELECT * FROM `psm_servers_uptime` WHERE `server_id` = 4 AND `date` BETWEEN '2015-09-28 00:00:00.000000' AND '2015-09-29 00:00:00.000000' ORDER BY `date` DESC results in our case in a lot of data points. If they could be deleted and replaced by one record with the average of the day periodically, that would save data.

**Comment by JackwBull** [comment]
I dont see how your usage is so high. Im monitoring 184 servers for the last 5 months are only used 8mb of data

**Comment by thijshakkenberg** [comment]
We run the cronjob every minute.

**Comment by sadortun** [comment]
This sounds like a resonance amount of data. What is the issue ?
