### ISSUE TITLE
Servers Status Update

### ISSUE THREAD

**Issue by kornett** [phpservermon/phpservermon#232]
I noticed that even though the "Status" tab page refreshes every 10 seconds like I configured, it doesn't really "Updates" the status, it only works when I go to Servers -> Update manually.
Any idea why?

**Comment by JackwBull** [comment]
Hello,

If you want the website to check the server status every 10 seconds you will need to edit he cron job to do so. as its the cron job that gets the server status

Thanks

Jack

**Comment by Togglinq** [comment]
Hello,

Could you possibly show us how to make the server status auto-update within the status.cron.php

Thanks,
Togglinq

**Comment by JackwBull** [comment]
What are you using phpservermon with? Windows/cpanel/plesk?

**Comment by Togglinq** [comment]
Hello,

I'm using it on Centos 6 (Linux).
It is currently monitoring a port 80 and 25565..


Thanks,
Togglinq

**Comment by Togglinq** [comment]
Hello,

I'm using it on Centos 6, no web control panel
It is monitoring my port 80 and 25565

Thanks,
Togglinq

**Comment by lupor0x** [comment]
You have to set a cronjob, in the crontab! Open the file ->  /etc/crontab and add this line for run the script every hour :

* 1 * * * /yourdirectory/update_server.sh

Each line in the /etc/crontab file represents a task and has the following format:

minute   hour   day   month   dayofweek   command.

# record the memory usage of the system every monday  
# at 3:30AM in the file /tmp/meminfo 
30 3 * * mon cat /proc/meminfo >> /tmp/meminfo 
# run custom script the first day of every month at 4:10AM 
10 4 1 * * /root/scripts/backup.sh

via : https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s2-autotasks-cron-configuring.html

**Comment by lupor0x** [comment]
You have to set a cronjob, in the crontab! Open the file ->  /etc/crontab and add this line for run the script every hour :

* 1 * * * /yourdirectory/update_server.sh

Each line in the /etc/crontab file represents a task and has the following format:

minute   hour   day   month   dayofweek   command.

# record the memory usage of the system every monday  
# at 3:30AM in the file /tmp/meminfo 
30 3 * * mon cat /proc/meminfo >> /tmp/meminfo 
# run custom script the first day of every month at 4:10AM 
10 4 1 * * /root/scripts/backup.sh

via : https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s2-autotasks-cron-configuring.html

**Comment by senthilpsk** [comment]
hi, i couldn't find update_server.sh
pls help on this
