### ISSUE TITLE
timeframe on 3.2.0 release

### ISSUE THREAD

**Issue by raggoo** [phpservermon/phpservermon#236]
What is the timeframe on 3.2.0 release please?

It has been almost a year since the last release and the best I can tell 3.2.0 is very far behind schedule.

Couldn't you release a current version with where it is now?

**Comment by raggoo** [comment]
HELLOOOOOOoooooooooo????

**Comment by sadortun** [comment]
We should relapease a minor 3.1.x in the upcoming weeks.
