### ISSUE TITLE
Running behind reverse proxy?

### ISSUE THREAD

**Issue by DeviantEng** [phpservermon/phpservermon#240]
So I have PSM installed on a CentOS box, using nginx, mariadb, and php-fpm.  Works great.  PSM is running on http on port 8083.

I've got a separate box running CentOS 7 and Nginx, used as a Reverse Proxy (contains a wildcard SSL cert, and is the only service available from the internet, so I proxy everything through it).  I have PSM proxied through it, and initially it works.  

It loads fine and I can log in, but if I try to click on anything in the navigation menu or any of the servers, the URI I get, for example, is http://172.16.1.115:8083//?&mod=server_status.  Now obviously, this won't load outside of my LAN.  And in previous experiences, this is usually happening because the application is hard coding URI's instead of using relative paths.  I've looked through the code, but I can't trace back how this is setup and happening (I'm not a web programmer).  How does PSM generate this URI, and how can I over-ride it to ensure everything works behind my reverse proxy?

Thanks!

**Comment by sadortun** [comment]
Hi! It look like a cookie/session issue, do you still have the issue?

**Comment by DeviantEng** [comment]
I do still have the issue, and gave up on using it behind my reverse proxy (and instead just use it locally).  I'd still like to get it working with my reverse proxy, if possible, though.

**Comment by sadortun** [comment]
This is not a issue with PSM. You should if cookies are set correctly by your reverse proxy. Please have a look at:
http://stackoverflow.com/questions/21575725/wordpress-behind-reverse-proxy-session-cookies-not-set-in-safarie-ie

**Comment by DeviantEng** [comment]
I don't think it's a cookie issue, though I have gotten closer since I've revisited this today.

Here is my current Nginx proxy config:
server  {
  listen  443 ssl;
  server_name  mon.domain.com;
  ssl  on;
  location  / {
    proxy_pass  http://172.16.1.122:8083/;
    proxy_set_header  Host $host;
    proxy_redirect  http://mon.domain.com https://mon.domain;
  }
}

I didn't realize until now that the links were being rewritten back to http, and I don't see any setting within the config itself to enable https.  So by adding `proxy_redirect`, I've been able to rewrite the links to https (whereas with http, css wasn't even loading).  

Anyway, the problem I'm having now is that when I click a link, such as the servers tab, I am sent to:
https://mon.domain.com/index.php//?&mod=server

Looking at the console I am seeing a couple errors (Uncaught SyntaxError: Unexpected token <) and (Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://mon.domain.com/index.php//static/css/style.css").

But if I take that same URL and and remove `/index.php`, making it `https://mon.domain.com//?&mod=server`, the page loads perfectly.  I'm still trying to figure out how to do that with nginx, but not having much luck.


FWIW, I run several apps behind my Nginx reverse proxy (plex, plexpy, zerobin, sabnzbd, sonarr, couchpotatoserver, splunk, owncloud, guacamole, and some others) and not a single one do I have to set the `proxy_cookie_path` or `proxy_cookie_domain` directives.  I know the framework of this app is unlike those, but I have my doubts that the issue would be resolved with either of those directives.
