### ISSUE TITLE
Request: Support Pushbullet

### ISSUE THREAD

**Issue by FrozenBeard** [phpservermon/phpservermon#242]
I just spent ages setting up Pushover only to find out the piece of crap lasts for 7 days and then forces you to pay $5 for it PER platform (Stinking bastards!), this is pointless when there are many other free alternatives that are much better, like Pushbullet. 
Can you please support pushbullet.

**Comment by CodeBrauer** [comment]
Duplicate #168

**Comment by FrozenBeard** [comment]
Is this now implemented? the initial request was Jan 1st 2015

**Comment by sadortun** [comment]
No, but if you are willing to make a contribution to the project, we will be happy to accept it!

**Comment by FrozenBeard** [comment]
Alright, I know PHP, you may laugh at my terrible PHP though. can you link me to where notifications are sent?

**Comment by sadortun** [comment]
Hehe ! If you know you are terrible in PHP, you should probably try to find someone interested in implementing this feature on your behalf :)

**Comment by FrozenBeard** [comment]
haha, well the Pushbullet api is extremely simple and they even offer php examples. 
I did come across this today as another alternative that does not have limits: https://github.com/ontopapp/ontop-push

**Comment by CodeBrauer** [comment]
@FrozenBeard - I think this would fit perfect: https://github.com/notifymehq/notifyme

The API is simple and it covers the most services.

**Comment by sadortun** [comment]
@CodeBrauer @FrozenBeard  Yes, this issue was closed in favor of #168 NotifyMe integration since the API already wrap multiple providers. Please continue the discussion on the #168 in order to have the other people who are interested in this topic notified of the discussion.

Thanks!
