### ISSUE TITLE
Fatal error: Uncaught exception 'PharException'

### ISSUE THREAD

**Issue by glenara** [phpservermon/phpservermon#243]
Add additional info to the install doc.

If you get "Fatal error: Uncaught exception 'PharException'..." run this and try again:

     curl -s http://getcomposer.org/installer | php

**Comment by sadortun** [comment]
Please submit a PR with your changes. thanks

**Comment by glenara** [comment]
Glad to see you grabbing the bull by the horns and moving the project forward.

I've included this documentation update in my PR #245 CarrierSMS SMS Gateway.
This one can be closed.
