### ISSUE TITLE
Check webpages from another server

### ISSUE THREAD

**Issue by r3m4k3** [phpservermon/phpservermon#248]
Hi there,

is there any possibility to monitor my websites from another server?
For example, I have run monitoring system on server XYZ, but I have to monitor too these stored on server ZYX, how can I do it?

Thanks in advance.
Best regards

**Comment by sadortun** [comment]
HI, you can monitor multiple servers at once if you want.

**Comment by r3m4k3** [comment]
Hi,
I have installed phpservermon on server A, but I want to monitor pages on server B.
And the question was - how is that possible?

**Comment by sadortun** [comment]
Simply add new servers in the settings page to m,omit or your various servers/services

**Comment by r3m4k3** [comment]
It doesn't work.
I will describe the problem later.
