### ISSUE TITLE
Cannot monitor Icecast statistics

### ISSUE THREAD

**Issue by danceboysf** [phpservermon/phpservermon#251]
Example page:
http://141.0.169.245

I cannot monitor any statistics from Icecast streaming servers

Output:
http://store.picbg.net/pubpic/50/A8/6a586178632350a8.PNG
Settiings:
http://store.picbg.net/pubpic/D8/B3/ac19089484b3d8b3.PNG

**Comment by kippg** [comment]
I'm checking my Shoutcast servers as a service, not a website. For the search string I am using .*, a dot and a star.

**Comment by sadortun** [comment]
Is your issue resolved ?
