### ISSUE TITLE
Feature request: Webhooks

### ISSUE THREAD

**Issue by levidurfee** [phpservermon/phpservermon#255]
Could you add webhooks to the next version? If a site goes down, it would deliver a payload to the configured webhook.

**Comment by sadortun** [comment]
Good idea! We will be accepting PR for this.

**Comment by diginet-md** [comment]
Please explain what do you mean under sentence 
"We will be accepting PR for this."
For Your information
We have interest to extend functionality of phpservermon but don't understand what do you mean.

**Comment by sadortun** [comment]
HI @diginet-md, please have a look on the guide on how to contribute to Open Source projects :

https://guides.github.com/activities/contributing-to-open-source/

**Comment by brumle80** [comment]
Support for Mattermost and Slack would be brilliant.

**Comment by valessiobrito** [comment]
Support Rocket.Chat (chat/notify) and Kanboard (tasks) it's cool and open source.

**Comment by bastians** [comment]
Maybe something for @Laupe ;)

**Comment by sadortun** [comment]
@bastians If you are willing to put a little bounty on the table, you might get is attention :) !

**Comment by bastians** [comment]
He will come to fame ;)

**Comment by tomhatzer** [comment]
Do you have any requirements for the implementation? Where do you want to store the webhook? In the server entry or in the user entry? What fields do you want to send to the webhook url? Do you want it to be slack/mattermost compatible?

**Comment by sadortun** [comment]
@tomhatzer 

- [ ] webhooks shall be defined in their own table
- [ ] the webhook shall be triggered on change.
- [ ] user shall be able to select which servers triggers the webhook
- [ ]  the webhook event  shall contains the  status, Id, URL , datetime
- [ ] the webhook may also contain  last known good , last known bad , 
- [ ]  the webhook çould be slack compatible.

**Comment by tomhatzer** [comment]
Great, thank you @sadortun ! I'll have a look into this and keep you updated.

**Comment by jkrehm** [comment]
Has any work been done to make this a reality? If so, could the developer(s) use a hand with anything?

**Comment by nhalstead** [comment]
For the related Issues (#473, #557, #561, #216, #606) I am working on a package for PHP that will be able to send events to Slack and Discord as well as the capability to send events to other systems that are not already designed for such as Pusher, Gitter, etc.

**Comment by TimZ99** [comment]
@nhalstead great that you’re working on the project! The notification part of the project will have some massive changes in v3.5.
This will make adding new notification methods as easy as adding new sms gateways.

**Comment by varunchandak** [comment]
@nhalstead Hey...! Did you get this working ?

**Comment by nhalstead** [comment]
I have gotten my [library ](https://github.com/nhalstead/PHP-WebhookCoordinator/)semi complete to make requests to Slack and Discord as well as other services but I have not gotten the time to implement the controls into the Interface of the project, I still would like to see this implemented but as the holiday is approaching time is tight.

I will continue to work on it but the timeline on it, I have not figured out at the moment.

**Comment by Yacine-krk** [comment]
I'm surprised no one had time to add the integration of webhooks. Especially to Slack or discord.

It's very easy to send message to Slack webhook for instance.
is this feature planned for next versions ?
I see the last posts mentioning it are from 2018... that's why i'm asking :)

**Comment by sadortun** [comment]
@Yacine-krk Feel free so submit a PR :)

**Comment by TimZ99** [comment]
Implemented 🎉
