### ISSUE TITLE
Javascript - update server status

### ISSUE THREAD

**Issue by TomasPic** [phpservermon/phpservermon#256]
Hey,
could you remove the "Update" in the menu and also the button "+ Update" in the "Servers". It would be better if you replace it with some javascript function which would work automatically. The server status would be also more interactive. Same thing is in the "Status" - refreshing values with JS.

**Comment by levidurfee** [comment]
Why are you asking for this? Are you experiencing a problem? How would this make it more "interactive"?

**Comment by TomasPic** [comment]
I think that clicking on the Update every time to see some result is not the best idea.... It shows up that the server/port/... is still up, but it's not - and you know that after the click on Update.

Here is an example:
1.
My server is up, and everything is running ok. I put the monitoring server down and it's still green. But when I press the Update button, it's red.

2.
My server is up, and everything is running ok. Every data is shown by JS so it doesn't need refreshing the whole page. When I put the monitoring server down it immediately turns to red and I don't have to click on something. And that's the main problem.

**Comment by levidurfee** [comment]
In the config change the `Auto-refresh` setting.
