### ISSUE TITLE
type server or website

### ISSUE THREAD

**Issue by Touch-My** [phpservermon/phpservermon#257]
Hello,

I added my Teamspeak server monitoring, but he said he and off for the reason: Connection refused

The shots I tested website mode, knowing that turns on debian, while the port is opened automatically, the blows it appears the site is in all cases.

**Comment by brumle80** [comment]
teamspeak is a service, just add ip and port or hostname, but remember to not add http:// on server address. should work with no issues.

**Comment by sadortun** [comment]
Is  the issue resolved ?

**Comment by Tealk** [comment]
I have the same problem:
![image](https://user-images.githubusercontent.com/12276250/74241619-4ef9e880-4cd4-11ea-9261-a2f619708782.png)
