### ISSUE TITLE
MySQL on non-standard port

### ISSUE THREAD

**Issue by petergrubercom** [phpservermon/phpservermon#261]
I cannot install this script on a system where MySQL uses a non-standard port.
I get the error message "Unable to connect to MySQL"

Providing 127.0.0.1:xxxx as host adress does not work.
Also, providing this information directly to the config.php file does not work.
`define('PSM_DB_HOST', '127.0.0.1:xxxx');`

However, if I run a mini-query in PHP manually, it works:

    $dbname = 'servermonitor';
    $dbuser = 'servermonitor';
    $dbpass = 'foobar';
    $dbhost = '127.0.0.1:xxxx';
    $connect = mysql_connect($dbhost, $dbuser, $dbpass) or die("Unable to Connect to '$dbhost'");
    mysql_select_db($dbname) or die("Could not open the db '$dbname'");
    $test_query = "SHOW TABLES FROM $dbname";
    $result = mysql_query($test_query);
    echo "List of tables:\n";
    while($tbl = mysql_fetch_array($result)) {
      echo $tbl[0]."\n";
    }

**Comment by Xendorf** [comment]
I don't know if work but ... try with:

`define('PSM_DB_HOST', 'localhost;port=xxxx');`

**Comment by sadortun** [comment]
@petergrubercom have you found a solution ?
