### ISSUE TITLE
Feature Request: Latest server response

### ISSUE THREAD

**Issue by geri777** [phpservermon/phpservermon#265]
I would like to suggest a feature in the backend to view the latest server output.
In best case it should be 2 buttons: "**latest positive server output**" and "**latest error server output**".
This would help a lot to find out why an alert was triggert - and it would even be more helpful for the setup, if you have redirects etc.
The output log should contain the raw response, including headers.

**Comment by TimZ99** [comment]
Looking at the logs will do the job, but I will add the date to the server info. 😃

Last check;
Last online;
Last error;
Last raw error output.

**Comment by TimZ99** [comment]
It's not ready for testing!
9c8b7e4 
The output collection needs to be written!

**Comment by pekiZG** [comment]
@TimZ99 What's the status of this?

**Comment by TimZ99** [comment]
I must admit that I forgot about it. [This](https://github.com/phpservermon/phpservermon/tree/feature/265) is the latest version.

If you have time, could you write the part to collect the raw data?

**Comment by pekiZG** [comment]
Sure,
Ill have time over the weekend :)

If I have any questions ill ping you here

**Comment by TimZ99** [comment]
Great! Keep me posted, I will also be working on the project this week.

**Comment by pekiZG** [comment]
I just saw that you are using gitter; tty there \o/

**Comment by TimZ99** [comment]
👍

**Comment by geri777** [comment]
Thank you for getting back on this feature suggestion. Much appreciated!!

**Comment by TimZ99** [comment]
You're welcome ;)

**Comment by pekiZG** [comment]
ok, after a little bit of poking :)

@TimZ99 I see you already did:
Last check;
Last online;

only thing left is;
Last error;
Last raw error output.

Can some one give me the context of that?

Is the last error HTTP STATUS ERROR, TEXT ERROR, TIMEOUT ERROR, etc... or something else;

and last raw error output? what is that?

**Comment by pekiZG** [comment]
@TimZ99 this can be used to get a better understanding of an error;
http://php.net/manual/en/function.curl-strerror.php

I'm still missing what's the raw error output?

**Comment by pekiZG** [comment]
@geri777 can you give us more explanation?

**Comment by pekiZG** [comment]
OK, i think i have done it;
No biggie, i just don't know if it's what @geri777 had in mind

**Comment by pekiZG** [comment]
Only problem; the way it's done now I don't think you can get the "raw" response

**Comment by pekiZG** [comment]
curl_exec is being used with CURLOPT_RETURNTRANSFER option enabled.

it returns mixed
http://php.net/manual/en/function.curl-exec.php

> Returns TRUE on success or FALSE on failure. However, if the CURLOPT_RETURNTRANSFER option is set, it will return the result on success, FALSE on failure.

Meaning that complete check has to be done in a different way to ger the "raw" response;

currently you only get "raw" response on SUCCESS;

@TimZ99 when you see this, if you have time ping me on _**Gitter**_

**Comment by pekiZG** [comment]
@TimZ99 I really don't see a way of getting a body or a headers if curl_exec() fails.

It just returns FALSE; only thing that you can get when that happens is a error message via curl_error().
http://php.net/manual/en/function.curl-error.php

--
I also see a way to simplify getting of http status code in case of success via curl_getinfo()
http://php.net/manual/en/function.curl-getinfo.php

https://httpstatuses.com/

**Comment by TimZ99** [comment]
I think I'm done. https://github.com/phpservermon/phpservermon/tree/feature/265 Could you guys check if you agree with me?
