### ISSUE TITLE
Server status codes?

### ISSUE THREAD

**Issue by MatejKovacic** [phpservermon/phpservermon#268]
In the documentation is stated that PHPServerMon checks status for websites (if the HTTP status code is in the 4xx range, it means an error occurred and the website is not accessible to the public).

Sorry to asking you here, but I was unable to get the answer from documentation. So, what if there is some other code, for instance 500 (Internal Server Error). Is there also error reported?

**Comment by sadortun** [comment]
An error is any code starting with a "4xx" or bigger

https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Util/Server/Updater/StatusUpdater.php#L200
