### ISSUE TITLE
Slovenian language pack

### ISSUE THREAD

**Issue by MatejKovacic** [phpservermon/phpservermon#269]
Hi,

I translated this software to slovenian. File is here:
[sl_SI.lang.php.txt](https://github.com/phpservermon/phpservermon/files/195477/sl_SI.lang.php.txt)

Download it, rename to sl_SI.lang.php and copy to <your_servermon_directory>/src/lang/

**Comment by Laupe** [comment]
complemented

**Comment by Laupe** [comment]
@sadortun pls close issue ;)
