### ISSUE TITLE
Unable to send Test SMS via SMSGlobal

### ISSUE THREAD

**Issue by Talderon** [phpservermon/phpservermon#271]
I manually created a URL request:

`http://www.smsglobal.com/http-api.php?action=sendsms&user=****&password=****&&from=*******&to=*******&clientcharset=ISO-8859-1%text=ThisIsATest`

This is using the HTTP/SMPP API Key.

This worked, however, when in the application, using various different log-ins, I cannot get a test SMS to fire off.

**Comment by sadortun** [comment]
What is the uRL the application is calling ?
