### ISSUE TITLE
css  h2 ./plugin/twitter-bootstrap/css/bootstrap.min.css

### ISSUE THREAD

**Issue by pkerekes** [phpservermon/phpservermon#272]
h2{font-size:16px;line-height:12px;}h2 small{font-size:18px;}

./plugin/twitter-bootstrap/css/bootstrap.min.css

I changed the CSS h2.
To adjust domain name saver pure.
I look gives this app. Thanks for this projeckt! :)

IMG1: http://felho.kerekespeterjanos.hu/index.php/s/Mu5VWFfTDLUzjya

IMG2: http://felho.kerekespeterjanos.hu/index.php/s/o00JtWrlTqP0oDZ

**Comment by sadortun** [comment]
please submit a PR with your proposed changes.  Thanks!

**Comment by sadortun** [comment]
Without suggestion

![image](https://cloud.githubusercontent.com/assets/794449/15412790/8f0710b0-1df8-11e6-87f5-95db0cda7d80.png)
![image](https://cloud.githubusercontent.com/assets/794449/15412794/94875ca2-1df8-11e6-8831-92cdd9c9c787.png)

With suggestion
![image](https://cloud.githubusercontent.com/assets/794449/15412800/a746ea42-1df8-11e6-9a78-ca4bff2bb47d.png)

![image](https://cloud.githubusercontent.com/assets/794449/15412798/a20f25bc-1df8-11e6-94d4-42ebb59c201e.png)

Please vote :+1:  or :-1:
