### ISSUE TITLE
Maintainers ?

### ISSUE THREAD

**Issue by sadortun** [phpservermon/phpservermon#276]
HI @dopeh 

I would like to propose myself to give you some help maontaining the project. We are using PHPServerMon for a couple of years and we would like to see the project growing again. 

If you have any questions, you can contact me by email.

Have a good day,
Samuel

**Comment by Mag2** [comment]
I was just thinking about asking if there were any developers who have thought about forking this project.  It's sad to see this project at a stand still.  I hope you get a favorable response and that they are few more like you wanting to push this forward.  If you don't, maybe it's time that few people like your self fork the project.

**Comment by dopeh** [comment]
Hi guys,
Yeah I'd definitely be open to add more developers to the project to kick it back into gear. Can you send me your email address and we can have a chat.
Cheers,
Pep

On Apr 24, 2016 6:29 PM, Mag2 <notifications@github.com> wrote:

I was just thinking about asking if there were any developers who have thought about forking this project.  It's sad to see this project at a stand still.  I hope you get a favorable response and that they are few more like you wanting to push this forward.  If you don't, maybe it's time that few people like your self fork the project.

---

**Comment by sadortun** [comment]
Hi @dopeh My email is there : https://github.com/sadortun

**Comment by dopeh** [comment]
Hello,
As I have discussed with @sadortun, he will be given full access to the repository and other resources to get some stuff moving and get this project back into active status. I have indeed not been able to spend the time on it that I wanted, so I am glad for this offer to keep this project going.
