### ISSUE TITLE
Setting Email

### ISSUE THREAD

**Issue by nurhambali** [phpservermon/phpservermon#281]
Hi , I'm having problems when the configuration of email , can you help me?

**Comment by sadortun** [comment]
If it' scan issue with PSM, yes, but not if it's a problem with your ISP

Please provide more details

**Comment by nurhambali** [comment]
![screenshot from 2016-05-02 09-05-47](https://cloud.githubusercontent.com/assets/18512905/14946053/a6acf32a-1046-11e6-8e58-b98b3ed5a6b2.png)
above is to see his error , and as for configuration:

![screenshot from 2016-05-02 09-18-56](https://cloud.githubusercontent.com/assets/18512905/14946085/18067fc8-1047-11e6-9669-bf3cad8b7058.png)

**Comment by bpvarsity** [comment]
That's a firewall issue on the server. Not a script issue

**Comment by nurhambali** [comment]
firewall on my server disabled,

**Comment by bpvarsity** [comment]
Try using the free sendgrid service. Much better then the Google smtp

**Comment by nurhambali** [comment]
What might I use google smtp is problem

**Comment by bpvarsity** [comment]
Sendgrid.com they are a free version and it works great

**Comment by nurhambali** [comment]
besides sendgrid does anyone else?

**Comment by sadortun** [comment]
You can gave à lock at mailgun

**Comment by nurhambali** [comment]
if I use the mail server itself and the local beada on whether there will be no error?

**Comment by sadortun** [comment]
I am sorry but i dont understand your question.

**Comment by nurhambali** [comment]
What if I use a local mail server?

**Comment by tbonnarens** [comment]
Are you using windows or linux on your server?
Try verifying your connection to the smtp server via telnet, check your php settings, logs, etc...
Local mail works just fine for me but php's mail implementation on windows requires more configuration.

**Comment by nurhambali** [comment]
I use the server windwos.
for smtp connections using telnet connection is stable.

**Comment by sadortun** [comment]
I am closing this issue since it's related to SMTP configuration of ISP issue.
