### ISSUE TITLE
phpservermon will support https

### ISSUE THREAD

**Issue by sjkeerthi** [phpservermon/phpservermon#283]
Hi

Just before I set up want to know will this support the https sites. Some site might configured to https redirect will this works.

**Comment by sadortun** [comment]
Yes, i dont see why HTTPS would not work. Redirects should work as well ( https://github.com/phpservermon/phpservermon/blob/a30dcf5610938dd96d20efe7cf0d2ee2bd74ad12/src/includes/functions.inc.php#L280 )
