### ISSUE TITLE
Popular Ports

### ISSUE THREAD

**Issue by Laupe** [phpservermon/phpservermon#286]
Hello,
it would be good to be able to choose from the port of "popular ports" see. screenshot. To me it's the transparent and the customer will be able to choose from the usual ports.

Can I adjust listening to PR if approved.

![port](https://cloud.githubusercontent.com/assets/1008242/15266525/c55faa18-19a8-11e6-9d48-b4414401fa5b.png)

**Comment by sadortun** [comment]
Sounds Good !  We are waiting for your PR !

**Comment by nurhambali** [comment]
How if the ping icmp added also ?

**Comment by sadortun** [comment]
ICMP is not done over TCP, therefore it can not be added here.

**Comment by sadortun** [comment]
Merged
