### ISSUE TITLE
Default language - English

### ISSUE THREAD

**Issue by Laupe** [phpservermon/phpservermon#287]
If there is no translation in the language it would be good to have placeholder text from a source language such as English.

I edited it straight. I suppose it's useful.

**Comment by Laupe** [comment]
- Modified file functions.inc.php - because if you add new language variable so it is necessary to immediately translate all languages or all files added to the English translation of which is very inconvenient and time consuming.

- Function psm_load_lang - loading the default language that I chose English and stored in the $ GLOBALS [ 'sm_lang_default'] for further use.

- Function psm_get_lang - edited selection of translation. If there is no translation in the language you chose the user returns to the default language.

**Comment by sadortun** [comment]
Merged
