### ISSUE TITLE
Use salt to encrypt the website check password

### ISSUE THREAD

**Issue by sadortun** [phpservermon/phpservermon#297]
#296

Since the encrypted password doesn't include a salt. Therefore, if multiple servers use the same password, the resulting encryption will be the same. This should be fixed before we merge this into `master`

**Comment by Laupe** [comment]
@sadortun So what is your goal? the setting is set one encryption key. So do you want to encrypt the password to use the encryption key + salt? There will modify the user for each server, or it must be SHA1 fingerprint ID server? Please your comments. I edit it.

**Comment by sadortun** [comment]
Yes,  combining the server ID + Key to encrypt the password.

```php
psm_password_encrypt( $this->server_id  . $key    , $password )
```

**Comment by Laupe** [comment]
OK for the moment will be done PR

**Comment by sadortun** [comment]
When the server is initially created, you'll need to insert the server and then re-encrypt using the `server_id` 

https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Module/Server/Controller/ServerController.php#L310
