### ISSUE TITLE
No eMail on Server down sent

### ISSUE THREAD

**Issue by phpfs** [phpservermon/phpservermon#306]
Hello!

When take my Test-Server offline, ServerMon knows it, but doesn't send me an email.

For testing this, i logged out, took the server offline and waited 5 minutes (cron runs every 2 minutes!). When I then loggend in again, the dashboard shows that my server is online and how log it has been offline/online, but in that whole time, i didn't get one email.

I already sent a test-mail!

Greetings, phpfs

**Comment by Laupe** [comment]
Hi @phpfs and you got it in the editing server enabled? Send Email item and the settings must be checked Allow sending email

**Comment by phpfs** [comment]
Yes, it's all enabled, Pushover doesn't work for me also...

Am I missing something?

Greetings, phpfs

**Comment by sadortun** [comment]
@phpfs  Does the "Forgot my password" email sent ?

**Comment by phpfs** [comment]
Yes, the password forgotten Mail works!

Seems to be limited to Update Mails/Pushover...

**Comment by phpfs** [comment]
Also, i can send test mails/pushovers from the Settings Page!

**Comment by sadortun** [comment]
@phpfs Have you selected which server you want to receive notifications in your user page ?

![image](https://cloud.githubusercontent.com/assets/794449/15624842/eebd0400-2461-11e6-8919-3a7aafb78388.png)

And selected `Yes` to receive emails
![image](https://cloud.githubusercontent.com/assets/794449/15624853/43c43f22-2462-11e6-9fcf-caaf87086d8a.png)

**Comment by phpfs** [comment]
Hello!

1. I don't have this setting, Mayer because I am Admin?
2. If you mean the setting on the Server edit Page, yes!

For Installation, I cloned from Github and deleted all unnecessary folders.

Greetings, phpfs

**Comment by phpfs** [comment]
Hello again!

EDIT:
1. I found this setting finally under "User" and selected all Servers there. Now, i get notified via eMail and Pushover.

Question:
Why isn't it selected as Standard? Do you have documentation where it says that I have to set this Setting?

Nevertheless, i am very happy with how your Tool works, keep your Great work up! :)

Greetings, perryfs

**Comment by sadortun** [comment]
Great!

**Comment by sadortun** [comment]
@phpfs  Can you submit a PR and add a few lines in the docs that explain how you solved your issue ?
