### ISSUE TITLE
3.2 compiled zip

### ISSUE THREAD

**Issue by bpvarsity** [phpservermon/phpservermon#313]
Can you create a new zip for 3.2 for those of us who can't do the manual compiling. http://www.phpservermonitor.org/download/ still has the old 3.1
Thanks

**Comment by sadortun** [comment]
HI @bpvarsity you can find it under the release tab

https://github.com/phpservermon/phpservermon/releases

**Comment by bpvarsity** [comment]
That still requires the program to be compiled and dependencies That is just the source and would need to use make and composer.

I need the prebuilt package like 3.1 was done

**Comment by sadortun** [comment]
You are right. I'll add the dependencies to the release tag

**Comment by bpvarsity** [comment]
Thanks look forward to it

**Comment by sadortun** [comment]
Here you go : 
https://github.com/phpservermon/phpservermon/releases/tag/v3.2.0-rc1

FYI we will be announcing a free hosted version of PhpServerMonitor soon !
