### ISSUE TITLE
Possible bug - Cron is already running. Exiting.

### ISSUE THREAD

**Issue by joubertredrat** [phpservermon/phpservermon#317]
Hi guys,

I'm receiving a lot of this messages on my e-mail, "Cron is already running. Exiting.". On my crontab, status.cron.php is running every 5 minutes as in documentation.

The problem is, in my environment display that status.cron.php is running, but if I inspect this on top or ps, don't have status.cron.php running.

What you think? Thanks.

**Comment by sadortun** [comment]
Do you have a cron log ? I would say that the corn task probably died before it had time to complete. 
Do you get your services/website status updated?

Fyi, The default timeout is 10 minutes,

**Comment by joubertredrat** [comment]
Hi @sadortun 

On my cronlog, display only that cmd was executed, as below:
```bash
Jun 14 10:15:01 myserver CRON[24032]: (uptime) CMD (/usr/bin/php /home/uptime/web/uptime.mydomain.tld/public_shtml/cron/status.cron.php)
Jun 14 10:20:01 myserver CRON[24943]: (uptime) CMD (/usr/bin/php /home/uptime/web/uptime.mydomain.tld/public_shtml/cron/status.cron.php)
Jun 14 10:25:01 myserver CRON[25793]: (uptime) CMD (/usr/bin/php /home/uptime/web/uptime.mydomain.tld/public_shtml/cron/status.cron.php)
Jun 14 10:30:01 myserver CRON[26711]: (uptime) CMD (/usr/bin/php /home/uptime/web/uptime.mydomain.tld/public_shtml/cron/status.cron.php)
Jun 14 10:35:01 myserver CRON[27638]: (uptime) CMD (/usr/bin/php /home/uptime/web/uptime.mydomain.tld/public_shtml/cron/status.cron.php)
Jun 14 10:40:02 myserver CRON[28535]: (uptime) CMD (/usr/bin/php /home/uptime/web/uptime.mydomain.tld/public_shtml/cron/status.cron.php)
```

My website is updated, but irregularly, my cron is every 5 minutes, but have 30, 15, 50 minutes between one and other point on Latency as example.

I don't know if status.cron.php have output text, but I changed my cron to write result from command on logfile to I verify and post here.

About 10 minute timeout, is about website configuration or timeout to status.cron.php finish run?

**Comment by joubertredrat** [comment]
Ah, isn't all time that I received e-mail with "Cron is already running. Exiting.", is intermittent. Today as example is 7 and counting, tomorow was run normally, on Sunday I received 32 e-mails.

**Comment by sadortun** [comment]
Hello @joubertredrat  if PSM_CRON_TIMEOUT` have not yet expired, it will display the warning, otherwise, if the timeout have been reach `> 10 minutes`  nothing will be displayed, and it will run again.

https://github.com/phpservermon/phpservermon/blob/develop/cron/status.cron.php#L64

You can try to modify the bottom and add `error_log` logging of your `status.cron.php` for 


```
error_log("PSM CRON Starting ", 0);
// prevent cron from running twice at the same time
// however if the cron has been running for X mins, we'll assume it died and run anyway
// if you want to change PSM_CRON_TIMEOUT, have a look in src/includes/psmconfig.inc.php.
// or you can provide the --timeout=x argument
$time = time();
if(
	psm_get_conf('cron_running') == 1
	&& $cron_timeout > 0
	&& ($time - psm_get_conf('cron_running_time') < $cron_timeout)
) {
error_log("PSM CRON Already Running ", 0);
   die('Cron is already running. Exiting.');
}
if(!defined('PSM_DEBUG') || !PSM_DEBUG) {
	psm_update_conf('cron_running', 1);
}
psm_update_conf('cron_running_time', $time);
$autorun = $router->getService('util.server.updatemanager');
$autorun->run(true);
psm_update_conf('cron_running', 0);

error_log("PSM CRON Finished ", 0);
```

**Comment by joubertredrat** [comment]
Hi @sadortun 

Cron status is defined on database and I think that isn't good idea, because you run script and add status 1 to cron on database, but is script crash without finish, status will continue 1 then will not run again.

My proposal is change this to run php file as a daemon or by cli similar to this example
```php
$pid = shell_exec('pidof -x cron.php');
if ($pid) {
    exit('script is already running');
}

system("nohup cron.php > /dev/null &");
```

What you think?

**Comment by siparker** [comment]
had this issue when i ahd the default gmail monitor left installed. i assume it fails for some reason or another and blocks the cron from finishing
try removing everything and adding one you know to work correctly

**Comment by pieter-groeneweg** [comment]
No, in older versions the cron activity is logged in the db table _config.
Fields: cron_running and cron_running_time.

Here things can go wrong.

Version 3.2.x newly installed does not have these fields. But when you updated, these fields are still there.
Can't tell if it is interfering though.
