### ISSUE TITLE
No warning treshold for service monitor.

### ISSUE THREAD

**Issue by Saken1990** [phpservermon/phpservermon#318]
Just updated the 3.1 version up to 3.2 from git, but this feature has dissapeared. Is this new in the new version or a bug?

**Comment by Saken1990** [comment]
The option to setup warning treshold is available when setting up website monitor. Its not available when setting up a service monitor.

**Comment by sadortun** [comment]
Hi @Laupe  Seems this bug was introduced in PR https://github.com/phpservermon/phpservermon/commit/340660da4bcceaaf0c312d79aeab0b74feef2436

Was this intentional ?

**Comment by Laupe** [comment]
Hi @sadortun @Saken1990 

I'm sorry, but I do not understand what is missing? I definitely do not delete anything intentionally, and it will be a mistake. I like to fix it, but please specify - for example screenshot.

Thank you

**Comment by sadortun** [comment]
Hi @Laupe 

If you check out ` src/templates/default/module/server/server/update.tpl.html `   you added class `typeWebsite` on `warning_threshold`   input row which hides it when editing a service.

If it was by mistake, I'll submit a PR to fix this issue soon.

**Comment by Laupe** [comment]
@sadortun There has to be a JavaScript that then appears. Items in update.tpl.html displayed by type. I'll fix it ASAP.

**Comment by Laupe** [comment]
@sadortun  I found out that the next commit, I fixed it.

https://github.com/Laupe/phpservermon/commit/d3489cfdaf45f7ff7f213b59c5bfbd16d026449a#diff-1a35383e34ef1ece812d28464511a222R54

I made a branch from develop version and thus try to go through the entire process of adding and editing server and all the possibilities that it's okay.

@Saken1990 Alternatively, please, for more info.

**Comment by Laupe** [comment]
Hi @sadortun done.. pls marge ;)

**Comment by sadortun** [comment]
Thanks!

**Comment by Saken1990** [comment]
@sadortun @Laupe, Thanks guys, wonderfull.
