### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by baptcottey** [phpservermon/phpservermon#320]
Hi,

We've installed phpservmon on our server, and we get php_network_getaddresses: getaddrinfo failed: Name or service not known error on all our domains.
We added it directly into database. If we edit them, monitor is working. 

We insert this inside psm_servers : 

```
$data = array(
        'server_id'   => false,
        'ip' => $result,
        'port'  => 80,
        'label'  => $result,
        'type'  => 'service',
        'pattern'  => '',
        'status'  => 'on',
        'error'  => '',
        'rtime'  => '',
        'last_online'  => '',
        'last_check'  => '',
        'active'  => 'yes',
        'email'  => 'yes',
        'sms'  => 'no',
        'pushover'  => 'yes',
        'warning_threshold'  => 1,
        'warning_threshold_counter'  => 0,
        'timeout'  => 30,
    );
```

Do you have any idea ?

**Comment by lunarthegrey** [comment]
After running PHP Server Monitor for a couple weeks I'm starting to experience the same issue. No idea why or how this occurred as I made no configuration changes.

**Comment by mooleshacat** [comment]
I get this issue randomly, and random servers will show offline at random times...

Never changed anything it just started doing it all of sudden

**Comment by TimZ99** [comment]
I guess that the problem is in your server. Have you checked you error log? Maybe restart apache/server?
