### ISSUE TITLE
Auto-refresh

### ISSUE THREAD

**Issue by Creeperman007** [phpservermon/phpservermon#322]
I have set auto-refresh for 900 seconds (15 minutes) but it's not refreshing.

**Comment by sadortun** [comment]
What browser ? 
On which page ?

**Comment by Creeperman007** [comment]
Chrome on http://serverstatus.creeperman007.tk

**Comment by sadortun** [comment]
On the Index page,  `View Sources` and verify that  you have the following line 

```
<meta http-equiv="refresh" content="900" />
```

**Comment by Creeperman007** [comment]
Yep i have it

**Comment by sadortun** [comment]
Test again with a lower value like `5 seconds` I've just tested it again and it working under Chrome

**Comment by Creeperman007** [comment]
Now it works

**Comment by sadortun** [comment]
Perferc! 

Have a good day!

**Comment by leshacat** [comment]
index.php is a php file...
