### ISSUE TITLE
field length 'ip' 100 not long enough

### ISSUE THREAD

**Issue by depositado** [phpservermon/phpservermon#323]
Can you please the default field length of the `prefix_servers.ip` field of checks to 255? 
I had to make changes in both MySQL and the `/src/templates/default/module/server/server/update.tpl.html` file in order to able to add a relatively long URL.

**Comment by sadortun** [comment]
Thia sèmes like a good idéal!

**Comment by sadortun** [comment]
@depositado  What version are you using ?

**Comment by mackaaij** [comment]
I was trying to add a long URL as well. In 3.1.1 the field length is 100, I needed 190. But I can easily envision longer URLs, even longer than 255.

**Comment by TimZ99** [comment]
Fixed in v3.2.0 with #169.
The new limit is 500 characters.
