### ISSUE TITLE
Add Freemobile to sms notification

### ISSUE THREAD

**Issue by quatrecentquatrenews** [phpservermon/phpservermon#325]
Can you add the freemobile support to notification sms ?

**Comment by wardpieters** [comment]
Hi @quatrecentquatrenews! If you still need this gateway, please let me know. Otherwise please close this issue.

**Comment by TimZ99** [comment]
I don't know if you meant FreeMobileSMS, but that one is added. If you meant another carrier, let us know and reopen the issue.
