### ISSUE TITLE
What is used to check services?

### ISSUE THREAD

**Issue by SephLeague** [phpservermon/phpservermon#326]
Hi

What do you use to check a service? Fsockopen? I tried using Fsockopen to monitor one of my servers but it gets blocked after a few attempts by the ddos protection yet this script somehow does not.

I have tried looking through the source but there are too many files.

Thank you

**Comment by sadortun** [comment]
Have you try the **Search** function on the system you use ?

https://github.com/phpservermon/phpservermon/search?utf8=%E2%9C%93&q=Fsockopen

**Comment by SephLeague** [comment]
Thank you.
