### ISSUE TITLE
Problem with monitoring meißner.click

### ISSUE THREAD

**Issue by Meiszner** [phpservermon/phpservermon#327]
I tried to monitor http://www.meißner.click/ (or https://www.meißner.click/) but PHP Server Monitor says 'The website URL is not valid.'

**Comment by sadortun** [comment]
Indeed. the domain doesnt seems to exists ....

![image](https://cloud.githubusercontent.com/assets/794449/16547805/35d4a472-4147-11e6-8f08-8441330957cf.png)

**Comment by Meiszner** [comment]
I registered the domain some hours ago and I got the info from the registrar that it needs some days to finish the order. Will PHP Server Monitor accept the URL when the registration is finished?

**Comment by sadortun** [comment]
We use PHP `filter_var()` to check the URL. If it's a valid URL it should work. Otherwise i suggest that you update your PHP version

http://php.net/manual/en/function.filter-var.php
