### ISSUE TITLE
Feature Request: Add Search to server overview page

### ISSUE THREAD

**Issue by sense-design** [phpservermon/phpservermon#333]
A search on the server overview page would be nice to filter the list.

**Comment by joubertredrat** [comment]
+1

**Comment by licafe** [comment]
like

**Comment by licafe** [comment]
Who can do this?
Thanks All.

**Comment by Kopertje** [comment]
+1

**Comment by criwe** [comment]
Maybe https://datatables.net/ would be an easy solution?

**Comment by sadortun** [comment]
@criwe Feel free to submit a PR !

**Comment by licafe** [comment]
howto step by step ? 
https://drive.google.com/file/d/0B0AriV_AGXSMZ2FRaHhlOURDWjg/view?usp=sharing

**Comment by lupor0x** [comment]
I've added the search with the JS script [CHOSEN](https://harvesthq.github.io/chosen/)

![image](https://cloud.githubusercontent.com/assets/16296163/21932677/18ba3548-d9a2-11e6-8712-2e452e38470c.png)

**Comment by licafe** [comment]
Howto add phpmonserver  with  JS script CHOSEN.
thanks you

**Comment by TimZ99** [comment]
Implemented.
