### ISSUE TITLE
composer.phar error

### ISSUE THREAD

**Issue by Haringstad** [phpservermon/phpservermon#335]
Trying to install on a Raspberry Pi, Ubuntu Mate 16.04 TLS:

PHP Fatal error:  Uncaught PharException: phar "/home/jko/Downloads/pipo/phpservermon-3.2.0-rc1/composer.phar" SHA1 signature could not be verified: broken signature in /home/jko/Downloads/pipo/phpservermon-3.2.0-rc1/composer.phar:23
Stack trace:
#0 /home/jko/Downloads/pipo/phpservermon-3.2.0-rc1/composer.phar(23): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in /home/jko/Downloads/pipo/phpservermon-3.2.0-rc1/composer.phar on line 23

**Comment by sadortun** [comment]
Hi @Haringstad  Did you use  master of develop ?   In the past, there were an issue with the `composer.phasr` in the repository.  you can download it seperatly if you still have the issue on `develop`

**Comment by xcafebabe** [comment]
Same issue here, tested with `develop` branch.

**Comment by sadortun** [comment]
I'll try to have a look. Composer.phar should probably not be in the repository anyway. You can download your own copy.

If replacing the composer.phar solve the issue, you can submit a PR for `develop` and `master` i'll merge it.

**Comment by xcafebabe** [comment]
thanks Samuel, I've downloaded bundle package and it works smoothly :+1:

**Comment by Haringstad** [comment]
Ok, fault was on me. I had it installed on my Pi, together with PiHole. After fiddling around, I got the main package working. But still, had the error on both develop and master. The package from the main site, now works flawless!

**Comment by nixis** [comment]
Same issue here, deleted composer.phar and installed it from composer website -> now it's running.

**Comment by Aestu** [comment]
Created PR #339 for develop branch

**Comment by Aestu** [comment]
Created PR #340 for master branch

**Comment by sadortun** [comment]
Thanks!
