### ISSUE TITLE
SMS Encoding

### ISSUE THREAD

**Issue by ChristianLJ** [phpservermon/phpservermon#349]
I have a problem with the SMS encoding. The K??RER should be KØRER. 

![screenshot_20160902-161256](https://cloud.githubusercontent.com/assets/3056379/18206763/6de72ae0-7128-11e6-930f-b148349b2f78.png)

**Comment by sadortun** [comment]
I am not sure if SMS are sent using a specific charset.

1) What provider do you use ?
2) What is your charset (you expect) ?

Thanks,
Sam

**Comment by ChristianLJ** [comment]
I just checked my providers API documentation (CpSMS) and it was possible to set an UTF8 flag to true. This seems to do the trick. Thank you.
