### ISSUE TITLE
Email encoding

### ISSUE THREAD

**Issue by ChristianLJ** [phpservermon/phpservermon#350]
When receiving an email with danish content there's a problem with the encoding:

```
Serveren 'SERVERNAME' kÃ¸rer igen:
Server: SERVERNAME
IP: IP
Port: PORT
Dato: 2016-09-02 16:28:04
```

The kÃ¸rer should be kører. UTF8 would do the trick.

Thanks, 
Christian

**Comment by robertzajda** [comment]
Hi,

This patch fixes the problem:
```
--- phpservermon-3.2.0-rc1.orig/src/includes/functions.inc.php	2016-05-19 05:31:40.000000000 +0200
+++ phpservermon-3.2.0-rc1/src/includes/functions.inc.php	2016-09-09 19:21:57.520198451 +0200
@@ -437,6 +437,7 @@ function psm_build_mail($from_name = nul
 		$from_email = psm_get_conf('email_from_email');
 	}
 	$phpmailer->SetFrom($from_email, $from_name);
+	$phpmailer->CharSet = "UTF-8";
 
 	return $phpmailer;
 }
```

Robert

**Comment by ChristianLJ** [comment]
@robertzajda that did the trick. Thank you.

**Comment by sadortun** [comment]
@robertzajda Can you submit a PR ?

**Comment by baur** [comment]
that not works for me (((

**Comment by baur** [comment]
but "send test mail" works fine with utf-8, although there is not used **utf8_decode($body);**

**Comment by baur** [comment]
any suggestions?

**Comment by danny00lo** [comment]
it is not fix the bug too. when i use the chinese lang. also the same problem with baur
i will show that:
??????????:

???: ??6
IP: 222.222.222.222
Port: 80
??: Connection timed out
??: 2017-02-07 15:29:08

**Comment by danny00lo** [comment]
in the log, the encoding is normal, so how to fix this bug?

**Comment by vus520** [comment]
@sadortun I also encountered this problem today. I will run some test on the fix proposed by robertzajda, after that i will submit a PR.

**Comment by vus520** [comment]
@sadortun @baur @danny00lo 

I think i have fixed this bug.
when i send test email from Email config page, the email is all good.
At last I found the issue is caused by StatusNotifier' utf8_decode.

```shell
diff --git a/src/psm/Util/Server/Updater/StatusNotifier.php b/src/psm/Util/Server/Updater/StatusNotifier.php
index 1b54a86..a87f554 100644
--- a/src/psm/Util/Server/Updater/StatusNotifier.php
+++ b/src/psm/Util/Server/Updater/StatusNotifier.php
@@ -202,11 +202,11 @@ class StatusNotifier {

                // build mail object with some default values
                $mail = psm_build_mail();
-               $mail->Subject  = psm_parse_msg($this->status_new, 'email_subject', $this->server);
+               $mail->Subject  = utf8_decode(psm_parse_msg($this->status_new, 'email_subject', $this->server));
                $mail->Priority = 1;

                $body = psm_parse_msg($this->status_new, 'email_body', $this->server);
-               $mail->Body             = $body;
+               $mail->Body             = utf8_decode($body);
                $mail->AltBody  = str_replace('<br/>', "\n", $body);
```

**You can fix this bug**  with replace `utf8_decode` to `trim`.

If you test OK, please let me know.

**Comment by danny00lo** [comment]
@vus520 i just try try.This great to heard that

**Comment by baur** [comment]
thanks, I'll try

**Comment by baur** [comment]
**@vus520** 
I confirm, problem is  solved!!!

**Comment by q629988171** [comment]
@vus520 I confirm, problem is solved!!!
