### ISSUE TITLE
why graph not working?

### ISSUE THREAD

**Issue by gigatoon** [phpservermon/phpservermon#354]
![graph](https://cloud.githubusercontent.com/assets/22144112/18428033/d249ef0c-78f5-11e6-8332-5fa2cdea65b3.png)
My PSM is Running 1 month ago.
in DB has data of uptime. But is not ploting graphs.

**Comment by Dima4ka** [comment]
Same for me

**Comment by gigatoon** [comment]
Now, I get it.
resolve by update php. before its 5.3.7 and then up to 5.4.9 last version is support apache 2.2
