### ISSUE TITLE
Zend OPcache Issue

### ISSUE THREAD

**Issue by mjbrancato** [phpservermon/phpservermon#356]
I am getting an error when trying to run my cron job from the command line: Zend OPcache requires Zend Engine API version 220121212.
The Zend Engine API version 220131226 which is installed, is newer.
Contact Zend Technologies at http://www.zend.com/ for a later version of Zend OPcache.

I have rebuilt my EasyApache and I am running PHP 5.6.

**Comment by sadortun** [comment]
Make sure you are using the same PHP executable as your Web server

**Comment by mjbrancato** [comment]
Not sure I follow? I am using PHP 5.6 provided with my cPanel.

**Comment by pboethig** [comment]
What abount an Health or Integriytycheck to compare webserver and cli version of PHP?

**Comment by pieter-groeneweg** [comment]
@mjbrancato 
Still your server can have more PHP versions available. Some explanation:
Depending on the user that runs the cron job it may use another version
Even depending on the folder it may use another version.
ie. I have a server that ages ago was setup with PHP5.3. which therefore ended up being the default.
Now later on I added PHP5.6 and PHP7.0 as extra available versions. I also had an issue with my cron jobs. Monitor in a virtual host on that server running on PHP5.6 (and the current 3.2 running on PHP7.0!) but the cron job insisted on using 5.3 as that was servers default. Setting a folder to use PHP7.0 in apache (what you probably see in Plesk) is not the same as setting the folder to use PHP7.0 from cli. You need another approach for that. This is one:

setting a cron job like 
`*/15 * * * * /usr/bin/php /var/www/html/phpservermon/cron/status.cron.php`
is using your servers default..
`*/15 * * * * 	/opt/remi/php70/root/usr/bin/php /var/www/html/phpservermon/cron/status.cron.php`
is a sample of using the other PHP executable. You of course need to check the path to the "other" PHP.
