### ISSUE TITLE
question not a reall issue: concurrent checks.

### ISSUE THREAD

**Issue by pieter-groeneweg** [phpservermon/phpservermon#359]
Here I am, the noob.

Is psm checking services/sites one by one? (this would explain the times such as 09:01:21)
And/Or are there any concurrent checks running? 

If so, how many at a time? Can I set this somewhere?

**Comment by sadortun** [comment]
Servers are check one by one.

**Comment by pieter-groeneweg** [comment]
Mmmmh... ok so in a worst case scenario, checking 20 sites with a default timeout of 10 seconds takes 200 seconds (3 minutes and 20 seconds)?

**Comment by sadortun** [comment]
Yes, but if your cron is scheduled every minute, all your checks will be done once per minute. As you said, the last check in a cron execution will be 3m20s later.

If all your sites takes 10 seconds to respond, you have a more important issue to solve than that :) :)

**Comment by pieter-groeneweg** [comment]
Agreed :) it was just to clarify how a job is processed. But certainly it is important knowledge for those who want to calculate how many sites they can test within any given interval they set in the cron jobs.
