### ISSUE TITLE
False Alerts

### ISSUE THREAD

**Issue by thatrez** [phpservermon/phpservermon#366]
My monitor keeps sending out alert emails but the services are fine when I check them using the included link to the webpages they are monitoring in the email. Is there a way to alter the program not the throw an alert if a box is down unless it checks a few more times first?

**Comment by sadortun** [comment]
Have you tried to increase the timeout ?

**Comment by thatrez** [comment]
how do you do that?

**Comment by thatrez** [comment]
I figured out how to adjust the settings, thank you for the reply.

**Comment by Abawell** [comment]
Click on menu Servers. Click on the edit button of the server you want to edit and change the timeout value.
You can change the Warning threshold too. It's the number of fails required before the server is marked offline.

**Comment by pieter-groeneweg** [comment]
This is not entirely true. Take a look at /src/psm/Util/Server/Updater/StatusUpdater.php line 76

It says it attempt twice (2 times) before it decides it is a fail. (see the comments above that line)
One thing you could do (if you have access to it of course) is check the access logs of the website probed and check for monitor hits with status 200 at almost the same time... I am sure you do have some even ones that succeeded the second attempt thus do not show in your alarms.

It sure is your web server not rendering ok. Not your monitor
