### ISSUE TITLE
Disable user login system

### ISSUE THREAD

**Issue by gustavomacedo** [phpservermon/phpservermon#368]
Hi all. First of all, tks for this amazing tool! it's awesome :)

So, I need to disable the user login system in order to keep the tool open.
I tried to do some changes on "\src\psm\Service\User.class.php" file, but didn't work.

Anyone can help me?

**Comment by sadortun** [comment]
You could try to set `PSM_USER_ANONYMOUS = PSM_USER_USER`
https://github.com/phpservermon/phpservermon/blob/68c087025dccc6f69a45e1f088350a22a2cd8d39/src/bootstrap.php#L37

Try at your own risk !

**Comment by Kopertje** [comment]
Hello,

When will this option been build in?

Greetings,
Robin

**Comment by sadortun** [comment]
When some contributor will take time to submit a PR

**Comment by Kopertje** [comment]
I export the data from the database into a .json file. Then i read the .json file on a external page for my users. This way i dont need any kind of authentication. Little bit less secure, but there is no any sensitive data in the .json file. It works great for me.

**Comment by TimZ99** [comment]
Additional requests from other issues:
- #539 Only disable login for specific IP.

Summery:
The user login could be disabled. 
- So the current status and the history will be publicly available. 
- But an administrator account will still be necessary to add and remove servers.

correct?

**Comment by badookey** [comment]
I found a workaround unofficial solution here: https://sourceforge.net/p/phpservermon/discussion/845823/thread/f1b2e4ff/

Credit: Tommy Grignon 
Edited a bit to fix english errors.

First, Create a Public user, assign servers as you wish the public user to.
Second, Memorize the ID it gives to you. (When I tried It didn't give me an ID, the ID is equivalent to the number of users you've made on PHPServermon, should be able to find it in your database as well)



Next, navigate to  \src\psm\Service\User.php
on Line 98 (after $this->session = $session;)

add code:
`global $_GET;`

 ` if ($_GET["kl"] == "public"){`
  `   $user_id = 2;`
  `   $this->setUserLoggedIn($user_id, true);`
  `   $user = $this->getUser($user_id);`
   `  $this->newRememberMeCookie();`
 ` }`
  

Enter URL http:/server/servermonitor/?kl=public to bypass login

This method use a particular userid so even if somebody change the password, the script will never use it anyway.

OPTIONAL:
You can change other things to cut some menu items, 
\psm\Module\AbstractController.php

Line 271 : erase the server_update function, I think this is only the crontab need to make a status update and I seen some troubles when I make it manually.

$items = array('server_status', 'server', 'server_log', 'user', 'config');

Line 274 : comment the entire items line, when you are only User (Public account) you don't want to have other things to see other then the servers status page

//$items = array('server_status', 'server', 'server_log', 'server_update');

**Comment by obriat** [comment]
Here a quick workaround:
Create a anonymous user.
Add this user to all the servers that should be displayed to everyone.
 
Add a file a the web root (`public_alerts.php`) with these lines :
`require __DIR__.'/src/bootstrap.php';`
`psm_no_cache();`
`$User = $router->getService('user');`
`// Use the anonymous login and password.`
`$User->loginWithPostData('anonymous','anonymous');`
`$router->run('server_status');`
` # Comment this line if you want anonymous users be able to see details and other pages /!\ The could also access profile pages and change password....`
`$User->getSession()->invalidate();`

The public alert are now available  on http://<you-server>/public_alerts.php

**Comment by kidtienk** [comment]
any chance this feature will be built in option?

**Comment by sadortun** [comment]
@kidtienk feel free to submit a PR

**Comment by TimZ99** [comment]
You can use the public page [(docs)](https://github.com/phpservermon/phpservermon/blob/develop/docs/faq.rst#setting-up-a-public-page).

Completely disabling the login system is not really an option here.
After 5 years of this feature request being open I don't think anyone will submit a PR.
It also won't be on the roadmap for v3.

**Comment by Peatty45113** [comment]
Hi  

if ($_GET["kl"] == "public"){
   $user_id = 2;
   $this->setUserLoggedIn($user_id, true);
   $user = $this->getUser($user_id);
  $this->newRememberMeCookie();
 }

This code works but I would like an user_id can work more than id=2  like I want to let it work from id 2 to id 50 how to do that
