### ISSUE TITLE
Broken Default Links

### ISSUE THREAD

**Issue by TimesEnemy** [phpservermon/phpservermon#372]
Greetings.

I am trying this application out.  The Readme instructions were oversimplified.  I had to create the database prior to running install.php.  I also had to manually create the config.php file, though I believe a permission test could have been done prior to install to give me a heads up.  Now for the issue at hand ...

The links by default do not include "index.php" in them, so they all force my server to return 404 errors.  For example:

http://myserver/phpservermon-3.1.1/index.php

The following are the links from the top menu:

Status: http://myserver/phpservermon-3.1.1/?&mod=server_status
Servers: http://myserver/phpservermon-3.1.1/?&mod=server
Log: http://myserver/phpservermon-3.1.1/?&mod=server_log
Users: http://myserver/phpservermon-3.1.1/?&mod=user
Config: http://myserver/phpservermon-3.1.1/?&mod=config
Update: http://myserver/phpservermon-3.1.1/?&mod=server_update
Help: http://www.phpservermonitor.org/support

The "Welcome, Username" points to: http://myserver/phpservermon-3.1.1/index.php#
Profile: http://myserver/phpservermon-3.1.1/?&mod=user_profile
Logout: http://myserver/phpservermon-3.1.1/?&logout=1

Logging in is broken as well.

So, when I add "index.php" in front of the question mark, the links seem to work.

It is quite annoying.

**Comment by sadortun** [comment]
This should work as is, you can:

Define : 
https://github.com/phpservermon/phpservermon/blob/68c087025dccc6f69a45e1f088350a22a2cd8d39/src/includes/psmconfig.inc.php#L114

You can aslo check that `$_SERVER['SCRIPT_NAME']` is defined correctly

**Comment by TimesEnemy** [comment]
@sadortun Thanks for the response!

It seems to be resolved after doing the following.

Located `$_SERVER['SCRIPT_NAME']` within the "..\phpservermon-3.1.1\src\includes\functions.inc.php" file.

Modified from:

`$url .= dirname($_SERVER['SCRIPT_NAME']) . '/';`

to:

`$url .= dirname($_SERVER['SCRIPT_NAME']) . '/index.php';`

Links that were missing the index.php seem to now have it as part of the URL, and all the buttons I have tried so far are now working.

Again, thank you!

**Comment by sadortun** [comment]
You should not add `/index.php` it's the job of the Apache DirectoryIndex to point to the index

**Comment by douzzel** [comment]
_I know that this is coming **so** much later, but as I was having a similar issue with v3.5.2 on my installation, I would like to add my "2 cents"..._
In my case, default links were broken and as such CSS wouldn't load properly.
I resolved the issue with the following two changes:
- in the `/src/includes/functions.inc.php` file, on _my_ line 812 (that corresponds to line **846** of the current GitHub branch at the time of writing this), the following bit of code seems redundant and to be the main source of the issue:
`$url = rtrim($url, '/') . '/';`
_(why remove something only to put it back?)_
As such I changed my deployed code to only be `$url = rtrim($url, '/');`
- in the `/config.php` file (at root level), on _my_ line 8, I set the following
`define('PSM_BASE_URL', '<full-path-including-any-subdirectories>/index.php');`

This not only resolves the issue for me but also keeps the impact of my changes minimal and, in my opinion, _logic_...
Hope that this helps anyone else that might also be facing similar issues!
