### ISSUE TITLE
'psm_goTo' is undefined "Add new" server button

### ISSUE THREAD

**Issue by bradgillap** [phpservermon/phpservermon#373]
So when I click add new server button I get this psm_goTo is undefined in the browser.

All of the other links seem to work through out the entire monitor site. I can edit existing items and delete but I cannot create new items.

version 3.1.1

lighttp
mysql
php5

The link I can't seem to get to is this one. It works if I just type the extra &action=edit myself.

http://192.168.1.2/up/index.php?&mod=server&action=edit

I imagine this is because apache does something that lighttp doesn't.  There is another help request on here with similar issues but I'm not sure if that person is using apache.

**Comment by pieter-groeneweg** [comment]
I don't work with lighttp, but this is probably caused by the way lighttp mod_rewrite handles URL querystrings. 
Please do check.

**Comment by TimZ99** [comment]
Guess this is no longer an issue. Feel free to reopen if I'm wrong.
