### ISSUE TITLE
list of requirements incomplete

### ISSUE THREAD

**Issue by jasondewitt** [phpservermon/phpservermon#377]
This list of server requirements appears to be incomplete:
```
Web server
MySQL database
PHP 5.3.7+
PHP cURL package
PHP PDO mysql driver
```
I was just attempting to install v3.2.0-rc1 on a fresh Centos7 droplet. I installed everything from the list above but I ended up with a blank page when running `install.php`. Even running `php install.php` resulted in no feedback.

Finally I created a `config.php` file and turned on debugging with `define('PSM_DEBUG', true);` and finally got an error message:
```
Uncaught Error: Class 'DOMDocument' not found in /var/www/servermonitor/vendor/symfony/config/Util/XmlUtils.php:52
```

Once I installed the `php-xml` package everything is working great. Should php-xml be listed as a requirement? Or is this a larger issue with Symphony since the error is occuring there and php-xml is listed as an optional requirement here: http://symfony.com/doc/current/reference/requirements.html

**Comment by sadortun** [comment]
Thanks, fixed by eadc9b145e574a43d4daad132d7de9157d9e2fe6
