### ISSUE TITLE
I receive mail with question marks when using non-English characters?

### ISSUE THREAD

**Issue by baur** [phpservermon/phpservermon#378]
I receive mail with question marks when using non-English characters?

?????????? ???????????? ? ?????????? ???????:

??????: ???????
IP: 10.28.XXX.XXX
????: 1
??????: 
????: 2016-11-15 11:43:52

**Comment by baur** [comment]
but "send test mail" works fine with utf-8

**Comment by sadortun** [comment]
Duplicate of #350
