### ISSUE TITLE
last online time is null

### ISSUE THREAD

**Issue by baur** [phpservermon/phpservermon#379]
last online time is null
![image](https://cloud.githubusercontent.com/assets/2898361/20334670/2d18a310-abe6-11e6-923f-200f6a61338a.png)

**ver 3.1.1**
![image](https://cloud.githubusercontent.com/assets/2898361/20376869/bfbeb12c-acb4-11e6-8bad-899800704113.png)

**ver 3.2** 
![image](https://cloud.githubusercontent.com/assets/2898361/20376882/e2895838-acb4-11e6-93c0-6bf71ebada5b.png)

mybe that's related with interruption of update polling 

![image](https://cloud.githubusercontent.com/assets/2898361/20334633/cbb01d7e-abe5-11e6-9d01-6442a89ca4c2.png)

**Comment by baur** [comment]
any sugestions? ...

**Comment by sadortun** [comment]
Did you solve your issue ?

Did you investigated to see what kind of data was in the db ?

**Comment by pieter-groeneweg** [comment]
Check your server time settings, your PHP time settings and PSM time settings.

**Comment by baur** [comment]
Thanks, you are right, I have wrong settings at **date.timezone**. Now I'll check is will this fix the problem?

**Comment by baur** [comment]
where I can find PSM time settings?

**Comment by pieter-groeneweg** [comment]
Well that is hard to find, but PSM times settings can be done in config.php

Add this above all define rules: 

ini_set('date_default_timezone_set', 'Europe/Amsterdam'); (or the one suiting your timezone of course)

But it doesn't work if your server doesn't allow these overrides. Else you set in the .ini file(s)

**Comment by baur** [comment]
I'm fixed tmezone 
1. php.ini date.timezone
2. ini_set('date_default_timezone_set', 'Europe/Amsterdam');
but the problem is not fixed (((

**Comment by pieter-groeneweg** [comment]
How is date time managed on the server itself? Is that working properly?

**Comment by baur** [comment]
> How is date time managed on the server itself? Is that working properly?

yes, of course

![image](https://cloud.githubusercontent.com/assets/2898361/24385768/c6770c90-138d-11e7-94bb-471bae73150d.png)

**Comment by pieter-groeneweg** [comment]
create a file in root "time.php" and drop this in

<?php
echo (date('d/m/Y h:i:s a', time()));
?>

browse to your domain.com/time.php see what it shows. If it shows OK, your host time settings are good.
Else change to 

<?php
ini_set('date_default_timezone_set', 'Asia/Almaty');
echo (date('d/m/Y h:i:s a', time()));
?>

check again.

**Comment by baur** [comment]
> create a file in root "time.php" and drop this in 
time.php code?

**Comment by baur** [comment]
```
<?php 
date_default_timezone_set("UTC"); 
echo "UTC:".time(); 
echo "<br>"; 

date_default_timezone_set("Europe/Helsinki"); 
echo "Europe/Helsinki:".time(); 
echo "<br>"; 

date_default_timezone_set("Asia/Almaty"); 
echo "Asia/Almaty:".time(); 
echo "<br>";
?> 
```
**result:**
UTC:1490691052
Europe/Helsinki:1490691052
Asia/Almaty:1490691052

**Comment by pieter-groeneweg** [comment]
Huh it stripped my code on save? 
try:
```
<?php
$timezone = date_default_timezone_get();
echo "The current server timezone is: " . $timezone;
echo (date('d/m/Y h:i:s a', time()));
?>
```

else add this to the top: 

`ini_set('date_default_timezone_set', 'Asia/Almaty');`

**Comment by baur** [comment]
![image](https://cloud.githubusercontent.com/assets/2898361/24398597/dbd22316-13cb-11e7-913f-676347f0971b.png)

**Comment by pieter-groeneweg** [comment]
Well that is working then.. We at least determined the time zone setting is correct.

We can look at the update polling interruption.
This also looks strange as usually when you don't have any periodical poll setup, it would show a line from the previous to the next.

**Comment by pieter-groeneweg** [comment]
Come to think of that, can you check the logs in the db?
Is there a change in date/time format noticable around the date time of the occurrence?
![image](https://cloud.githubusercontent.com/assets/10771283/24402221/e67581fa-13b7-11e7-94ce-df8c9aa01714.png)

**Comment by baur** [comment]
I'm sure it's not related with interruptions of polling. Null value appears when server long time offline and I noticed Null value appears temporarily before Last Time value changes to dates (as March 24 etc) but there appears another bug #430

**Comment by pieter-groeneweg** [comment]
Well as the image shows no graph between 11/15 16:00 and 11/16 08:00 there is something wrong there as even when there was no polling done in between those times, a blue line would show between the two known polls. 
There is up time showing, (no red block) but no blue line. That makes me think there is some wrong with the notation of time date since 11/15 16:00. 
In your db you should be able to see a change of date time notation or any other anomaly around that date/time.
I believe it is psm_servers_uptime you need to check. But also do check other tables.

**Comment by TimZ99** [comment]
Could you update to the latest version and see if the problem is still present?

**Comment by baur** [comment]
I can not accurately reproduce this bug
