### ISSUE TITLE
can not set mysql server port excluding 3306

### ISSUE THREAD

**Issue by zuocheng-liu** [phpservermon/phpservermon#382]
My mysql service works on port 8306 , phpservermon displays "can not connect to mysql".

**Comment by sadortun** [comment]
Hi,

You are right, currently the Database class doesnt allow to change the port via config 😞 
https://github.com/phpservermon/phpservermon/blob/68c087025dccc6f69a45e1f088350a22a2cd8d39/src/psm/Service/Database.php#L501

Feel free to submit a PR if you can. As a short term fix you can set the port directly in :
```
'mysql:host='.$this->db_host.';port=XXXXXX;dbname='.$this->db_name.';charset=utf8',
```

**Comment by tomhatzer** [comment]
Please see https://github.com/phpservermon/phpservermon/issues/382

**Comment by hector-romero** [comment]
This introduced a new issue: when you use a db which do not require to specify a port to connect (Example: the db provided in a shared hosting environment) you have no way to avoid connect to the db since the service will force the port 3306 when connecting.

**Comment by tomhatzer** [comment]
@hector-romero can you please try with this change: https://github.com/phpservermon/phpservermon/pull/403

**Comment by pieter-groeneweg** [comment]
Sorry, but isn't this what "Port: Custom" is for? AFAIK the options list with predefined (default) ports is just a 'service' to make thinks a little easier for the people that use defaults.. (defaults are there for reason)

This is not a bug.

**Comment by TimZ99** [comment]
The original reason for this issue has been solved. The new issue can be discussed in #403. 

EDIT: Thanks for the pr 😄 btw.
