### ISSUE TITLE
SSL certificate check

### ISSUE THREAD

**Issue by av2k** [phpservermon/phpservermon#384]
Hello,

I like phpservermon very much because it's simple and just gets its job done! So thank you for this great tool!

However, I needed to check if SSL certificates are about to expire on the watched servers, since an invalid certificate basically renders a site unusable for average site visitors.

I've added a new field for SSL certificate checking in the settings. It represents the minimum days for which the SSL certificate has to be valid. If the user enters 0, no checking is done. If he enters any positive integer, there will be a warning if the certificate for a given site expires in less than the entered days. For example: User enters 20 and as soon as the SSL certificate validity has only 20 days left, phpservermon will send an error mail with the content "SSL certificate expiring in X days.".

First I thought about adding another state like "yellow" besides "red" (error) and "green" (everything fine), but I thought it would bloat phpservermon. So just letting expiring certificates behave like normal errors in phpservermon was sufficient for me.

For me this added functionality is valuable since some new CAs like "Let's Encrypt" issue certificates with a short duration and it's very helpful to know beforehand if a server will soon run into issues because of a soon-to-expire certificate.

I thought there might be other people who could also benefit from this.

Please let me know if you are interested in include this functionality in phpservermon, I'll upload the changes and create a pull request.

**Comment by pieter-groeneweg** [comment]
Certainly an interesting addition. I like it but..
Question. Would it then show RED when the certificate is about to expire, marking the server/site off line in the stats? IMO the function is nice but should not interfere with the statistics and graphs on latency and such..
Receiving the message and just mark it orange would do for me.

**Comment by Kopertje** [comment]
This option is great! I love it!

**Comment by sadortun** [comment]
#102

**Comment by brasileric** [comment]
A SSL certificate check will be great for me as well!

**Comment by tttttx2** [comment]
Yes, please! SSL certificate check would be just awesome!

**Comment by rolero** [comment]
Yes SSL check would be great.

**Comment by SimonFearby** [comment]
Love the ssl expire feature as I recently blogged about this and let's encrypt http://fearby.com/article/using-phpservermonitor-org-check-whether-websites-servers-running/

**Comment by av2k** [comment]
Hello,

see here: https://github.com/phpservermon/phpservermon/pull/494/commits/1743b6e3f9d0af8111f52abdcecf4f2cfe954a87

**Comment by tttttx2** [comment]
@av2k thank you very much for sharing, will give it a try soon :)

**Comment by SarahTrees** [comment]
plus 1
Yes SSL check would be great.
