### ISSUE TITLE
Add Telegram for notifications

### ISSUE THREAD

**Issue by bilyboy785** [phpservermon/phpservermon#389]
Hi ! It's possible to add Telegram for notifications ? With BOT Telegram.

**Comment by sadortun** [comment]
Hello @bilyboy785 please submit a PR and we will merge it !

**Comment by hadagalberto** [comment]
I need this too!
Is there any tutorial for create a new notification gateway?

**Comment by sadortun** [comment]
You can look on how others did for other providers in closed PR
https://github.com/phpservermon/phpservermon/pull/375/files

**Comment by hadagalberto** [comment]
Hello, i got it, Telegram Notifications, but how to submit a PR?

**Comment by strugee** [comment]
@hadagalberto see https://help.github.com/articles/about-pull-requests/
