### ISSUE TITLE
double slash redirect 

### ISSUE THREAD

**Issue by fferraro87** [phpservermon/phpservermon#396]
hi, 
why every page redirect to // address?
for example http://minomitor.com//?&mod=server&action=view&id=23&back_to=server_status

every address has // and i had everytime error to open pages

**Comment by sadortun** [comment]
The `dirname` or `SCRIPT_NAME` probably ends with a `/`

https://github.com/phpservermon/phpservermon/blob/74efd243c52df7b25769dd24c72450fd7eb5f85f/src/includes/functions.inc.php#L563

Feel free to submit a PR if you solve the issue.

Thanks,
Samuel

**Comment by fferraro87** [comment]
Ok thanks now it works,
i've modified this https://github.com/phpservermon/phpservermon/blob/74efd243c52df7b25769dd24c72450fd7eb5f85f/src/includes/functions.inc.php#L563
in this:
`
$url .= dirname($_SERVER['SCRIPT_NAME']) . '';
`

**Comment by fferraro87** [comment]
sorry i've open PR but maybe i'm wrong, it's first time that i open a PR on a project

**Comment by sadortun** [comment]
Your change might have some effects, you need to ensure the url have a `/` at the end

**Comment by TimZ99** [comment]
This is solved I guess. Latest version seems to be okay.
