### ISSUE TITLE
Integrate width LDAP autentication

### ISSUE THREAD

**Issue by vmonteirobr** [phpservermon/phpservermon#399]
Please if possible integrate with LDAP autentication to stablish SSO (single sign on) DevOps concept.
thanks for the project very helpful to me.

**Comment by sadortun** [comment]
Hi, feel free to submit a PR !

**Comment by sadortun** [comment]
#206

**Comment by viharm** [comment]
@vmonteirobr , this had been implemented in #507 . Please test and provide feedback
