### ISSUE TITLE
Minimum number of  sequential failures before error report

### ISSUE THREAD

**Issue by vmonteirobr** [phpservermon/phpservermon#400]
Hi if posible i need a feature to set a minimum number of  sequential failures before error report (service down, send mail), is useful to ignore transient or random network erros. thanks

**Comment by pieter-groeneweg** [comment]
There is a series of checks... /src/psm/Util/Server/Updater/StatusUpdater.php line 76 it is hardcoded to 2 times.

**Comment by sadortun** [comment]
@victormacko if your checks fails more than two times, you have more than random errors, you should investigate the issue on your side !

**Comment by vmonteirobr** [comment]
Yes, you is right, thanks so much.
Pieter thanks for the tips, i will try that.

**Comment by victormacko** [comment]
Ah great -- thanks for that :)
