### ISSUE TITLE
ping problem

### ISSUE THREAD

**Issue by masiarekrafal** [phpservermon/phpservermon#405]
Hey, 
in 1st case i can't add domain to ping service (returned "the ip adress is not valid"),  in second ping not working as well.
for testing im ping google or facebook, always i have result &quot;Failed to parse address 157.240.3.35&quot; when services works fine.

**Comment by schiegg** [comment]
I have the same problem. 
Updates via CRON work perfectly but when I press any update button it fails parsing.

**Comment by sadortun** [comment]
@schiegg does your cron user is the same as Web server user ? Looks like a permission issue

**Comment by schiegg** [comment]
Cron user is root as instructed in your docs.
Web server user is www-data and all files in the web folder are owned by this user.

**Comment by EmanH** [comment]
I have the same problem.
