### ISSUE TITLE
installation problem fix

### ISSUE THREAD

**Issue by masiarekrafal** [phpservermon/phpservermon#406]
in 3.1.1 when you try get install.php script you see 500 error , to fix this add separator (comma) after db_port variable in $config array inside /src/psm/Module/Install/Controller/InstallController.php

btw when you run composer install can you see:
`Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.` 
update is safe?

Thanks for great script!

**Comment by sadortun** [comment]
Thanks, it fixed !
