### ISSUE TITLE
Servers always green?!

### ISSUE THREAD

**Issue by twister5800** [phpservermon/phpservermon#408]
Hi and thanks for this great tool :)

I have installed it and setup cron job, everything is great, but servers are always green.

It updates the "last checked", and when I block the traffic to that particular host, the "last checked" just rises in time, in ex. last checked 24mins ago, but no alert is being triggered.

I have setup timeout for 10s and warning threshold to 1, string is empty.

What have I done wrong? :-)

Br. Martin

**Comment by pieter-groeneweg** [comment]
You say string so I guess you are monitoring websitses?
How do you block? 
And what do you see when you browse to that host yourself using a browser?

**Comment by twister5800** [comment]
![image](https://cloud.githubusercontent.com/assets/13104344/22333136/acd9a736-e3d4-11e6-8aa2-899e11be145b.png)

This i all I have done :-)

I block incoming port 80 to the webserver and I cannot browse site i browser when this is done, PHPMONITOR does count minutes since the host has be seen last, but does get "RED" ?!

**Comment by twister5800** [comment]
have also tried with port 80 instead of 0

**Comment by pieter-groeneweg** [comment]
when you set "website" it checks what is returned whatever the port you don't have to (or cannot) specify port (afaik). So what does it show when you hit the site using your browser? What is the statuscode returned?

**Comment by twister5800** [comment]
It's just a website, so it's needed to fill out search string/pattern?

**Comment by twister5800** [comment]
Did a "Service" setup, the behavior is the same, it shows it online, when i block the traffic it just shows that it was online x minutes ago, but no alert triggered, what have I done wrong?

![image](https://cloud.githubusercontent.com/assets/13104344/22375529/b7bb039e-e4aa-11e6-8a69-00f20f5ecd21.png)

It was 3 minutes ago that i closed SMTP port on server, it cannot check the service, but why does the alert not trigger?

**Comment by twister5800** [comment]
![image](https://cloud.githubusercontent.com/assets/13104344/22375555/d9a0b468-e4aa-11e6-967d-8b8dce52bdf8.png)

mail.mlf.dk is offline since 3 minytes, why no alert?

**Comment by twister5800** [comment]
When i enable SMTP on my server (mailserver), screen changes:

![image](https://cloud.githubusercontent.com/assets/13104344/22375602/16e0bdbe-e4ab-11e6-8268-01c570ce5f28.png)

**Comment by pieter-groeneweg** [comment]
what is your cron schedule?
ie. when it probes every 15 minutes and you disable your server on php monitor wait for at least 15 minutes OR click update in the menu bar.

You stated you disabled port 80... I wonder how as the url of your site has an IP from a shared host... usually on a shared host you are stuck with the ports they gave you and no way if changing that. (let alone disabling them)

**Comment by twister5800** [comment]
I checks every minute! Is that to soon?
i own the webhost it runs on, so I just get a timeout when i block the port :-)
But the same thing is with the service on port 25...no red alerts :-(

**Comment by pieter-groeneweg** [comment]
well if your script ends within the minute... I usually have it run every 10 minutes..

anyway I'll add n-a-a.dk to my monitor. It runs every ten minutes and sends me a message when errored twice (20 minutes at most)...

So let's see if some happens on my end when you block the port for some time if you like.
I know mine works  ok :)

**Comment by twister5800** [comment]
Thanks, But I Cannot take the site down, I usually block the ip to the site in my firewall ;-)

Best regards
Martin

Sendt fra min telefon.

Den 30. jan. 2017 kl. 17.52 skrev pieter-groeneweg <notifications@github.com<mailto:notifications@github.com>>:


well if your script ends within the minute... I usually have it run every 10 minutes..

anyway I'll add n-a-a.dk<http://n-a-a.dk> to my monitor. It runs every ten minutes and sends me a message when errored twice (20 minutes at most)...

So let's see if some happens on my end when you block the port for some time if you like.
I know mine works ok :)

-

**Comment by pieter-groeneweg** [comment]
incoming or outgoing....? Do you block on the server running the site or on the server running the monitor?
As now I think it is a firewall issue.

**Comment by twister5800** [comment]
I block outgoing in my firewall the psm sits behind on.

Not a fw issue.

I work as an network consultant, so I'm not completely noob ;-)

Mvh. Martin

Sendt fra min telefon.

Den 31. jan. 2017 kl. 09.39 skrev pieter-groeneweg <notifications@github.com<mailto:notifications@github.com>>:


incoming or outgoing....? Do you block on the server running the site or on the server running the monitor?
As now I think it is a firewall issue.

-

**Comment by pieter-groeneweg** [comment]
When it comes to unanswered questions I always consider myself a noob..  I am a noob most of the time anyway :) .. proud of it too... leaves me a lot to learn.

Anyway...
Just to be sure...  So, what if you'd block the IP of the monitor on the sites webserver's firewall.. ?

**Comment by twister5800** [comment]
Well that's a good point of view :-) - was just to let you know that i have tried to block both on the fw at home and the web servers firewall, and PSm can see the cnages as is shows that is is xx minutes since it was offline, as written earlier, when I allow the traffic again, the it writes "last seen: seconds ago", so it can clearly see the difference, but just no error.

maybe PSM it not suited for checks every minute?

**Comment by pieter-groeneweg** [comment]
come to think of it, yes.... read this http://docs.phpservermonitor.org/en/latest/install.html#setting-up-a-cronjob

This may very well be.

As I have on monitor running for about 70+ sites.. all set to allow 10 seconds to respond. In worst case scenario they all are down, the monitor waiting for 10 seconds on each makes it 700+ seconds in total. exceeding the 600 seconds (10 minutes)... I also increased the max execution time for php.

Another thing that may as well interfere, but that is more on the blocking, when using a CDN like cloudflare i experienced that my monitor appeared to be on a complete different IP than it really was. Just the cloudflare IP got logged. Cause... Missing Apache Mod..  ((if you use cloudflare: https://www.cloudflare.com/technical-resources/#mod_cloudflare)

Not that I was testing phpmonitor then.. but I blocked my site for all when I was setting up fail2ban back then...... cal me a noob.. :)

**Comment by twister5800** [comment]
i have read that article, thanks :-)
i have setup timeout for 10 seconds in the beginning, and still use that, the shell kindly tells me if i am to anger to get it running before it finishes :-)

The webserver is hosted on my own server at job, and the PSM is sitting on my home network, so no changes in IP's here, but i completely understand your example.

Well I guess we are alll noob's somewhere, I am in PSM, no doubt about that :-P

But will try to change the cron to 15 mins for know and see what happens :-)

**Comment by sadortun** [comment]
You can try to add a pattern in PSM that is not in your Web page to see if it's turn red

**Comment by twister5800** [comment]
Yup that did it - pattern not found, box RED alerts are being triggered.

So what now? :-)

**Comment by pieter-groeneweg** [comment]
well it sure than has something to do with the port blocking going 
wrongs somewhere...

What does your webserver return to blocked visitors? What status code?


Op 31-1-2017 om 21:33 schreef twister5800:

**Comment by twister5800** [comment]
No code, I block it in my firewall:
![image](https://cloud.githubusercontent.com/assets/13104344/22483466/acf25632-e7fd-11e6-929d-411abdb1350a.png)

So traffic = red = traffic dropped, when i browse from the host i get "timeout page cannot be displayed"

**Comment by twister5800** [comment]
212.116.232.225 is n-a-a.dk webhost.

**Comment by pieter-groeneweg** [comment]
Ok, block my IP on port 80 Ill add your site to my monitor on 
46.129.62.158 no pattern set.


Op 31-1-2017 om 21:39 schreef twister5800:

**Comment by twister5800** [comment]
I block it outgoing on my side, not destination firewall as is hosts selfservice for 8000 tv users on my city :-)
Can you block the Ip for webhost on your firewall, else i can block you on my private page martinsblog.dk :-)

**Comment by pieter-groeneweg** [comment]
Well... I am not in your city, so you can safely block my ip... But I'll 
add your private blog site to the monitor :)


Op 31-1-2017 om 21:45 schreef twister5800:

**Comment by twister5800** [comment]
Try to update now :-)

**Comment by twister5800** [comment]
I can see you :-)

**Comment by twister5800** [comment]
![image](https://cloud.githubusercontent.com/assets/13104344/22484304/1cd8ea26-e801-11e6-9bb7-fbd3036f53d7.png)

**Comment by sadortun** [comment]
Guys, please use https://gitter.im/phpservermon/phpservermon  to "chat"  issue tracker is not the best place to have a discussion !

**Comment by twister5800** [comment]
Sorry will do that.,

**Comment by pieter-groeneweg** [comment]
Server: martinsblog.dk
IP: http://martinsblog.dk
Port: 0
Error: TIMEOUT ERROR: no response from server
Date: 2017-01-31 22:02:45


Op 31-1-2017 om 22:03 schreef twister5800:

**Comment by pieter-groeneweg** [comment]
I don't quit agree.... on that.

People may watch and learn here.. so do we.

That does not happen on gitter....


Op 31-1-2017 om 22:05 schreef twister5800:

**Comment by twister5800** [comment]
Thanks for now pieter, I will go for the beds and try harder tomorrow :-)
