### ISSUE TITLE
add HTTPS site

### ISSUE THREAD

**Issue by mrlaigle** [phpservermon/phpservermon#412]
hello,
i want to monitor HTTPS site but it alaways shutdown , i put 443 port and doesn't work

site www.j4tinfo.com @pieter-groeneweg can you help me please

**Comment by pieter-groeneweg** [comment]
Added to mine, your site is showing ok at my monitor.
Settings:
label: https://www.j4tinfo.com/ (can be anything)
type: website
ip/domain: https://www.j4tinfo.com/

rest is left to defaults... no pattern set.

**Comment by mrlaigle** [comment]
thank you so much , i've tried also on localhost it work , but when in put it on website heberged on OVH all https don't work

**Comment by pieter-groeneweg** [comment]
Check with your OVH hosting.. check the error logs maybe...
