### ISSUE TITLE
Auto Refresh Problem

### ISSUE THREAD

**Issue by danny00lo** [phpservermon/phpservermon#413]
i am using 3.1.1, i found the problem on auto refresh problem. when i set up the auto-refresh in 300s. it cannot refresh auto or it just refresh the status page.

**Comment by pieter-groeneweg** [comment]
auto-refresh updates your page in the browser it does not trigger an status check.
for status checks on your monitored servers you need to set a cron job.

**Comment by danny00lo** [comment]
i just fix my problem.
i just use the ajax method to check my status, and i open the website in my linux server. this is work for monitor the server status. However, i want to know is there any more user friendly method to auto check my server

**Comment by danny00lo** [comment]
thankyou pieter reply. i am glad to discuss with you and your comment~

**Comment by pieter-groeneweg** [comment]
IMO phpservermonitor is the most friendly monitor.
but best practice is to set it up using a cron job to trigger the monitor regularly.

**Comment by danny00lo** [comment]
IMO?what it the IMO?
Now, i use the linux server to open the website and every 10 mins will auto ajax to the update page to update the status.
The linux server is held on the data-center, so it is ok

**Comment by pieter-groeneweg** [comment]
IMO = In my opinion...... :)

**Comment by danny00lo** [comment]
HAHA... i just think this is the other server monitor haha
