### ISSUE TITLE
Use Clickatell REST API

### ISSUE THREAD

**Issue by Ben-Atherton** [phpservermon/phpservermon#423]
For newly registered Clickatell accounts it would appear you can only use the REST API and currently PHP Server Monitor uses the HTTP API, it would be good to have the option to use the REST API.

**Comment by vus520** [comment]
psm_curl_get function will send a GET request by default.
add a `CURLOPT_CUSTOMREQUEST` method can support this feature. Looks like easy.

**Comment by mattronix** [comment]
Ouch annoying I created my clickatell account a week ago looks like this is the reason it is not working.

**Comment by TimZ99** [comment]
#451
