### ISSUE TITLE
when is 3.2.x past rc?

### ISSUE THREAD

**Issue by pieter-groeneweg** [phpservermon/phpservermon#424]
v3.2.0 has been RC since may last year.
When does it become stable release?

The bug list contains a few bugs that are not really bugs (ie. feature request cannot be a bug) and some already can be closed.

I would be nice now to have a stable release that include all dependencies.

**Comment by e-alfred** [comment]
And patched vulnerabilites. A new release would be really appreciated.

**Comment by sadortun** [comment]
@dopeh can you publish the 3.2 release ?

Thanks

**Comment by dopeh** [comment]
Sure, I will get it sorted next weekend. Could you have a look at the 
changelog to make sure it's up to date?

Cheers.

**Comment by e-alfred** [comment]
Any news on this? A version with all the security related stuff fixed would be much appreciated.

**Comment by dopeh** [comment]
Sorry guys, my bad. Will sort it out tomorrow!

**Comment by dopeh** [comment]
Should be all sorted. Just to make sure, what was on develop was good to go for v3.2.0 right? I noticed the version in the psmconfig file so blindly assumed I could merge everything to master for this release.

**Comment by e-alfred** [comment]
Awesome, thanks for the work.
