### ISSUE TITLE
Can't use install.php to configure Database

### ISSUE THREAD

**Issue by BristolITDave** [phpservermon/phpservermon#427]
I cloned the latest version from Github and built using Composer and tried to do a fresh installation today.

When trying to configure the database using install.php - it constantly said MySQL details were incorrect. I checked MySQL logs and it was trying to login with username '3306' - I can only imagine this is something to do with the custom port changes done around December.
MySQL Log: 2017-03-17T14:36:24.195994Z 142 [Note] Access denied for user '3306'@'localhost' (using password: YES)

I copied the example config, and re-ran the install file and was then able to carry on.

**Comment by sadortun** [comment]
@tomhatzer any clues in this ? Have you tested the install script ?

**Comment by pieter-groeneweg** [comment]
@BristolITDave You write username = "3306". Are you sure your username is 3306 as this is also default portnumber for MySQL

**Comment by BristolITDave** [comment]
@pieter-groeneweg - Exactly, my username **is not** 3306! I clearly put the correct username in the username box. @sadortun I'll run it again on a different box and check this is an actual issue. The first box I ran it on, was a fresh install of Ubuntu 16.04 on Linode. PHP version 7.0.15-0, MySQL 14.14 Distrib 5.7.17.

**Comment by BristolITDave** [comment]
Confirmed on an older Ubuntu (14.04.5) box:
http://gosub.me.uk/i8fuo --- 170320 14:43:11 [Warning] Access denied for user '3306'@'localhost' (using password: YES)
PHP 5.5.9, MySQL 14.14 Distrib 5.5.54

**Comment by pieter-groeneweg** [comment]
I peeked through the code in github (till now searched fro db_user and dp_port in the code) but nothing odd there...

**Comment by bryanschmidty** [comment]
To get past this issue, I had to manually add the database config in `config.php.sample` and renamed it to `config.php`.  Reloading the page will then allow the installation to continue to the next step.

**Comment by laangen** [comment]
The problem lies in the InstallController: the order of the parameters is wrong when testing the database connection. Line 144

**Comment by sadortun** [comment]
@laangen please submit a PR if you have a few minutes !

**Comment by laangen** [comment]
@sadortun OK my first PR has been made

**Comment by sadortun** [comment]
@laangen  Thanks a lot  for your contribution ! Hope to see you again soon !

**Comment by sadortun** [comment]
Fixed by #428
