### ISSUE TITLE
Last online: text encoding error

### ISSUE THREAD

**Issue by baur** [phpservermon/phpservermon#430]
English
![image](https://cloud.githubusercontent.com/assets/2898361/24386336/dce56582-1390-11e7-9692-8d9b2803e8ff.png)
Russian
![image](https://cloud.githubusercontent.com/assets/2898361/24386317/c58780b4-1390-11e7-8c74-19b32a75ad49.png)

this encoding error related with month, in other case works well
![image](https://cloud.githubusercontent.com/assets/2898361/24386462/7ffacaa0-1391-11e7-99d0-e398c16ea6a2.png)

**Comment by baur** [comment]
any suggestions?

**Comment by TimZ99** [comment]
I will have a look for you!

**Comment by TimZ99** [comment]
Can't reproduce this on version 3.3.1. Could you update to the latest version and check if the problem is gone?
If not; what are you running PSM on?

**Comment by baur** [comment]
Problem is actual for 3.3.1. It appears after long time

**Comment by TimZ99** [comment]
What do you mean by ‘after a long time’? A long time after loading the page or...

**Comment by baur** [comment]
After a long time, the server was unavailable

**Comment by TimZ99** [comment]
Could you remove `, 'ru_RU', 'russian', 'russian'` from https://github.com/phpservermon/phpservermon/blob/de29906f274a6b573d8fd8e8dd0dfc3acd1edf6d/src/lang/ru_RU.lang.php#L31 and see if the problem is gone?

**Comment by baur** [comment]
Yes, the problem is gone, but the name of the month in English

**Comment by TimZ99** [comment]
And only ru_RU?

You're running PSM on windows right?

**Comment by baur** [comment]
left only **ru_RU.UTF-8**, yes, PSM running on windows.

**Comment by baur** [comment]
**PSM 3.4** 
![image](https://user-images.githubusercontent.com/2898361/63738467-ab468880-c8ab-11e9-98b5-673377665871.png)

**Comment by baur** [comment]
any suggestions?

**Comment by baur** [comment]
@TimZ99

ver 3.6.0 from Master

![image](https://user-images.githubusercontent.com/2898361/141714930-4df744a5-d5fd-4069-93d3-6c40a62e03ea.png)

**Comment by baur** [comment]
![image](https://user-images.githubusercontent.com/2898361/141717848-f958c152-261a-448a-bf20-3a41ad749dac.png)

![image](https://user-images.githubusercontent.com/2898361/141717903-ce7a2c94-04da-4413-9e56-8f1799d1d759.png)
