### ISSUE TITLE
[FEATURE REQ] Possibility to notify non-users

### ISSUE THREAD

**Issue by TheCelavi** [phpservermon/phpservermon#431]
We are using this tool to monitor some services from various clients. One of our client wants to be notified in real time when his application is down. 

We do not want to create new user (client should not be able to login), we would like to just provide in server configuration additional mail addresses where notification should be sent.

**Comment by pieter-groeneweg** [comment]
Well even if the user can login, what could he possibly do as long as it is not an admin user?

**Comment by TheCelavi** [comment]
Ok, my bad, I didn't know that he can see only assigned server.

Hm... but it seams that there is no fine granulation of permission, like:

1. User X -> see server
2. User X -> notify 
3. User Z -> notify

That could be useful. But it is not something that is a blocker, and should be in new ticket. Closing this one, thank you for your time.
