### ISSUE TITLE
phpservermon API

### ISSUE THREAD

**Issue by skydiver** [phpservermon/phpservermon#438]
Hello,

I took the API from **asuknath** and made compatible with PHP7 (functionalities remains the same).

The mobile apps works great.

If anyone is interested, here is the repo: https://github.com/skydiver/PHP-Server-Monitor-API

**Comment by vus520** [comment]
great. I need this api very much.

**Comment by 2ge** [comment]
thanks so much

**Comment by sadortun** [comment]
Hi @skydiver  Can you submit a PR ? I'll merge this in PSM it's a well wanted feature !

Thanks !

**Comment by skydiver** [comment]
@sadortun sure (will take a few days)

**Comment by mklemme1** [comment]
Nice work, @skydiver !

 Could you add an API call to update all servers?

I cannot set up cron jobs and would like to call this API from my other home system

**Comment by katsil** [comment]
Can someone help me please with app issue "Connection Error"?
