### ISSUE TITLE
DATA BASE BUILD

### ISSUE THREAD

**Issue by jonasyd** [phpservermon/phpservermon#439]
How does phpservermonitor install the database? I cant complete the installation ...
can you help me? Or provide the creation script?

tanxs

**Comment by pieter-groeneweg** [comment]
Did you follow the installation instructions? You need to have the database setup first.

**Comment by Nailzy** [comment]
As stated you need an appropriate MySQL database setup first. The installation only creates the tables within the database configured against your web server.

**Comment by jonasyd** [comment]
Hello, the problem has already been solved first create the database so that the tables can be created.
A new question is .. which collation should it be?

**Comment by TimZ99** [comment]
All the tables are utf8_general_ci, only the users_servers table is latin1_swedish_ci. Don't know if this by mistake or...
