### ISSUE TITLE
why last check  don't change when cron is enabled

### ISSUE THREAD

**Issue by dimitrilongo** [phpservermon/phpservermon#442]
Hi

First time I install phpservermon, all is working well, I set the cron job on my centos 7 server, for testing purpose i check status every minute, so i put one website online, wait until cron do the job, no issue website turn to red (auto refresh), i put the server online again, website turn to green. So all is working. 
But i don't understand why last check  don't change it says 2 hours ago, and 2 hours ago correspond to a manuel check in phpservermon config i did.

So it's a normal behavior or something is wrong?

Thanks

**Comment by pieter-groeneweg** [comment]
something is wrong...

First: A once each minute check is too short a time. If previous cron is not finished yet, a new one cannot start. If you have a series of websites and services to check, it will take some time. By default, each check has max of three attempts. So when you set the max timeout to default 10 seconds, a check can take half a minute before it returns a service down. Now assume you have more than one service to check.. let's say 10.. two failing services will block your next checkup.

Second:  A time difference of two hours? Are you sure it is a manual check and not a timezone setting gone wrong on your server?

**Comment by dimitrilongo** [comment]
thanks for answers, i will check time zone and change check to every 15 mn to see what happen

**Comment by TimZ99** [comment]
I assume it's working. Feel free to reopen if it didn't.
