### ISSUE TITLE
Cronjob  - Unable to establish database connection...

### ISSUE THREAD

**Issue by Potomarus** [phpservermon/phpservermon#446]
Everything is fine, but I have a problem with the cron job.

I can´t run the status.cron.php on my shell. Everytime I get this error: 

Unable to establish database connection...

Did you have the same problem?

PS: Can please someone explain where is the Update-Function? Maybe I can build a new scipt.

**Comment by pixeline** [comment]
Same issue here.

`php /home/user/domain.tld/public/phpservermon/cron/status.cron.php`return "unable to establish database connection"

**Comment by pixeline** [comment]
Solved it: after updating php, I was missing latest php_mysql and php_curl libraries.
