### ISSUE TITLE
email should also be sent to specific email

### ISSUE THREAD

**Issue by naqirizvi** [phpservermon/phpservermon#448]
Hi,
This is not the issue but I just want this feature to be introduced.
Every Website that is added should also include an email field that can also be informed about the site offline email notification.

currently it is only sending emails to the user email that has created the account and added the website.

**Comment by TimZ99** [comment]
Find support and someone that's willing to add this 😉.

**Comment by naqirizvi** [comment]
never mind I did that on my own :D
