### ISSUE TITLE
Feature Request: Guest or user account to have no authentication needed

### ISSUE THREAD

**Issue by mattspulse** [phpservermon/phpservermon#449]
Is there any way to make it so the user account doesn't need to authenticate? I already have authentication on an apache server website and I just want to display the status of servers in phpservermonitor rather than have users log in again. 

If anyone can suggest any modified code to make this happen it would be greatly appreciated. 

Thanks guys, I love the new update!

**Comment by sadortun** [comment]
Duplicate #51
