### ISSUE TITLE
AWS Simple Notification Service (SNS)

### ISSUE THREAD

**Issue by llwp** [phpservermon/phpservermon#450]
Looking around, I don't see any specific references to AWS SNS.
I did find AWS SES in issue #156 which is a related service.

Just checking to see if there is any interest in this capability?
I was looking at the code and there are several places it could fit. (ie src/psm/Txtmsg)
Open to thoughts...

Thanks..

**Comment by sadortun** [comment]
Yes, your PR would be welcomed !
