### ISSUE TITLE
Clickatell

### ISSUE THREAD

**Issue by helmi1987** [phpservermon/phpservermon#451]
with a new clickatell account is it not possible to send sms.

**Comment by mattronix** [comment]
Hi, 

I seem to have the same problem any way i can help with solving it?

**Comment by realitygaps** [comment]
I've figured out what to change, the following is from our (working) phpservermon:

`                $result = $this->_auth_https_post('https://platform.clickatell.com',
'/messages/http/send',
                        '?apiKey=' . 'YOUR API KEY HERE' .
                        '&to=' . $recipients .
                        '&content=' . substr(urlencode($message), 0, 153)
                );
`

instead of the current $result= in the file psm/Txtmsg/Clickatell.php should make it work.

I think you need to also ensure username and password on the SMS configuration page in phpservermon config are both empty. (API key gets used instead of username/password anyways)

**Comment by helmi1987** [comment]
YES did it work. Thanks very much

**Comment by helmi1987** [comment]
If I want to send multiple users a sms at error. This does not work

**Comment by realitygaps** [comment]
I think i figured this out, use the following block:

```
                foreach($this->recipients as $recipient){
                $result = $this->_auth_https_post('https://platform.clickatell.com', '/messages/http/send',
                        '?apiKey=' . 'ZXytEZ5eRr6a01I1EwS1gA==' .
                        '&to=' . $recipient .
                        '&content=' . substr(urlencode($message), 0, 153)
                );
                }
                return $result;
```

should fix the issue (works here with multiple users now)

**Comment by realitygaps** [comment]
I think i figured this out:
```

                foreach($this->recipients as $recipient){
                $result = $this->_auth_https_post('https://platform.clickatell.com', '/messages/http/send',
                        '?apiKey=' . 'YOURAPIKEYHERE' .
                        '&to=' . $recipient .
                        '&content=' . substr(urlencode($message), 0, 153)
                );
                }
                return $result;
```

works for me (multiple users)

**Comment by TimZ99** [comment]
🤔 only get this working when I sent a test message.

**Comment by TimZ99** [comment]
c3751e7 & a496874
