### ISSUE TITLE
Advice on re-skinning UI

### ISSUE THREAD

**Issue by shwashbuckle** [phpservermon/phpservermon#452]
Hi,
Has anyone attempted to re-skin the default HTML UI for PHP Server Monitor and if so could provide any advice on doing this?

Looking at some pretty cool looking Bootstrap based themes and wondering if these could be integrated with PSM?
http://webapplayers.com/inspinia_admin-v2.7.1/metrics.html
http://webapplayers.com/luna_admin-v1.3/metrics.html

Thanks,
Leigh.

**Comment by Masriyan** [comment]
btw the engine for template use twig , did u have tried to make the concept view with twig ?

**Comment by TimZ99** [comment]
Looking at how it's currently done and some copy paste helps a lot 😜
