### ISSUE TITLE
Cron never update server status

### ISSUE THREAD

**Issue by Havouza** [phpservermon/phpservermon#453]
I have activated a cronjob 15 min but the server status never gets updated.
I have a VPS on Centos7 with Plesk control panel. It say the cron is correct

**Comment by pixeline** [comment]
Did you check your cron.log file ?

Also: try launching the command manually via the Terminal, errors will appear : 
ex: `php /home/domain.com/public/phpservermon/cron/status.cron.php`

**Comment by TimZ99** [comment]
More information was requested but never came. Feel free to reopen if you have the additional info.
