### ISSUE TITLE
Status for type: "ping" shows as half-html

### ISSUE THREAD

**Issue by davehamer** [phpservermon/phpservermon#457]
When clicking into a server's record when being monitored by ping, the status shows as per below screenshot:
http://gosub.me.uk/7mo17

"Failed to parse address &quot;<IPADDRESS>&quot;

This does not seem to affect functionality and appears to be cosmetic only.
For reference, this is what a service looks like: http://gosub.me.uk/0q8mq

**Comment by davehamer** [comment]
Further comment: This is from the database - the column "error" includes this text for all ping tests
http://gosub.me.uk/5hg8l

**Comment by davehamer** [comment]
I think this is an easy fix:
https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Util/Server/Updater/StatusUpdater.php#L153 - this line has been left in from the other two types of checks. Simply delete it.

https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Util/Server/Updater/StatusUpdater.php#L163 - Add a description for failed to "Ping timeout" or similar?

**Comment by sadortun** [comment]
Can you submit a PR ?

**Comment by TimZ99** [comment]
Fixed wrong ping error (79742fe).
