### ISSUE TITLE
Telegram notifications

### ISSUE THREAD

**Issue by buzzard10** [phpservermon/phpservermon#459]
Hello
is there any chance to create notification about servers to Telegram chanel?

**Comment by phpfs** [comment]
Hi :)

I'd think that this would be not too difficult to implement.

We'll need a setting where the user drops the bot's token and on the profile page an input to paste the users chat_id. There are many bots out there to do that :) (@cid_bot)

Maybe we can register it as an sms service provider? (although this would be quick and dirty :)

I'll have a look at that when I have time :)
Greets, phpfs

**Comment by buzzard10** [comment]
Thanks for your reply :) 
I really want to implement this because Telegram have fantastic notifications 😄 
Give me a tip when you have something new :D

**Comment by TimZ99** [comment]
First steps are made #468 😄

**Comment by buzzard10** [comment]
Thanks! 
Can i download it and test ? :D

**Comment by TimZ99** [comment]
👍 
Use @ChatIDBot to get your chat_id. 
@cid_bot wasn't working for me.

**Comment by TimZ99** [comment]
Big steps are made today.

- [x] UI (Same as Pushover)
- [x] Install.php (add column in sql tables)
- [x] Dutch translation
- [x] Added Telegram to the backend (not working 😢)

The backend and the translations take some time.
 If somebody want's to help, feel free: [PSM > Telegram](https://github.com/TimZ99/phpservermon/tree/telegram) . 
At this moment I have only made the Dutch translation, English translation will be there soon. 😄

**Comment by buzzard10** [comment]
Hi :) 
Thanks for update. I can help you with Polish language, but tell me where i have file to translate/which words i need to translate 😄 

Can you also tell me how i can add telegram to my instance. 👍

**Comment by gitty8** [comment]
How status here?

**Comment by phpfs** [comment]
@TimZ99 @cid_bot is fixed and working again - see github.com/phpfs/cid_bot

**Comment by TimZ99** [comment]
@phpfs Thanks 👍🏼

**Comment by buzzard10** [comment]
Hmmm i don't know why, but I can't implement this in my version of PMS 😢

**Comment by buzzard10** [comment]
I also tried to install new instance from [here](https://github.com/TimZ99/phpservermon/tree/telegram)
But i can't finish installation because after i try to configure new user i see error 500.

**Comment by TimZ99** [comment]
[Ready to implement](https://github.com/TimZ99/phpservermon/tree/Telegram-notifications)
Working on the translations right now. Help is always appreciated 😉.

Will update this list:
- [x] bg_BG
- [x] cs_CZ
- [x] da_DK
- [x] de_DE
- [x] en_US
- [x] es_ES
- [x] et_ET
- [x] fa_IR (English)
- [x] fi_FI
- [x] fr_FR
- [x] it_IT
- [x] ja_JP (English)
- [x] ko_KR (English)
- [x] nl_NL
- [x] pl_PL @emillod I've put the English translation in the file. Just search for 'Telegram' .
- [x] pt_BR
- [x] ru_RU (Partly English, Partly  translated)
- [x] sk_SK
- [x] si_SI
- [x] sv_SE
- [x] tr_TR
- [x] vi_VN
- [x] zh_CN (Partly English, Partly  translated)

**Comment by TimZ99** [comment]
> is there any chance to create notification about servers to Telegram chanel

For the Telegram notifications you're required to make a bot. In this version of the code you can only receive messages in the private chat with the bot, not in a channel. I will look if I can add this also.

**Comment by phpfs** [comment]
I agree with @TimZ99 about channels - but you can send messages to groups as they seem to have normal chatIDs at first sight. Just add @cid_bot to your group and you will receive your chatID like you normally would. Only the dash before the chatID differs from normal Chats...
I will look at this later this day!

EDIT: Group chatIDs are all negative numbers compared to normal chats which have positive chatIDs!
This shouldn‘t make any difference for implementation in phpservermon.

Greetings, phpfs

**Comment by TimZ99** [comment]
The chatID variable is a string so a negative number shouldn't be a problem.

EDIT: Checkt and this isn't a problem.
Will search in the API documentation for a way to send messages to a channel.

**Comment by TimZ99** [comment]
Finally found a simple way to get the chatID from the channel. 

Go to: https://api.telegram.org/bot `[replace with bot token]` /getUpdates
The chatID will be specified as id.
Add your bot as an admin to the channel and fill in the chatID on your profile.

I don't know if I add this instruction, translating is a lot of work.

**Comment by phpfs** [comment]
Because every user needs to create a new telegram bot - I suggest the following:

Make the bot which a user creates able to answer to basic questions like:
/status - return the status of all servers
/online - only return all Servers that are online
/offline - ... that are offline
/details `<id>` - get details like status, speed, last_check for a specific server

This would be done by using telegram web hooks:
On the settings page, we add a "Set Webhook" button which will POST the Webhook-URL "https://mymonitor.me.com/phpservermon/webhooks/telegram.php" to the Telegram Bot API.
On every new message to a users bot, telegram calls this URL. Now, we can download all new messages from the API and react based on what a user sends. Authorization would be handled via a users chatID which is connected to a phpservermon-account. Based on these permissions, we will answer as requested or 401.
In this case, I suggest to use irazysed`s php library https://github.com/irazasyed/telegram-bot-sdk for easy use of the telegram bot API.

I think this would be a nice addition :)  -  but also a lot of work :/

Greetings, phpfs

**Comment by TimZ99** [comment]
It’s probably a lot of work, but will look into it after I finish the last translations.

**Comment by TimZ99** [comment]
Wow juli 26, that's a long time ago. Hope I can find some time this week to finish. 
@emillod did you find time to translate?

Current status:
- [x] Telegrambot can send messages on status change.
- [x] Translated in most languages.
- [x] Working on web hook / receiving messages from telegram and respond with the answer.
- [x] Custom login created for the bot so the bot can respond with data from the servers.
- [ ] The next problem 😋

**Comment by buzzard10** [comment]
@TimZ99 hello! Woow 👍 Great job! 
Here You have file with Polish Translate :) 
[pl-telegram.zip](https://github.com/phpservermon/phpservermon/files/1610793/pl-telegram.zip)

**Comment by nalakawula** [comment]
I follow this:

How do I setup Telegram?

A few steps are required to get Telegram notifications working. You need to be an administrator for this part.

    Go to @botfather (https://t.me/BotFather) and type /start .
    Type /newbot and give your bot an unique name.
    Save the API token.

but got:
 Unable to send test notification: no chat id found in your profile.

**Comment by nalakawula** [comment]
Ah got it, so i must put my chat id into my profile page

**Comment by petrk94** [comment]
Small improvement:
You must put "my chat id" into your profile at PHP Servermonitor.
I really had to search what that meant, I thought I had to save it in the Telegram settings or in the telegram app. I think this can be improved in the documentation or by showing the screen in the docs which form is meant.
