### ISSUE TITLE
Can't save anything when SSL is on

### ISSUE THREAD

**Issue by ryannix123** [phpservermon/phpservermon#462]
Hello,

I'm having a strange issue where if I'm in the webui and I try to make any chances, I get a warning: "This form will be sent in a way that is not secure. Are you sure you want to send it?" and if I click "Ok" the data never saves. If I remove the .htaccess file that forces the SSL redirect, I can save changes or add new system to monitor without issue. Is there a better way for me to force using SSL with PHPServerMon?

My .httaccess file:

RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R,L]

Thanks,

Ryan

**Comment by mtahiue** [comment]
in config.php add

define('PSM_BASE_URL', 'https://YOURDOMAIN');

will work then ...

**Comment by ryannix123** [comment]
That worked. Thank you!

**Comment by cytracon** [comment]
Hi, same problem here, but doesn't work with the config.php addition with version 3.2.0.
