### ISSUE TITLE
Please add lang 'ja_JP' (Language file is ready)

### ISSUE THREAD

**Issue by acrylic-style** [phpservermon/phpservermon#465]
I am Japanese.
I want to use language 'Japanese' but it is not found.
So I created a language file myself.

I have already tested this file.

[php-server-monitor-ja_JP.zip](https://github.com/phpservermon/phpservermon/files/981592/php-server-monitor-ja_JP.zip)

**Comment by vus520** [comment]
I suggest you to submit a request.
If you don't know how to submit PR, I can help you do this.
