### ISSUE TITLE
I am not able to ping a local ip

### ISSUE THREAD

**Issue by robinblogspot** [phpservermon/phpservermon#467]
![untitled](https://cloud.githubusercontent.com/assets/5363337/26022345/78b822b2-37c0-11e7-9afa-f321b3d3c07b.png)

I am able to ping with windows cmd
but not able to ping with phpservermonitor

**Comment by theknigge** [comment]
same Problem here 👎 :-(

**Comment by TimZ99** [comment]
79742fe
