### ISSUE TITLE
StatusUpdate for Ping mark ALL servers down

### ISSUE THREAD

**Issue by tgrignon** [phpservermon/phpservermon#472]
I recently create a CentOS 7 server rather than my Windows server for the application, I think the Ping not working well with Windows.

Now the Ping working fine with CentOS but when the cron start and check if one of my server is down he mark ALL my servers down. Each one with different IPs and different name. I try one server at a time and all turns red.

I receive the maila fter that all my servers down.

**Comment by tgrignon** [comment]
When the cron start, there is no problems. Only when I click on "Update" directly on the webpage.

**Comment by TimZ99** [comment]
Is this still a problem?
