### ISSUE TITLE
Slack Notifications

### ISSUE THREAD

**Issue by phpfs** [phpservermon/phpservermon#473]
Hi!

As a telegram integration is currently made, I'd like to suggest Slack as well.

Integration won't be too difficult as it is as simple as calling a webhook.
Still, it is different from SMS or Pushover as you write to a channel from a specific team, not directly to a user.

To implement, I suggest to create it as a standalone service like Pushover with the two settings "webhook" and "channel(s)" per user on their notifications page.
A system wide setting (besides maybe an activation-toggle) therefore wouldn't be necessary.

Greetings,
phpfs

**Comment by versavius** [comment]
Interesting idea so would this work for example website X goes offline, so standard alert on phpservermon of a nice red alert and then a message posted to a specific slack group or set of users saying its gone offline? Or maybe stating every alert?

**Comment by TimZ99** [comment]
#255
