### ISSUE TITLE
Small username validation bug

### ISSUE THREAD

**Issue by djmixman** [phpservermon/phpservermon#478]
There seems to be a small problem with the username validation during setup. During setup, I was able to create a username with a dash it its name "user-name" however when I went to make changes to my profile after everything was installed the validator would not let me save it because I had a "-" in my name.

**Comment by Masriyan** [comment]
yeah i also make user with "-" and no validator works for it , thanks for issues it first

**Comment by TimZ99** [comment]
[Validation added](https://github.com/TimZ99/phpservermon/commit/e590022cf89ea46d70220eaa81662aa3089c1e77). Only need to change the error messages.
