### ISSUE TITLE
License

### ISSUE THREAD

**Issue by buzzard10** [phpservermon/phpservermon#483]
Can i remove note about PHPServer from footer?

**Comment by TimZ99** [comment]
I can't tell you the answer to this question, did you read the [license](https://github.com/phpservermon/phpservermon/blob/develop/LICENSE)?

**Comment by TimZ99** [comment]
A copy of the license and copyright notice must be included with the software. 
I think you can count the footer as copyright notice, so that’s a no I I guess.

**Comment by buzzard10** [comment]
Thanks for your reply :) 
PHPServerMon is based on GPL license, right? So i must add information about license for example in files, but do i need to put information in footer?

**Comment by TimZ99** [comment]
Here is a link to the license. https://github.com/phpservermon/phpservermon/blob/develop/LICENSE

```GNU General Public License v3.0```

I need to say that I'm in no way a legal expert. Maybe this link will help you: http://www.gnu.org/licenses/gpl-faq.html

Here are a few links to interesting questions:
- http://www.gnu.org/licenses/gpl-faq.html#RequiredToClaimCopyright
- http://www.gnu.org/licenses/gpl-faq.html#NoticeInSourceFile
