### ISSUE TITLE
not able to ping ip

### ISSUE THREAD

**Issue by inkrement** [phpservermon/phpservermon#488]
I tried to setup a new (working) server, but it appears to be offline. ping in the console works and apache's error.log does not show errors.

**Comment by baur** [comment]
same problem, ping not works

**Comment by vus520** [comment]
Can you support some more details?

**Comment by inkrement** [comment]
What do you need? I really would like to provide some additional information, but I get no response - it simply does not work and there are no error messages or logs. I run a fresh php7 installation on ubuntu 16.04.

**Comment by inkrement** [comment]
ok, it seems to work, but the response is quite strange:

1) the status is "ok", but there is a error message, which is weird!
![screen shot 2017-07-08 at 11 56 28](https://user-images.githubusercontent.com/604528/27984382-235feb1a-63d5-11e7-86f9-87793b909265.png)


2) The daily plot shows multiple points, but the hourly just one. the cron triggers the status.php every 5 minutes...

![screen shot 2017-07-08 at 11 59 03](https://user-images.githubusercontent.com/604528/27984372-01dfbe16-63d5-11e7-89ec-76bb770bd5a1.png)
![screen shot 2017-07-08 at 11 59 19](https://user-images.githubusercontent.com/604528/27984373-02068cf8-63d5-11e7-9aa8-01bfb566c6da.png)

**Comment by bpodwinski** [comment]
Crontab error debug:

`Fatal error: Call to undefined function psm\Util\Server\Updater\socket_create() in /var/www/html/src/psm/Util/Server/Updater/StatusUpdater.php on line 154`

For fix enable Socket for php:

`apt install php-net-socket`

**Comment by inkrement** [comment]
It seems to work, but some plots are still "missing". I see the results if I click on day or week, but nothing on hourly level (but the daily plot indicates that there are multiple measurements each hour). So this is not a measurement error, this is just a visualisation problem.

However, if php-net-socket is is an requirement it should be checked on installation or mentioned somewhere. In my case it was not installed and it was not obvious that it is required..

**Comment by TimZ99** [comment]
Fixed wrong ping error (79742fe). 
Updating ping requires root at this moment. #576 more about this.
