### ISSUE TITLE
Undefined constant PSM_DB_PORT

### ISSUE THREAD

**Issue by mudolux** [phpservermon/phpservermon#492]
Hello,

there is an undefined constant.

Warning:  constant(): Couldn't find constant PSM_DB_PORT in /var/www/.../phpservermonitor/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php on line 417

(PHP 7.1.7)

**Comment by TimZ99** [comment]
Is this everything the warning had to say? 
Because there are no PSM variables in the vendor directory.

**Comment by TimZ99** [comment]
Feel free to reopen with a response.
