### ISSUE TITLE
NEW SMS Integration

### ISSUE THREAD

**Issue by buzzard10** [phpservermon/phpservermon#493]
Hello 
Is there any chance to add new integration SMS? 
I mean SMS provider from Poland. Here you have any programmers informations:
https://en.serwersms.pl/integrations/for-programmers

**Comment by TimZ99** [comment]
There is! 😄
Maybe you can find someone that's willing to implement this.

**Comment by wardpieters** [comment]
Hi @emillod,
Do you still need this SMS Gateway? If not, please close this issue. Otherwise, let me know and i will try my best.

**Comment by TimZ99** [comment]
Haha that's a no

**Comment by buzzard10** [comment]
Haha you want my reply, so... :D 
It's not urgent.. :)
