### ISSUE TITLE
CRON job for Windows?

### ISSUE THREAD

**Issue by seanvree** [phpservermon/phpservermon#498]
Love the application guys!

Got the application running on Windows 10 behind IIS. 

Question - what's the best way to config a CRON job for windows?

THX!

**Comment by seanvree** [comment]
Edit:  Figured this out for windows, not sure if you want to include this in your WIKI or Docs:

1.  Create the following file " cron.vbs " in \phpservermon\cron\
a.  Obviously, change the values below inside of the " < > "
```
Set WinScriptHost = CreateObject("WScript.Shell")

WinScriptHost.Run "c:\<PathToPHP>\php.exe C:\<PathToPhpserverMon>\phpservermon\cron\status.cron.php --uri=https://<yourdomin>/phpservermon/", 0

Set WinScriptHost = Nothing
```

2.  Create a basic windows task:  Settings:
a:  General: ENABLE  "run when user is logged on or not"
b.  Triggers:  Daily, Repeat every <x> minutes / hours, ENABLED
c.  Actions:  program script:  c:\<PathToPHPservermon>\phpservermon\cron\status.cron.php

3.  Enable task. 

Done. 

Screenshot:

![image](https://user-images.githubusercontent.com/8906637/29237198-1d29658c-7ece-11e7-9336-94f682201d1c.png)

**Comment by TimZ99** [comment]
Send a Pr, think it would be nice to have it in the [docs](https://github.com/phpservermon/phpservermon/blob/develop/docs/install.rst#setting-up-a-cronjob). 

```
Windows
-------

1. Create the following file `cron.vbs` in \phpservermon\cron

2. Add the following to the file::

     Set WinScriptHost = CreateObject("WScript.Shell")

     WinScriptHost.Run "c:\<PathToPHP>\php.exe C:\<PathToPhpserverMon>\phpservermon\cron\status.cron.php --uri=https://<yourdomin>/phpservermon/", 0

     Set WinScriptHost = Nothing

3. Create a basic windows task: 
Settings:

- General: ENABLE "run when user is logged on or not"

- Triggers: Daily, Repeat every minutes / hours, ENABLED

- Actions: program script: c:<PathToPHPservermon>\phpservermon\cron\status.cron.php

4. Enable task.
```

**Comment by CMircea** [comment]
Why the indirection through VBScript? Can't you just run PHP directly from the task action with the arguments?

**Comment by mooleshacat** [comment]
I agree, you should be able to run it directly with a task...
