### ISSUE TITLE
history graph not working?

### ISSUE THREAD

**Issue by Eddy2909** [phpservermon/phpservermon#499]
![sadsadsadsadafa](https://user-images.githubusercontent.com/12877411/29166949-bedd5480-7dc8-11e7-9f21-e72011fe6c8a.JPG)
I dont see any graphs in the historie..

**Comment by jckruger** [comment]
I have the same issue even from a new install. The database table is bare. The structure seems to be there but no data.

**Comment by jckruger** [comment]
Just realised that it takes a week for the archiving bit to kick in and start showing some data. Just wait a week and see what happens
![image](https://user-images.githubusercontent.com/20898927/30406218-d706d442-9933-11e7-866f-1193081258b1.png)
