### ISSUE TITLE
allowed chars in username: Setup tool allows more chars than profile editor

### ISSUE THREAD

**Issue by stefan-muc** [phpservermon/phpservermon#503]
Setting up PHP Server Monitor via install.php allows adding an user with a dot ».« in username.
During later edit of my profile, I can't save it anymore, because the error message tells me that a dot is not allowed: _The username may only contain alphabetic characters (a-z, A-Z), digits (0-9) and underscores (_)._

I would like to see the dot being allowed also on user profile, and having the same validity check in install tool so there's no surprise on later profile edit.

**Comment by TimZ99** [comment]
#478 I will PR the Validation check soon, will look in to adding a dot.

**Comment by TimZ99** [comment]
[Validation added](https://github.com/TimZ99/phpservermon/commit/e590022cf89ea46d70220eaa81662aa3089c1e77). Only need to change the error messages.
