### ISSUE TITLE
upgrading from 3.1.1 to 3.2.0 makes servers dissappear.

### ISSUE THREAD

**Issue by pieter-groeneweg** [phpservermon/phpservermon#511]
I upgraded a "running backup" of 3.1.1 to 3.2.0 according to the (old) instructions.
(copy and replace files but config.php, follow instructions.....)

It appeared to work, but my monitored sites and servers no longer show up in phpservermon. 
As a proof they are still there I can only see it has something on these sites and servers as it shows in the Users Tab, column "servers".
Also my Pushover is flooded with server xxx is DOWN messages (so it appears to do something, but not doing not right as all seems to be up).

Anyone?

**Comment by TimZ99** [comment]
Have you ran the install process after replacing the files? (install.php).
Or
Have you made any changes to 3.1.1 or to the database that could have broke the program?

**Comment by pieter-groeneweg** [comment]
As I said, followed instructions, no it is not a customized version.
No error messages in the logs either.

**Comment by TimZ99** [comment]
Do you still have this problem?
