### ISSUE TITLE
Unable to choose port for website

### ISSUE THREAD

**Issue by sgtcoder** [phpservermon/phpservermon#513]
The system forces you to use website feature on port 80. All my sites are port 443/SSL. Please see screenshot: http://prntscr.com/gkw6x1

The service feature does not work either.

**Comment by AHTOLLlKA** [comment]
+1, how i can setup to chek my website with SSL at 443 port
connect + find string in raw html

**Comment by TimZ99** [comment]
It does show a port on ?&mod=server (https:// 443, http:// 80 and rdp:// 3389), but the website check does **not** use the port.
Service does use the port, but this does not always work for websites. My own website gives a 400 error if I put :443 behind the url. It all depends on the way you have your website setup.

 If you're still having trouble with this, maybe getting the latest update will fix it. There have been some changes to the website check.

**Comment by usmanranatig** [comment]
there must be an option to check different application working on http but on different ports like portainer or phpmyadmin , they work on different port then 80 and its good but i want to mon my phpmyadmin also
