### ISSUE TITLE
Email/SMS/Pushover Do not work

### ISSUE THREAD

**Issue by sgtcoder** [phpservermon/phpservermon#514]
The notification system to push email/SMS/Pushover do not work. The test does work, but nothing else.

**Comment by swiffer** [comment]
Same here is another cron Job needed?

**Comment by swiffer** [comment]
it is working, you need to make sure you defined at least one user in server settings under premissions tab. that solved the issue for me!

@sadortun think that can be closed.

**Comment by sgtcoder** [comment]
@swiffer Thank you! This ended up working.
