### ISSUE TITLE
Posting to Slack channel?

### ISSUE THREAD

**Issue by ryannix123** [phpservermon/phpservermon#517]
Any plans to add Slack integration?

**Comment by leonardpg** [comment]
I added a Slack integration to my local. It uses the incoming message hook url (See api.slack.com), and it posts a message to a channel in our slack with the '@everyone' tag so team members will see a notification even if they don't have slack open on their device. I still have a couple issues to work out, but I would like to contribute the feature to the project if they will have it.

**Comment by ryannix123** [comment]
@leonardpg that would be fantastic.

**Comment by varunchandak** [comment]
@leonardpg Is the Slack integration working for you ?
