### ISSUE TITLE
 Failed to parse address &quot;8.8.8.8&quot; 	

### ISSUE THREAD

**Issue by rAmfu** [phpservermon/phpservermon#524]
I can't ping and server adress.
**EDIT:**
When cronjob is working status is on, but error still on server name: Failed to parse address &quot;8.8.8.8&quot;
Manual update = server down O.o

**System:** Debian 9
**PHP Version 7.0.19-1 -m:**
[PHP Modules]
bz2 calendar Core ctype curl date dom exif fileinfo filter ftp gd gettext hash iconv json libxml mbstring mcrypt mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql Phar posix readline Reflection session shmop SimpleXML sockets SPL standard sysvmsg sysvsem sysvshm tokenizer wddx xml xmlreader xmlwriter xsl Zend OPcache zip zlib

[Zend Modules]
Zend OPcache

**apt install php-net-socket** done, but not fix my problem ;/

**Comment by TimZ99** [comment]
This line causes this specific error: https://github.com/phpservermon/phpservermon/blob/fc4ffd6b2f6611cb983d2adf57409d53e4e17f48/src/psm/Util/Server/Updater/StatusUpdater.php#L153

Ping doesn't work because you need root access to use SOCK_RAW (on Unix). 
This issue can be continued on #576.
