### ISSUE TITLE
Possible To have public status page

### ISSUE THREAD

**Issue by decentguy49** [phpservermon/phpservermon#525]
Is it possible to have a front page which shows all websites and there status, I mean to check status i have to login and then it shows all, but is it possible to have look without logging in?

**Comment by masonr** [comment]
Not currently supported, but you can modify some of the PHP code to enable this as a workaround:
https://sourceforge.net/p/phpservermon/discussion/845823/thread/f1b2e4ff/

**Comment by TimZ99** [comment]
#368
