### ISSUE TITLE
config - email settings - test fails

### ISSUE THREAD

**Issue by pieter-groeneweg** [phpservermon/phpservermon#526]
I have a new install of phpservermon on debian9/webmin/virtualmin

Upon testing the email settings for the notifications with SMTP enabled, the test fails with:

`Error in email sending: The following From address failed: address@domain.com : Called Mail() without being connected`

The mail server is on another remote machine.
I first though it to be a firewall or port forwarding issue. But another application on the same server has no problems sending email with the same method and credentials. 

Any thoughts?

**Comment by hiagodotme** [comment]
Have you tried a machine tellnet in which is the phpservermon application for the SMTP it is using?

**Comment by TimZ99** [comment]
Due to the lack of response, I assume that this problem has been resolved.
