### ISSUE TITLE
Possible to remove port on list view?

### ISSUE THREAD

**Issue by matroidde** [phpservermon/phpservermon#531]
Hello, 

is it possible to remove the port field in the server list view..
Look at the screenshot:
![jojo](https://user-images.githubusercontent.com/31346301/32603651-c2e92dd2-c54a-11e7-9e08-e32003342049.png)

**Comment by TimZ99** [comment]
No. Why would you remove it?

**Comment by TimZ99** [comment]
Please reopen if you have the answer.
I’m wondering why you would remove it.
