### ISSUE TITLE
Problème avec le service PING avec PHP Server Monitor 3.2.0 - Problems with PING service

### ISSUE THREAD

**Issue by Philippe38** [phpservermon/phpservermon#534]
Bonjour,

Je me retrouve dans l'impossibilité d'activer le service "PING" sur la console PHP Server monitor qui ne fonctionne pas.
Quand je fais un test, voici en gros la réponse que j'obtiens 

Etat "Off" filed to parse adresse &quot;192.168.1.130&quot  ---> alors que le service est bien sur "surveillance activée". Je n'arrive pas à comprendre pourquoi les "&quot" sont ajoutés à l'adresse IP.

Merci de votre aide.
Cordialement.
Philippe

_----- English translation  - added by TimZ99 -----_
Hello,

I find myself unable to activate the "PING" service on the PHP Server monitor console that does not work.
When I'm doing a test, here's basically the answer I'm getting

Status "Off" filed to parse address "192.168.1.130 & quot ---> while the service is on" monitoring enabled "I can not understand why" & quot "is added to the IP address.

Thank you for your help.
Cordially.
Philippe

**Comment by mupett** [comment]
Hello, I have the same problem. Any fix or workaround? Database type field seems to be ok with the ping type declared.

Regards
Luca

**Comment by wedge1001** [comment]
Hello, 
I got the same problem. 
It's a fresh installation with a fresh database from the 3.2 version. 

Regards
wedge

**Comment by Philippe38** [comment]
Hello

In fact, after doing some tests, I realized that the BUG only happens when you force the monitor to refresh.

On the other hand, if you let it check normally, the ping responds correctly.

Regards

Philippe

**Comment by wedge1001** [comment]
Okay, 
i've found the problem: 

The code is trying to open a socket connection. 
this will only work if your user, running the php process is allwed to open sockets - which the normal php-user isn't. 
so trying to manually updating the servies within the web-gui will normally fail. 
If you have running a cronjob for the testing it could work. if your cronjob runs as root server the ping will succeed. 

you answer has gotten me on the right track.

I'm not sure if there exists a way to fix this...

**Comment by ghost** [comment]
I have the same problem. Does anyone know how to solve this problem?

**Comment by ntsoaua** [comment]
J'ai aussi le même problème. Merci de nous aider

**Comment by TimZ99** [comment]
Haha okay, my French isn't that good, glad that Google Translate exists 😅. 

There are a few more issues with the ping function. Will look for a solution asap. In the meantime, do some Google searches, maybe you're lucky.

**Comment by C00Lzero** [comment]
@vjdjPL / @ntsoaua 
setup a cronjob which runs as root like written here: 
http://docs.phpservermonitor.org/en/latest/install.html#setting-up-a-cronjob

@TimZ99 
there shouldn't be a solution which would do a real icmp without having root rights, due to the fact, that we are opening a layer3 socket, (fsockopen) 
Perhaps there is something that can be done with the php-user, but that would also be a little bit ugly.

**Comment by ghost** [comment]
@C00Lzero I have configured to as root and it works, but when I use update in panel all servers are "down" and I have an error:  filed to parse address

**Comment by TimZ99** [comment]
@vjdjPL This line causes this specific error: https://github.com/phpservermon/phpservermon/blob/fc4ffd6b2f6611cb983d2adf57409d53e4e17f48/src/psm/Util/Server/Updater/StatusUpdater.php#L153 removing this line will fix the error. 
This small fix will be in the next release.

@C00Lzero Even without the fsockopen you need root. SOCK_RAW need it also (on unix).

This issue can be continued on #576.
