### ISSUE TITLE
Option that no login is needed? (that is no public status page request!)

### ISSUE THREAD

**Issue by mpathy** [phpservermon/phpservermon#539]
We have some TV screens in the company and want to view the status page there. The problem is, we have no possibility to login on those devices.

So my question is: Can I login with some URL parameters, too - or is there an option that there is no login needed overall?

Regarding security: I will of course restrict the viewing of the website to the IP address of the company - inside there its okay when people can go to the site without login needed.

**Comment by jmcgranahan** [comment]
definitely would like to see this

**Comment by mkaand** [comment]
+1 But I think this project doesn't develop anymore.

**Comment by TimZ99** [comment]
@mkaand On the contrary, the project is in active development (again)!

**Comment by TimZ99** [comment]
#368 Feel free to reopen when I'm wrong :smile:!
