### ISSUE TITLE
how to start a cronjob from extern server?

### ISSUE THREAD

**Issue by Berni-MD** [phpservermon/phpservermon#542]
Is it possible to run the cron from an external server as well?
For example about cron-job.org 

Whenever I call the url http: //server-xyz.de/phpservermon/cron/status.cron.php 
via my browser nothing happens

**Comment by pbksol** [comment]
You have to create a little bit php code to be run from the external cron.

Something like… Let's say we call this file "cronexternal.php" and we place it into the root dir.

`<?php
exec ('php ./cron/status.cron.php --uri="http: //server-xyz.de"');
?>`

You can run the cron using http: //server-xyz.de/cronexternal.php. Ok, you're running it in a subfolder, but you get the idea.

Limitation: you need PHP exec rights on your server.

**Comment by TimZ99** [comment]
I assume that you got the answer you were looking for. @pbksol thanks for answering 😄
