### ISSUE TITLE
Docker Version Lacks Cron Setup

### ISSUE THREAD

**Issue by king-jam** [phpservermon/phpservermon#543]
Need to add default cron setup or instructions for cron setup

**Comment by TimZ99** [comment]
Feel free to add this! 👍

**Comment by Foorack** [comment]
@TimZ99 I made a PR for it https://github.com/phpservermon/docker-phpservermonitor/pull/3 :smiley:

**Comment by TimZ99** [comment]
And I reviewed it and requested some changes. Do you have time to fix those?

**Comment by TimZ99** [comment]
Implemented with phpservermon/docker-phpservermonitor@0e945a1
