### ISSUE TITLE
"GET /?&mod=server_update HTTP/1.1" 500 5 "-"

### ISSUE THREAD

**Issue by goodzht** [phpservermon/phpservermon#547]
500 error 
when i visit /?&mod=server_update

**Comment by vletroye** [comment]
Me too. 

It used to work in the past, but I did reinstall it on my NAS (Synology DSM 6.1) and impossible to get the server_update working anymore

I have checked all log files (webserver, php, ...) and tested with apache or nginx without success :(
Curl is well installed (and used successfully by a few other php sites on the same NAS)

I have no idea how to trace & debug this issue...

**Comment by TimZ99** [comment]
Which PSM version are you on?

Did you change anything to the environment, like upgraded PHP version or so?

Have you tried to enable the [debug mode](http://docs.phpservermonitor.org/en/latest/install.html#troubleshooting)?

**Comment by jmcgranahan** [comment]
I'm getting the same with PHP Monitor 3.2.0, with the following errors:

Warning: socket_create(): Unable to create socket [1]: Operation not permitted in /apps/phpservermon-3.2.0/src/psm/Util/Server/Updater/StatusUpdater.php on line 154

Warning: socket_set_option() expects parameter 1 to be resource, boolean given in /apps/phpservermon-3.2.0/src/psm/Util/Server/Updater/StatusUpdater.php on line 155

Warning: socket_connect() expects parameter 1 to be resource, boolean given in /apps/phpservermon-3.2.0/src/psm/Util/Server/Updater/StatusUpdater.php on line 156

Warning: socket_send() expects parameter 1 to be resource, boolean given in /apps/phpservermon-3.2.0/src/psm/Util/Server/Updater/StatusUpdater.php on line 158

Warning: socket_read() expects parameter 1 to be resource, boolean given in /apps/phpservermon-3.2.0/src/psm/Util/Server/Updater/StatusUpdater.php on line 159

Warning: socket_close() expects parameter 1 to be resource, boolean given in /apps/phpservermon-3.2.0/src/psm/Util/Server/Updater/StatusUpdater.php on line 165

**Comment by TimZ99** [comment]
Did you guys check the file permissions?

**Comment by vletroye** [comment]
I have dropped my DB and created a new one, with a dedicated user being granted all rights. I did next copy the sources from v3.2.0 into a new folder in my Synology's web station (using Windows Explorer to drop the files into a folder like \\<Synology>\web\phpServerMon). And now, when I click on "Update" it's just running fine...

The only difference I am aware is that I have updated my DSM... It is now "6.1.5-15254 - update 1". The Web Station is still running apache Server 2.2 with php 5.6.

**Comment by TimZ99** [comment]
`<?php echo phpinfo(); ?>` please check if Sockets Support is enabled.

**Comment by vletroye** [comment]
As far as I am concerned, I have the following module enabled in the php settings used for my website:

- curl
- opensll
- pdo_mysql (this one I am 100% sure I had to enable it to be able to run PhpServerMon properly.)
- phar
- zip

**Comment by TimZ99** [comment]
The monitor uses SOCK_RAW and this requires root access.

**Comment by vletroye** [comment]
That's really wierd because phpServerMonitor runs now fine on my Synology and is using the web 'http' account ?!

**Comment by TimZ99** [comment]
I honestly don't have a better answer right now. You could try to change SOCK_RAW to the non-root required version...

**Comment by vletroye** [comment]
Hey Tim. As far as my case is concerned, as I mentioned above: now, when I click on "Update" it's just running fine... ;) 

So, the problem is gone, possibly since I have updated my DSM or more probably my WebStation (as the  new version come with support for php settings dedicated per back-end servers).

**Comment by TimZ99** [comment]
Whoops, I misread that. 😄
