### ISSUE TITLE
Wrong status checks.

### ISSUE THREAD

**Issue by mkaand** [phpservermon/phpservermon#548]
Hello,

I just wonder, the developer of this project is here or not. Seems nobody is taking care of it. I had some issue with latest release.

I moved my hosting from Windows Server to Linux (Ubuntu Server) Scaleway VDS

My previous hosting was shared hosting but on Windows Hosting PHPServerMonitor was working OK. My new server I set unlimited PHP Max Execution time. I hace more option (CRON) But this script doesn't work properly. I mean my port 83 is OPEN I know I check it but PHPMon does not check my 83 port. I have no idea. Definitely this project needs update. I use PHP 7.0 something.

**Comment by mkaand** [comment]
I understood what is the problem.

I added 6 Service Alarm + 3 Web Check and PHPServerMon all default settings.
Port 83 didn't checked. I disabled all of other alarms then It checked. Looks like something time out. But I couldn't find it.

**Comment by TimZ99** [comment]
Last commit was in may and to be honest I don't think that there will be any activity soon. They need to add a third admin to the project. I mean, I have 3? open pull requests pending, would be nice if they can be merged.

**Comment by mkaand** [comment]
I hope they can be more active in this project. Very nice php script but it needs to fix some problems like UDP port check (I tried udp://ip_addres) For my problem I think it was related with IIS. I am not make sure. I set my IIS port on 83 and phpmon cannot check it.

**Comment by pekiZG** [comment]
@dopeh or @sadortun are you here?
Community would like to keep project alive :)

**Comment by sadortun** [comment]
@mkaand @TimZ99 @pekiZG yes we are still here ! But already very busy, if you find issues feel free to submit PR and keep issues updates. If you are interested in volountering as a maintainer help is welcome !

**Comment by TimZ99** [comment]
@sadortun I did, but I'm waiting for @dopeh s response. Think he is busy because his last reply was two weeks ago. 🤓

**Comment by dopeh** [comment]
Sorry guys, for not responding any sooner. The plan is to get Tim 
involved to keep the project alive, but I just haven't gotten around to 
sorting it out yet. I will get back to you Friday at the latest, Tim.

**Comment by TimZ99** [comment]
:+1:

**Comment by TimZ99** [comment]
@mkaand does everything work when you’re not checking an IIS port?
If so, do you have a solution for the problem?

**Comment by mkaand** [comment]
@TimZ99 It seems OK now. I changed my server's PHP settings (time out settings) Now phpservermon checks perfectly but still UDP checks has a problem: Check this post: https://github.com/phpservermon/phpservermon/issues/495
