### ISSUE TITLE
FreeMobileSMS : Bug when error sending

### ISSUE THREAD

**Issue by ghost** [phpservermon/phpservermon#550]
Hi, 

On the file FreeMobileSMS.php (l.43), $message must be encoded :  
`$message = urlencode( $message );`
`curl_setopt($ch, CURLOPT_URL, "https://smsapi.free-mobile.fr/sendmsg?user=$this->username&pass=$this->password&msg=$message");`
Otherwise, the SMS is not sent
Thanks

**Comment by TimZ99** [comment]
Thanks :smile: ! Could you send a PR please.

**Comment by TimZ99** [comment]
Ehm how do I get an API key, my French isn't that good.

**Comment by ghost** [comment]
Hi :-)

Sorry for my response time and poor level of English.

Unfortunately, the Free SMS API is reserved for Free mobile clients.

This is what I'm trying to explain in my other PR (https://github.com/phpservermon/phpservermon/issues/551), the Free API can only be used by the owner of the number.

Like, for example: 
https://smsapi.free-mobile.fr/sendmsg?user=FREE_ID&pass=PASS_FREE&msg=MY_MESSAGE
can only send an SMS to the user ID_FREE, and on no other mobile phone
