### ISSUE TITLE
FreeMobileSMS : settings per user

### ISSUE THREAD

**Issue by ghost** [phpservermon/phpservermon#551]
FreeMobileSMS plateform enable you to send sms for only one mobile phone number.

You need to set the API connexion parameters for each user, and not as a global configuration.

**Comment by TimZ99** [comment]
Sorry, I don't know what you mean. Please explain.

**Comment by ghost** [comment]
Sorry for my response time and poor level of English.

Unfortunately, the Free SMS API is reserved for Free mobile clients.

The Free API can only be used by the owner of the number.

Like, for example: 
https://smsapi.free-mobile.fr/sendmsg?user=FREE_ID&pass=PASS_FREE&msg=MY_MESSAGE
can only send an SMS to the user ID_FREE, and on no other mobile phone

it should be possible to set up the FREE_ID and PASS_FREE for each user at this level: https://screenshots.firefox.com/nVXMkgYxOEu463Da/phpservermon.dev

**Comment by TimZ99** [comment]
Feel free to send a pr.

**Comment by wardpieters** [comment]
Hi @mathieuaubert could you please upload the screenshot again and i will take a look at it.

**Comment by TimZ99** [comment]
Ehm I think that rewriting half of the project for this isn't really an option, as this will only be used for one gateway. We could do something with the phone number field on the profile page. 
Maybe make the input for this gateway something like`Phone_number:free_id:free_password` and split the value in the backend.

**Comment by TimZ99** [comment]
Due to the inactivity of this issue, I assume this is no longer needed.
Feel free to reopen if this is still needed.
