### ISSUE TITLE
New Telegram integration

### ISSUE THREAD

**Issue by V1n1v131r4** [phpservermon/phpservermon#556]
I set chat id on user profile and set token in configuration page but when i test the telegram integration doesn't work for me... chat is appears in the database (psm_users table) but doesn't work the integration.

**Comment by TimZ99** [comment]
You need to activate the bot first. 
1. Open a chat with your bot. (Botfather gave a link to it.)
2. Press start or type /start .
3. Try the test again.

**Comment by TimZ99** [comment]
Got confirmation via Gitter that this was the solution. Will add this to the docs soon.😄
