### ISSUE TITLE
Unauthorized issue on installation

### ISSUE THREAD

**Issue by coolguruji** [phpservermon/phpservermon#558]
Hi,

I am trying to install this script on my centos server.
PHP / Curl module both found

So I entered the details and its now giving me the following error:
Unauthorized
You do not have the privileges to view this page.

I don't know what's the problem

**Comment by TimZ99** [comment]
Which version are you using?

Does this problem occur after you finish the installation?

**Comment by coolguruji** [comment]
Well, I just downloaded it yesterday from the website. Its newer version.
When i tried to install it on my vps. I am not able to install it.

But i tried to install it on one of my shared host. I got it installed.
It looks like something is wrong with my vps but i cant detect that.

**Comment by TimZ99** [comment]
Do you have the required php modules installed and is your MySQL setup correctly?

**Comment by TimZ99** [comment]
Do you have an update on this issue?

**Comment by TimZ99** [comment]
I will close this issue tomorrow and assume the problem is gone if there is no response.

**Comment by TimZ99** [comment]
Reopen if you have an update.
