### ISSUE TITLE
User Login Fails

### ISSUE THREAD

**Issue by gaia** [phpservermon/phpservermon#56]
All notices pointed to a successful upgrade. I then chose user/pword, but when I tried to login it gave me incorrect password. So I reset it. Three times. And I still can't get in.

Please advise.

**Comment by raenk** [comment]
Same problem running 5.4.41

Tried everything

PHP 5.4.41 (cli) (built: May 14 2015 23:15:28)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by rorian** [comment]
Sam problem, 
it's the second time (last time i had to reinstall) now again:
did password reset, can't login, there'is no warning about wrong credentials, i see form data passes properly but in respond i get login screen again
