### ISSUE TITLE
HTTPS Website with a port different from 443 doesn't work

### ISSUE THREAD

**Issue by marc-farre** [phpservermon/phpservermon#560]
In a terminal, if I write `curl https://idp.co.tools:8443/auth/` I have the HTML code.

But if I want to monitor this website with phpservermonitor, it does'nt found it.

What can I do ? Thanks.

**Comment by TimZ99** [comment]
Just choose type website and the monitor should take care of the rest.
![afbeelding](https://user-images.githubusercontent.com/15219858/37248407-dfe37c76-24d1-11e8-9540-23aa10273d28.jpeg)

**Comment by marc-farre** [comment]
Thanks for your answer. It's exactly what I did, so it means it's a problem from my server.
Sorry for the question, next time I will try on an other server before asking !

**Comment by TimZ99** [comment]
No problem 😉
