### ISSUE TITLE
Allow custom webhooks

### ISSUE THREAD

**Issue by jangrewe** [phpservermon/phpservermon#561]
Hi, i reused one of the SMS providers to have PSM speak its messages through my Serverless Nabaztag (https://github.com/andreax79/ServerlessNabaztag/) using Google Translate's TTS feature (e.g. http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=en&q=Test+message), but i was wondering if there's a cleaner way to allow integration calls to custom services?

My hackish solution is this:
```
class Mosms extends Core {

	public $gateway = 1;
	public $resultcode = null;
	public $resultmessage = null;
	public $success = false;
	public $successcount = 0;

	public function sendSMS($message) {

		$nabaztag_url = "http://bunny.example.com/play";
		$googletts_url = "http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=en&q=";

		$result = file_get_contents( $nabaztag_url . "?u=".urlencode( $googletts_url ) . rawurlencode( urlencode( $message ) ) );

		return $result;
	}
}
```
Even just allowing to call a shell script and passing things like the message to it would already be a nice solution, as the shell script could then do whatever it wants with the status/messages.

**Comment by TimZ99** [comment]
Haha nice solution. At this moment custom webhooks are not supported. It's on the list tho #255 !
Will work on it asap.

**Comment by buzzard10** [comment]
@jangrewe can You help me implement that solution in my phpservermon instance? :)

**Comment by jangrewe** [comment]
@emillod I can't help you with the Nabaztag part, but on the PSM side you just need to replace the class in `src/psm/Txtmsg/Mosms.php` with the class above, and of course configure your PSM to send notifications via MoSMS.
The `bunny.example.com` has to be adjusted to your environment, too.

**Comment by TimZ99** [comment]
Adding a new gateway is fairly simple (or in this case, adding Nabaztag). 
It only requires two steps;
- Adding 3 lines to a file
- Creating a new file


You add a new file to the src/psm/Txtmsg folder:

SpeechToText.php
```
class SpeechToText extends Core {
  public function sendSMS($message) {
$nabaztag = "YOUR URL"
$googletts_url = "http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl=en&q=";
			$ch = curl_init();
			curl_setopt($ch, CURLOPT_URL, $nabaztag . "?u=".urlencode($googletts_url).rawurlencode(urlencode($message)));
			curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
			$result = curl_exec($ch);
			curl_close($ch);
		 	

			return 1;
	}
}
```

Add 
```
case 'SpeechToText':
 $sms = new \psm\Txtmsg\SpeechToText();
 break;
```
after https://github.com/phpservermon/phpservermon/blob/62254a534b80fa2a1e60167f12d600ad0cd75bec/src/includes/functions.inc.php#L615


This is not the cleanest way, it doesn't test for errors for example, but it will do the job!

**Comment by TimZ99** [comment]
You could even change $nabaztag for $this->username and put the URL in the username field on the config page. This is handy when you want to change the URL in the feature and don't want to go into the files again.
