### ISSUE TITLE
blank page http://www.alo.com/?&mod=user

### ISSUE THREAD

**Issue by mlarac** [phpservermon/phpservermon#562]
hello: 

I installed the server monitor, but when I click on the user from the menu bar, it shows the blank page. I guess I missed FTP files?

**Comment by TimZ99** [comment]
There is no monitor on http://www.alo.com . Please upload again and provide a valid url.

**Comment by TimZ99** [comment]
I assume you missed a file and that everything works fine by now.
Feel free to reopen if it isn't.

**Comment by Servery** [comment]
Now I got the same problem at http://up.ferienpark-ostsee.de/?&mod=user,
my page is blank and if I try to view the source code of this site it`s also blank.

**Comment by TimZ99** [comment]
@Servery Your site gives `Fatal error: Declaration of psm\Module\User\Controller\UserController::run() must be compatible with psm\Module\AbstractController::run($action = NULL) in /mnt/web423/a2/71/54591171/htdocs/phpservermon/src/psm/Module/User/Controller/UserController.php on line 36`.

Are you using the latest version of PSM?

**Comment by Yelles** [comment]
same for me, it has always worked and now no more access, white page.
error 500

**Comment by Maksim-us** [comment]
I just installed the latest version on a new server and am also getting a blank page when clicking on the "Users" tab.

**Comment by TimZ99** [comment]
Please enable debug mode and check if any messages appear.
________________________________
Van: Max <notifications@github.com>
Verzonden: Thursday, July 11, 2019 9:38:05 PM
Aan: phpservermon/phpservermon
CC: Tim; State change
Onderwerp: Re: [phpservermon/phpservermon] blank page http://www.alo.com/?&mod=user (#562)


I just installed the latest version on a new server and am also getting a blank page when clicking on the "Users" tab.

**Comment by Maksim-us** [comment]
This is what I get when going to the user tab:
`Fatal error: Declaration of psm\Module\User\Controller\UserController::run() must be compatible with psm\Module\AbstractController::run($action = NULL) in /var/www/html/monitor/src/psm/Module/User/Controller/UserController.php on line 36`

**Comment by TimZ99** [comment]
This should be fixed with 08eb9a5 around a year ago.

**Comment by Maksim-us** [comment]
Didn't find it when searching for some reason. Thank you!

**Comment by TimZ99** [comment]
No problem!
________________________________
Van: Max <notifications@github.com>
Verzonden: Friday, July 12, 2019 5:07:26 PM
Aan: phpservermon/phpservermon
CC: Tim; State change
Onderwerp: Re: [phpservermon/phpservermon] blank page http://www.alo.com/?&mod=user (#562)


Didn't find it when searching for some reason. Thank you!
