### ISSUE TITLE
Upgrading tutorial

### ISSUE THREAD

**Issue by mkaand** [phpservermon/phpservermon#563]
Hello,

This is not issue. I just wonder. I am using 3.2.0 and I would like to upgrade to 3.2.2 is there any tutorial for upgrade progress? I guess DB will be change too. If you can give me information about upgrade, I will be appreciate.

**Comment by baur** [comment]
how to migrate DB?

**Comment by TimZ99** [comment]
http://docs.phpservermonitor.org/en/latest/install.html#upgrade

**Comment by TimZ99** [comment]
Ehm wait one sec, want to test something.

**Comment by mkaand** [comment]
OK @TimZ99 Thank you for fast response. I will wait news from you. I will read docs

**Comment by TimZ99** [comment]
Changed the releases to pre-release. There seems to be a problem during the upgrade. Having a look at it right now.

**Comment by ryannix123** [comment]
Confirmed. Fortunately, I was able to rollback the upgrade.

**Comment by TimZ99** [comment]
Everything works fine when you replace the 3.2.1 or 3.2.2 files with the 3.2.0 files.
There is an unknown column s.header_name in 'field list'.

**Comment by TimZ99** [comment]
The problem is that the version is changed before the actual upgrade. The install thinks that you're already updated and won't add the new columns to the database.

**Comment by TimZ99** [comment]
Okay took a bit longer than planned, but I think I fixed it!

**Comment by TimZ99** [comment]
Could you guys test it btw! 
Made a small update to the releases.

- Just upload the files (leave config.php)
- Open your monitor, it should give a message that the database is outdated.

**Comment by mkaand** [comment]
Is it safe to upgrade now?

**Comment by TimZ99** [comment]
Yes.

**Comment by TimZ99** [comment]
You should download the release again btw! If you're using the release you downloaded yesterday it won't work.

**Comment by TimZ99** [comment]
@baur The db will be updated by the monitor during the upgrade.

**Comment by ryannix123** [comment]
It worked. Thanks, @TimZ99!

Any chance you could merge the LDAP plugin?

**Comment by TimZ99** [comment]
Just looking at it! Need to figure out how to test it tho, never used LDAP 😅

**Comment by TimZ99** [comment]
Had a look at it, if I understand correctly you need to add a few files yourself and I'm not a fan of that. The setup needs to be as simple as possible.

**Comment by mkaand** [comment]
Hi @TimZ99 I had issue for my upgrading progress. What I did:

1. I renamed my servermon folder to servermon_old
2. I copied config.php to my laptop.
3. I uploaded all files in 3.2.2 as servermon folder.
4. I copied back config.php to the server.
5. I try to open install.php

It says: 
No dependencies found in vendor dir. Did you install the dependencies? Please run "php composer.phar install".

It seems your zip file has not vendor folder. I will copy vendor folder from servermon_old to servermon folder.

**Comment by mkaand** [comment]
Hello again,

I copied vendors folder and try to run install.php. It works perfectly. Thank you @TimZ99 Telegram notifications are great. I already have Telegram Bot. I use same API for servermon. But I think in user details section we should write Telegram USER_ID not USERNAME. I wrote my username TEST telegram message doesn't work. I typed my Telegram USER_ID it worked.

**Comment by TimZ99** [comment]
Both releases now contain the vendor folder!

I will have a look at the Telegram user_id.

**Comment by Frontend-Head** [comment]
Fatal error: No dependencies found in vendor dir. Did you install the dependencies? Please run "php composer.phar install". vendor still missing?

**Comment by TimZ99** [comment]
Remove the vendor folder if it's there. Run `php composer.phar install`. This will create the vendor folder and install the dependencies.
