### ISSUE TITLE
services-1.0.xsd is missing

### ISSUE THREAD

**Issue by ksuuk** [phpservermon/phpservermon#564]
Hi,

phpservermon-v3.2.0.tar.gz, install.php error:

Fatal error: Uncaught exception 'InvalidArgumentException' with message '[WARNING 1549] failed to load external entity "file:////var/www/data/sm/vendor/symfony/dependency-injection/Loader/schema/dic/services/services-1.0.xsd" (

The reason - file is "services-1.0.xs" not "services-1.0.xsd". Manually renaming is workaround.

**Comment by TimZ99** [comment]
v3.2.2 is available.
I install the monitor quite often but never had this issue. Think something went wrong during the composer install.

**Comment by TimZ99** [comment]
Correction, I have had this issue, but composer was the problem.
