### ISSUE TITLE
UDP Port testing problem v3.2.2

### ISSUE THREAD

**Issue by mkaand** [phpservermon/phpservermon#566]
I upgraded my Server Monitor to 3.2.2 It is perfect but still cannot check UDP ports correctly. Here is the my testing environment. 

I have DD-WRT router UPNP disabled
My torrent client uses UDP 499 port and it is already forwarded.
Servermon shows always open even if I shutdown torrent client.
But https://check-host.net/check-udp website correctly shows my UDP 499
If my torrent client running it says OPEN or Filtered
If my torrent client not running it says Connection refused.

You can test it with your own network. I hope servermon can handle UDP ports correctly.

**Comment by TimZ99** [comment]
Yeah I know, haven't had the time to look at it.

**Comment by TimZ99** [comment]
#99
