### ISSUE TITLE
FREE major carrier SMS text notifications workaroud

### ISSUE THREAD

**Issue by raggoo** [phpservermon/phpservermon#567]
Most major carriers have email to SMS gateways so the work around here is to setup your servers/users to use email and set the email address to your number @ your carriers email to SMS gateway.

i.e. My carrier is cricket wireless so to send a test message to my phone I set my email address to 167XXX61223@mms.cricketwireless.net and it automagically comes through as text message on my phone!

COST? NOTA NOTHING ZERO ZIP

FINALLY! Here is the workaround for FREE text notifications LOL!  

Here is list of major carriers gateways, etc for your convenience:
https://is.gd/8OGTeC

HTH!

IMHO this should be added to the documentation for everyone's benefit!

**Comment by TimZ99** [comment]
Feel Free to write a short explanation for in the docs. 
Please mention that people need to check with there carrier and that not all carriers support this.
(Non in the Netherlands do for example.)

**Comment by TimZ99** [comment]
Feel Free to write a short explanation for in the docs. 
Please mention that people need to check with there carrier and that not all carriers support this.
(Non in the Netherlands do for example.)

**Comment by raggoo** [comment]
How do I  do that?

**Comment by TimZ99** [comment]
Maybe [here](https://github.com/phpservermon/phpservermon/blob/develop/docs/intro.rst), or [here](https://github.com/phpservermon/phpservermon/blob/develop/docs/faq.rst)
