### ISSUE TITLE
Error 500 /?&mod=user

### ISSUE THREAD

**Issue by RP92** [phpservermon/phpservermon#572]
/?&mod=user
trying to go to the users tab the page returns a 500 error

**Comment by TimZ99** [comment]
500 of 505?
Which version are you on?

**Comment by RP92** [comment]
Excuse me I was wrong to write the 500 error title

**Comment by TimZ99** [comment]
Which version are you using?

**Comment by RP92** [comment]
3.2.2

**Comment by TimZ99** [comment]
#547 do you have the same problem?

**Comment by RP92** [comment]
Yes I just click on the user from the menu the page from error 500

**Comment by TimZ99** [comment]
Okay than I will close this one. 
Will look at it ASAP.

**Comment by leochzl** [comment]
Hello,
I have the same problem... all works very well except users... anyone have a solution ? i have to create another admin haha :P
