### ISSUE TITLE
Ping not working on 3.2.2 or on current development branch

### ISSUE THREAD

**Issue by sean-perryman** [phpservermon/phpservermon#576]
My apologies if this is not in the right area, but I am having trouble with the ping monitor in both the release 3.2.2 as well as the cloned development branch I'm testing. The best I can do after installing php-net-socket and upgrade to php7.2 is to get the "Failed to parse address &quot192.168.1.1&quot;" response. This is referenced in another GitHub repo as a potential issue with fsockopen() for a particular range of php versions, which prior to the update I was in the middle of. However, after updating past that affected version I am still getting the same thing.

Should I try and drop down to the PHP version listed on the requirements page? 

Ref: https://github.com/centraldesktop/php-stomp/issues/16

**Comment by sean-perryman** [comment]
On the current 3.2.2 install, the server configured with a Ping monitor doesn't ever seem to react. Just sits there in the On state (even if the IP address does not return an ICMP reply) and says "Never updated". Other monitors are working just fine on this install.

On the development branch clone I get the error message and it shows the monitor as being offline, even if it is indeed responding to ICMP replies. Happy to provide any other relevant information you might need. 

```
$ php -v
PHP 7.2.4-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:53:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

```
$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

**Comment by TimZ99** [comment]
You could try.
I personally haven’t had the time to check this issue, yet. Hope you find the solution!
________________________________

**Comment by sean-perryman** [comment]
Following some instructions to add php5 and switched to it proved to be productive, so I just switched back to php7.2. Much rather have the rest of the monitors functioning rather than nothing at all. Thanks for making this software, I, for one, much appreciate it!

**Comment by TimZ99** [comment]
The everything should function on php5 (idk the exact version).
You suggest that the problem is caused by php7, good to know that!
________________________________

**Comment by sean-perryman** [comment]
I've installed php5 on my host-server and have a similar result on 3.2.2. Does seem like the dev branch will load any longer, throwing a 500 error. Again, all other monitors are working excellent, its just the ping function. Really seems like it is something on my server, but not sure how to go about troubleshooting it at the moment.

**Comment by sean-perryman** [comment]
I did some digging and I believe I've found the cause of the non-ability to ping, if not also a potential solution. Creating a script with the referenced SO article (https://stackoverflow.com/questions/20467432/php-how-to-ping-a-server-without-system-or-exec/20467492#20467492) and adding an 'echo ping('192.168.1.1');' to the end, I was unable to perform this without running it elevated (e.g. sudo php ping.php). As I am running the phpservermon script as the www-data user I can imagine this is the problem I am facing. 

It would appear that suEXEC could be a potential solution (http://alain.knaff.lu/howto/PhpSuexec/), though if I am reading it correctly it would just be running the entire site as whatever user is su'd. If this is the case why not just add www-data to the sudoers group, but that would bring in a whole slew of other issues. This is an internal-only server with no external access, and is running by itself as a VM, so that is a potential solution I suppose. 

Anyone have any thoughts on this?

**Comment by sean-perryman** [comment]
Forgive my presumptuousness, but I believe I've solved the problem on my install. I've re-worked the updatePing function in 'src/psm/Util/Server/Updater/StatusUpdater.php' to instead exec a ping command out and return the average that it receives. Likely not the most secure move, but for something that has little to no access to outside influence it is a risk I am willing to take. Might even be able to pre-scrub the input ($max_runs, $this->server['ip']) to further secure it. 

For anyone interested here is that updated function:

```
protected function updatePing($max_runs, $run = 1) {
  if ($max_runs == NULL || $max_runs > 1) $max_runs = 1;
  $txt = exec("ping -c " . $max_runs . " " . $this->server['ip']);
  $re1='.*?';     # Non-greedy match on filler
  $re2='[+-]?\\d*\\.\\d+(?![-+0-9\\.])';  # Uninteresting: float
  $re3='.*?';     # Non-greedy match on filler
  $re4='([+-]?\\d*\\.\\d+)(?![-+0-9\\.])';        # Float 1

  if ($c=preg_match_all ("/".$re1.$re2.$re3.$re4."/is", $txt, $matches)) {
    $result=$matches[1][0];
  } else { $result = NULL; }

  if (!is_null($result)) {
    $status = true;
  } else {
    $status = false;
  }
  $this->rtime =  $result;

  // check if server is available and rerun if asked.
  if(!$status && $run < $max_runs) {
    return $this->updatePing($max_runs, $run + 1);
  }
  return $status;
}
```

**Comment by Kopertje** [comment]
I added this function to my PSM installation and it works.

**Comment by badookey** [comment]
I've added @sean-perryman's code to two of my PSM (3.2.0 & 3.4.0) installations and they both have worked. My only gripe is it displays ms as s. I've slightly modified code to add three more decimals to convert the milliseconds to seconds.

Below is the changed function
> ```
> protected function updatePing($max_runs, $run = 1) {
>   if ($max_runs == NULL || $max_runs > 1) $max_runs = 1;
>   $txt = exec("ping -c " . $max_runs . " " . $this->server['ip']);
>   $re1='.*?';     # Non-greedy match on filler
>   $re2='[+-]?\\d*\\.\\d+(?![-+0-9\\.])';  # Uninteresting: float
>   $re3='.*?';     # Non-greedy match on filler
>   $re4='([+-]?\\d*\\.\\d+)(?![-+0-9\\.])';        # Float 1
> 
>   if ($c=preg_match_all ("/".$re1.$re2.$re3.$re4."/is", $txt, $matches)) {
>     $result=$matches[1][0];
>   } else { $result = NULL; }
> 
>   if (!is_null($result)) {
>     $status = true;
>   } else {
>     $status = false;
>   }
>   //Divide by a thousand to convert to milliseconds
>   $this->rtime =  $result / 1000;
> 
>   // check if server is available and rerun if asked.
>   if(!$status && $run < $max_runs) {
>     return $this->updatePing($max_runs, $run + 1);
>   }
>   return $status;
> }
> ```

**Comment by jimmyg2times** [comment]
Just my two cents here - I used @sean-perryman 's code with @badookey 's modifications and it works like a charm.  Thanks for this.

**Comment by TimZ99** [comment]
Thanks! I added this to the develop branch.

**Comment by Onul2** [comment]
It solves this problem, but when 50 ping checks are performed, the update process takes too long.
Do you have a solution for this?

**Comment by TimZ99** [comment]
Currently not.
