### ISSUE TITLE
CRON frequency

### ISSUE THREAD

**Issue by jeff-h** [phpservermon/phpservermon#577]
The installation instructions say to run CRON every 15 mins. Is it possible to set this to whatever you like, and therefore run the server checks at whatever frequency you wish eg every minute, or every 5 mins? Or is there some reason this isn't considered wise?

**Comment by Pofilo** [comment]
I'm running it every 5 minutes, no problem so far.

**Comment by jeff-h** [comment]
Thanks! Good to know.

**Comment by TimZ99** [comment]
I’m running it every 5 minutes too, no problems.
