### ISSUE TITLE
can't get cron job to work

### ISSUE THREAD

**Issue by oplf** [phpservermon/phpservermon#578]
I'm running on a Synology server.  It worked fine on an older Synology box.  Then I migrated the PHP server monitor to a newer Synology box.  And the cron job ("Task Scheduler") does not work any more.  It develops a status code of 255 and never actually logs any status.  I'm not that strong on Linux and have dabbled with the command line and have not figured out what I am doing wrong.

I'd like to pay somebody money to join me in a remote desktop session to try to figure out why the cron job won't work any more.

Plus I can't get it to ping.  It says "Failed to parse address &quot192.168.1.1" or something along those lines.  

Or if you won't accept a payment of money, tell me your favorite charity and I will donate money to your favorite charity.

**Comment by TimZ99** [comment]
Ping is a known issue, this will be the next issue I'm going to look at.

Have you tried updating the Task Scheduler? I know that another user had some problems with Synology as well and he fixed it by updating DMS and WebStation.

**Comment by oplf** [comment]
Thank you for posting.  Yes I am using the most current version of DSM and I am using the most current version of Web Station.  Because I have the most recent version of DSM this means I automatically have the most recent version of Task Scheduler.

Keep in mind that for this problem (the cron job doesn't work right) the explanation cannot be in the Web Station.  The cron job simply executes a PHP file, but does not make any use of the apache or nginx.

Thank you for looking at the ping issue.

Again thank you.

As a reminder there's a gift of a free pocket-sized digital voltmeter, or a gift to a person's favorite charity, for a kind soul who might join me in a shared desktop session to try to figure out what is going wrong with this cron job.
