### ISSUE TITLE
Version 3.3.0 Files

### ISSUE THREAD

**Issue by raggoo** [phpservermon/phpservermon#599]
On the page for v3.3.0 we have:
index.php 	preparing for 3.2.0 release 	2 months ago
install.php 	preparing for 3.2.0 release 	2 months ago

Are these files misnamed and are actually 3.3.0 instead or what?

Rather confusing at best.

**Comment by TimZ99** [comment]
Those files needed changes to be ready for 3.2.0. 
In 3.3.0 there are no changes to those files. 
No change means no new commit message.
