### ISSUE TITLE
ping hostname (not ip)

### ISSUE THREAD

**Issue by ale82x** [phpservermon/phpservermon#601]
Hello,
i install phpservermon and work great! :)

i have an issue with a server.
i try to setup a monitoring (ping) ahostname server , not ip.

when i click on Save i receive
The IP address is not valid

how can i solve this problem?

thank you

Alessandro

**Comment by TimZ99** [comment]
Which version are you on?

**Comment by ale82x** [comment]
last
 PHP Server Monitor v3.2.0

**Comment by raggoo** [comment]
Sounds like the hostname is not resolving to an IP address.
i.e.  has a chname or alias record pointing to another server.

Example would be:
domain.com A xxx.xxx.xxx.xxx
xyz.domain.com CHNAME domain.com (points to record with IP address)

Use IP address that the chname record points to should make it work.

**Comment by TimZ99** [comment]
Hostnames should be allowed in 3.3.0. 
3.3.0 is available as a pre-release, maybe you could test if it workes for you.

**Comment by ale82x** [comment]
ok i wait 3.3.0

can i update my version or is not safe use in production?

thank you again

**Comment by TimZ99** [comment]
It's not safe for production yet. Maybe you could upload it to a second folder?

**Comment by TimZ99** [comment]
Have you had the time to test it?

**Comment by ale82x** [comment]
Hello,
i tried to upload on two different hosting server but i see same error...

No dependencies found in vendor dir. Did you install the dependencies? Please run "php composer.phar install".

i can't install...

Thank you

**Comment by TimZ99** [comment]
It's not an error. The project uses parts of other projects (called dependencies). Composer handles the download of those dependencies.
Normally I manually upload a version with the dependencies included. Because it's a pre-release I forgot to do that.
It should be up there within a few minutes.

**Comment by ale82x** [comment]
Hello,
ok i'm download new "version" and now i'm able to setup application.

i configure a server correctly . but when i click update (now i haven't configured cron) , app tells me server down... i configured more servers to test, all works but app not see online...
i tested also www.google.com

Thank you

**Comment by RedSparr0w** [comment]
What host are you using?
One problem I could think of is the host blocking the connections, I've seen other projects have trouble with free hosting.

**Comment by TimZ99** [comment]
Do you have root access for the webserver?
Ping won’t work if you’re not root.

**Comment by ale82x** [comment]
ok, i'm tried on OVH .

ok i test it on my other server and i post the result.

thank you

**Comment by ale82x** [comment]
ok i have a server with full root access but for hosting i use a normal user...
and not working...

i need use root user to execute php script ?

thank you

**Comment by TimZ99** [comment]
It's a known issue that ping requires root access. PHP only allows the function when it's running with root permission.

**Comment by paulpeeters** [comment]
I use Service instead of Ping and choose a TCP port that is normally always open on the remote PC or server. For example on Windows PC's I use port 135.

**Comment by TimZ99** [comment]
@ale82x PHP needs to be running with root privileges.

**Comment by smadds** [comment]
Isn't it a big security weakness if the webserver is running as root?

**Comment by Mohue** [comment]
If ping command need root privileges, maybe you should add an option to ask another server to ping the host and to send the result to phpservermonitor?

**Comment by TimZ99** [comment]
Any ideas on how to do that?
