### ISSUE TITLE
Non english not correctly show at email

### ISSUE THREAD

**Issue by tommy110** [phpservermon/phpservermon#603]
For non english,the alert email is not showing the correct title and content,
For example:
Title: IMPORTANT: ??? 'NO SMTP SERVER' ??
Content:
??????????: 

???: NO SMTP SERVER 
IP: 103.200.XX.XX
Port: 25 
??: 
??: 2018-06-28 22:32:00

**Comment by tommy110** [comment]
VERSION: 3.2.0

**Comment by TimZ99** [comment]
Are the words missing or are they there, but just in English?

**Comment by TimZ99** [comment]
It's a known problem that not all translations are complete. The missing parts should be displayed in English.

 I made a small program to easily find and fix the problems in the translation files. This should also make it way less time consuming to add new words/sentences. 
The only problem is that I accidentally deleted it 😢. Haven't had the time to remake it.

**Comment by TimZ99** [comment]
@tommy110 I'm curious to know the answer.

**Comment by tommy110** [comment]
The missing part if non-english,for example,you can test in Chinese.

**Comment by tommy110** [comment]
Also,it is possbile to add alibaba sms?
https://www.alibabacloud.com/product/short-message-service?spm=a2796.7990255.247275.75.621161c5oT3tbw

**Comment by TimZ99** [comment]
Ah okay. I personally don't speak 23 languages and Google Translate isn't always that good. I will rebuild the earlier mentioned program to make working on the translation files easier. Hopefully this way the translations will be completed faster.

**Comment by TimZ99** [comment]
Made a new issue for your feature request: #604.
