### ISSUE TITLE
[Feature Request] Support for notifications via Discord 

### ISSUE THREAD

**Issue by RedSparr0w** [phpservermon/phpservermon#606]
More info [here](https://discordapp.com/developers/docs/resources/webhook)

Some Example Code:
```php
function postToDiscord($message, $username = "PHP Server Monitor", $avatar = null){
    $data = array("content" => $message, "username" => $username, "avatar_url" => $avatar);
    $curl = curl_init("https://discordapp.com/api/webhooks/<WEB HOOK KEY HERE>");
    curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");
    curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    return curl_exec($curl);
}
```

**Comment by nhalstead** [comment]
I have been writing a Package that will interact with Slack and Discord as well as other services using Webhooks. Once I have it up and running, Ill see about adding it to the project.

**Comment by mooleshacat** [comment]
I am working on webhooks with my fork :)

**Comment by daxsis** [comment]
Any updates ?

**Comment by mooleshacat** [comment]
I gave up it's language and frameworks I do not understand... Got other stuff to work on :+1: 

will wait for another genius to figure it out :nerd_face:

**Comment by TimZ99** [comment]
#971 added support for Discord!
