### ISSUE TITLE
Wrong notification time in mail alert

### ISSUE THREAD

**Issue by abramofranchetti** [phpservermon/phpservermon#607]
The monitor showed correctly the times in the web application as  timezone in php.ini  but in the mail of notification of offline service the time reported was the UTC time and not the time zone set on php.ini. The only way I found to correct the time sent in the email is to go to the setDate method of the Response class and change it as follows setting the corret timezone in the code:

  ```
public function setDate(\DateTime $date)
    {
       //original: $date->setTimezone(new \DateTimeZone('UTC'));
        $date->setTimezone(new \DateTimeZone('Europe/Rome')); 
        $this->headers->set('Date', $date->format('D, d M Y H:i:s').' Europe/Rome');

        return $this;
    }
```

I double checked that in my php.ini the timezone is set to Europe/Rome and the php code "date('Y-m-d H:i:s')" return the correct time.

**Comment by TimZ99** [comment]
Did you check  with```<?php phpinfo(); ?>``` ?

**Comment by TimZ99** [comment]
Whoops, the code in my previous comment wasn't visible, at least not for me.

**Comment by buzzard10** [comment]
I have same thing in telegram notifications.. 
https://i.imgur.com/aAz8kcA.png

**Comment by TimZ99** [comment]
2 hours, 5 minutes and some seconds is strange time.
Do you have this problem every time, or occasionally?

**Comment by buzzard10** [comment]
@TimZ99  thank you for fast reply. I have this every time. This is really weird because PSM send notification in correct time, without any delay

**Comment by TimZ99** [comment]
Sinds when (which version) do you have this problem?
