### ISSUE TITLE
Users Hyperlink is broken 3.2.0

### ISSUE THREAD

**Issue by tmbutterworth** [phpservermon/phpservermon#608]
Selecting users in 3.2.0 links to http://127.0.0.1/?&mod=user and presents no data.

**Comment by tmbutterworth** [comment]
Also broken in 3.1.1

**Comment by tmbutterworth** [comment]
Also broken in 3.1.0

**Comment by tmbutterworth** [comment]
Works in 3.0.1

**Comment by tmbutterworth** [comment]
In 3.0.1 the page works, the form to create a new user works but after completing the form the user information is not being created in the database.

**Comment by TimZ99** [comment]
Check PSM_BASE_URL in config.php. If you're not running PSM on your localhost, it shouldn't be 127.0.0.1

**Comment by tmbutterworth** [comment]
It is blank. I have it running as a virtual host on 127.0.0.4.
define('PSM_BASE_URL', '');

I upgraded to 3.3 and it works fine. same config.php I used with all previous versions.

**Comment by TimZ99** [comment]
Great!
