### ISSUE TITLE
how to update?

### ISSUE THREAD

**Issue by petrk94** [phpservermon/phpservermon#619]
Hello,
I would like to know I can update the installation on my server.
I have version 3.2.1, in the meantime is already version 3.3.1 published.

Thanks

**Comment by TimZ99** [comment]
It's really easy;
1.  Remove 3.2.1 (only keep config.php).
2. Add 3.3.1 and place config.php in it.
3. If you downloaded the version without the vendor directory: run `php composer.phar install`

Open PSM in your browser. The rest will speak for itself.

Let me know if you have any more questions 😄.

**Comment by petrk94** [comment]
@TimZ99 
thank you for the instruction. I just wrote in the last hour a updating script, which automate this steps and make the update automatically.
The shell script update.sh has to be located in the root of the phpservermonitor folder
I would like to contribute this to the project, how I can provide the file to the project? Its my first time I contribute to a project

**Comment by TimZ99** [comment]
1. Fork the repository.
2. Add the file to your fork.
3. Open a pull request.

**Comment by petrk94** [comment]
@TimZ99 thanks for help, Pull request is ready.
