### ISSUE TITLE
CRON not works

### ISSUE THREAD

**Issue by baur** [phpservermon/phpservermon#622]
**Describe the bug**
CRON just not works, running wtih admin rights, nothing is happens: no error, no update status, last update time: never, just silence

**Steps To Reproduce**
Just update manually or by task sheduler (cmd)

**Expected behavior**
Update status

**Your Configuration (please complete the following information):**
 - Exact Phpservermon Version: v3.3.1
 - PHP Version: 7.2.8
 - Hosting Method (Apache, Windows Server 2016): 

**Additional context**
Everything works well except CRON

**Comment by TimZ99** [comment]
Do you use CRON over web (see [docs](http://docs.phpservermonitor.org/en/latest/install.html#cronjob-over-web))?

**Comment by baur** [comment]
Thank you!
Error was crearified with define('WP_DEBUG', true);
php socket extension was disabled
