### ISSUE TITLE
Change all server lists to the same sort order

### ISSUE THREAD

**Issue by damiankw** [phpservermon/phpservermon#632]
It looks like the server lists are sorted differently depending on area, it would be good to have all of these sorted alphabetically unless in the actual monitor window.

For example, in the Users (?&mod=user) section it's sorted by order of addition. In the server selection area in a user edit (?&mod=user&action=edit&id=<userid>) the order is the online status then alphabetically. This one is a little worse as it's sorted by a method that you can't readily see from the UI it's presented on (there's no online/offline status on this page)

I feel like these should both be sorted alphabetically for easily determining which are selected and which need to be selected. I only have 90 added but it's a little hard to determine.

**Comment by TimZ99** [comment]
Done. Could you review it?
