### ISSUE TITLE
Wrong encoded characters in SMS text

### ISSUE THREAD

**Issue by ptrj** [phpservermon/phpservermon#643]
Hi,

I'm using SMS Nexmo gateway and in attached picture you can find how it looks like.
![image](https://user-images.githubusercontent.com/5557356/45208761-eb67c200-b27a-11e8-8951-6bce1bd97966.png)

Ubuntu 16.04
PHP 7.1
PHP Server Monitor 3.3.1

It is bug or wrong configuration please?

Thank you

**Comment by TimZ99** [comment]
This is a bug indeed. Will have a look at it.

**Comment by TimZ99** [comment]
#644 should fix this. Could you confirm?

**Comment by ptrj** [comment]
Yes it works, thank you @TimZ99
