### ISSUE TITLE
[PR #642 for 3.4] - Post field cannot be null - no server created.

### ISSUE THREAD

**Issue by SciLor** [phpservermon/phpservermon#647]
#638 #642 

If I am creating a new server, no server entry is created in the "psm_servers" sql table. "Server added" popup comes up, but no new entry is visible.

> Warning: SQL error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'post_field' cannot be null in

**Comment by TimZ99** [comment]
<REMOVED FILE>
Follow the same steps as discussed in, but before opening install.php, open test.php.

**Comment by SciLor** [comment]
There seems to be no test.php file?!

**Comment by TimZ99** [comment]
Strange.
<REMOVED FILE>

It should be placed in the same folder as index.php etc.

**Comment by SciLor** [comment]
Warning: SQL error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'psm_x_dev_config.key' in 'where clause' in /home/scilmhmx/monitor.scilor.com/src/psm/Service/Database.php on line 544
OK

**Comment by TimZ99** [comment]
My bad, forgot the change the variable. one sec (again).

**Comment by SciLor** [comment]
Upgrade from 331 to 340 but with warning 
:  SQL error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'combine_notifications' for key 'PRIMARY' in

**Comment by SciLor** [comment]
Fine, did test.php then upgraded. 
But on server creation
:  SQL error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'post_field' cannot be null in

**Comment by TimZ99** [comment]
[phpservermon.zip](https://github.com/phpservermon/phpservermon/files/2363771/phpservermon.zip)
Only changed the query for the upgrade part and not for the fresh install part.

**Comment by TimZ99** [comment]
Did it work this time?

**Comment by SciLor** [comment]
Yes, I was able to add another server.
