### ISSUE TITLE
PHP 7.2 / ubuntu 18.04 - User page not loading.

### ISSUE THREAD

**Issue by kiwichrish** [phpservermon/phpservermon#654]
Hi-ho,

Running PSM on an Ubuntu 18.04. (php 7.2.7).  psm 3.2.0

The user page (/?&mod=user) kicks a 500 error as well per:

'Fatal error: Declaration of psm\Module\User\Controller\UserController::run() must be compatible with psm\Module\AbstractController::run($action = NULL) in /data/www/xxxxxxxx/src/psm/Module/User/Controller/UserController.php on line 36'

Looks like a re-defintion of a method that's not making php happy, will delve into it a bit more but thought I'd post here as well in case someone else is looking at it. :-)

**Comment by TimZ99** [comment]
Updating to the latest version should fix this.

________________________________
Van: kiwichrish <notifications@github.com>
Verzonden: zaterdag, september 15, 2018 1:25 AM
Aan: phpservermon/phpservermon
CC: Subscribed
Onderwerp: [phpservermon/phpservermon] PHP 7.2 / ubuntu 18.04 - User page not loading. (#654)


Hi-ho,

Running PSM on an Ubuntu 18.04. (php 7.2.7). psm 3.2.0

The user page (/?&mod=user) kicks a 500 error as well per:

'Fatal error: Declaration of psm\Module\User\Controller\UserController::run() must be compatible with psm\Module\AbstractController::run($action = NULL) in /data/www/dash.logicalit.biz/src/psm/Module/User/Controller/UserController.php on line 36'

Looks like a re-defintion of a method that's not making php happy, will delve into it a bit more but thought I'd post here as well in case someone else is looking at it. :-)

**Comment by kiwichrish** [comment]
Ay, just found that...  I'm way behind.  For some reason I thought 3.2.0 was current, but I see the trunk is 3.3.1.  Will update it now and move on. :-)  Cheers.

**Comment by kiwichrish** [comment]
Make that 3.4.0 and it's all working now.. :-)

**Comment by TimZ99** [comment]
Just a little warning: 3.4 is still in development should be considered unstable.
It’s not strange that you thought that 3.2 was the most recent version. The update check gets the version from phpservermonitor.org but I still can’t update the version there.

________________________________
Van: kiwichrish <notifications@github.com>
Verzonden: zaterdag, september 15, 2018 2:44 AM
Aan: phpservermon/phpservermon
CC: Tim; Comment
Onderwerp: Re: [phpservermon/phpservermon] PHP 7.2 / ubuntu 18.04 - User page not loading. (#654)


Make that 3.4.0 and it's all working now.. :-)

**Comment by kiwichrish** [comment]
That's OK, I like living on the edge.  :-)
