### ISSUE TITLE
Can we use this in a commercial software?

### ISSUE THREAD

**Issue by ashfaqahmed** [phpservermon/phpservermon#658]
Can we use this in a similar commercial software which is already built and ready with API  ?

**Comment by Pofilo** [comment]
See the [LICENSE](https://github.com/phpservermon/phpservermon/blob/develop/LICENSE).

**Comment by ASHAHMED** [comment]
> See the [LICENSE](https://github.com/phpservermon/phpservermon/blob/develop/LICENSE).

i have seen that that says

<img width="142" alt="screen shot 2018-11-09 at 2 44 16 pm" src="https://user-images.githubusercontent.com/11181264/48258236-0fd44c00-e42e-11e8-8f7d-cf9a8f75a6f2.png">

Means Yes ?

**Comment by ashfaqahmed** [comment]
> See the [LICENSE](https://github.com/phpservermon/phpservermon/blob/develop/LICENSE).

i have seen that and it says

<img width="142" alt="screen shot 2018-11-09 at 2 44 16 pm" src="https://user-images.githubusercontent.com/2121712/48258363-59bd3200-e42e-11e8-920a-afab1fb45e82.png">

means yes ?

**Comment by Pofilo** [comment]
Well yes, but you also have to respect all conditions.

**Comment by TimZ99** [comment]
I assume that you have read the license and will fully comply with it. 
If you have any other questions, feel free to ask. Or consult your legal counsel.
