### ISSUE TITLE
Is there a run now?

### ISSUE THREAD

**Issue by stccorp** [phpservermon/phpservermon#660]
How can I quickly check if the test works or not?  I was expecting somekind of run now button on the interface

Thank you

**Comment by TimZ99** [comment]
The update button in the nav bar.

________________________________
Van: stccorp <notifications@github.com>
Verzonden: zaterdag, september 22, 2018 9:28 PM
Aan: phpservermon/phpservermon
CC: Subscribed
Onderwerp: [phpservermon/phpservermon] Is there a run now? (#660)


How can I quickly check if the test works or not? I was expecting somekind of run now button on the interface

Thank you

**Comment by stccorp** [comment]
thank you
