### ISSUE TITLE
FreeMobileSMS curl_exec missing

### ISSUE THREAD

**Issue by EU-INEA** [phpservermon/phpservermon#666]
Pretty everything is in the title. 

The FreeMobileSMS alerts were failing with $httpcode 0 and $err 0 and no SMS received after that.

I added the ligne ```curl_exec($curl);``` on line 62 in src/psm/Txtmsg/FreeMobileSMS.php and the problem has gone.

**Comment by Erreur32** [comment]
Yes , need to be updated with 

`curl_exec($curl);`

**Comment by TimZ99** [comment]
Will be released with the next update.

________________________________
Van: Erreur32 <notifications@github.com>
Verzonden: Monday, April 1, 2019 1:13:46 PM
Aan: phpservermon/phpservermon
CC: Subscribed
Onderwerp: Re: [phpservermon/phpservermon] FreeMobileSMS curl_exec missing (#666)


Yes , need to be updated with

curl_exec($curl);
