### ISSUE TITLE
Problem with HTTP2

### ISSUE THREAD

**Issue by sinasalek** [phpservermon/phpservermon#672]
Couldn't match "HTTP/2 200" and says "TIMEOUT ERROR: no response from server" on php7.2
i changed the regular expression that matches the HTTP code to his 
```
/[A-Z]{2,5}\/\d\.\d\s(\d{3})\s(.*)|HTTP\/2 200/
```

Sample Header
===
```
HTTP/2 200 
server: nginx
date: Wed, 07 Nov 2018 12:31:30 GMT
content-type: text/html; charset=utf-8
content-length: 8802
last-modified: Wed, 07 Nov 2018 11:22:23 GMT
etag: "182ca2-2262-57a11550b1d22"
accept-ranges: bytes
cache-control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Sun, 19 Nov 1978 05:00:00 GMT
vary: User-Agent
content-encoding: gzip
```

**Comment by Helox** [comment]
Workaround (dont to HTTP2, but just use HTTP1.1): 
add the following line to src/includes/functions.php line 360

> curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
