### ISSUE TITLE
Website saying its down

### ISSUE THREAD

**Issue by Gaeta** [phpservermon/phpservermon#673]
Hi im trying to figure out why it is saying that this is down "https://bot.dreaming.ga:3001/"

![image](https://user-images.githubusercontent.com/31389391/48304043-ce50a900-e4e0-11e8-97af-ced1afd4b208.png)

if you look at the img it i have it if the site shows `ImHere` then it is up and if you click the site it does show that any ideas why it is not working?

**Comment by pieter-groeneweg** [comment]
probably because it expects document=html.
your page is "json".

**Comment by Gaeta** [comment]
then how do i allow json

btw sorry for late responce

**Comment by TimZ99** [comment]
Just tested it and it's working for me. Are you using the latest version of PSM?
