### ISSUE TITLE
Tabs will not open

### ISSUE THREAD

**Issue by raggoo** [phpservermon/phpservermon#675]
Just installed v3.3.1 over v3.2.0 with no errors

When I  go to any page that has tabs at top (EX. logs,config) it will not change to the tabs when I  click on them.

It just sits there and does nothing.

Same in latest firefox and Google chrome so don’t think the browser is the problem. (could be wrong)

How to fix please?

Thanks.

**Comment by TimZ99** [comment]
Please try to reinstall (leave config.php).

**Comment by TimZ99** [comment]
I assume that it worked. Please reopen if you encounter any problems.
