### ISSUE TITLE
Not working with PHP 7.2

### ISSUE THREAD

**Issue by travisbotello** [phpservermon/phpservermon#678]
mycrypt extension not included in PHP 7.2

`Call to undefined function mcrypt_get_iv_size() in /src/includes/functions.inc.php on line 785`

**Comment by TimZ99** [comment]
The function has been deprecated as of PHP 7.1.0. I will rewrite it asap. Which page did you try to load?

**Comment by travisbotello** [comment]
Manually calling `?&mod=server_update` and automatic cron update was not working anymore.

**Comment by jmcgranahan** [comment]
this is definitely an issue - we are running PHP 7.4 and we have to keep our software at the most current release. Can this be corrected? It seems to be on the following files:
phpservermon-develop/src/includes/functions.inc.php, lines 806, 812

Function mcrypt_decrypt() is deprecated in functions.inc.php, line 814

Should be able to use openssl to accomplish the same tasks (I think).

**Comment by travisbotello** [comment]
This is getting very urgent since PHP 7.1 will reach eol on 1 Dec 2019...

**Comment by travisbotello** [comment]
This PR https://github.com/phpservermon/phpservermon/pull/805 should fix the problem.

**Comment by TimZ99** [comment]
Fixed in #805.
