### ISSUE TITLE
Ping Error

### ISSUE THREAD

**Issue by darvinrivera** [phpservermon/phpservermon#684]
I use develop branch.
New **Server** configuration:
         **Domain/IP**: 10.7.1.2
          **Type**: Ping
Save and run Update y get this error:  Couldn't create socket [1]: Operation not permitted

Updated:
When i run **php cron/status.cron.php** ping work perfect but not web interface http://url.to.domain/?&mod=server_update

**Comment by Puyodead1** [comment]
same

**Comment by dktcoding** [comment]
According to #611: **Ping requires root**.

Regards

**Comment by rwwest77** [comment]
I have the same problem. I noticed that if I have just 1 device being pinged, the update button works fine. If I add a 2nd device to ping it errors out ever time.

I have about 50 devices set to "service" and port 80 and 1 device pinging. Works great! But toggling just one other device to ping makes it fail.

**Comment by Puyodead1** [comment]
i have it as root

**Comment by pieter-groeneweg** [comment]
mmm so using cron as root works.
having update run through the navigation (not root) fails.

for simple users I like to hide/disable the update from navigation... where and how can I do that?

**Comment by TimZ99** [comment]
Remove `server_update` [here](https://github.com/phpservermon/phpservermon/blob/1249e98a0fb9d3024afd36b9875a0a227b7eccb1/src/psm/Module/AbstractController.php#L273) and [here](https://github.com/phpservermon/phpservermon/blob/1249e98a0fb9d3024afd36b9875a0a227b7eccb1/src/psm/Module/AbstractController.php#L276) to remove the update button from the navigation bar.

**Comment by mouradev1** [comment]
Boa Noite, apaguei mas também ele não atualiza automaticamente.
