### ISSUE TITLE
Not working with PHP 5.6

### ISSUE THREAD

**Issue by 2ge** [phpservermon/phpservermon#693]
Using phpservermon v3.3.2 [Security], while installing:

```
# php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/filesystem v4.1.3 -> satisfiable by symfony/filesystem[v4.1.3].
    - symfony/filesystem v4.1.3 requires php ^7.1.3 -> your PHP version (5.6.20) does not satisfy that requirement.
  Problem 2
    - symfony/filesystem v4.1.3 requires php ^7.1.3 -> your PHP version (5.6.20) does not satisfy that requirement.
    - symfony/config v3.4.14 requires symfony/filesystem ~2.8|~3.0|~4.0 -> satisfiable by symfony/filesystem[v4.1.3].
    - Installation request for symfony/config v3.4.14 -> satisfiable by symfony/config[v3.4.14].

Exit 2
```

please allow to run it on PHP 5.6 versions

**Comment by TimZ99** [comment]
No idea why you try to install `v4.1.3`, `v3.4` should be installed. `v3.4` will run on `PHP ^5.5.9|>=7.0.8`.

`v3.4` is also the version in de composer.json file.

**Comment by BeecherNetworks** [comment]
I'm having the same problem. Like OP, I've run "php composer.phar install" from the command line, as per the installation instructions and that's the error I get. How do I select the version you mention above?

**Comment by TimZ99** [comment]
I don’t know why it tries to download v4. Could you check if v3.4 is specified in `composer.json`? 
Try to run `composer require symfony/filesystem:3.4`

Btw, PHP5 has reached the end of life. Please update to PHP7!

**Comment by BeecherNetworks** [comment]
composer require symfony/filesystem:3.4 worked for me, thanks.

Old server, deprecating in a month or two, no point.

**Comment by TimZ99** [comment]
Great! I think that one of the packages tries to install v4. `composer require symfony/filesystem:3.4` forces v3.
