### ISSUE TITLE
Where do I put Matomo script?

### ISSUE THREAD

**Issue by davidtessier** [phpservermon/phpservermon#698]
Hello,
I use Matomo (formerly Piwik) on my sites and I’d like to track usage on phpServerMon. It’s not obvious to me where I should put my Matomo JavaScript site tracking code. I am hoping someone could give me some direction as to the file(s) that I’d have to add the code snippet to so that I can track all site usage.
Thank you and keep up the solid development work on this project. It's fantastic!

**Comment by dktcoding** [comment]
Hello,

I'm no expert in phpservermon, but I believe the correct place would be in `src/templates/default/main/body.tpl.html`

Regards

**Comment by davidtessier** [comment]
Thank you. That looks right to me as well. I added it there and then did a test to see if it appeared in the inspector and it did.
