### ISSUE TITLE
[Q] Windows server status update

### ISSUE THREAD

**Issue by elessargr** [phpservermon/phpservermon#699]
Hello everyone,

I just installed the phpservermon (3.3.1) on my windows server 2008 R2 (with PHP7).

I have been trying to find a way for the tool to check the status of my "servers" every x mins but havent found anything.
The closest issue I have read is the #232 but this is for linux, I have windows :)

What I have done is put on task schedule a task to run every 5 min for the command "C:\xxxx\PHP7\php.exe -f C:\xxxx\xxxxx\cron\status.cron.php" but unfortunately doesnt seems to do the trick. :(
I know I need to do something with the "status.cron.php" but no idea what else.

Can I edit somewhere the code of the page so its automatically check for the health of the servers without me need to manually update it or need to have my webpage open?

Thank you guys in advance!

**Comment by ghost** [comment]
The task schedule you created should do the trick and i’m not aware of other ways in which you could do it but the task schedule should be working correctly. 

Have you tried running C:\xxxx\PHP7\php.exe -f C:\xxxx\xxxxx\cron\status.cron.php from a command prompt window to verify that the configuration is set up? (for each of your servers it should show on the webpage of phpservermon last check relatively short moments ago.) 

also if you wanted a more actuate monitor i recommend you reduce the 5 minute interval to 1. 

let me know if all that goes well and then we can isolate the issue to the task configuration via task scheduler. 

- daniel2029

**Comment by elessargr** [comment]
So the command is correct BUT!!!
you need to put the "C:\xxxx\PHP7\php.exe" on the setting for running program and then on the lower box for variables you need to insert the "-f C:\xxxx\xxxxx\cron\status.cron.php".... it took me 9 days to find what the heck was wrong hehe.
Thanks everyone!
