### ISSUE TITLE
mail nothing happens when test send mail

### ISSUE THREAD

**Issue by yalgva** [phpservermon/phpservermon#700]
Hello

phpservermon 3.3.2 - windows 2012 r2
When I start test I just have a white page http://glpi.latour.ch/servermon/index.php?mod=config&action=save

setup is ok with smtp server but I receive nothing.
Thx for your help

**Comment by undauntedspirit** [comment]
Same here.
My first guess is that php is too new - running 7.2.15 on Ubuntu 18.04.

Here's the error with debug turned on:

Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in /var/www/html/apps/monitor/src/includes/functions.inc.php:479 Stack trace: #0 /var/www/html/apps/monitor/src/psm/Module/Config/Controller/ConfigController.php(233): psm_build_mail() #1 /var/www/html/apps/monitor/src/psm/Module/Config/Controller/ConfigController.php(198): psm\Module\Config\Controller\ConfigController->testEmail() #2 /var/www/html/apps/monitor/src/psm/Module/AbstractController.php(193): psm\Module\Config\Controller\ConfigController->executeSave() #3 /var/www/html/apps/monitor/src/psm/Module/AbstractController.php(164): psm\Module\AbstractController->runAction('save') #4 /var/www/html/apps/monitor/src/psm/Router.php(102): psm\Module\AbstractController->run('save') #5 /var/www/html/apps/monitor/index.php(42): psm\Router->run('config') #6 {main} thrown in /var/www/html/apps/monitor/src/includes/functions.inc.php on line 479

**Comment by undauntedspirit** [comment]
Confirmed -- phpmailer needs to be updated to the 6.x version.  Looks like there may be breaking changes though.   

The current version included has security vulnerabilities anyway.

**Comment by undauntedspirit** [comment]
I was able to get my install working with emails by running the composer install commands to update dependencies.   I don't recommend doing this unless you know what you're doing and take backups first.  I'm not familiar with the php package managers at all.

**Comment by steve0023** [comment]
Hello
I Have the same issue, same version and nothing in php/apache log, any issue ?

**Comment by TimZ99** [comment]
Try: https://github.com/phpservermon/phpservermon/issues/719#issuecomment-485137246

**Comment by gregkuhnert** [comment]
@TimZ99 - Your FAQ works great for people who use composer. But, you still package the broken PHP Mailer vendor package with your source archive. Are there plans to update future source archive builds, so that this will work out of the box without the need to tweak a stock source download?

**Comment by TimZ99** [comment]
My bad, next one will have the right package!
