### ISSUE TITLE
User page not working

### ISSUE THREAD

**Issue by Servery** [phpservermon/phpservermon#701]
If I open the user page the following error comes up:

> Fatal error: Declaration of psm\Module\User\Controller\UserController::run() must be compatible with psm\Module\AbstractController::run($action = NULL) in /mnt/web423/a2/71/54591171/htdocs/phpservermon/src/psm/Module/User/Controller/UserController.php on line 36

Upgrade to v3.3.2 solved this problem.

**Comment by TimZ99** [comment]
Great!
