### ISSUE TITLE
Website URL not accepted when underscore is in subdomain.

### ISSUE THREAD

**Issue by undauntedspirit** [phpservermon/phpservermon#704]
Example:   hello_world.mydomain.com  Will say it's not a valid URL when submitting a new site to monitor.

Version 3.3.2 tested.

**Comment by mtelgkamp** [comment]
According to https://tools.ietf.org/html/rfc1035 only letters, digits and `-` are allowed in subdomains.

> They must start with a letter, end with a letter or digit, and have as interior characters only letters, digits, and hyphen.

**Comment by TimZ99** [comment]
I will add this. Subdomains with underscores occur sometimes. If you have a subdomain with an underscore, you should be able to check it and not be rejected by PSM.

**Comment by TimZ99** [comment]
Have looked into this a bit more. It seems like PHP FILTER_VALIDATE_URL won't allow underscores, at least not at this time. Maybe someone can make a regex.

**Comment by ICTman1076** [comment]
Found some regex that after a quick bit o' testing seemed to work fine. Will try to implement and make a PR.

**Comment by ICTman1076** [comment]
^ Made my PR. Sorry it's a bit of a mess - it's my first code PR to an open source project. Feedback welcome :)
