### ISSUE TITLE
HTTP2 Authentification Bug

### ISSUE THREAD

**Issue by PixiBixi** [phpservermon/phpservermon#706]
Hi!

I've a weird case, i don't know if it's a well-known issue.

I put my HTTP identifiants (I'm sure they're correct), but I still have a 401 error... These are my logs...

```
nginx.1    | $SRV_IP $PHPMON_IP - - [20/Feb/2019:08:30:53 +0000] "HEAD / HTTP/2.0" 401 0 "-" "Mozilla/5.0 (compatible; phpservermon/3.3.2; +http://www.phpservermonitor.org)"
```

If someone have an idea.

**Comment by xsuchy09** [comment]
I can confirm that. There is a bug in decrypt function. PR sent - see #843.

**Comment by PixiBixi** [comment]
Please, merge it asap, i need to test it :)
