### ISSUE TITLE
Notifications only working in test mode

### ISSUE THREAD

**Issue by joydashy** [phpservermon/phpservermon#709]
I am running the latest version: 3.3.2. But previously had the same issue on the Docker v3.3.1.

I can't for the life of me get notifications to work, outside of Test mode. Both Pushover and Email are working great when using the Test button, but not on any live events.

Server config: https://i.imgur.com/JN9CFNn.png
Event log: https://i.imgur.com/fqUSqlc.png
Email log: https://i.imgur.com/T8pHMwD.png

Any idea what this could be? Seems no one else has this issue?

**Comment by freezesis** [comment]
Does the monitoring server have a specified User?

**Comment by joydashy** [comment]
Aaah so that's what the "Permissions" is for...wow, ok. thanks so much! It works now.
