### ISSUE TITLE
Error monitoring webservice wsdl

### ISSUE THREAD

**Issue by jhuertaa** [phpservermon/phpservermon#710]
How to the monitor site ?

https://some-ip/some-name/some-name/some-name?wsdl

Always return: 405 Method Not Allowed for type Website or Service

Thanks a lot.

**Comment by freezesis** [comment]
Maybe you can try the latest version V3.4 (not released yet).

Https://github.com/phpservermon/phpservermon/issues/386

**Comment by jhuertaa** [comment]
Hi freezesis, thanks quickly response. 
i upgrade to 3.4 , but the problem is not solved.

I will wait a new update.

thanks a lot.

**Comment by freezesis** [comment]
I set the webservice request method to "GET" and it doesn't seem to have a 405 error.

**Comment by jhuertaa** [comment]
Thanks a lot.
Now is working.

Rgds.
