### ISSUE TITLE
[Request] Custom fields on a service or website

### ISSUE THREAD

**Issue by Kopertje** [phpservermon/phpservermon#715]
Hi,

I currently got cachethq.io running and i would like to connect it to PSM with cachethq's API. The API requires a ID to set the right status. So my plan is to give each service/website in PSM the ID that matches the component in cachethq. To make this work i need to define the ID somewhere in PSM. Custom Fields would make this possible. Is there any chance anyone could add this?

If someone has questions about my request, please ask them.

**Comment by Kopertje** [comment]
This can be closed. I figured out how i can add fields myself to PSM.

**Comment by pieter-groeneweg** [comment]
You mind sharing how you added custom fields?
