### ISSUE TITLE
SMTP emails notification no workie

### ISSUE THREAD

**Issue by tridoan** [phpservermon/phpservermon#716]
hi there,
I updated to 3.3.2 from 3.2 and now my SMTP email notifications do not work. Even the tests shows no output...anyone else have this issue?

**Comment by nelsondcosta23** [comment]
hmm 3.2 works, I ll upgrade to 3.3.2 and test.

**Comment by nelsondcosta23** [comment]
yap 3.2 works, 3.4 dont :S

**Comment by TimZ99** [comment]
Do you receive the test message with smtp disabled?

**Comment by nelsondcosta23** [comment]
Hi Tim,

With or without smtp when send a test, goes to a blank page. Tested with hotmail, gmail, and private exchange.

**Comment by TimZ99** [comment]
I'm moving this to #719.
