### ISSUE TITLE
multiple notification not working

### ISSUE THREAD

**Issue by steve0023** [phpservermon/phpservermon#717]
Hello,
Since Email notification seems not working on 3.3.2 (same as #716 and #700) so I configured a telegram notification.
It appears that if the email are still enabled in the servers pages, the telegram notification is not send.

**Comment by TimZ99** [comment]
Could you try to disable the combined notification and see if you get the Telegram notifications?

**Comment by steve0023** [comment]
After disabling the other types of notification, the Telegram notification is working.

it seem be related to #719

**Comment by nelsondcosta23** [comment]
Use compose, it works

**Comment by nelsondcosta23** [comment]
Resolution:
1- instal composer https://getcomposer.org/download/
2- using console (windows cmd) go to server monitor directory (cd path linux) (pushd path windows)
3 execute php composer.phar install

and w8
done :) 

Solve mail smtp problem too

**Comment by steve0023** [comment]
after updating compose, 
no more blank page when i testing an email sending but i have the error
`smtp connect() failed. https //github.com/phpmailer/phpmailer/wiki/troubleshooting`

**Comment by steve0023** [comment]
After somme further research it was just the "use SMTP server" parameter who did this issue. 
now it's working
Also now the email and telegram is working both for a same server alert

**Comment by slothking87** [comment]
Hi guys. The same thing is happening to me. Have installed the latest composer as suggested and its saying that everything is up to date. I'm using an internal SMTP server without authentication. Any suggestions as to what the issue might be? I get the same error "Error in email sending: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting"

**Comment by dieideeistgut** [comment]
> Hi guys. The same thing is happening to me. Have installed the latest composer as suggested and its saying that everything is up to date. I'm using an internal SMTP server without authentication. Any suggestions as to what the issue might be? I get the same error "Error in email sending: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting"

Exactly same here, validated SMTP logins. Did you ever come up with a solution @slothking87 ? Thanks!

**Comment by TimZ99** [comment]
Which version do you use?

**Comment by dieideeistgut** [comment]
Updated to v3.4.5. - tried 3.3.2 too. Same results.  

RESOLVED: Was a Docker-issue as the requested port was non-reachable. Which resulted in a 504 timeout from PHPMailer. Thanks though! ;)
