### ISSUE TITLE
Unable to Sign In, Fresh Install - Unauthorized 

### ISSUE THREAD

**Issue by johntrask** [phpservermon/phpservermon#718]
I am running version 3.3.2, PHP 7.3.4. Install goes fine but after the install when I sign in I get the below message. 

PHP Fatal error:  Redirect failed. in C:\inetpub\wwwroot\monitoring\src\psm\Module\User\Controller\LoginController.php on line 59

I hit refresh and I get the Unauthorized error. Everything looks fine in the DB, User is there with a good looking hash. 

Any quick thoughts or suggestions?

**Comment by TimZ99** [comment]
I had the same problem, but haven’t had the time to look in to it. Something changed with this PHP version, maybe have a look at PHP s changelog.
________________________________
Van: johntrask <notifications@github.com>
Verzonden: Sunday, April 14, 2019 4:13:40 AM
Aan: phpservermon/phpservermon
CC: Subscribed
Onderwerp: [phpservermon/phpservermon] Unable to Sign In, Fresh Install - Unauthorized (#718)


I am running version 3.3.2, PHP 7.3.4. Install goes fine but after the install when I sign in I get the below message.

PHP Fatal error: Redirect failed. in C:\inetpub\wwwroot\monitoring\src\psm\Module\User\Controller\LoginController.php on line 59

I hit refresh and I get the Unauthorized error. Everything looks fine in the DB, User is there with a good looking hash.

Any quick thoughts or suggestions?

**Comment by johntrask** [comment]
Dropped back on PHP version and that fixed it. I checked the PHP changelog but nothing jumped right out at me. Thanks for the fast reply.
