### ISSUE TITLE
SMTP Seems Broken in 3.3.2

### ISSUE THREAD

**Issue by johntrask** [phpservermon/phpservermon#719]
Looks like a few other people are noticing issues with email in 3.3.2. Any suggestions on things to try? Looks like there was a change in namespace for email in 3.3.1?

**Comment by TimZ99** [comment]
Could you change it back and try if it works after that?

**Comment by nelsondcosta23** [comment]
I tested today, and it works. 

Tested with SMTP

**Comment by TimZ99** [comment]
Did you change to v3.3.1 or did you change the namespace?

**Comment by TimZ99** [comment]
Do you receive the test message with smtp disabled?

**Comment by nelsondcosta23** [comment]
Hi, I upgrade 3.2 to 3.4 just replacing the files files and folling the steps.

with or without smtp when send a test, goes to a blank page. Tested with hotmail, gmail, and private exchange.

**Comment by nelsondcosta23** [comment]
Hi again, I just found out 3.4 if the configuration to send email its on, telegram doesnt work.
I think this might have something to do because the problem reported

**Comment by TimZ99** [comment]
I think that Telegram doesn't work because of the page timing out when the email function fails.

Could you run `composer update` and try the test email again, without smtp enabled?

**Comment by nelsondcosta23** [comment]
![report](https://user-images.githubusercontent.com/11686595/56460095-095ede80-6395-11e9-8f98-de32c5ece7d5.JPG)
This? I ll test now.

**Comment by TimZ99** [comment]
Did you receive the test message?

**Comment by nelsondcosta23** [comment]
Yep, Email with SMTP ON, and Telegram :)
I own you one :)

Resolution:
1- instal composer https://getcomposer.org/download/
2- using console (windows cmd) go to server monitor directory (cd path linux) (pushd path windows)
3 execute php composer.phar install

and w8
done :)

Tested with SMTP ON

**Comment by TimZ99** [comment]
Great 🎉!  The namespace was changed by PHPMailer, I think that you had an old version installed with the old namespace.

**Comment by ryannix123** [comment]
@TimZ99 That worked for me as well.

`php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 4 installs, 9 updates, 4 removals
  - Removing symfony/polyfill-php54 (v1.1.0)
  - Removing symfony/polyfill-php55 (v1.1.0)
  - Removing ircmaxell/password-compat (v1.0.4)
  - Removing indigophp/hash-compat (v1.1.0)
  - Updating phpmailer/phpmailer (v5.2.6 => v6.1.3):Downloading (100%)         )
  - Installing symfony/polyfill-ctype (v1.13.1): Downloading (100%)         
  - Updating symfony/filesystem (v3.0.1 => v3.4.36):Downloading (100%)         )
  - Updating symfony/config (v2.8.2 => v3.4.36): Downloading (100%)         
  - Installing psr/container (1.0.0): Downloading (100%)         
  - Updating symfony/dependency-injection (v2.8.2 => v3.4.36):Downloading (100%)  - Updating symfony/event-dispatcher (v2.8.2 => v3.4.36): Downloading (100%)     - Updating paragonie/random_compat (1.1.6 => v2.0.18): Downloading (100%)       - Installing symfony/polyfill-php70 (v1.13.1): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.13.1): Downloading (100%)         
  - Updating symfony/http-foundation (v2.8.2 => v3.4.36): Downloading (100%)      - Updating twig/twig (v1.24.0 => v1.42.4): Downloading (100%)         
  - Updating php-pushover/php-pushover dev-master (d13d08d => b2d060e):  Checking out b2d060efac
Generating autoload files`
