### ISSUE TITLE
Some database tables not updating

### ISSUE THREAD

**Issue by andreaswork** [phpservermon/phpservermon#721]
Using version 3.2 on Ubuntu Server 16.04.

Since 3 days ago, i noticed that my monitor wasnt being updated, the system has been working flawlessly for the past year and half.

Upon searching i found out that, the "PSM_server_uptime" table in database isnt being updated when the cron is run, but "PSM_servers" table is, so i know the cron is working.

Manually updating phpservermon via websites "Update" button refreshes "PSM_server_update" table in database and website is also updated when updated.

**Comment by andreaswork** [comment]
Oh and i am using php5 if thats relevant information.

Did some more looking into this and found out that the website is actually working via cronjob, but `last online` and `last check` fields are not being updated on website via cronjob. 

These fields only update when hitting the "Update" button on webgui, which i find wierd, since the `last_online` and `last_check` columns in `psm_server` table are being updated when cronjob is run, only `psm_servers_uptime` is not updated when cronjob is run.

**Comment by andreaswork** [comment]
Any tips/tricks on how to fix this?
Very annoying, this messes up graphs, since every time a server is offline for 1 check, it its marked as being offline for an hour. since last updated isnt being updated in database.

**Comment by andreaswork** [comment]
New info, all database tables are now being updated correctly when cron is ran, (no idea why, changed nothing), but on website, "last online" is always "about an hour ago" and in "server details" page graphs are not being updated. And again, when clicking the "update" on website, everything updates correctly.

**Comment by TimZ99** [comment]
Did you enable debug mode and did this give you any errors when updating?

**Comment by andreaswork** [comment]
Debug is enabled, produces no errors when running cron or clicking "update" on website.

**Comment by Urano-Gonzalez** [comment]
How is configured your cron?
Your host permit you run cron every minute?
