### ISSUE TITLE
Ideia - Make Groups

### ISSUE THREAD

**Issue by nelsondcosta23** [phpservermon/phpservermon#722]
The ideia is not something new. Many people before me talk about this.

But waht you think about, make a view for groups?
Like tags, printers, servers, websites, etc...

![sss](https://user-images.githubusercontent.com/11686595/56448984-15528e00-630c-11e9-851e-bb5ea30308ab.JPG)

**Comment by TimZ99** [comment]
This idea is already on the wishlist 👍🏼. #176
