### ISSUE TITLE
Cannot find phpmailer

### ISSUE THREAD

**Issue by jeffshead** [phpservermon/phpservermon#726]
I have tried all versions. I get the following error on a Ubuntu 16.04 server with PHP 7.0 when I try to send an email test:

`Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in /var/www/mysite.com/public_html/phpservrmon/src/includes/functions.inc.php:495 Stack trace: #0 /var/www/mysite.com/public_html/phpservrmon/src/psm/Module/Config/Controller/ConfigController.php(234): psm_build_mail() #1 /var/www/mysite.com/public_html/phpservrmon/src/psm/Module/Config/Controller/ConfigController.php(199): psm\Module\Config\Controller\ConfigController->testEmail() #2 /var/www/mysite.com/public_html/phpservrmon/src/psm/Module/AbstractController.php(193): psm\Module\Config\Controller\ConfigController->executeSave() #3 /var/www/mysite.com/public_html/phpservrmon/src/psm/Module/AbstractController.php(164): psm\Module\AbstractController->runAction('save') #4 /var/www/mysite.com/public_html/phpservrmon/src/psm/Router.php(102): psm\Module\AbstractController->run('save') #5 /var/www/mysite.com/public_html/phpservrmon/index.php(42): psm\Router->run('config') #6 {main} in /var/www/mysite.com/public_html/phpservrmon/src/includes/functions.inc.php on line 495`

**Comment by TimZ99** [comment]
Try https://github.com/phpservermon/phpservermon/issues/719#issuecomment-485137246

**Comment by jeffshead** [comment]
Thank you! I had already ran composer update but I neglected to cd to the phpservermonitor directory.

The test emails are now being sent but only if I untick 'Enable SMTP'. I get the following error if I leave it ticked:
```
Error in email sending: SMTP connect() failed.
https://github.com/PHPMailer/PHPMailer?/wiki/Troubleshooting
```
Why is that?

**Comment by jeffshead** [comment]
Thanks!
I neglected to cd to the phpservermonitor directory when I ran 'composer update'. Since I updated phpservermonitor from an earlier version, the vendor directory was pre-existing so I did not realize phpmailer was not up to date. Since running 'composer update' in the phpservermonitor directory, it's now working.
