### ISSUE TITLE
[Feature Request] Curl http request notify

### ISSUE THREAD

**Issue by 12nick12** [phpservermon/phpservermon#727]
I use mattermost for a chat system and it has the ability for inbound HTTP requests. I would love the ability to have PSM notify over a curl request.

**Comment by xsuchy09** [comment]
Ok, can you read the docs and specify that webhook (or what is it) api? Just to help developers to spent a little bit less time on your request. It can help and you will get what you want for free at all ...

**Comment by TimZ99** [comment]
Duplicate of #255
