### ISSUE TITLE
Fatal error: Call to undefined function psm\hash_equals() 

### ISSUE THREAD

**Issue by andreaswork** [phpservermon/phpservermon#728]
On fresh install (3.2) trying to create new user on install screen throws:

Fatal error: Call to undefined function psm\hash_equals() in /var/www/www.domain.fi/htdocs/monitor2/src/psm/Router.php on line 170

**Comment by TimZ99** [comment]
hash_equals() is a function for PHP 5 >= 5.6.0 and PHP 7. I guess that you're using an older PHP version? 

Quick fix: Add the following on [Router.php line 164](https://github.com/phpservermon/phpservermon/blob/1249e98a0fb9d3024afd36b9875a0a227b7eccb1/src/psm/Router.php#L164).
```
if(!function_exists('hash_equals'))
{
    function hash_equals($str1, $str2)
    {
        if(strlen($str1) != strlen($str2))
        {
            return false;
        }
        else
        {
            $res = $str1 ^ $str2;
            $ret = 0;
            for($i = strlen($res) - 1; $i >= 0; $i--)
            {
                $ret |= ord($res[$i]);
            }
            return !$ret;
        }
    }
}
```

An even better solution: update to PHP 7. As of January 1st, 2019, PHP 5 is no longer supported by PHP.

**Comment by andreaswork** [comment]
Yes using PHP Version 5.5.9, will have to update. Fix works, thank you!
