### ISSUE TITLE
Catalan translation language file to be added, please

### ISSUE THREAD

**Issue by caos30** [phpservermon/phpservermon#731]
I've created a language file for catalan, for my personal use. But it would be great if any of the administrators of the project can add it to the /src/lang/ directory ;-)

I uploaded a [ZIP file](https://imasdeweb.com/_DOC/ca_ES.lang.zip) to my server containing the php language file. 
Thanks in advance! This software is great.
Sergi

**Comment by TimZ99** [comment]
Could you submit a pr 👍🏼
________________________________
Van: caos30 <notifications@github.com>
Verzonden: vrijdag, mei 17, 2019 3:04 AM
Aan: phpservermon/phpservermon
CC: Subscribed
Onderwerp: [phpservermon/phpservermon] Catalan translation language file to be added, please (#731)


I've created a language file for catalan, for my personal use. But it would be great if any of the administrators of the project can add it to the /src/lang/ directory ;-)

I uploaded a ZIP file<https://imasdeweb.com/_DOC/ca_ES.lang.zip> to my server containing the php language file.
Thanks in advance! This software is great.
Sergi

**Comment by caos30** [comment]
Thanks! I've done just now, following your suggestion. :-)
