### ISSUE TITLE
Users table is unreadable

### ISSUE THREAD

**Issue by dktcoding** [phpservermon/phpservermon#736]
The `Servers` column in the `Users` tab is very hard to read:

![Screen Shot 2019-05-19 at 19 45 36](https://user-images.githubusercontent.com/709639/57989494-bb132d00-7a71-11e9-82d5-f42cab2acb78.png)

Perhaps a table format such as:

<table>
    <thead>
        <tr> 
            <th> User </th>
            <th> Name </th>
            <th> Email </th>
            <th> Level </th>
            <th> Mobile </th>
        </tr>
    </thead>
    <tbody>
        <tr> 
            <td> user1 </td>
            <td> Example User 1 </td>
            <td> user@example.com </td>
            <td> Administrator </td>
            <td> 123-4567890 </td>
        </tr>
        <tr>
            <td rowspan=5 colspan=2 align="right"><b>Servers:</b></td>
            <td colspan=3><a href="">Server 1</a></td>
        </tr>
        <tr>
            <td colspan=3><a href="">Server 2</a></td>
        </tr>
        <tr>
            <td colspan=3><a href="">Server 3</a></td>
        </tr>
        <tr>
            <td colspan=3><a href="">Server 4</a></td>
        </tr>
        <tr>
            <td colspan=3><a href="">Server 5</a></td>
        </tr>
        <tr> 
            <td> user2 </td>
            <td> Example User 2 </td>
            <td> user2@example.com </td>
            <td> User </td>
            <td> 098-7654321</td>
        </tr>
        <tr>
            <td rowspan=2 colspan=2 align="right"><b>Servers:</b></td>
            <td colspan=3><a href="">Server 3</a></td>
        </tr>
        <tr>
            <td colspan=3><a href="">Server 4</a></td>
        </tr>
    </tbody>
</table>

Might be easier to use (including links to the server's status page).

Regards!

**Comment by dktcoding** [comment]
There's a bit of _killer_ debugging code left: https://github.com/phpservermon/phpservermon/commit/5d81d560e6ef275f8a2cadb297a89c17f341d124#r33626316

**Comment by TimZ99** [comment]
Whoops! Removed it in 66996f0. Thanks for noticing.
