### ISSUE TITLE
Automatic Updates not working

### ISSUE THREAD

**Issue by xcellenceit** [phpservermon/phpservermon#737]
We are using 3.1.1, however since last few weeks we noticed that automatic updates has stopped. And we need to click update button then only it works. The configurations are all good.

Can someone point us at what could be wrong? And how to fix?

**Comment by TimZ99** [comment]
Try to add the following to your `config.php` file:
```
// PHP 7.0.0 and higher
define('PSM_CRON_ALLOW', array("your_ip"));
// lower versions
define('PSM_CRON_ALLOW', serialize(array("your_ip")));
```

**Comment by xcellenceit** [comment]
this doesn't solve it! What could be wrong? Any idea how to fix it?

**Comment by TimZ99** [comment]
If it suddenly stopped working, it’s probably not PSM that’s causing trouble. Is your cron running properly?
________________________________
Van: Krunal <notifications@github.com>
Verzonden: Monday, July 1, 2019 6:41:10 AM
Aan: phpservermon/phpservermon
CC: Tim; Comment
Onderwerp: Re: [phpservermon/phpservermon] Automatic Updates not working (#737)


this doesn't solve it! What could be wrong? Any idea how to fix it?

**Comment by xcellenceit** [comment]
Can you share Cron that I should be checking?

**Comment by xcellenceit** [comment]
I am using this cron job.

*/5 | * | * | * | * | /usr/local/bin/php /home/uptimete/public_html/phpservermon/cron/status.cron.php
-- | -- | -- | -- | -- | --

Its defined under cPanel

**Comment by TimZ99** [comment]
This was what I needed to do to setup a cron job using cPanel: [docs](http://docs.phpservermonitor.org/en/latest/install.html#cpanel).
