### ISSUE TITLE
Some advice

### ISSUE THREAD

**Issue by helloxz** [phpservermon/phpservermon#739]
1. It is recommended to add server groups
2. Monitoring can add notes
3. It is suggested to add a public page for visitors to view

**Comment by BasicWombat** [comment]
#746 

We need a place to list feature requests (unless there is already one and I don't know about it)

**Comment by mooleshacat** [comment]
This is what I need the most... Group a bunch of servers into a "folder" and check them all...

Duplicate:
https://github.com/phpservermon/phpservermon/issues/190
