### ISSUE TITLE
Servers table looks weird

### ISSUE THREAD

**Issue by dktcoding** [phpservermon/phpservermon#742]
The servers table columns look weird... it appears to be the `class="full"`

![Screenshot from 2019-06-05 20-39-33](https://user-images.githubusercontent.com/709639/58997369-abfedf80-87d2-11e9-88bb-656989e35136.png)

**Comment by TimZ99** [comment]
The latest version:
<img width="1129" alt="Schermafbeelding 2019-07-18 om 15 12 21" src="https://user-images.githubusercontent.com/15219858/61469653-1c228880-a96f-11e9-9c6d-2fc786bf6cf0.png">
Without `class="full"`:
<img width="1133" alt="Schermafbeelding 2019-07-18 om 15 12 49" src="https://user-images.githubusercontent.com/15219858/61469654-1c228880-a96f-11e9-8c72-22121d97c5e7.png">
I don't want the scrollbar.
