### ISSUE TITLE
Notification and display issues

### ISSUE THREAD

**Issue by zeas62** [phpservermon/phpservermon#744]
Good morning, everyone,

I am new on PHPSERVERMON I have version 3.3.2 and I have problems: 

- I don't receive any notifications: neither emails nor sms (SMSFreeMobile) but the tests work.

- When I click on "update" I get a white window.

I'm sorry for my approximate English.

In advance I thank you for your contribution.

Zeas62

**Comment by TimZ99** [comment]
Hopefully updating to the latest version will work for you. Reopen is not.
