### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by plegrand1** [phpservermon/phpservermon#746]
Hello,
i've got some question about some improvements
- would it be possible to be able to define in one server several services instead of one (ping + some ports tests) ?
- would it be possible to add icon for each machine?
- Moreover would it be possible to add a field "comments" to document each machine?
Thanks for your great app.

**Comment by BasicWombat** [comment]
@plegrand1 

> would it be possible to be able to define in one server several services instead of one (ping + some ports tests) ?

This would be great to be able to bundle services under a single host. We're entering Nagios territory here, but I love that. Nagios is way too hard to configure for simple uses.

> would it be possible to add icon for each machine?

+1 to this. 

> Moreover would it be possible to add a field "comments" to document each machine?

+1 to this as well.

To add your list of Feature Requests, I would like an Acknowledgement button for failures, with a notes field. Sometime you know that a service is down, but letting your team know that it's down is important. This would be a handy little feature.
