### ISSUE TITLE
Ping local ip 

### ISSUE THREAD

**Issue by wandersonbrazdf** [phpservermon/phpservermon#748]
Hello friends, how are you.

I am trying to deploy this tool in the local network of the company we have vpns that communicate the desktop with the stores I put the function of ping with the internal and external ip of a store but I have the error message of the attached print I saw that the ping needs of root access I have the root of the machine how can I configure it to work correctly ping

thanks for the help

![gith](https://user-images.githubusercontent.com/40546756/60144510-0b7c5980-9799-11e9-955b-323bc22a1ea2.png)

**Comment by BasicWombat** [comment]
Forcing the ping (or Update button) will result in this error for me.
However letting the [cronjob run ](http://docs.phpservermonitor.org/en/latest/install.html#setting-up-a-cronjob)on it's schedule and the ping should work fine.

As long as you have followed the guide to configure your installation, it should work fine.
http://docs.phpservermonitor.org/en/latest/install.html#configure-your-installation

**Comment by TimZ99** [comment]
You need root to ping. Cron runs probably as root.

**Comment by mouradev1** [comment]
Last error output:
Could not get headers. probably HTTP 50x error.
