### ISSUE TITLE
Blank Page At Config Page After Upgrading

### ISSUE THREAD

**Issue by RileyMarquis3** [phpservermon/phpservermon#753]
After upgrading from 3.2.1 and keeping my config.php, everything works, except the Config page.

I enabled the debug option in config.php, and here is what came up:
Parse error: syntax error, unexpected 'servidores' (T_STRING), expecting ')' in /home/tcshost_samurai/samurai.tcshosting.net/src/lang/es_ES.lang.php on line 361

Love the improved interface, BTW!

**Comment by TimZ99** [comment]
Line 361 should be 
`'combi_email_subject' => 'IMPORTANTE: %UP% servidores están en línea, %DOWN% servidores están ahora fuera de línea',`

and line 362 
`'combi_pushover_subject' => '%UP% servidores están en línea, %DOWN% servidores están ahora fuera de línea',`

in /home/tcshost_samurai/samurai.tcshosting.net/src/lang/es_ES.lang.php.
Will create an update for this later. 👍

**Comment by RileyMarquis3** [comment]
The fix you listed above worked perfectly!  Thanks!

**Comment by TimZ99** [comment]
Fixed in 9c16883 on juli 18.
