### ISSUE TITLE
Incorrect timezone in Log

### ISSUE THREAD

**Issue by Maksim-us** [phpservermon/phpservermon#754]
It seems the information in the Log is recorded Using UTC even though in the graph the time shows the correct (CDT) time.
Graph shows outage from 00:11 to 00:41
![image](https://user-images.githubusercontent.com/29838695/61457910-fa091600-a92e-11e9-86ec-69231a728a24.png)
Log shows 05:11 to 05:41
![image](https://user-images.githubusercontent.com/29838695/61457988-350b4980-a92f-11e9-9aec-2dd9130010cc.png)

php.info shows the correct timezone. Server timezone is also correct.
date_default_timezone_get() produces:
`The current server timezone is: America/Chicago18/07/2019 07:41:40 am`

**Comment by TimZ99** [comment]
Try changing 
`return strftime('%x %X', strtotime($time));` 
to 
`return $time;` 
in [this](https://github.com/phpservermon/phpservermon/blob/fc5110b1747c39b3a595551790dd5fc72dd709ba/src/includes/functions.inc.php#L457) file.

**Comment by Maksim-us** [comment]
didn't help.
Graph:
![image](https://user-images.githubusercontent.com/29838695/61469372-aef9fd80-a944-11e9-9a31-0432d7cfbf1a.png)

Log:
![image](https://user-images.githubusercontent.com/29838695/61469501-ed8fb800-a944-11e9-954e-c48306bddeaa.png)

Edit: I am running v. 3.2.0. Should I be running 3.3.2?

**Comment by TimZ99** [comment]
You should always be on the latest version 😄.

v3.4 has a new graph. The logs show you the server time and the graph shows your local time.
What would you prefer, the time being displayed as your local time or the server time?

**Comment by Maksim-us** [comment]
Ideally, they should be the same. My server time and my local time are the same:

> $ timedatectl
>       Local time: Thu 2019-07-18 12:22:42 CDT
>   Universal time: Thu 2019-07-18 17:22:42 UTC
>         RTC time: Thu 2019-07-18 17:22:42
>        Time zone: America/Chicago (CDT, -0500)
>  Network time on: yes
> NTP synchronized: yes
>  RTC in local TZ: no

**Comment by Maksim-us** [comment]
I updated to 3.3.2 and the issues is still the same.

**Comment by baur** [comment]
Same problem #1163
