### ISSUE TITLE
Randomly stopped working?

### ISSUE THREAD

**Issue by Kopertje** [phpservermon/phpservermon#760]
Hi there,
I was useing version 3.2.2 but that one stopped working for some weird reason, no errors in the /var/log/httpd/error.log or database error's.. when i edit/add a new server to PSM the server is not edited or added to the server list, i just get redirected to the overview of servers.
So i thought, oke, ill install a new one with the newest version and import my old database. Done that, but some issues.. Is there someone else who had these weird problems?

Kind Regrads,
Robin

**Comment by Kopertje** [comment]
It seems that it doesnt write anything to the database when i add or eddit something. I can clear the logs tho... im using PHP 7.2 and  5.5.60-MariaDB.

**Comment by TimZ99** [comment]
Think it's a problem on your side. If it suddenly stops working, its probably not PSM. Have you enabled debug on PSM?
