### ISSUE TITLE
Version 3.4.0 some servers are offline without checking if they really are

### ISSUE THREAD

**Issue by taavit21** [phpservermon/phpservermon#761]
Version 3.4.0 some servers are offline without checking if they really are.

![servermonitor](https://user-images.githubusercontent.com/47745930/62618697-8b135180-b91d-11e9-98d6-ae809be9cfb1.PNG)

**Comment by TimZ99** [comment]
Please provide more info. 
Do you check a service or a website?
Are you sure that some other check isn't failing, like a pattern?
What is the error output?

**Comment by TimZ99** [comment]
Feel free to reopen.
