### ISSUE TITLE
User tab don't work 

### ISSUE THREAD

**Issue by EgoLeX** [phpservermon/phpservermon#762]
Hello,
i'm not sure if this issue is only coming because i'm working localy with Xampp. But the user tab seems to be not working. If i click in the navbar on the user tab i get an HTTP ERROR 500.
I'm testing this little tool locally before putting it on my server but this is one of the only problems i got / found.

**Comment by bitwit42** [comment]
in the file <path to phpservermon>/src/psm/Module/User/Controller/UserController.php
I added   $action = NULL as parameter to the run function.
Now the user tab works for me with php 7.2.19-0ubuntu0.18.04.2

Like this:
      public function run($action = NULL) {

**Comment by EgoLeX** [comment]
Thank you. It works.
Greets from Germany
