### ISSUE TITLE
unable to use update button after installation

### ISSUE THREAD

**Issue by morteza3000** [phpservermon/phpservermon#768]
Hi, 
I just installed version 3.2.0 but update part is not working and I faced with below error.

Fatal error: Uncaught Error: Call to undefined function psm\Util\Server\Updater\socket_create() in C:\xampp\htdocs\phpservermon\src\psm\Util\Server\Updater\StatusUpdater.php:154 Stack trace: #0 C:\xampp\htdocs\phpservermon\src\psm\Util\Server\Updater\StatusUpdater.php(94): psm\Util\Server\Updater\StatusUpdater->updatePing(2) #1 C:\xampp\htdocs\phpservermon\src\psm\Util\Server\UpdateManager.php(71): psm\Util\Server\Updater\StatusUpdater->update('6') #2 C:\xampp\htdocs\phpservermon\src\psm\Module\Server\Controller\UpdateController.php(44): psm\Util\Server\UpdateManager->run() #3 C:\xampp\htdocs\phpservermon\src\psm\Module\AbstractController.php(191): psm\Module\Server\Controller\UpdateController->executeIndex() #4 C:\xampp\htdocs\phpservermon\src\psm\Module\AbstractController.php(162): psm\Module\AbstractController->runAction('index') #5 C:\xampp\htdocs\phpservermon\src\psm\Router.php(102): psm\Module\AbstractController->run('index') #6 C:\xampp\htdocs\phpservermon\index.php(42): psm\Router->run('server') #7 {main} thrown in C:\xampp\htdocs\phpservermon\src\psm\Util\Server\Updater\StatusUpdater.php on line 154

**Comment by TimZ99** [comment]
Try [this](https://stackoverflow.com/questions/6137823/fatal-error-call-to-undefined-function-socket-create).

**Comment by TimZ99** [comment]
See #784.
