### ISSUE TITLE
v3.4?

### ISSUE THREAD

**Issue by BeecherNetworks** [phpservermon/phpservermon#769]
The README says the latest version is 3.4 but the latest release is 3.3.2? I'm having trouble with doubled push messages and missing RUNNING notices, when will 3.4 be released?

**Comment by TimZ99** [comment]
There was one feature left in the 3.4 project. That’s why 3.4 wasn’t officially released. This feature has been moved to a next version. 
V3.4.1 is the latest release as of yesterday.
