### ISSUE TITLE
adding password fails

### ISSUE THREAD

**Issue by jmcgranahan** [phpservermon/phpservermon#771]
Using 3.4.1, downloaded from GitHub - Tried adding a username/password for one of my servers to monitor and it fails with this error:
[Fatal error: Uncaught Error: Call to undefined function mcrypt_create_iv() in /apps/phpservermon-develop/src/includes/functions.inc.php:768 Stack trace: #0 /apps/phpservermon-develop/src/psm/Module/Server/Controller/ServerController.php(247): psm_password_encrypt() #1 /apps/phpservermon-develop/src/psm/Module/AbstractController.php(193): psm\Module\Server\Controller\ServerController->executeSave() #2 /apps/phpservermon-develop/src/psm/Module/AbstractController.php(164): psm\Module\AbstractController->runAction() #3 /apps/phpservermon-develop/src/psm/Router.php(102): psm\Module\AbstractController->run() #4 /apps/phpservermon-develop/index.php(42): psm\Router->run() #5 {main} thrown in /apps/phpservermon-develop/src/includes/functions.inc.php on line 768](url)

**Comment by TimZ99** [comment]
#491
