### ISSUE TITLE
after update to 3.4.1 not work auto refresh

### ISSUE THREAD

**Issue by ale82x** [phpservermon/phpservermon#772]
i updated correctly from 3.3.2 to 3.4.1.
but status page not auto refresh and when i set 10 (sec) in config and click save , this value not saved...
i see only 0 sec...

thank you

**Comment by TimZ99** [comment]
Whoops I probably forgot or used the wrong variable. Will have a look at it!

**Comment by ale82x** [comment]
ok thank you.

can i fix or i wait to next release?

thank you in advance

**Comment by DominikWA** [comment]
Same problem for me, using nginx.

**Comment by DominikWA** [comment]
To set the auto_refresh_servers value to 10 in the monitor_config DB table did not solve to problem.

**Comment by TimZ99** [comment]
A wrong variable and old an id where used. Should be working now!
