### ISSUE TITLE
non login option

### ISSUE THREAD

**Issue by jmcgranahan** [phpservermon/phpservermon#773]
The previous version of PHP Monitor allowed us to display a status page of select resources to an account that did not require a user to login. We used this to show the status of our various systems to all of our users, especially Administrators. With the 3.4.1 version, however, I haven't figured out a way to do this. Is this available?

**Comment by TimZ99** [comment]
I believe that v3.4.1 didn’t change the login part.

**Comment by jmcgranahan** [comment]
Unfortunately, it's still not working for us - https://monitor.library.vanderbilt.edu/?&kl=prodnon - this used to give the public a view of our current status of all of our systems without having to log in. Now it prompts users to log in. This is a problem and I'm not sure of an easy solution.

**Comment by jmcgranahan** [comment]
Just to update this - using the post here - https://sourceforge.net/p/phpservermon/discussion/845823/thread/f1b2e4ff/ - I added the following code to Users.php which has resolved our issue:
```
  if ($_GET["kl"] == "public"){
     $user_id = 2;
     $this->setUserLoggedIn($user_id, true);
     $user = $this->getUser($user_id);
     $this->newRememberMeCookie();
  }
```
Now I just need to get the options removed, but that can wait until Monday.
