### ISSUE TITLE
GraphHistory is only loading records for one month

### ISSUE THREAD

**Issue by rabauss** [phpservermon/phpservermon#774]
The generateGraphHistory is only loading records for one month - because of this line:

https://github.com/phpservermon/phpservermon/blob/b0ea45ae76d8b2f83ac63c6e4833de71a3d14b00/src/psm/Util/Server/HistoryGraph.php#L147

The `$month` should be replaced by `$year` or `$start_time`, shouldn't it?

**Comment by TimZ99** [comment]
Done ✅
