### ISSUE TITLE
Service update not honoring the timeout

### ISSUE THREAD

**Issue by dktcoding** [phpservermon/phpservermon#775]
In:

https://github.com/phpservermon/phpservermon/blob/b0ea45ae76d8b2f83ac63c6e4833de71a3d14b00/src/psm/Util/Server/Updater/StatusUpdater.php#L218

The timeout argument is hardcoded to `10` instead of using `$this->server['timeout']`.

**Comment by TimZ99** [comment]
Fixed 👍

**Comment by dktcoding** [comment]
Sorry for reopening the issue, but no service is being scanned with `$this->server['timeout']`... I have no idea why... (works with the hardcoded 10...)
