### ISSUE TITLE
Servers table layout: Multiple line breaks

### ISSUE THREAD

**Issue by qx54** [phpservermon/phpservermon#779]
The new table layout results in multiple line breaks in the Label and Domain/IP fields, see screenshot:

![Embedding images in Github issues sucks](https://i.imgur.com/wfxLkuX.png)

It doesn't look nearly as neat as in https://github.com/phpservermon/phpservermon/issues/742

**Comment by TimZ99** [comment]
I agree, but I’m really not a fan of the scroll bar. Maybe you can find a better alternative?

**Comment by JIGR1969** [comment]
I also agree on this and amended the template file, "/src/templates/default/module/server/server/list.tpl.html", to match my requirements. Obviously if there's an update, then it may be overwritten, but provided you know what you changed your version to, shouldn't be much of a problem.

```
                        <tr>
                                <!--class="d-none d-lg-table-cell"-->
                                <th scope="col">{{ label_label }}</th>
                                <th scope="col">{{ label_domain }}</th>
                                <th scope="col" style="width: 5%;">{{ label_port }}</th>
                                <th scope="col" style="width: 8%;">{{ label_type }}</th>
                                <th scope="col" style="width: 8%;">{{ label_rtime }}</th>
                                <th scope="col" style="width: 10%;">{{ label_last_online }}</th>
                                <th scope="col" style="width: 10%;">{{ label_last_offline }}</th>
                                <th scope="col" style="width: 10%;">{{ label_monitoring }}</th>
                                {% if user_level == 10 %}
                                <th scope="col" style="width: 5%;">&#32</th>
                                {% endif %}
                        </tr>
```
