### ISSUE TITLE
Upgrade from 3.2.0 to 3.4.1 - Error 500 after first logon

### ISSUE THREAD

**Issue by red-erik** [phpservermon/phpservermon#780]
Hello,
after the upgrade I receive "error 500" only, without other errors.

Regards.

Red.

**Comment by TimZ99** [comment]
Did you run install.php and enable debug mode?

________________________________
Van: red-erik <notifications@github.com>
Verzonden: Tuesday, September 24, 2019 4:15:03 PM
Aan: phpservermon/phpservermon <phpservermon@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [phpservermon/phpservermon] Upgrade from 3.3.0 to 3.4.1 - Error 500 after first logon (#780)


Hello,
after the upgrade I receive "error 500" only, without other errors.

Regards.

Red.

**Comment by red-erik** [comment]
Hello,
I run it without error. Database Update done and fine but nothing else...

**Comment by TimZ99** [comment]
Did you dan php composer.phar update?
________________________________
Van: red-erik <notifications@github.com>
Verzonden: Tuesday, September 24, 2019 5:06:37 PM
Aan: phpservermon/phpservermon <phpservermon@noreply.github.com>
CC: Tim <tim.zandbergen@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [phpservermon/phpservermon] Upgrade from 3.2.0 to 3.4.1 - Error 500 after first logon (#780)


Hello,
I run it without error. Database Update done and fine but nothing else...

**Comment by red-erik** [comment]
yes..but with an error on the last phase (I'm on Windows and I don't have GIT commands). If I can  download and install something else....
P.S. For Windows users "SET HTTP_PROXY=http://username:password@proxy.yourdomain.com:8080 && php composer.phar install"

**Comment by TimZ99** [comment]
- What error do you get?
- Could you run php composer.phar diagnose.
- Have you checked the Apache/ngix error files?

I will add a version to the release with the new dependencies pre-installed
________________________________
Van: red-erik <notifications@github.com>
Verzonden: dinsdag, september 24, 2019 5:30 PM
Aan: phpservermon/phpservermon
CC: Tim; Comment
Onderwerp: Re: [phpservermon/phpservermon] Upgrade from 3.2.0 to 3.4.1 - Error 500 after first logon (#780)


yes..but with an error on the last phase (I'm on Windows and I don't have GIT commands). If I can download and install something else....
P.S. For Windows users "SET HTTP_PROXY=http://username:password@proxy.yourdomain.com:8080 && php composer.phar install"

**Comment by red-erik** [comment]
I don't use Apache but IIS and I don't see any error. After logon the page is blank and I receive a 500 error. I rolled back to prevous relese and everything is working as expected.
Waiting your new version with all dependencies.
Regards.

Red.

**Comment by TimZ99** [comment]
Can we close this issue?
