### ISSUE TITLE
Upgrade from 3.4.0 to 3.4.4 all custom port check failing

### ISSUE THREAD

**Issue by red-erik** [phpservermon/phpservermon#787]
Hello,
after the upgrade, all checks defined as "service- Custom port" or "service- known port" are failing.
All website checks are fine
Regards.

Red,

**Comment by red-erik** [comment]
With DEBUG Mode on, I receive

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Notice: Undefined index: last_output in C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php on line 162

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1 in C:\Reports\ServMon\src\psm\Service\Database.php on line 544

Warning: Cannot modify header information - headers already sent by (output started at C:\Reports\ServMon\src\psm\Util\Server\Updater\StatusUpdater.php:162) in C:\Reports\ServMon\src\psm\Module\Server\Controller\UpdateController.php on line 48

Fatal error: Redirect failed. in C:\Reports\ServMon\src\psm\Module\Server\Controller\UpdateController.php on line 49

**Comment by tpokorra** [comment]
This behaviour for checking services is caused by this commit: https://github.com/phpservermon/phpservermon/commit/4ebe934b2e1ceb3915292a5a80a028c6700c98f6#diff-180eaf5857e48996ab0732c98885d77e

For existing services, the timeout value is now 0.
So the workaround is to edit each service, and change the timeout value to 10. Then it works fine.
