### ISSUE TITLE
Best Practice to upgrade from v3.3.2 to v3.4.4

### ISSUE THREAD

**Issue by latency0ms** [phpservermon/phpservermon#788]
What needs to be considered to ensure a smooth upgrade from version 3.3.2 to version 3.4.4?

**Environment:**
Server version: Apache/2.4.23 (Win64)
MySQL Server: 5.7.15
PHP Version 5.6.25

Thank you.

**Comment by latency0ms** [comment]
I just found http://docs.phpservermonitor.org/en/latest/install.html#upgrade

After replacing the files (except config.php), I am getting an "**Internal Server Error**" message.

`define('PSM_DEBUG', true);` has been enabled

**Comment by TimZ99** [comment]
Did you update the dependencies using composer?
________________________________
Van: latency0ms <notifications@github.com>
Verzonden: Monday, September 30, 2019 11:59:56 AM
Aan: phpservermon/phpservermon <phpservermon@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [phpservermon/phpservermon] Best Practice to upgrade from v3.3.2 to v3.4.4 (#788)


I just found http://docs.phpservermonitor.org/en/latest/install.html#upgrade

After replacing the files (except config.php), I am getting an "Internal Server Error" message.

define('PSM_DEBUG', true); has been enabled

**Comment by latency0ms** [comment]
Nope I didn't.

Also on Sourceforge there is no version 3.4.4 available http://sourceforge.net/projects/phpservermon/files/phpservermon/

Is there any pre-built package of version 3.4.4 available?

**Comment by TimZ99** [comment]
Unfortunately I only have access to the Github repos, nothing else. Pre-build wil be available later today 👍🏼
________________________________
Van: latency0ms <notifications@github.com>
Verzonden: maandag, september 30, 2019 12:42 PM
Aan: phpservermon/phpservermon
CC: Tim; Comment
Onderwerp: Re: [phpservermon/phpservermon] Best Practice to upgrade from v3.3.2 to v3.4.4 (#788)


Nope I didn't.

Also on Sourceforge there is no version 3.4.4 available http://sourceforge.net/projects/phpservermon/files/phpservermon/

Is there any pre-built package of version 3.4.4 available?

**Comment by latency0ms** [comment]
I assume you will release the Pre-Built version on Sourceforge?

Looking forward to it. Thank you.

**Comment by TimZ99** [comment]
No, I only have access to the github repos, not to sourceforge. I just added a pre-build on the Github release.
________________________________
Van: latency0ms <notifications@github.com>
Verzonden: Monday, September 30, 2019 12:54:19 PM
Aan: phpservermon/phpservermon <phpservermon@noreply.github.com>
CC: Tim <tim.zandbergen@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [phpservermon/phpservermon] Best Practice to upgrade from v3.3.2 to v3.4.4 (#788)


I assume you will release the Pre-Built version on Sourceforge?

Looking forward to it. Thank you.

**Comment by latency0ms** [comment]
> I just added a pre-build on the Github release.

Thats even better, thank you! I'll give it a shot.

**Comment by latency0ms** [comment]
Same problem / error with the Pre-Built package of version 3.4.4

**Internal Server Error**

**Comment by baur** [comment]
Blank install and manual export & import

**Comment by TimZ99** [comment]
Could you check the Apache error log?

**Comment by latency0ms** [comment]
I will check the logfiles this weekend and publish the results.

**Comment by TimZ99** [comment]
Any updates?

**Comment by latency0ms** [comment]
I haven't had time so far, but it should be possible next week. Keep it locked!
