### ISSUE TITLE
Lack of new version info in footer.

### ISSUE THREAD

**Issue by pawelantczak** [phpservermon/phpservermon#789]
As per title. Version scrapping from github doesn't work apparently.

**Comment by TimZ99** [comment]
It updates ones every week, I already chanced this to ones a day.
________________________________
Van: Paweł Antczak <notifications@github.com>
Verzonden: Monday, September 30, 2019 6:54:58 PM
Aan: phpservermon/phpservermon <phpservermon@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [phpservermon/phpservermon] Lack of new version info in footer. (#789)


As per title. Version scrapping from github doesn't work apparently.
