### ISSUE TITLE
Monitor color goes to red bypassing the orange status

### ISSUE THREAD

**Issue by apio-sys** [phpservermon/phpservermon#790]
I'm glad to see this project is being actively worked on again. It's a great tool I've been using for years. I just did a huge upgrade from v3.2.0 (released April 15, 2017) to the current v3.4.5 (released September 30, 2019) and all works well. One point of attention is the time-out field that wasn't there before and at zero most services are considered not to respond in time and will show alerts. So just changed that to 10 and all is well. One minor thing I notice though is that I no longer have the "orange" status for a specific server. Since I have my threshold set to 2, this used to pass the service to orange and during it's next cycle either to red or green again. Maybe this is by design though in the new version ? The status will be "warning" in orange in the service detail page just not on the main overview. Might be a good thing to bring back I reckon. Other than that all good.

Thanks !

Joris.

**Comment by TimZ99** [comment]
I probably forgot to put that back in. Will have a look at it.
