### ISSUE TITLE
3.4.5 upgrade from previous versions

### ISSUE THREAD

**Issue by red-erik** [phpservermon/phpservermon#792]
Hello,
With debug enable I receive:
Notice: Undefined offset: 2 in C:\Reports\ServMon\src\includes\functions.inc.php on line 482
Notice: Undefined offset: 2 in C:\Reports\ServMon\src\includes\functions.inc.php on line 482
Notice: Undefined offset: 2 in C:\Reports\ServMon\src\includes\functions.inc.php on line 483
Warning: SQL error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value' cannot be null in C:\Reports\ServMon\src\psm\Service\Database.php on line 544
Notice: Undefined offset: 2 in C:\Reports\ServMon\src\includes\functions.inc.php on line 489
Notice: Undefined offset: 2 in C:\Reports\ServMon\src\includes\functions.inc.php on line 491

you can solve it by disabling updates check in config.php
define('PSM_UPDATE', false);

The same problem on "check on well known services" or "custom defined services" remains.
See #787
Regards.

Red.

**Comment by TimZ99** [comment]
Could you change line 489 to `if ($latest !== false) {` and check if it's fixed?

**Comment by red-erik** [comment]
Hello,
after modifying line 489 in functions.inc.php I don't receive any errors but tried a new, fresh installation and ALL servers, anyway configured, are always marked as DOWN.
for every new server I add I receive
Couldn't create socket [10013]: An attempt was made to access a socket in a way forbidden by its access permissions.
Tryed different versions of PHP (php_sockets.dll) with same result.

Regards.

Red.

**Comment by red-erik** [comment]
Hello,
Running on windows 2016, IIS and latest PHP, the solution is to create a dedicated application pool with administrative privileges, convert the virtual directory into an application ad bind it with preceding application pool. Socket error disappeared. Not a directory structure permission problem.
Regards.

Red.
