### ISSUE TITLE
Undefined index: type_ on Servers tab

### ISSUE THREAD

**Issue by BeecherNetworks** [phpservermon/phpservermon#793]
Version 3.4.5, just updated from 3.4.1. Got stuck in an upgrade loop but it has resolved itself now apart from a notice on the Servers tab:

`Notice: Undefined index: type_ in /var/www/3.4.5/src/includes/functions.inc.php on line 66`

What should the index be, or where can I find the SQL?

**Comment by TimZ99** [comment]
Look like it’s in the language part. Which language are you using?
________________________________
Van: Beecher Networks <notifications@github.com>
Verzonden: Friday, October 4, 2019 12:18:41 AM
Aan: phpservermon/phpservermon <phpservermon@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [phpservermon/phpservermon] Undefined index: type_ on Servers tab (#793)


Version 3.4.5, just updated from 3.4.1. Got stuck in an upgrade loop but it has resolved itself now apart from a notice on the Servers tab:

Notice: Undefined index: type_ in /var/www/3.4.5/src/includes/functions.inc.php on line 66

What should the index be, or where can I find the SQL?

**Comment by BeecherNetworks** [comment]
English

**Comment by TimZ99** [comment]
Could you check you db for a server without a type set?

**Comment by BeecherNetworks** [comment]
Not sure I'm following you, this what you mean?

![image](https://user-images.githubusercontent.com/179583/66197928-4133b700-e693-11e9-8d73-9e7f1eeca924.png)

**Comment by TimZ99** [comment]
No I wanted to know if there is a row in the servers table without a type (as in the server type, website, service or ping).

**Comment by BeecherNetworks** [comment]
Got it. Yes indeed, I added a new server recently with the type "ping", and it doesn't have a type in the database. It isn't added with an edit either. I'll try adding it in the table manually, I assume it should be "ping"?

**Comment by TimZ99** [comment]
Indeed.
I guess that you saved the server manual because if you try to do it via the UI it gives an error. The only way I was able to change the type to blank was by changing it directly in the db.

**Comment by BeecherNetworks** [comment]
No, I added it via the UI, and subsequently edited via the UI. The Type isn't saved.

I tried adding a "ping" type in the database manually, but it's an ENUM with only "service" and "website" options, is there supposed to be a "ping" option?

**Comment by BeecherNetworks** [comment]
![image](https://user-images.githubusercontent.com/179583/66573340-68debf80-eb6a-11e9-85be-0b6e136b1a49.png)

**Comment by TimZ99** [comment]
Thats strange. I really don't know how this happened. If you add ping to the set, it will work.

**Comment by BeecherNetworks** [comment]
Yes, I tried that a couple of days later and it seems to have worked. The upgrade loop I mentioned in my first post must have borked the table modifications.

**Comment by travisbotello** [comment]
Same problem here after upgrade. I had to manually add ping as a type to get it working again.
