### ISSUE TITLE
Services with timeout 0

### ISSUE THREAD

**Issue by TimZ99** [phpservermon/phpservermon#794]
This behaviour for checking services is caused by this commit: https://github.com/phpservermon/phpservermon/commit/4ebe934b2e1ceb3915292a5a80a028c6700c98f6#diff-180eaf5857e48996ab0732c98885d77e

For existing services, the timeout value is now 0.
So the workaround is to edit each service, and change the timeout value to 10. Then it works fine.

_Originally posted by @tpokorra in https://github.com/phpservermon/phpservermon/issues/787#issuecomment-538075182_

**Comment by Supportedge** [comment]
Can you make it so the default behaviour when adding a new server will have '10' automatically input. I would pull request it myself but have no idea which file would be responsible.
