### ISSUE TITLE
Cache busting?

### ISSUE THREAD

**Issue by blogtutor** [phpservermon/phpservermon#802]
Is it possible to add a random query string variable to each test, for the purpose of cache busting?

Something like setting up the URL to be checked like this:

`https://www.website.com/?%cachebust%`

...and then the `%cachebust%` would be replaced with a different random string every time the URL is tested.

[Here's how Uptime Robot does this.](https://blog.uptimerobot.com/cachebuster-a-pro-tip-for-bypassing-cache/)

Thanks!

**Comment by TimZ99** [comment]
Would `curl_setopt($ch, CURLOPT_FRESH_CONNECT, 1);` work you think?

**Comment by blogtutor** [comment]
Hey Tim! it looks like CURLOPT_FRESH_CONNECT just forces a "new connection to be used."

The issue is server-side caching, not client-side caching. All of our clients use WordPress with caching plugins (WP Rocket), so stored versions of the pages are saved on the server. In addition, we have the Sucuri Firewall in front of that as a proxy, which also stores HTML at their edge locations.

So, PHP Server Monitor is likely to get a cached response back from either Sucuri or the server itself -- which tests if the cache is working, but doesn't test if the underling server and/or WordPress installation is working.

By adding a random query string to the URL, that will force a bypass of both caches - and cause WordPress to generate a new version of the page.

(Some caching plugins may not bypass with the query string, so this might not be perfect, but I know Sucuri and WP Rocket will; both are quite common).

Hope that helps clarify!
