### ISSUE TITLE
Shared hosting 

### ISSUE THREAD

**Issue by iandk** [phpservermon/phpservermon#803]
Hi, 

Does PHPSM work in shared hosting environments? 

I noticed that the cronjob has to be run as the root user, but I can’t see the reason behind it. 

I’d appreciate an added support for shared hosting accounts with an unprivileged user. 

Thanks!

**Comment by TimZ99** [comment]
Ping requires root, so you only need to run as root if you want to use ping.
________________________________
Van: Ian <notifications@github.com>
Verzonden: Tuesday, October 22, 2019 4:34:36 AM
Aan: phpservermon/phpservermon <phpservermon@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [phpservermon/phpservermon] Shared hosting (#803)


Hi,

Does PHPSM work in shared hosting environments?

I noticed that the cronjob has to be run as the root user, but I can’t see the reason behind it.

**Comment by iandk** [comment]
Isn’t there another option which is also available for non privileged users? 
I just gave it a try, and the command „ping“ is also usable for my shared hosting users, could you explain it a bit further what’s the problem?

**Comment by TimZ99** [comment]
Website and services are available for non-root.
For ping the exec() function is sometimes used, but it differs if it needs root to run. At this moment I don’t have a better alternative for non-root ping. Maybe you can find one?
________________________________
Van: Ian <notifications@github.com>
Verzonden: dinsdag, oktober 22, 2019 7:42 AM
Aan: phpservermon/phpservermon
CC: Tim; Comment
Onderwerp: Re: [phpservermon/phpservermon] Shared hosting (#803)


Isn’t there another option which is also available for non privileged users?
