### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by intervisionlord** [phpservermon/phpservermon#804]
Ver 3.4.5.

After i entered credentials i have redirect to login form again without any error.

**Comment by TimZ99** [comment]
Do you have debug enabled?

**Comment by intervisionlord** [comment]
well... no, but something strange happens: i try to log in now and it was success... strange magic...
Maybe it's because of caching or smth. else?

**Comment by TimZ99** [comment]
Maybe, can't tell. Glad it's working!
