### ISSUE TITLE
Server Downtime is displayed in correctly when receiveing e-mails about it.

### ISSUE THREAD

**Issue by taavit21** [phpservermon/phpservermon#810]
Hello,

My server was down for atleast 4 minutes. I puprosely added search string to something it didn´t exist on the site and the webui also showed downtime for 4 minutes.
Now when i removed the incorrect search string i received e-mail:

Server 'xxxxxxxxx' is running again, it was down for 59 seconds:

While in reality it was down for more than 4 minutes.

**Comment by DominikWA** [comment]
Same on my instance, the server was down for around 12 hours, the email and telegram messages told that the server was down for 2 minutes and a few seconds, when it was up again. On latest version V3.4.5

**Comment by taavit21** [comment]
I should also add that i am running version V3.4.5 with PHP version PHP 7.2.24

**Comment by BeecherNetworks** [comment]
I've been getting reports that look wrong too. For some sites / services I double up with UptimeRobot, and in a lot of cases PHPSM is saying 1-2 minutes, but UR says 4-5 mins. Actually came here today to check for a new version for this reason.

**Comment by wienfuchs** [comment]
There's definately an issue with this, had a downtime of nearly 1 hour on one server yesterday, with server update every 2 minutes, that's how it shows in protocols and notifications:
![grafik](https://user-images.githubusercontent.com/44177781/70514039-181c2080-1b33-11ea-9f0d-78e4d9bf8362.png)

**Comment by Clust3r** [comment]
Hi, 
I have no idea if i have make a Fix patch correctly, but you can find my fix in this pull request: https://github.com/phpservermon/phpservermon/pull/825

**Comment by TimZ99** [comment]
Thanks 👍
