### ISSUE TITLE
Database record update failure

### ISSUE THREAD

**Issue by KminekMatej** [phpservermon/phpservermon#811]
When I run update process, everything passes, website is detected, but no database update is performed. Therefore - system next time thinks the website was down, and sends me email again

**Comment by KminekMatej** [comment]
This is due to the DB field last_output, which is specified as varchar(255). When the output is longer (which is pretty much usual), SQL query fails.

I strongly believe that older MySQL servers just truncated input to 255 chars and just raised a warning. Server 10.3.17-MariaDB-0 emits error instead.

**Comment by KminekMatej** [comment]
Solved by #812

**Comment by benIT** [comment]
A huge thanks for this fix guys !

The change on the  `last_output` field VARCHAR -> TEXT fixes the following error : 

`Warning: SQL error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'last_output' at row 1 in /var/www/alerte/src/psm/Service/Database.php on line 544`


Without your  work, when this warning is triggered, website status does not refresh correctly.

In my case, the website state was offline whereas the CRONJOB returns a 200 http return code.

Hope I will be delivered soon in a production ready release.

Have a nice day guys!
