### ISSUE TITLE
got this error when adding new url

### ISSUE THREAD

**Issue by ranrinc** [phpservermon/phpservermon#816]
I add a correct URL which is https://krdesigns.com

However it fail to add that domain with this error message "The website URL is not valid." 
Help?

**Comment by nvieirapt** [comment]
same here... using latest commit. :(

**Comment by TimZ99** [comment]
The regex got an update, but it apparently doesn’t work as intended. Hope to fix this tomorrow, maybe someone else has time earlier?

**Comment by wienfuchs** [comment]
There is no modifier g for preg_match. Instead, you have to use the preg_match_all function. That's the problem and the solution: omit the "g" at the end of regex in line 92 in src/psm/Util/Server/ServerValidator.php and use preg_match_all instead:
`if (!preg_match_all("/(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,12}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)/", $value)) {`

**Comment by TimZ99** [comment]
Thanks @wienfuchs 👍
