### ISSUE TITLE
Monitoring for expired SSL certs

### ISSUE THREAD

**Issue by brad1001** [phpservermon/phpservermon#820]
Hi there

I would like to monitor Let's Encrypt certs to ensure that websites are loading and displaying correctly.

Would anyone know how to setup a monitoring service that would trigger an alert if a certificate was not valid (failed to auto renew) .

It seems that the standard monitoring still finds the website active with or without a valid certificate (as the error warning are browser based and not bot based - I presume)

Any help would be greatly appreciated.

Brad

**Comment by DominikWA** [comment]
You could look into this PR https://github.com/phpservermon/phpservermon/pull/494

**Comment by brad1001** [comment]
Hi Dominik 
Thank you for your comment and link.
Yes that looks like what I am after.
May I ask for further assistance - please 
I currently have version 3.4.5 running  -  how do I implement this patch mentioned 494

Kind Regards
Brad

**Comment by TimZ99** [comment]
Could someone test/review #831?

**Comment by DominikWA** [comment]
> 
> 
> Could someone test/review #831?

I would like to do so, but ever time i install via git (+ composer.phar install ) independently of the branch, i only get a white page. If i unzip a pre-built package in the same dir, everything works like expected.

EDIT: php7.0 was the problem, at least php7.1 is required to be compatible with the code used.
