### ISSUE TITLE
Adding authentication settings to a server fails

### ISSUE THREAD

**Issue by zottto** [phpservermon/phpservermon#822]
I'm trying to add authentiction settings to a server (Apache BasicAuth), but whenever I add username and password there and it save, I get an error:

- on version 3.2.0: I got an server error 500 (with nothing helpful in the server error log)
- after an update to 3.4.5: I just get an empty white page. After reloading the settings site I can see that my authentication details are not saved.

Additionally I can see in the source code that the password field has a maxlength="10" attribute, but my password is longer than 10 characters.

Do you have any hints for my how I can solve this issue?

Thanks,
Marc

**Comment by wienfuchs** [comment]
Maybe https://github.com/phpservermon/phpservermon/commit/7e3cbc94a95a736781bc388504247a0c0c598e33 is the solve for your problem? What PHP Version do you use - if higher then 7.0 this should be the issue?

**Comment by zottto** [comment]
@wienfuchs Mmmh, not really, but at least partly.
- I replaced functions.inc.php from the mentioned commit. That helped, because saving the settings does not result in a white screen

- the maxlength of the input field for the password ist still "10", which does not allow passwords with more than 10 characters (I tricked that by changing the HTML in the browser for testing)

- reloading the server settings does not show any saved username/password and the server is still "offline" with an 401 status error

**Comment by TimZ99** [comment]
> * the maxlength of the input field for the password ist still "10", which does not allow passwords with more than 10 characters (I tricked that by changing the HTML in the browser for testing)

Got fixed with #796.

> * reloading the server settings does not show any saved username/password and the server is still "offline" with an 401 status error

They actually are being saved. Wrong variable is used for the frontend.
