### ISSUE TITLE
Last output data too long

### ISSUE THREAD

**Issue by fv-chrisc** [phpservermon/phpservermon#823]
When updating status, the last output is set as:
$save['last_output'] = substr($this->header,0,5000);

but the table field is a varchar(255). As a result, the database was not updated for one my website that was returning a long output.

Same for last_error_output.

**Comment by wienfuchs** [comment]
AFAIS source of this should be fixed through https://github.com/phpservermon/phpservermon/commit/7f5e69875284187e2fbf49d53899db1be06656a1 - I saw this personally yesterday and simply changed the relevant field in my database manually. This will probably solve your problem too.
Maybe one will write a little code to check and update the database automatic :)

**Comment by TimZ99** [comment]
This will be in the next release and will be fixed on upgrade.
