### ISSUE TITLE
[Feature Request] support xmpp notifications

### ISSUE THREAD

**Issue by albjeremias** [phpservermon/phpservermon#829]
**Is your feature request related to a problem? Please describe.**
I would like to receive notifications in a federated service such as xmpp/jabber

**Describe the solution you'd like**
i just want to implement another notification method cloned from telegram

**Describe alternatives you've considered**
- i can also use email, but i dont see it as often as xmpp
- i am using telegram, but i dont like to use non-opensource proprietary services

**Comment by xsuchy09** [comment]
It is possible but Jabber is so specific ... it can have many troubles with many providers. For example connect to gmail from PHP is not so easy. If we want I can implement for gmail.com method at first ... everyone have or can have gmail.com account.

edit: But you need at least two accounts. One for sending (gmail.com as I suggested) and one for receiving. You can not send message to yourself.

**Comment by xsuchy09** [comment]
Pull request done: #852
You can test it before merging in my fork - branch https://github.com/xsuchy09/phpservermon/tree/feature/xmpp_notifications

I tested it with Google Account successfully. But you have to set specific/right setting.

You can play more with some constants (settings):
```
if (defined('PSM_JABBER_FORCE_TLS') === false) {
	define('PSM_JABBER_FORCE_TLS', true);
}
if (defined('PSM_JABBER_AUTH_TYPE') === false) {
	// possible values: PLAIN, X-OAUTH2, DIGEST-MD5, CRAM-MD5, SCRAM-SHA-1, ANONYMOUS, EXTERNAL
	define('PSM_JABBER_AUTH_TYPE', 'PLAIN'); // default just plain because of google for example :(
}
if (defined('PSM_JABBER_DEBUG_LEVEL') === false) {
	define('PSM_JABBER_DEBUG_LEVEL', JAXLLogger::WARNING);
}
```

Just define them in your own config to replace default settings. But it is prepared for Google Account.

See documentation:
https://github.com/xsuchy09/phpservermon/blob/feature/xmpp_notifications/docs/faq.rst#how-do-i-setup-jabber-notifications-from-google-account

edit: btw app password for Google Account is encrypted before saving in database ... I just notice that smtp_password is not encrypted - it should be solved - security bug (I created #853).

**Comment by albjeremias** [comment]
Not Google.. what a nightmare... :( https://mastodon.social/@FuckOffGoogle
owao nice.. you implemented it.. ill test it.. but i have no google stuff.. i hate google.

**Comment by xsuchy09** [comment]
You can test it with any Jabber account. I just prepare it and test it with Google account (which is great with app password possibility btw ... but you can create special account for this use). Maybe you just need to change default settings with:
```
define('PSM_JABBER_FORCE_TLS', true);
// possible values: PLAIN, X-OAUTH2, DIGEST-MD5, CRAM-MD5, SCRAM-SHA-1, ANONYMOUS, EXTERNAL
define('PSM_JABBER_AUTH_TYPE', 'PLAIN');
```
in your config.php.

So any XMPP account can be used. You just need to find right config. So try it and let me know.

edit: I used https://github.com/jaxl/JAXL/ library and set path to the log to `/logs/jaxl.log` ... so if you will have troubles pls share that log. And you can set the higher log level:
```
// possible values: ERROR, WARNING, NOTICE, INFO, DEBUG
define('PSM_JABBER_DEBUG_LEVEL', JAXLLogger::WARNING);
```
