### ISSUE TITLE
URL not valid

### ISSUE THREAD

**Issue by hamelsveld** [phpservermon/phpservermon#833]
When adding a web server like subdomain.xxxx_xxxx.domain.org

it looks like the "_" is the problem

**Comment by wienfuchs** [comment]
As _ is not a valid sign in DNS (only a-z, 0-9 and - are valid), the regexp is correct and this is _not_ a bug!
Visit: https://en.wikipedia.org/wiki/Domain_Name_System#Domain_name_syntax,_internationalization

**Comment by hamelsveld** [comment]
oops sorry...
