### ISSUE TITLE
[BUG] Ping is not working

### ISSUE THREAD

**Issue by dragelecpc** [phpservermon/phpservermon#835]
Dear,
I choosed ping checking type, but i got red alert all time with ping type, how can i fix it?
thanks

**Comment by TimZ99** [comment]
Which version are you using?

**Comment by dragelecpc** [comment]
> Which version are you using?

Hi, i'm using the latest release v3.4.5

**Comment by wienfuchs** [comment]
It is fixed in development and working fine at my systems.

**Comment by SpcCw** [comment]
Are you running cron task as root?

It never worked for me otherwise.

**Comment by wienfuchs** [comment]
Was before, changed now to latest commit https://github.com/phpservermon/phpservermon/commit/6ba4b5923907df3793b5e22c04cd1335b3d944a7 which solved this point too and works now using exec, so this runs as non-privileged user as well.

**Comment by TimZ99** [comment]
I pushed changes for ping yesterday. You can use the develop branch.

**Comment by wienfuchs** [comment]
@TimZ99: You quoted hashed links to your account settings, which u probably urgently want to remove from github!

**Comment by TimZ99** [comment]
You still need to sign in if you use the url, so I guess it does no harm. Still removed it tho 👍🏼.
