### ISSUE TITLE
Telegram issue

### ISSUE THREAD

**Issue by mattish91** [phpservermon/phpservermon#836]
So after configuring telegram with id and token i get this wierd error, not sure if it's a server side issue on my side or if it just doesn't want to connect to telegram.

"An error has occurred while sending the Telegram notification: Unknown " 

This message appears while im trying to test the connection.

API is a 45 letters, numbers and symbols combination and ChatID is a 9 number configuration right?

ChatID should be located under user config and API in config if im correct? this should be documented more in case i missed something out and i taught it was straight forward this way.

If there is a log for only the telegram notification i can't find it and log i empty.

Also, the server im running this trough is not on port 80 or 443 in case that's a issue to make this work.

**Comment by TimZ99** [comment]
The settings are correct. It says unknown if there is no description in the Telegram response. Add `die(var_dump($result));` [here](https://github.com/phpservermon/phpservermon/blob/0550ff7dcf5162f446188de264fe26f3b302117c/src/psm/Module/Config/Controller/ConfigController.php#L368) and check is you can find a clue why it won't work.

**Comment by coronas2k** [comment]
It might have been an error with the cURL configuration, let me test this out.

**Comment by coronas2k** [comment]
**Update**

It works just make sure you're using the [Telegram BOT API](https://t.me/botfather) and not the Telegram API, the curl method could use refactoring, but I found it fails if your servers ISP blocks Telegram, in that case, `curl_init` would return false and `die(var_dump($result));` would return null. thus resulting in the above error message.

**Comment by TimZ99** [comment]
Don't know why an ISP would ever block Telegram. In the EU this is prohibited by law.
