### ISSUE TITLE
[BUG] Updating via CRON

### ISSUE THREAD

**Issue by NickSchick** [phpservermon/phpservermon#838]
**Updating via CRON**
PSM Vanilla install with the CRON job setup and firing successfully, however, a few things do not seem to work properly.
(e.g.: Hourly chart in Server Page, Last online, Last Check on Default is "about an hour ago")

**Steps to reproduce the behavior (Version 3.4.5):**
1. Download Zip
2. Unpack on Server
3. Run install.php
4. Setup CRON
5. Setup Test Website

**Steps to reproduce the behavior (Version current Development Version):**
1. Download Zip
2. Unpack on Server
3. Run install.php
4. Setup CRON
5. Setup Test Website

**Our Experience**
The red boxes are shown after the CRON runs when clicking "update" all information shows correctly.
![PSM1](https://user-images.githubusercontent.com/32733210/72717438-4b12f480-3b74-11ea-9f62-aa251cb31c28.JPG)

***

![PSM3](https://user-images.githubusercontent.com/32733210/72717519-70076780-3b74-11ea-9fdf-7100731d014d.JPG)
When letting the CRON run without using "?&mod=server_update" - we receive blank graphs for "Hour". However "Day" seems to work
![PSM2](https://user-images.githubusercontent.com/32733210/72717620-ac3ac800-3b74-11ea-8129-eae41488c798.JPG)

***

![PSM5](https://user-images.githubusercontent.com/32733210/72717691-d68c8580-3b74-11ea-9c13-d845c6baaf39.JPG)
On the status page if you use "?&mod=server_update" you will receive proper info in "last online" - however once the CRON runs. 
![PSM4](https://user-images.githubusercontent.com/32733210/72717655-c4124c00-3b74-11ea-98b0-8df4a3970ad5.JPG)

**Additional Information**

- We have 2 versions (3.4.5) and the Current Dev running with the same result.
- We have tried the monitor with "website" and "service" with the same result.
- We receive no errors via the webserver nor from the "define('PSM_DEBUG', true);".
- We see that the CRON does fire because (offline) emails do send, and Last positive output time stamps update and latency numbers also change

**Comment by gitalexa** [comment]
is there any workaround?

**Comment by wienfuchs** [comment]
I don't see this problem existing in v3.4.6-beta.2, but this is an "old" installation, which has been upgraded several times.
![grafik](https://user-images.githubusercontent.com/44177781/76660829-1e7ac800-657a-11ea-84de-f6b87e0f39d2.png)

**Comment by gitalexa** [comment]
Today installed version: 3.4.5

**Comment by TopicsLP** [comment]
Did you check if the System Time matches the time configured in the php.ini?
I had the same issue because my system time was offset by one hour.

Also be sure to configure the timezone in all php.ini files.
`find /etc/ -name "php.ini"`
it returned me two files one for "fpm" and one for "cli"
