### ISSUE TITLE
Wrong mouse cursor icon when hovering over server

### ISSUE THREAD

**Issue by Germs2004** [phpservermon/phpservermon#855]
**Describe the bug**
On the "server_status" page, it lists all my servers.  When I hover my mouse over one of the servers, the mouse cursor looks like the text icon.  This implies that I cannot click the server box like a button.  The cursor should be a hand icon like it is when I hover over "Log" in the top main menu.

**Expected behavior**
Mouse cursor should be a hand icon whenever it's over a link-type or button-type element.

**Desktop (please complete the following information):**
 - Version 3.4.5 Docker image (https://github.com/bpodwinski/docker-phpservermon)

**Comment by TimZ99** [comment]
Since 1d77976 it will show a hand when hovering the label.
