### ISSUE TITLE
[BUG] minor HTML text wrapping issues

### ISSUE THREAD

**Issue by Germs2004** [phpservermon/phpservermon#857]
**Describe the bug**
On same pages, the text wraps around because the containing element is too small.  There's plenty of space on my screen so this can be fixed easily by increasing the size of the container or by changing the text to take up less space.

on page "server_status", using the default boxy view (instead of the row view), the text that says "Last online: about a minute ago" has the word "ago" on a second line because it doesn't all fit on one line due to the size of the green containing element.  This can be fixed by changing the size of the box or by changing the text to something like "< 1 minute ago" instead of "about a minute ago".

on page "server", the table only fills about 60% of my screen's horizontal space, so several of the table cells have wrapping.  It's very distracting and unnecessary.  Please increase the width of the table so the text doesn't have to wrap.  If you want to make it customizable, maybe each column could have a custom width setting, so the user can specify their own preferred widths.  Those settings should be stored in the database so it persists between docker image updates.

**Expected behavior**
Text should not wrap unless really necessary.  It looks nicer, and is easier and faster to read that way.

**Desktop (please complete the following information):**
 - Version 3.4.5

**Comment by TimZ99** [comment]
Let me know what you think.

**Comment by Germs2004** [comment]
Sorry, I'd like to help test since I created the ticket, but I'm not sure how to test it.  I know how to pull the latest docker image from dockerhub, but I don't see any newer images there.  A screenshot of your browser posted here would probably be enough for everyone to give feedback.  Though I'm sure if it looks good to you with the new changes then it's probably great.
Thank you

**Comment by mtelgkamp** [comment]
In my opinion the width of the main container should not be limited for large screens
This is the way the table looks on 1920px width:
![grafik](https://user-images.githubusercontent.com/33117529/76826084-d975c080-681b-11ea-9433-eece40cdbc2b.png)
This is the way I would like to have it look like.
![grafik](https://user-images.githubusercontent.com/33117529/76826163-04f8ab00-681c-11ea-9588-64efbf1d6ece.png)
For three items in the list it is not that important to have on item on one row, but if you have more, every line break in the list makes you scroll more to review all status information.

**Comment by TimZ99** [comment]
I removed the css modifications and just changed container to container-fluid. PSM will now use the full screen (minus padding/margin).

This is how it looks on a 1460px screen.
<img width="1680" alt="Schermafbeelding 2020-05-17 om 20 20 06" src="https://user-images.githubusercontent.com/15219858/82156722-42f66780-987d-11ea-9184-37536e58fa5b.png">
<img width="1680" alt="Schermafbeelding 2020-05-17 om 20 13 11" src="https://user-images.githubusercontent.com/15219858/82156733-4d186600-987d-11ea-8921-7701a2921e6e.png">
