### ISSUE TITLE
[Feature Request] Hide nonfunctional alert method controls and icons

### ISSUE THREAD

**Issue by Germs2004** [phpservermon/phpservermon#858]
**Is your feature request related to a problem? Please describe.**
On the "server" page, it has a table of all the servers. One column has a group of icons representing which alert methods are enabled.  My table shows alert methods that are disabled from the config page (the "Allow sending text messages" textbox is unchecked), so I prefer those icons not appear in this table.  For example, SMS isn't configured for me, so the SMS icon should not appear on the table.

Also, the associated controls on the "Add new" server page should be removed or grayed out if the associated alert method is disabled from the Config page.  So if SMS is not enabled on my system, the SMS section of the "Add new" page should be grayed out or hidden completely.

**Describe the solution you'd like**
Only show the icons for the alert methods that the user should actually expect to work.  If SMS is not configured, the SMS icon should not appear on the table.

Likewise, hide the controls on the "Add new" server page if those controls aren't going to work anyway due to being unconfigured.

**Comment by TimZ99** [comment]
I left the controllers on the "Add new" page. This way you can set every thing up and add the service afterwards without needing to go through all your servers again.
