### ISSUE TITLE
[Question] file permissions

### ISSUE THREAD

**Issue by DanielRuf** [phpservermon/phpservermon#863]
It seems many files have the executable flag and read + write + execute (=7) set which should not be the case:

<img width="449" alt="Bildschirmfoto 2020-02-08 um 22 04 04" src="https://user-images.githubusercontent.com/827205/74092017-1af9aa00-4abf-11ea-8caa-c483248587bb.png">

**Comment by TimZ99** [comment]
Let me know if you find more.
