### ISSUE TITLE
[BUG] Cant check Teamspeak

### ISSUE THREAD

**Issue by Tealk** [phpservermon/phpservermon#865]
**Describe the bug**
Teamspeak is always displayed as offline

**Version (please complete the following information):**
 - Version 3.4.5
 - PHP 7.4.2
 - MariaDB 10.3.22

![image](https://user-images.githubusercontent.com/12276250/74258766-c3418580-4cee-11ea-8d60-1890c72146b5.png)

there was already a report but no solution
https://github.com/phpservermon/phpservermon/issues/257

**Comment by kurremkarmeruk** [comment]
Hi,
when I use port 9987 i get Connection refused..
So i change the port to 10011 (ServerQuery) - and it works..

**Comment by Tealk** [comment]
That doesn't work for me either.

**Comment by kurremkarmeruk** [comment]
Change timeout to something else than 10 sec/default.

Pozdrawiam,
Łukasz .


śr., 1 kwi 2020 o 08:46 Tealk <notifications@github.com> napisał(a):

**Comment by TopicsLP** [comment]
Hi as TeamSpeak is running over UDP and not TCP you have two options:
1. wait for the UDP implementation: #834 
2. or you can use following workaround, modify the mysql database and adjust the 'ip' of the server with the prefix "udp://"
example "udp://127.0.0.1"
This can not be done in the WebUI as it is not officially supported and can make trouble.
