### ISSUE TITLE
[BUG] Bug with updates with pattern testing

### ISSUE THREAD

**Issue by vitangames** [phpservermon/phpservermon#868]
When adding pattern testing to the monitor - it never updates and stays always online, while there are errors in log file:

![image](https://user-images.githubusercontent.com/5188413/74548803-96e07000-4f5f-11ea-926d-9c688e828ae9.png)

but status is still active and it never changes last checked value:

![image](https://user-images.githubusercontent.com/5188413/74548954-d1e2a380-4f5f-11ea-89a6-1529b354508f.png)

**Comment by wienfuchs** [comment]
Cannot confirm this, it works (at least in pre-3.4.6 develop still labelled "3.4.5" and also 3.4.6-beta.2).
Can you screenshot the relevant part of your pattern config?

**Comment by vitangames** [comment]
Please check this:

![image](https://user-images.githubusercontent.com/5188413/74642679-7fce9780-5184-11ea-8b90-5a43be7bf36c.png)

![image](https://user-images.githubusercontent.com/5188413/74642756-a391dd80-5184-11ea-9b7a-f3a19c23fda4.png)

![image](https://user-images.githubusercontent.com/5188413/74642855-c91ee700-5184-11ea-9b00-e54453b6c51b.png)

**Comment by wienfuchs** [comment]
Maybe you should also enter a "request method"? "None" is not a good idea ;)

**Comment by hausmonarch** [comment]
I am seeing this issue on a fresh install of 3.4.5 on Ubuntu 20.04.

I created a monitor for www.google.com, request method GET, and search string/pattern "sheboygan" (which I would not expect to appear on Google's home page). Pattern indicates web site is "online".

After running status.cron.php a few times, the graph shows the site offline (red), but none of the data gets filled out under "Status" and "Output". The log says "Server "Google" is DOWN but the status page shows green. Inline edit- initially I wasn't getting notifications but I am receiving them now (maybe I hadn't selected myself as a user for that server). The status page still indicates nothing is wrong, though.

I'll try adding screen shots below.

(edit: ignore the two "online" dots in the second screen shot graph. I was confused by the wording of the help text under "Search string/pattern" which seems to indicate the opposite of what might be expected by "Pattern indicates web site is online", so I tried switching to "offline" to see what would happen).

One more edit: I will add that when I changed the search pattern to something that is found on the web site, the log stops saying the page is down, but it never says the page is up, and I never get an email notification that the site is running again. In my general settings, I have notification set to "Status Change" so I should receive a notice when the site is online again.

![phpsm1](https://user-images.githubusercontent.com/25462995/80422473-10b3a480-8893-11ea-8aaa-ff84f43afd12.PNG)
![phpsm2](https://user-images.githubusercontent.com/25462995/80422486-14472b80-8893-11ea-84e6-8e3118d799a9.PNG)

**Comment by wienfuchs** [comment]
As mentioned above, with me it cannot be reproduced in recent devel, it is working also in  v3.4.6-beta.3. Have also checked with your settings, so this probably is fixed
![grafik](https://user-images.githubusercontent.com/44177781/80425370-cc042980-88e3-11ea-81f6-cabba1c4315f.png)

**Comment by hausmonarch** [comment]
Indeed - I downloaded the latest, ran composer.phar, and it seems to be working nicely. Thank you. I misread & misunderstood your earlier post about a later update still being labelled as 3.4.5, and OP never came back to indicate whether fixing the request method had any impact on this issue. Thank you!
