### ISSUE TITLE
[BUG] Fail to ping IPv6

### ISSUE THREAD

**Issue by fgsl** [phpservermon/phpservermon#879]
**Describe the bug**
phpservermon version version 3.4.5 and master (until 24 march, 2020) presents a fail when a address IPv6 is added to ping.
In version 3.4.5 occurs the error: `"Couldn't create socket [1]: Operation not permitted"`
In master occurs the error: `"Server '[name of server]' is OFFLINE: ip=[ipv6], porta=0. Erro=PING [ipv6]([ipv6]) ... data bytes"`

**To Reproduce**
0. Install phpservermon from version 3.4.5 or from master.
1. Go to 'Servers'
2. Click on 'Add New'
3. Put a IPv6 address online into field Domain/IP
4. Select Type 'Ping'
5. Save
6. See in Status that server appear as offline (in red)

**Expected behavior**
A online server must be appear as online.

**Screenshots**
phpservermon shows server [Ingress_03 IPV6] as offline
![screen01](https://user-images.githubusercontent.com/128915/77464122-78368a00-6de5-11ea-85c8-8c792e8ea506.png)
but a ping in terminal shows it as online
![screen02](https://user-images.githubusercontent.com/128915/77464125-7a004d80-6de5-11ea-9f41-60d237ee78f3.png)

**Version (please complete the following information):**
 - Version 3.4.5 and master (24 march, 2020)
 - PHP 7.2.28

**Additional context**

**Comment by wienfuchs** [comment]
https://github.com/phpservermon/phpservermon/issues/835 should probably have solved this (too) in develop

**Comment by fgsl** [comment]
> #835 should probably have solved this (too) in develop

Strange, because I pulled from branch develop this month (I wrote 'master' in description, in fact it is 'develop').

**Comment by wienfuchs** [comment]
> Strange, because I pulled from branch develop this month (I wrote 'master' in description, in fact it is 'develop').

Develop is v3.4.6-beta.2, not 3.4.5 -so, are u sure?  :)

**Comment by fgsl** [comment]
> > Strange, because I pulled from branch develop this month (I wrote 'master' in description, in fact it is 'develop').
> 
> Develop is v3.4.6-beta.2, not 3.4.5 -so, are u sure? :)

Yes, I have cloned develop from Github. The last commit is https://github.com/phpservermon/phpservermon/commit/ee16078884e661c87250b06e2d7e11aaa7352358

I tried with 3.4.5 stable and with branch develop. The fail happened in both of them.

**Comment by fgsl** [comment]
To confirm, I installed again from develop and ping fails for IPv6.

I am using an Amazon Linux AMI and command ping does not work for IPv6, only command ping6.

And current StatusUpdater uses only command ping.

https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Util/Server/Updater/StatusUpdater.php
