### ISSUE TITLE
Donations possible?

### ISSUE THREAD

**Issue by ghost** [phpservermon/phpservermon#887]
Thanks for this tool. For me this is very simple: Good open source software must be supported. :wink: 

I would like to thank you with a small donation, but the PayPal link on sourceforge.net does not work. I get the message: 

> We can't complete this donation. The receiver doesn't have a valid PayPal account.

I would also be happy about privacy-friendly ways to donate, e.g. bank transfer or Bitcoin. Stay healthy!

**Comment by TimZ99** [comment]
I don't have access to the sourceforge so it's outdated.

I added a PayPal link to the sponsor button. I also added a link to bunq, a dutch bank. It accepts debit and creditcards, iDeal, Bancontact and sofort.

I will look into bitcoin in the feature.
