### ISSUE TITLE
[BUG] PHP 5.5.9 - Parse error: syntax error, unexpected const (T_CONST)

### ISSUE THREAD

**Issue by LazyQuad** [phpservermon/phpservermon#889]
Runing PHP Version 5.5.9-1ubuntu4.29 and getting the following error upon install:

`Parse error: syntax error, unexpected const (T_CONST), expecting variable (T_VARIABLE) in /var/www/monitor/src/psm/Module/User/UserEvents.php on line 38
`

Is PHP 5.5.9 no longer supported?

**Comment by imsoftware** [comment]
Which version/branch of phpservermon do you use? develop?
https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Module/User/UserEvents.php#L38
https://www.php.net/manual/en/language.oop5.constants.php

**Comment by wienfuchs** [comment]
> Which version/branch of phpservermon do you use? develop?
> https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Module/User/UserEvents.php#L38

AFIS it does not matter, as difference production 3.4.5 to develop it's just "const" not "public const". But both are expression declaration, which was enabled only since PHP 5.6.0

> https://www.php.net/manual/en/language.oop5.constants.php

Quote from this place: "Constant expression support was added in PHP 5.6.0. "

Anyway: Both PHP 5.5 and PHP 5.6 already reached EOL and should not be used anyhow. PHP themselves only support versions 7.2 and up:
- https://www.php.net/supported-versions.php

**Comment by LazyQuad** [comment]
I was wanting to tryout the latest version on one of my older servers which is running Ubuntu 14.29 and only supports up to PHP 5.5.9.  The server doesn't have access the internet so I'm not worried about security.  I can update the server or run it on another, not a big deal, but the dev should update the requirements info to avoid getting questions from people with antiquated systems like me lol.

I will also try to remove "public" from "public const" and see if it fixes it but I wouldn't doubt if I run into more issues down the line. Even if that does work I know that using a more up-to-date version of PHP would be the best option in the long run.

I will report back my findings then close the issue.  Thx!

**Comment by lazyjeffllc** [comment]
I just upgraded from 3.2.0 to 3.4.5 and the cron job stopped working. Based on this I upgraded from PHP 5.4 to PHP 7.1 and still get the same error.  Does anyone have any tips that I missed?

`<br />
<b>Parse error</b>:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in <b>/%redacted%/vendor/symfony/dependency-injection/ContainerBuilder.php</b> on line <b>147</b><br />`

**Comment by LazyQuad** [comment]
Removing "public" from "public const" did allow the install actually run but after entering my credentials and submitting the install I just ended up with another error.

`Fatal error: Call to undefined function psm\hash_equals() in /var/www/monitor/src/psm/Router.php on line 180`

I will probably continue running into errors so my best option is to run it on a higher version of PHP. 

Thx for the replies.

**Comment by TimZ99** [comment]
Minimal requirement is now 5.6.0.
Thanks @imsoftware.
