### ISSUE TITLE
phpservermon-3.5.0.tar.gz does not contain /vendor

### ISSUE THREAD

**Issue by mklemme1** [phpservermon/phpservermon#901]
The installation package `phpservermon-3.5.0.tar.gz` does not contain the directory `/vendor`.
When unpacked, the application complains about this.

It is included in `phpservermon-3.5.0.zip`.
This package works.

**Comment by docb7** [comment]
Ah - maybe that is why I am not able to get the docker container running (besides my not very deep knowledge ;-)

**Comment by TimZ99** [comment]
There are 2 versions. The version Github makes, without the vendor folder and the version I upload every release, with vendor folder. I updated the docker file to download composer and install the dependencies.
