### ISSUE TITLE
[BUG] Installer should check for needed PHP functions

### ISSUE THREAD

**Issue by spmfox** [phpservermon/phpservermon#903]
Currently the installer checks for a few needed PHP functions but not all of them. This is an issue because different platforms include different PHP packages on a default install.

This time in particular, using CentOS 8 + PHP 7.2.11, php-json was not installed. This leads to a half-way working Telegram notification system. Basically one alert would go out, but the script was crash (looking for the php-json provided function). This was fine unless you had multiple servers pending alerts, only one would happen per check.

I don't know the full list of functions that PHP Server Monitor uses - perhaps @TimZ99 would have the list.

My opinion on how it should work: any functions absolutely needed for the installer to work should be in the "Requirements" documentation - then the rest of them should be checked for when running the installer. If the installer wont run, shows a blank page, then the user is stuck unless they turn on the debug. Get them to the installer, let the GUI show the warnings for the other missing functions.

Here is an example of the installer checking for the cURL module:
```
src/psm/Module/Install/Controller/InstallController.php

        if (!function_exists('curl_init')) {
            $this->addMessage('PHP is installed without the cURL module. Please install cURL.', 'warning');
        } else {
            $this->addMessage('PHP cURL module found', 'success');
```

**Comment by spmfox** [comment]
I just wanted to add, I love this project and everyone please keep up the good work. If we had a absolute list of needed functions, perhaps I could take a crack at this - or it would be a good "first issue" for someone just getting into PHP. I would think copy and paste of the code above, with a few modifications, this could be done somewhat easily. Without that list, you'd need an in-depth understanding to dig all the functions out.

**Comment by TimZ99** [comment]
@mtelgkamp made the following list of extension in  #904 :
- [x] php version
- [x] ext-curl
- [ ] ext-ctype
- [ ] ext-filter
- [ ] ext-hash
- [ ] ext-json
- [ ] ext-libxml
- [ ] ext-openssl
- [x] ext-pdo
- [ ] ext-pcre
- [ ] ext-sockets
- [ ] ext-xml
