### ISSUE TITLE
[Question] Cronjob - Update Servers

### ISSUE THREAD

**Issue by meisterjoda** [phpservermon/phpservermon#910]
- [x] Looked at the documentation first

**Describe the question**
I want to update my servers with cronejob. I create a job in my hosting webinterface to the path .../cron/status.cron.php. My cronjob runs perfektly, but at Server Monitor the Servers don't update. There is always the time of my last manually check. My cronjob runs every minute.

**Version (please complete the following information):**
 - Version 3.5.0
 - PHP 7.4

**Comment by chintoo1919** [comment]
@madeinnordeste  did you look at the logs of cron job , I too had the same issue, after carefully looking at the document, Figured out that cron setup on Debian and ubuntu is different , after correcting the same it started working for me.

screeshot of the cronjob and logs of cronjob should be able to tell the story here .
