### ISSUE TITLE
[Question] website checks are sync or async and monitoring x number of websites

### ISSUE THREAD

**Issue by chintoo1919** [phpservermon/phpservermon#914]
- [ x] Looked at the documentation first

**Describe the question**

I am totally new to coding as well as PSM, While checking for websites status on PSM does it do Sync or async calls? As i see status page have different "Last Online time" ( I believe that time is when the website was last checked) for all the websites i am checking.

current setup for monitoring (PSM) has 300 websites for testing purpose ,  plan is to use PSM in production (1000+ websites) after testing is completed.

sample screenshot : 
![Screenshot_2020-05-12_15-57-30](https://user-images.githubusercontent.com/65225811/81674452-d0474f80-946a-11ea-95fe-855c13cbdd51.png)

**Version (please complete the following information):**
PHP 7.3.14-1~deb10u1
PSM:v3.5.0
**Additional context**
Just wondering if it could be due to system configuration? current test are running from VM which is _single CPU and  1GB RAM_ , 

![Screenshot_2020-05-12_16-12-27](https://user-images.githubusercontent.com/65225811/81675457-7b0c3d80-946c-11ea-87a7-1dc56b505a15.png)

![Screenshot_2020-05-12_16-11-47](https://user-images.githubusercontent.com/65225811/81675493-89f2f000-946c-11ea-9590-2b2a827404e5.png)

What it will take to monitor around 1000+ websites with SSL, I totally understand the answer is not simple.

**Comment by dhanrajbsheth** [comment]
@chintoo1919 : Looking at the code looks like it's sync (one check action at a time) , looks like it will take lots of changes to make it async, Just updating  **psm_curl_get()** function for[ curl_multi](https://www.php.net/manual/en/function.curl-multi-init.php) _will **not** do the full trick_ but , if you look deep down, we will have to enable threading, in function run for **class UpdateManager**  that what i can say with the peep i did in the current code of production on github Dev/Contributors can correct me here .

On the part of the which system to use , I tried your kind of test with system with below config with 300 websites to check every 5 min, I didn't see any changes , still i saw the diff you had seen , but less in terms of minutes, it went from 15 min of diff to 6 min of diff between websites checks, and while for the first check most of them took a while 

Here is my test system config: 
Intel(R) Xeon(R) CPU E5-2687
Memory 12 GB,
Storage: SSD
Bandwidth : Unrestricted 40 Mbps


But without the code changes (to make the "website check" fully async) i think it will not make  sense here if you want to check large number of sites to be checked every 5 min or less.

Let us know if that helps you.
