### ISSUE TITLE
[Question] Ping not working

### ISSUE THREAD

**Issue by slothking87** [phpservermon/phpservermon#916]
Hi all

I just reinstalled V3.5.0 after taking a break from the tool. I cant get ping to a local IPV4 address over my wan to work? 

Monitoring a website works fine, just not anything using ping. Even checking 8.8.8.8. Any suggestions? 

PHP 7.1, Servermon version 3.5.0

**Comment by wienfuchs** [comment]
Pinging a local IP from WAN will never work, how should that?
Or do you mean pinging an external IP from your LAN? If yes, can you check on commandline of your system, if you can manually ping?
As with me, ping works fine, so I guess it's not a phpservermon but probably a network config issue.

**Comment by slothking87** [comment]
Sorry, should have clarified. It’s a local IP over a VPN wan. I can ping it from the server it’s running on fine - just not any ping to any location in servermonitor. No error when manually running the cron update web page either even with debug turned on

**Comment by wienfuchs** [comment]
phpservermon tries a ping6 (if IPv6 is enabled), otherwise IPv4. Maybe you have IPv6 enabled but not connected? If yes, check if "exec" is allowed in php and "ping6/ping" is allowed by webserver user.

**Comment by slothking87** [comment]
I’ll give that a go tomorrow. It’s weird as it detects the last checked time value a negative response for the ping. 

A website check works fine, but I really need to be able to ping a number of different IP addresses

**Comment by slothking87** [comment]
Thanks guys - unfortunately i still get the same error after updating those files. Even running the cron job from an administrator command line I cant get the pings to show a result. Could there be something else Im missing?
