### ISSUE TITLE
Error pinging servers

### ISSUE THREAD

**Issue by slothking87** [phpservermon/phpservermon#927]
- [X ] Looked at the documentation first

Unable to ping IPV4 addresses. No error when running cron job manually with debug turned on. Last test check time updates. Running the cron job as admin via php.exe doesn't help either. Shows this in the log - monitoring a website works fine
Server 'Google' is DOWN: ip=8.8.8.8, port=0. Error= -6 Force using IPv6.

**Version):**
 - Version 3.5.0
 - PHP 7.1.1

**Additional context**
Updated to the latest develop version and reinstalled but that hasnt helped

**Comment by mateuszmalek** [comment]
Could you post the whole output from section "Output"?

> Updated to the latest develop version

If you're talking about 3.5.0 - it's not working properly on this version. Bug was recently fixed in #919 and it's available on 'develop' branch as for now. If you'd like to check if it will be working in the nearest version - download and replace [StatusUpdater.php](https://raw.githubusercontent.com/phpservermon/phpservermon/develop/src/psm/Util/Server/Updater/StatusUpdater.php) file.

**Comment by slothking87** [comment]
Hey mateuszmalek
I updated the file again but didnt help. The output is: 
-Bad option -c.


Usage: ping [-t] [-a] [-n count] [-l size] [-f] [-i TTL] [-v TOS]
[-r count] [-s count] [[-j host-list] | [-k host-list]]
[-w timeout] [-R] [-S srcaddr] [-4] [-6] target_name

Options:
-t Ping the specified host until stopped.
To see statistics and continue - type Control-Break;
To stop - type Control-C.
-a Resolve addresses to hostnames.
-n count Number of echo requests to send.
-l size Send buffer size.
-f Set Don't Fragment flag in packet (IPv4-only).
-i TTL Time To Live.
-v TOS Type Of Service (IPv4-only. This setting has been deprecated
and has no effect on the type of service field in the IP Header).
-r count Record route for count hops (IPv4-only).
-s count Timestamp for count hops (IPv4-only).
-j host-list Loose source route along host-list (IPv4-only).
-k host-list Strict source route along host-list (IPv4-only).
-w timeout Timeout in milliseconds to wait for each reply.
-R Use routing header to test reverse route also (IPv6-only).
Per RFC 5095 the use of this routing header has been
deprecated. Some systems may drop echo requests if
this header is used.
-S srcaddr Source address to use.
-4 Force using IPv4.
-6 Force using IPv6.

**Comment by wienfuchs** [comment]
@slothking87 
> Bad option -c.

What OS and OS-Version do you use? Let me guess: Microsoft, true?

**Comment by wienfuchs** [comment]
Have a change to adress this in my fork https://github.com/wienfuchs/phpservermon/commit/9b89a3d64c0b6cef79d16c8e2423ab19cb2e7d88 but cannot raise a pull request for this yet as another PR is waiting to be merged. Will do as soon as the other request is through.

**Comment by mateuszmalek** [comment]
@wienfuchs You can create new branch which will base on `develop` (a feature branch; https://guides.github.com/introduction/flow/) and create a new pull request from new branch.

**Comment by wienfuchs** [comment]
Done by creating https://github.com/phpservermon/phpservermon/pull/932

**Comment by slothking87** [comment]
> @slothking87
> 
> > Bad option -c.
> 
> What OS and OS-Version do you use? Let me guess: Microsoft, true?

How did you guess? Server 2012 standard

**Comment by slothking87** [comment]
> Done by creating #932

That helps the pinging, but doesnt seem to change the status.  

Error: 
Approximate round trip times in milli-seconds:

Last error output: 
-
Pinging 127.0.0.1 with 32 bytes of data:
Reply from 127.0.0.1: bytes=32 time&lt;1ms TTL=128

Ping statistics for 127.0.0.1:
Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
Minimum = 0ms, Maximum = 0ms, Average = 0ms

**Comment by wienfuchs** [comment]
That brings it to a further point - output depends not only OS but also language specific. So the regexp to check this will fail on various reasons if OS and language differ fron Linux and English ...
No, I don't have a solution for this atm. but I will think it over.

**Comment by wienfuchs** [comment]
As far as I investigated into this, Linux does not seem to change language or output format neither on changing LANG nor locales, but Windows does, So using "old" socket method on Windows (where no administrative privileges are necessary to this) should fix this for Windows servers. Does anyone disagree or see any other ways?
