### ISSUE TITLE
3.5.0 Active Directory integration still missing

### ISSUE THREAD

**Issue by red-erik** [phpservermon/phpservermon#928]
Hello,
great work as usual. running on windows with PHP 7.x everything is working as expected.
Do you plan to merge the work for Active Directory integration?

Regards,

Red.

**Comment by TimZ99** [comment]
I updated #507 to the develop branch. Can you confirm that everything works?

**Comment by TimZ99** [comment]
Moving to #801.

**Comment by viharm** [comment]
Related to #206
