### ISSUE TITLE
VarCheck on steroids

### ISSUE THREAD

**Issue by nerdalertdk** [phpservermon/phpservermon#93]
Hi,

Was thinking about the varcheck pattern and how we could use this better.

I have a script(will be uploaded to my fork) that check disk space, cpu usage, etc. on linux system you can make the same for windows systems), but the errors only shows on my varcheck page if there is a problem.

Output example 
```
VARCHECK:almost-down:/ running out of space i (42.5 GB ) left!
VARCHECK:warn:Data Collection failed - mailqueue status UNKNOWN ...
VARCHECK:down:apache-test is NOT running ...
VARCHECK:almost-down:MySQL is down (connect error from localhost) 
```
the syntax is 
```
VARCHECK : array('warn','almost-down','down') : ERROR MSG

warn - Warning only. (ram or cpu high) 
almost-down: - If there is still error on the next check, set the status to down 
down: - The server reported down. (mail and text message sent).
```
Could be a nice feature if the pattern system had rules or just an (if exists / don't exists) function.

**Comment by sadortun** [comment]
If you are still interested in this idea, please submit a PR. Thanks!
