### ISSUE TITLE
Restore mail

### ISSUE THREAD

**Issue by dmonaay** [phpservermon/phpservermon#940]
Great project.

Is it possible to do a server restore mail when server is back up again in the future? Would be great.

**Comment by wienfuchs** [comment]
@dmonaay Ahm, that is, what it does? There comes a restore mail info, telegram, sms, whatsoever?

**Comment by dmonaay** [comment]
Is that true? I didn't receive them that's why i ask for it. My bad.

**Comment by wienfuchs** [comment]
> Is that true? I didn't receive them that's why i ask for it. My bad.

What version do you use? As with 3.5.0 (and develop) it does.

**Comment by dmonaay** [comment]
I'm new and use the 3.5.0 version. 
My log shows the connection timed out message and send an email, the restore message is not show in the log.

**Comment by wienfuchs** [comment]
This is weird, as with me i functions fine. That I can confirm as I have a bad wirkong VPS at the moment which f*cks off twice a day actual days and the monitor works like a charm ....

**Comment by dmonaay** [comment]
Could it be that the option "Always" for the notification settings is the wrong one and i need to use Status change?

**Comment by dmonaay** [comment]
Yes that's the problem... In my opinion "Always" will also send the running message
