### ISSUE TITLE
[BUG] Blank Page "Users"

### ISSUE THREAD

**Issue by DennisBeee** [phpservermon/phpservermon#942]
**Describe the bug**
When clicking "Users" a there´s a blank page.

**To Reproduce**
1. Go to 'Homescreen'
2. Click on 'Users'
3. Blank Page ([HOST]/?&mod=user

**Version (please complete the following information):**
 - Version 3.2.0
 - PHP 7.2.27

**Comment by wienfuchs** [comment]
That is already fixed in actual versions. Pls use a more recent release, e.g. 3.5.0. Probably duplicate to issue https://github.com/phpservermon/phpservermon/issues/562 fixed by https://github.com/phpservermon/phpservermon/commit/08eb9a55f7cf9110463c0a556378846939023476
