### ISSUE TITLE
[BUG] ping doesn’t monitor correctly

### ISSUE THREAD

**Issue by MatzeKitt** [phpservermon/phpservermon#943]
**Describe the bug**
The ping test uses the first line outputted to mark the test as positive. I tested it with `test.com`, which has the following result:
```
Last positive output:
PING test.com (69.172.200.235) 56(84) bytes of data.
```

Via terminal:
```
 ping test.com
PING test.com (69.172.200.235) 56(84) bytes of data.
^C
--- test.com ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 122ms
```

As you can see, there is a 100% package loss but the test in phpservermon describes the server as online.

Additionally, the latency is always `0`.

**To Reproduce**
1. Create a server with domain test.com and type set to ping.
2. Check the details page of this test.

**Expected behavior**
The ping statistics are monitored properly with the correct latency and online/offline flag.
**Version (please complete the following information):**
 - Version 3.5.0
 - PHP 7.3

**Comment by wienfuchs** [comment]
There were recentliy some changes to the ping routine to adresse various problems (that sound to be yours), could you pls download the actual latest commit of src/psm/Util/Server/Updater/StatusUpdater.php  at https://raw.githubusercontent.com/phpservermon/phpservermon/7deac0815afb010cce81e964fd710b8c7bcaab25/src/psm/Util/Server/Updater/StatusUpdater.php and recheck, if your issue still exist? As with me and this (latest) version it shows proper latency on working and also non-avaliability of your statet IP.

**Comment by MatzeKitt** [comment]
Thank you for the quick reply!

That fixes the problem with the latency. However, the main problem with `test.com` remains as this host doesn’t seem to allow pings.

**Comment by wienfuchs** [comment]
As with me, a (newly) added "test.com" server produces proper output (with a/m version):
![grafik](https://user-images.githubusercontent.com/44177781/83306025-1db11400-a202-11ea-8c24-8fe5af649c13.png)
Maybe your "Last positive output" is a result of the previously not working version? To test this, you may try deleting the server and re-adding it, I'd guess you see no "positive output" entry anymore, same as I do not see it :)

**Comment by MatzeKitt** [comment]
I re-added the test but the same result, with one difference: There is no positive output anymore. Now, there is no output at all.

Notice: I just replaced the one file you mentioned above and didn’t use the master version as complete package.

**Comment by wienfuchs** [comment]
There should be a "error" output and the server should go to offline - could you screenshot the part I showed above on you system? What OS do you use?

**Comment by MatzeKitt** [comment]
<img width="574" alt="Bildschirmfoto 2020-05-31 um 17 55 01" src="https://user-images.githubusercontent.com/1018979/83356663-db094c00-a367-11ea-8708-af3288b90208.png">
It’s just empty.

I’m using the current version of Debian 10 Buster.

**Comment by wienfuchs** [comment]
Tracked it down, the problem results as trailing line(s) from ping output differs between versions. Will adress this in a pull PR soon.

**Comment by wienfuchs** [comment]
> 
> 
> Tracked it down, the problem results as trailing line(s) from ping output differs between versions. Will adress this in a pull PR soon.

Untrue, this is _not_ the issue. Will have to work further on this, but I can reproduce it on a local debian 10 VM. So I will be able to find the source and fix it the next days.

**Comment by TimZ99** [comment]
Can confirm. Ubuntu xenial server shows as online without any output. macOs  shows offline with 

```
-ping: sendto: Socket is not connected
PING test.com (0.0.0.0): 56 data bytes

--- test.com ping statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
```

Google.com works fine.

**Comment by wienfuchs** [comment]
Tracked data transmission up to "$this->db->save" - data is there, so bug is probably somewhere in the save routine. Output on Ubuntu 18.04 (bionic) shows fine although.
Edit: If to do with database maybe, I'm using 10.1.44-MariaDB-0ubuntu0.18.04.1 on working system

**Comment by TimZ99** [comment]
Shouldn't be. My Ubuntu and macOs are running on the same database.

**Comment by hjcday** [comment]
Hi All, I am also experiencing this issue. It is showing that the Pings have failed however the server remains green. Run as Docker container. All other features work well

**Comment by wienfuchs** [comment]
One more weird thing: I upgraded my system on Ubuntu 18.04 from PHP7.3 to PHP 7.4 and also from MariaDB 10.1 to 10.3 - result: Now I don't receive ping (only ping) offline's combined but on every check .... Still investigating, but busy and sick those days, so could not continue on this issue yet, sry

**Comment by wienfuchs** [comment]
So, tracked one thing down. There is a type bug in UPDATE of `` `psm_servers` `` - the query contains `` `psm_servers`.`rtime`=''` `` - but rtime is of type float, so this update is not executed and therefore not inserted. That's probably where above errors come from. Searching for the source of this query now.

**Comment by wienfuchs** [comment]
Tracked it down to a conflicting variable type and issued a pullrequest for fix. Tested locally on debian 10, where it totally solved the ping issue. Also https://github.com/phpservermon/phpservermon/issues/943#issuecomment-658063444 was solved by this minimal change.

**Comment by wienfuchs** [comment]
@ KittMedia, @hjcday - could you possibly download https://raw.githubusercontent.com/phpservermon/phpservermon/d5005505acf2ff3b151024be6ef1568f70673784/src/psm/Util/Server/Updater/StatusUpdater.php as your src/psm/Util/Server/Updater/StatusUpdater.php and check, if your ping problems are also gone with that? Just to verify.

**Comment by hjcday** [comment]
@wienfuchs made that amendment on my running version of the monitor and all issues resolved. Good find and thanks for looking into it!

**Comment by MatzeKitt** [comment]
Works fine for me now, too.

**Comment by GiovanniK** [comment]
I had the problem that all my ping monitors were reported down.
@wienfuchs your version of the script worked and solved it.

Although I had to use the fix from #945 too for my docker container (/bin/ping).

**Comment by wgiacomelli** [comment]
@wienfuchs mesmo com a configuração do link que segue o Ping segue sem funcionar, algum outro ajuste necessário?

https://raw.githubusercontent.com/phpservermon/phpservermon/d5005505acf2ff3b151024be6ef1568f70673784/src/psm/Util/Server/Updater/StatusUpdater.php

**Comment by wienfuchs** [comment]
@wgiacomelli project language is English and I also do not understand your language, sorry.
