### ISSUE TITLE
[BUG] Attaching users to a new server throws PDO error

### ISSUE THREAD

**Issue by n0nag0n** [phpservermon/phpservermon#946]
**Describe the bug**
I was adding a new server to my PHP Server Monitor instance, and when I went to add users to it at the bottom, I could see there was enough space for 3 users (in my case), but all the user names where the text would have gone for their first/last name was empty. I clicked Select All and it put a check next to each of the users. When I added the server, it added the server just fine but then I saw this error at the top. `Warning: SQL error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-14' for key 'PRIMARY' in /path/to/phpservermonitor/src/psm/Service/Database.php on line 578`

One other oddity that may be a feature, not a bug, is if you have a server with no users attached to it, it will display for all users to see in the "Status" and "Servers" tabs, but you won't actually get notified about it until you tie the user to a server. This could be a totally separate issue, just thought I'd bring it up.

**To Reproduce**
1. Go to add a new server.
1. Mark it as a website
1. Fill out the form.
1. Go to the bottom
1. Try to add a new user to the server and it shows what's described.

**Expected behavior**
I should be able to add a new server, with the users I want, and it should work like a dream.

**Screenshots**
![image](https://user-images.githubusercontent.com/2322095/83584942-ca8ed800-a505-11ea-8281-fb76cfa3e514.png)

**Version:**
 - Version 3.5.0
 - PHP 7.3.18

**Additional context**

**Comment by TimZ99** [comment]
Fixed with #923.
