### ISSUE TITLE
[Feature Request] Add config for Octopush

### ISSUE THREAD

**Issue by marc-farre** [phpservermon/phpservermon#957]
Please give the possibility to change https://github.com/phpservermon/phpservermon/blob/5ecdc75dcf3c156d6694ac261a6e04df560d6134/src/psm/Txtmsg/Octopush.php#L62 `$smsType` value in the configuration

Thanks!

**Comment by TimZ99** [comment]
Feel free to send an Pr. Or you can change the value in the source.

**Comment by marc-farre** [comment]
https://github.com/phpservermon/phpservermon/pull/975
