### ISSUE TITLE
Authentication fields for website/services

### ISSUE THREAD

**Issue by gotfredsen** [phpservermon/phpservermon#96]
I can use http://username:password@www.example.com/ 
but that would show my password in clear text, and is less user-friendly 

I suggest a checkbox for authentication and then a field for username and password, little alà kingdom.com

**Comment by njh** [comment]
yes please

**Comment by sadortun** [comment]
Hi @Laupe Would you be willing to propose a PR for this ?

**Comment by Laupe** [comment]
Hi @sadortun Great idea! OK prepare PR

**Comment by Laupe** [comment]
Hi @sadortun It is the PR as https://github.com/phpservermon/phpservermon/pull/296
