### ISSUE TITLE
[Feature Request] check https site if SSL check expiration

### ISSUE THREAD

**Issue by PtrckM** [phpservermon/phpservermon#960]
**Describe the solution you'd like**
- check https website then if SSL check expiration

**Describe alternatives you've considered**
- check https website then if SSL check expiration shows warning if nearly expired

**Additional context**

**Comment by wienfuchs** [comment]
Duplicate to https://github.com/phpservermon/phpservermon/issues/384 which was implemented as https://github.com/phpservermon/phpservermon/pull/831

**Comment by PtrckM** [comment]
@wienfuchs are this enabled by default or i have to play with warning threshold?

**Comment by wienfuchs** [comment]
Default is a disabled SSL check, so you need to enter a value to "SSL Certificate Validity" entry. This are the number of days minimum remaining not to trigger the warning. If it's still not working, you system configuration may relate to the https://github.com/phpservermon/phpservermon/issues/896 mentioned bug - i.e. CentOS 7 cURL 7.29 is buggy by distribution.

**Comment by PtrckM** [comment]
@wienfuchs would you mind teach how to enable it? Can't seems to find any documentation or wiki. Mine looks like this

![image](https://user-images.githubusercontent.com/54516858/86694389-220cf000-c03e-11ea-864c-47e012821ab5.png)

I saw this on the link you posted earlier..

![image](https://user-images.githubusercontent.com/54516858/86694517-449f0900-c03e-11ea-891e-51886264cbaf.png)

**Comment by wienfuchs** [comment]
Initially: What verison of PSM are you using? This setting is avail as of 3.4.6-beta (recent 3.5.0 stable) only.

**Comment by PtrckM** [comment]
![image](https://user-images.githubusercontent.com/54516858/86696010-a4e27a80-c03f-11ea-91c4-1a105ce55b0a.png)

now that make sense

**Comment by PtrckM** [comment]
thank you for your support and fast response you guys have an amazing product.
