### ISSUE TITLE
[Question/BUG] Telegram test works; but doesn't.

### ISSUE THREAD

**Issue by ceesvanegmond** [phpservermon/phpservermon#962]
I've configured Telegram notifications as said in the documenation. When click on 'Config' in the menu bar I can test my Telegram and it works; I get an message 'Test message' which is good 👍 

However when some site changes status, no Telegram is send. The icon in the UI changes color thus. I've enabeld telegram to the specific servers as well. When clicking on 'Log' there aren't any log messages for Telegram as well. Yes Telegram is allowed to send; the checkboxes 

- Allow sending Telegram messages
- Log Telegram messages sent by the script

are both checked

Version 
 - Version 3.5
 - PHP 7.3

It's weird that the test works as expected but don't get any results

**Comment by wienfuchs** [comment]
Did you also add the relevant server to the specific user (Permission setting at the lower end on server edit page)? That's the most source with me for not receiving notifications ;) Also telgram need to be enabled at server level, but this should be default.

**Comment by ceesvanegmond** [comment]
@wienfuchs Yes; thats it. The permission wasn't set. Fixed! Thanks!
