### ISSUE TITLE
[BUG] Update to 3.5.0 fails with PHP 7.0.33

### ISSUE THREAD

**Issue by TheLalaMan** [phpservermon/phpservermon#966]
**Describe the bug**
After updating a 3.4.5 installation  (replacing installation with new release files and adding the config.php), navigating to install.php throws the following error:

```
syntax error, unexpected ‘const’ (T_CONST), expecting variable (T_VARIABLE) in var/www/html/phpservermon/src/psm/Module/User/UserEvents.php on line 38
```

**Expected behavior**
Installation instructions on how to finish the update.

**Version (please complete the following information):**
 - Version 3.5.0
 - PHP 7.0.33

After a quick check it seems that PHP Server Monitor now depends on PHP 7.1+, because according to https://www.php.net/manual/en/language.oop5.constants.php, "As of PHP 7.1.0 visibility modifiers are allowed for class constants. ". However, the Readme still states that PHP 7.0.8+ is the lowest supported version.

**Comment by wienfuchs** [comment]
Duplicate as of https://github.com/phpservermon/phpservermon/issues/908 solved by https://github.com/phpservermon/phpservermon/pull/913 - referrring to PHP version pls read note as of https://github.com/phpservermon/phpservermon/issues/908#issuecomment-629279273

**Comment by TimZ99** [comment]
@wienfuchs we should make a release with those changes in it 😅 thought this was in production already
