### ISSUE TITLE
Website check do not use the port number

### ISSUE THREAD

**Issue by gotfredsen** [phpservermon/phpservermon#97]
When you have websites that runs on port, say 8080, it would be nice if the port number field worked for websites. As minimum it should be greyed out when not applicable.

Great product, btw!

**Comment by pieter-groeneweg** [comment]
In order not to run into any risk tempering with current functionality, I'd suggest a jQuery solution?

**Comment by sadortun** [comment]
@pieter-groeneweg please explain.

**Comment by pieter-groeneweg** [comment]
simple have jQuery check in field type if it is a site or service. based on that enable/disable (or hide/unhide) port field....

**Comment by TimZ99** [comment]
This is in version 3.2.1 right? Is there a reason why this issue isn't closed?

**Comment by TimZ99** [comment]
As far as I know this is present in the current version.
