### ISSUE TITLE
A new version still available after upgrade to latest

### ISSUE THREAD

**Issue by prathers** [phpservermon/phpservermon#974]
- [x] Looked at the documentation first

I've done a complete install of source code and run install.php - the footer still tells me that there is a new version available.

**Version:**
 - Version 3.5.1
 - PHP 7.2

**Comment by prathers** [comment]
Close after new hotfix v3.5.2

**Comment by TimZ99** [comment]
Correct, I forgot to change the version numbers. Fixed with 5c5d980. I have published a new release too. 👍

**Comment by prathers** [comment]
And it worx - thanks for your good work!
