### ISSUE TITLE
[BUG] User Blade error (HTTP 500)

### ISSUE THREAD

**Issue by Gill-Bates** [phpservermon/phpservermon#977]
URL: https://foo.bar/?&mod=user
Version: 3.2.0
PHP: 7.3 (Apache)

Bug: Klick on the link above result in an empty page

Apache Log:
`194.xxx.xxx.xxx - admin [13/Aug/2020:10:16:41 +0200] "GET /?&mod=user HTTP/1.0" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0" foo.bar`

**Comment by wienfuchs** [comment]
This was referenced several times (pls use search function) and solved long time ago. Pls simply use a recent release (3.5.2 is the most recent), 3.2.0 is outdated

**Comment by Gill-Bates** [comment]
The most recent Version is 23 hours old :-)

![grafik](https://user-images.githubusercontent.com/25774289/90121718-9c771100-dd5c-11ea-835a-aa53d12b3b7c.png)

I got Version 3.2.0 from the official Website: https://www.phpservermonitor.org/download/

**Comment by wienfuchs** [comment]
> The most recent Version is 23 hours old :-)
> 
> ![grafik](https://user-images.githubusercontent.com/25774289/90121718-9c771100-dd5c-11ea-835a-aa53d12b3b7c.png)
> 
> I got Version 3.2.0 from the official Website: https://www.phpservermonitor.org/download/

Congratulations, this is right.
