### ISSUE TITLE
Slack Webhook Variable

### ISSUE THREAD

**Issue by helmi1987** [phpservermon/phpservermon#978]
Hello is it posible to give the JSON Meassage a new Variable

Red for Down
red = #FF0000

and

Green for Up
green = #008000

here my JSON Example
{"username": "PHP Server Monitor", "icon_url": "https://phpServerMonUrl/phpservermon.png", "attachments": [{"text": "#message", "color": "#008000"}]}

**Comment by TimZ99** [comment]
Feel free to send a pr.

**Comment by helmi1987** [comment]
what you exactly mean with pr?

**Comment by TimZ99** [comment]
PR stand for Pull request. If you or someone else implements this function, you can send it in using a Pull request.

**Comment by helmi1987** [comment]
yes i will do it thanks
