### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by artiomma** [phpservermon/phpservermon#980]
Is it possible to change status page from 4 columns to more?

**Comment by TimZ99** [comment]
Changing the column width in the template.
https://github.com/phpservermon/phpservermon/blob/ba0fa251e9f9dded91ec72bec02a12cb47c13592/src/templates/default/module/server/status/index.tpl.html#L7
https://github.com/phpservermon/phpservermon/blob/ba0fa251e9f9dded91ec72bec02a12cb47c13592/src/templates/default/module/server/status/index.tpl.html#L20
https://github.com/phpservermon/phpservermon/blob/ba0fa251e9f9dded91ec72bec02a12cb47c13592/src/templates/default/module/server/status/index.tpl.html#L33
