### ISSUE TITLE
[BUG] Type: Ping responds online to IP with known no host

### ISSUE THREAD

**Issue by bcsanford** [phpservermon/phpservermon#982]
**Describe the bug**
Type: Ping responds online to IP with known no host. as well as to ip addresses/domains that the linux(same box hosting PSM) ping command can not successfully ping(100% Packet Loss)

![image](https://user-images.githubusercontent.com/185097/90422531-01967380-e089-11ea-9f90-c24c530bd856.png)

![image](https://user-images.githubusercontent.com/185097/90422649-2be83100-e089-11ea-9039-9b43b10992bf.png)

**Version (please complete the following information):**
 - Version 3.5.2
 - PHP 7.2.33-1+ubuntu18.04.1+deb.sury.org+1
 - ping utility, iputils-s20161105
 - nginx version: nginx/1.14.0 (Ubuntu) <-- probably not relevent but i figured i'd give it anyway

**Comment by wienfuchs** [comment]
Probably duplicate to #943 and solved by #963

**Comment by bcsanford** [comment]
Thank you swapping out only this one file did the trick.

https://raw.githubusercontent.com/phpservermon/phpservermon/d5005505acf2ff3b151024be6ef1568f70673784/src/psm/Util/Server/Updater/StatusUpdater.php 

 i had only just updated but i guess the final problem fix is only 5 days old.
