### ISSUE TITLE
Add SMS gateway

### ISSUE THREAD

**Issue by artiomma** [phpservermon/phpservermon#983]
Hi.
First of all Thank You for your work.
Can you help me to add our local sms provider "Inforu"
This is a php code example

<?php
function SendSMS($message_text,$recepients) {
$sms_user = "USERNAME"; // User Name (Provided by Inforu)
$sms_apitoken = "APITOKEN"; // Password (Provided by Inforu)
$sms_sender = "MyCompany"; //
$message_text = preg_replace( "/\r|\n/", "", $message_text); // remove line breaks
$xml = '';
$xml .= '<Inforu>'.PHP_EOL;
$xml .= ' <User>'.PHP_EOL;
$xml .= ' <Username>'.htmlspecialchars($sms_user).'</Username>'.PHP_EOL;
$xml .= ' <ApiToken>'.htmlspecialchars($sms_apitoken).'</ApiToken>'.PHP_EOL;
$xml .= ' </User>'.PHP_EOL;
$xml .= ' <Content Type="sms">'.PHP_EOL;
$xml .= ' <Message>'.htmlspecialchars($message_text).'</Message>'.PHP_EOL;
$xml .= ' </Content>'.PHP_EOL;
$xml .= ' <Recipients>'.PHP_EOL;
$xml .= ' <PhoneNumber>'.htmlspecialchars($recepients).'</PhoneNumber>'.PHP_EOL;
$xml .= ' </Recipients>'.PHP_EOL;
$xml .= ' <Settings>'.PHP_EOL;
$xml .= ' <Sender>'.htmlspecialchars($sms_sender).'</Sender>'.PHP_EOL;
$xml .= ' </Settings>'.PHP_EOL;
$xml .= '</Inforu>';
$ch = curl_init();
curl_setopt($ch,CURLOPT_URL,'https://api.inforu.co.il/SendMessageXml.ashx');
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, 'InforuXML='.urlencode($xml) );
curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
$response = curl_exec($ch);
curl_close($ch);
return $response;
}
// example
SendSMS(
'Hello',
'0501111111;0502222222'
);

Thank You

**Comment by TimZ99** [comment]
Please have a look at the more than 20 examples in [src/psm/Txtmsg](https://github.com/phpservermon/phpservermon/tree/develop/src/psm/Txtmsg)
