### ISSUE TITLE
[BUG] Server History not Stored inside SQL

### ISSUE THREAD

**Issue by Gill-Bates** [phpservermon/phpservermon#984]
In Version 3.5.2, the Server History is not stored in the DB:

As you can see, after upgrading to a newer Version pf PHPServermon, the logging has stopped:
![image](https://user-images.githubusercontent.com/25774289/90834774-4a7d4f00-e34b-11ea-8ba5-542ca3046da7.png)

A fresh installation, the DB remains empty:
![image](https://user-images.githubusercontent.com/25774289/90834644-0ee28500-e34b-11ea-8993-d0792efc99d8.png)

**Comment by wienfuchs** [comment]
wrong original comment: ``Confirmed for 3.6.0.beta2 - last entry as of Aug 13th before upgrade ....``

As stated below by others, data is stored, but a week delayed. So history log is "only" delayed.

**Comment by Meuschke23** [comment]
Confirmed for 3.6.0.beta2 - last entry as of Aug 16th before upgrade ....

![2020-08-24 12_35_34-Window](https://user-images.githubusercontent.com/65863113/91035124-64968600-e606-11ea-83d3-e2e89742cc0d.png)

**Comment by TimZ99** [comment]
@Gill-Bates are you on 5.5.2 or higher? 
Because I honesty don't know what could cause this issue if you're on 5.5.2. The only thing that changes was jQuery and version number.

**Comment by cyberal77** [comment]
The history log is generating with 1 weeks late, for me last log entry is 2020-08-17 this morning. 

I don't know if a bug, but in UptimeArchiver.php "date < :latest_date"  with lastest date set to now - 1 week.

**Comment by Meuschke23** [comment]
> 
> 
> The history log is generating with 1 weeks late, for me last log entry is 2020-08-17 this morning.
> 
> I don't know if a bug, but in UptimeArchiver.php "date < :latest_date" with lastest date set to now - 1 week.

In my instance it seems to be the same.

![2020-08-25 10_32_08](https://user-images.githubusercontent.com/65863113/91151921-94a16000-e6be-11ea-9f64-6e0228043912.png)

**Comment by TimZ99** [comment]
The -1 week is because you can go back 1 week in the uptime graph. After 1 week the uptime records are removed and bundles into the history table.
