### ISSUE TITLE
[BUG] Downtime always 1 or 2 minutes

### ISSUE THREAD

**Issue by BarryBaksteen** [phpservermon/phpservermon#994]
With PHP server monitor v3.4.5 and on another instance with v.3.5.2, we see in the monitoring notification an incorrect duration of the downtime, see below:
This happens to telegram, as well to Pushover.

Baksteen monitoring, [26.07.20 12:41]
Failed to connect to the following server:
Server: Minecraft server
IP: 192.168.1.114
Port: 25565
Error: Connection refused
Date: 2020-07-26 **12:41:07**

--------------------------------------------------
Baksteen monitoring, [26.07.20 12:44]
Server 'Minecraft server' is running again, it was down for: **1 minute 1 second**
Server: Minecraft server
IP: 192.168.1.114
Port: 25565
Date: 2020-07-26 **12:44:06**

More information:
PHP server monitor instance 1:
v3.4.5
OS: Ubuntu server 18.04

PHP server monitor instance 2 (Clean installation):
v3.5.2
OS: CentOS 7 2003

This happens with all servers in PHPservermonitor
Is this a known bug?

**Comment by wienfuchs** [comment]
In fact this is no bug but depending on the update cron job. Downtime is always ("only") calculated based on the update interval of the cron job.

**Comment by BarryBaksteen** [comment]
Maybe it is not a bug, but a useless feature? We have a default installation with default cronjob settings. Why is this information wrong by default?

How can we setup the cronjobs to get this information right?

**Comment by wienfuchs** [comment]
Ah, sorry, I was reading your info wrong. You are claiming that a downtime of three minutes was shown as 1 minute. That in fact would be a bug. But I cannot confirm this, as with my systems, the down time is shown properly:
![grafik](https://user-images.githubusercontent.com/44177781/91481299-7d23cc00-e8a4-11ea-842d-4a44e20d28d4.png)
![grafik](https://user-images.githubusercontent.com/44177781/91481425-b2301e80-e8a4-11ea-954d-5ff87a0b58c3.png)
(telegram)

**Comment by BarryBaksteen** [comment]
No problem.

I'm pointing on these lines: "Server 'Minecraft server' is running again, it was down for: **_1 minute 1 second_**"
I see you don't have these in your notifications? (older version?)

**Comment by wienfuchs** [comment]
Probably not, as this was 3.6.0beta2 (but similar to 3.5.2 and 3.5.0 with me) - but "combined" format. Maybe that's the difference, this ar my settings:
![grafik](https://user-images.githubusercontent.com/44177781/91482169-ea842c80-e8a5-11ea-8c78-5bb76870ed0f.png)
What notification format are you using?

**Comment by BarryBaksteen** [comment]
I get all notifications separated (Not combined). I have enabled the combine setting and tested the notifications, but with the same result:

Error: Connection timed out
- Date: 2020-08-27 **20:53:12**



The following servers are up again:
- Server: Dynmap Minecraft
- IP: 192.168.1.114
- Port: 8123
- Downtime: **51 seconds**
- Date: 2020-08-27 **21:08:03**

I brought it down at 20:53 and up again at 21:08. According to the notification, the downtime was only 51 seconds?

**Comment by BarryBaksteen** [comment]
Maybe helpfull:
PHP server monitor instance 1:
PSM v3.4.5
OS: Ubuntu server 18.04 
PHP 7.0.33

PHP server monitor instance 2 (Clean installation):
PSM v3.5.2
OS: CentOS 7 2003
PHP 7.4

**Comment by wienfuchs** [comment]
Just to clarify again: Both servers show downtime period incorrect or "only" 3.4.5? Did you verify the issue on _your_ system against 3.6.0beta?

As mentioned above, I cannot reproduce the problem as yes, as my systems _do_ send correct information.

**Comment by BarryBaksteen** [comment]
Yes, both servers show the same 'bug'. I will upgrade to the latest version to check if the problem still exists, i will let you know.

**Comment by BetTD** [comment]
I remember this being a bug in a previous PSM version, but as far as I know, it was fixed not too long ago. All I can really say is that my v3.5.2 installation does not experience this bug.

@BarryBaksteen Is the issue still happening for you?

**Comment by BarryBaksteen** [comment]
Sorry for my late response.

I can verify this has been fixed in (at least) 3.6.0. I've updated both instances to this version and now the time is displayed correctly.

Thanks for your input.
